---
contributors:
- LiChuang Huang
title: "White heart breath"
date: "2023 Apr 30 14:45:08 | Sun"
lastmod: "2023 Apr 30 14:45:08 | Sun"
draft: false
images: []
menu:
  docs:
    parent: "novel"
weight: 510
toc: true
---


## Chapter 1


   他不知道为什么，这个他在走廊上时、在对面大楼看到过的女人，又会出现在这个阶梯教室了。他因为一时震惊，连笔都被他丢开了。他离开座位，去隔了两排座位远的位置去把自己的笔捡回来。这会儿，那个女人正绕着教室的最外围绕圈。她路过讲台，望着他；她经过了靠门那边的过道，也看向他；她横过了教室的后方，也看向他。

   他注意到了异常，她走得太快了。她一步跨出，像没有重量一样，像被风吹走一样。还有异常，如果这个和红伊水长得一模一样的人真的是红伊水，那么他十分钟之前在对面大楼看见的那个女人是谁？——如果她们都是红伊水，那么她是如何在短短十分钟时间，从那幢楼跨到这幢楼，连衣装都改变了？

   在十分钟之前，她穿着不肥不瘦、时尚到平庸的秋季女生装；而现在，她穿得过于诡异了，或者说，时尚前卫到非主流了——她的长裙披戴而下，漆黑色的，带着深邃下沉的感觉，在肩膀和裙摆处有暗红色的流纹。那流纹如火焰的流纹，好像会顺着他的视线烧回来一样；他不敢多看。她还穿着一双高帮长靴，她的靴子的底子好像很厚，踩在地面上，嘎登嘎登响——她在十分钟之前，绝对穿得是一双跑步鞋。她的发型都变了，十分钟之前她的额头被头发盖住了，现在露出来了。那双额头下的眼睛一直盯着她看，这会儿，那双眼睛到了讲台那儿了——为什么他会有这种诡异的感受，好像那双眼睛脱离了脑袋在移动一样？

   他明白了，是因为他一直注视着那双眼睛的时候，那双眼底的暗红色，会让他有种眩晕的感受，周围的光线都变得昏暗了下来，视野中只有那双眼睛；于是，那双眼睛变得像一直飞着的蝙蝠，飞着的毒蛇，飞着的血蛭……他觉得自己想多了，也许是昨晚没睡够，脑袋糊涂了。他拍了拍自己的脑袋。

   可能是他拍天灵盖的声音太响了，让这个女人的脚步停了下来——也有可能她早就停下来了。她这会儿，往他这边走近了。他下意识地往后靠。他的后背撞上了后排的桌子，发出嘭的一声。他忘了自己的痛觉神经是否传递来了信号，这会儿，他只想逃跑。为什么要逃跑？

   他顾不上自己的东西了，他嗖地一下站起，往教室后门跑——他的手被抓住了。他回头——他只敢看那抓住他的手，根本不敢看那双眼睛。那双手是普通的女人的手——不，她的指尖是青紫色的，指甲盖边缘还有暗红地血渍。他宁愿相信那只是没刮干净的指甲油。

   她手腕一带，正跨到两步外的红黎被拽飞了过去。他以为自己要撞上她了，甚至可能来一场——她的另一只手按在了他的额头上。他纹丝不动了。他还在前冲的动能全部震入了他的内脏，他感觉五脏六腑一阵颠倒。他本会捂住自己的腹部，佝偻下腰；然而，他一动不动。他的身体不听使唤了。冷汗从他的脸颊滚落。他还能瞪大眼睛，他这个角度，正好对着她的那双眼睛。现在，她的那双眼睛没有那么诡异幽暗又吸光了，但是，她本人看起来更加可怕了。他这个距离，面对面看清了她的面容。没错，她长得和红伊水一模一样。但这个人，绝对不是红伊水。

   "You can move now."这女人说。

   她会说人话。红黎跳动的心脏的沉重好像减轻了些。但是，他不像她说的那样可以动。他现在感受得更清楚了，他的浑身好像被什么包被住了。如果他眼睛往下看，能看见身体上好像有一层赤色的透明雾霭，淡淡的，很容易以为那是因为他眼睛充血导致的错视。

   "I can't move yet."他说。

   "What is your name?"她说。

   他用英文说："我叫红……"他改口，"我叫红帽。"

   "你在说谎。"

   她的青紫色的指尖触摸向了他的脖颈的动脉。她的指尖抵住了它；它每一次地跳动，都会在她指尖上走一遭。

   "我叫红黎。"他马上说。

   "你可以动了。"

   现在，他真的可以动了。他浑身紧绷，做出了一些机器人般地怪异动作——他的动作幅度太大了，一拳打在了那女人的胸口——他当然没打上，他的拳头在中途被什么软绵绵的雾霭挡住了。他刚刚一直在试图挣脱束缚，现在突然没了束缚，一时没有控制住自己的身体。他瞥了一眼她的眼睛，缩回了目光。她的眼神好像没有生气。

   "我给你三分钟，让你冷静下来。"她说。

   她不知从哪里搬出来一张雪白的扶手椅，就这么让自己坐在过道上。她的手中还出现了一盏茶杯，一个水壶。她端起水壶，稍微举起，让它倾倒下来。汩汩汩。其中好像既有她倒水的声音，也有红黎吞咽唾沫的声音。他现在好像更难以冷静下来了。

   "我叫阿贝莉亚·戴安娜。"

   总而言之，他肯定是走不了了。他摸向旁边的排桌，让自己挪到座位点，然后按下后面的坐板。他一直看着阿贝莉亚的脸色行事，所以他的手总是摸不准那坐板。他抓住了。他的手抖了一下，那坐板又翻了回去，啪的一声打在了后座上。

   阿贝莉亚还在悠哉游哉地喝着茶水。

   费了不知道多少力气，他总算坐下来了。他把手摆在桌子上，向阿贝莉亚示意自己没有轻举妄动，然后尝试让自己放松。也许还剩下一分钟，他需要冷静下来，厘清头绪。从五分钟——他甚至感觉是一年前——到现在到底发生了什么。

   啪叽。

   阿贝莉亚的茶杯放在了红黎面前的桌子上。

   "请你回答我的问题。这里是哪里？"

   这可能是个哲学问题。红黎心想。他从口袋里摸出手机——他的手机上一秒抓在手上，下一秒不见了。他抬头，手机出现在了阿贝莉亚手中。

   她的两根指头捏住了手机HOME键的位置，让手机这么横在面前。她另一只手的食指勾了起来，关节向下，敲了一下屏幕。

   咔嚓。

   屏幕裂了，裂出一片蜘网。

   阿贝莉亚抬头看他了。他也抬头看她。他此时心情复杂，两股声音在他心底大战：一个声音让他摆出和阿贝莉亚一样的手势，然后砸她脑袋上；另一个声音让他臣服，为她说明，这手机太脆弱了，经不起她钻石般的手指触碰。最后，两个声音都被他压下去了。

   "这是什么？"阿贝莉亚问。

   "这是我的命。"红黎说。

   不管她再怎么用眼神威胁他，他就是不移开眼睛。他在说真话，没骗人。

   "它碎了，你怎么没死？"阿贝莉亚说。

   "我的心死了。"红黎的眼睛往天上看——只有天花板。

   她的手中传来细碎的声音。她递来了一串翡翠项链。

   她要贿赂我。红黎心想。他没伸手去接。

   她的手在半空中搁置了几秒钟，然后移向了桌面，把那项链放在了桌上。

   "这里是哪里？"她又问。

   "这里是世界第一的医药大学。"他胡说八道。

   "这是什么？"她把手机丢在桌上，指着问。

   又是这个哲学问题。他不是哲学专业的，他只是一个普通的药学学生，学了些半斤八两的化学知识，真正的专业知识都还没接触到——他发现自己不可遏制地开始胡思乱想了。

   她又说："请你具体解释它。"

   红黎端正了自己的坐姿，让自己表现得诚恳一点。"请问你的来历？"

   "现在是我问你。"

   "但是我不知道你的身份，就没法因材施教。"

   红黎觉得自己的表达很准确，她应该感恩戴德地说出自己的身份。然而，阿贝莉亚朝他伸出了一只手。她的掌心按在了他右眼上；那大鱼际肌群和小鱼际肌群吸住了他的眼眶，那一瞬间，他感觉自己的眼眶好像变得真空了，连光线都没能逃脱掉。不是的，他只是被遮住了眼睛而已。他后悔自己没能及时躲开。红黎抓住了那只手的手腕，想把它从自己的眼睛上扯下来。那手腕冰凉入骨。

   "别动，否则我把你眼睛剜下来。"

   红黎松开了手。

   她静默地维持着这个状态。她的上身微微前倾，这样才能让她自己的手够到他的眼睛。她的眼睛正盯着他的眼睛看——他那唯一的看得见的眼睛。周围的光线越来越暗了，他几乎只看得见阿贝莉亚的那双眼睛了。他被按住的眼睛传来一丝搏动。那到底是他的心跳，还是从阿贝莉亚的手掌上传来的脉搏，他难以得知。他心底氤氲起了些许害怕，也许阿贝莉亚打算对他洗脑。

   她的手离开了。

   红黎眨了眨眼睛……那只脱困的眼睛久久也难以回复光明。他闭上完好的左眼。他的右眼看到的是一片漆黑。据说，瞎子眼中的世界是一片虚无，而不是黑暗，因为黑暗也是一种光感。这样想，他的右眼并没有瞎。他摸了摸自己的右眼眼球。眼球还在，没有被摘走。

   "现在你可以告诉我来历了？"红黎说。

   阿贝莉亚的那双眼睛越来越亮了，眼底的深红色也越来越刺目了；她似乎是想借此隐藏自己的情绪，而给予他恐惧的情绪。她越是这样，红黎反而越是不害怕。

   "你为什么没有恐惧？"

   "我害怕啊，你看见了吗，我的嘴角在抽搐。"红黎故意扯了两下嘴角。

   "你没有恐惧。"

   "哈哈哈，"红黎故意笑了，"因为我知道你会把光明还给我的。"

   阿贝莉亚的手又按在了他的左眼上。

   大约过了一分钟，当阿贝莉亚的手离开时，他的左眼也看不见了。现在他的眼前只有黑暗。他的呼吸变得急促了，但他努力让自己变得冷静下来。人的感观不只有眼睛，天地下那么多的盲人都在坚强地活着，他为什么要害怕？

   "现在你可以告诉我来历了？"红黎说。

   他看不见，不知道阿贝莉亚的神情变化。他听不到太多，阿贝莉亚微不可闻的呼吸被教室外传来的喧嚣给淹没了；但有那么一会儿，她的呼吸好像变得急促了，像是在暴风雨夜的海洋中加急上浮的木筏。

   红黎调整了一下坐姿。他坐下的坐板发出嘎吱嘎吱的声响。这样的声响比他过去几年里听过的都要响，好像声源就在耳蜗一样。他失去的光明似乎转化成了听觉能力了。

   这时，红黎感觉自己的两颗眼球被什么戳中了。凭触感，还有那冰凉的温度，他觉得是阿贝莉亚的两根指头。他本能地战栗了一下。但是他克制了逃跑的冲动。他心想，既然她夺走了他的光明了，那么即使她再剜走了这两颗眼球，那又如何呢？于是，他就这么坐着，等着，甚至上半身前倾，让她作业起来更轻松些。

   过了一会儿，她的两根手指离开了。

   他黑暗的世界逐渐渗入光明。再过了一会儿，他眨眼的时候已经能看见这个教室了。阿贝莉亚抱着胳膊坐在雪白的扶手椅上。红黎再看看教室的各个角落，那些地方好像都藏着他从未发现过的秘密一样；他站起来，坐下的坐板啪地打在身后的座位上。

   "你坐下。"

   红黎还在感动于自己重获的光明，哪里管她说的什么。

   "我不是这个世界的人。"她说。

   红黎坐下了。他发现自己完全无法否决她的说法。不知为何，他想到了一个月前，那个夏末的时节，在这滨海的地区，忽然满天飞雪了。全校的学生大呼世界末日。警车呜呜呼啸，开到了宿舍楼下，把他对面寝室的学长给带去了警局改造了。好像那学长是造谣者。他还想到了，在隔一天的早晨，他在积雪堆中发现了一颗漂亮的水晶……

   咚、咚。

   阿贝莉亚在敲桌子。

   "它是什么？"她重复。

   她怎么这么有耐心，又心地这么好，居然把他失去光明的眼睛给治愈了？……红黎一时间有种冲动——他的冲动一来，他就控制不住了。

   "它是我的变身器。"他要试探她耐心的极限。

   她青紫色的五指抓住了他的肩膀。他马上准备道歉了，然而，他的视野倒了过来——他人倒过来了。阿贝莉亚提着他的脚站了起来。从他的视角上看，他清楚看见了她长靴上缠绕的长长鞋带，最后在鞋面上绑成了一个漂亮、端庄的蝴蝶结。这意味着什么？……

   他的思考变得迟钝了。因为他浑身的血液都在往脑袋灌。他的身体素质好像经受不住这样的折磨，他感觉脸颊像烧起来了一样，脑袋好沉，好重。他憋住一口气，不让自己求饶出口。且听听她是怎么说的。

   "像这样变身吗？"她说。

   "这只是形体上的变身——我说的是社会意义上的变身——它让我真正成为人——否则就是猴子——"他倒着说话好累啊……但是，阿贝莉亚没弄死他，这说明他赢了。她也不过如此。

   阿贝莉亚把他正回来了，然后把他丢在座位上。座位的坐板还没按下来呢，他被迫一屁股坐在了地上。

   他站起来了。他发现自己比阿贝莉亚要高半个脑袋。

   "你演示给我看，你要如何用它变身。"

   她指着那个屏幕碎成网状的手机。

   "它坏了。"红黎说。

   阿贝莉亚把桌上的翡翠项链推向他。"把它修好。"

   "一时半会儿修不好。"红黎说。

   "要多久？"

   "要一年。"

   她一拳打在了他胃的位置。他佝偻下来了。好痛苦啊，他感觉自己要死掉了。他不断干呕……过了一会儿，他发现自己又生龙活虎了。不过，刚刚的痛苦他不想再承受一遍。

   "我要给专业的人修。"

   她说："你修好，明天来这里找我。"

   红黎好心提醒她："你可能等不到明天，你或许等会儿就会被警察抓走。"

   "执法的？"

   "我一离开这里，也许就会报警。"红黎露出了真诚的笑容。

   她不说话了。

   操场方向传来一声喝彩，好像有哪一精彩的球得分了。

   阿贝莉亚缓缓地眨了一下眼睛。那睫毛漆黑而浓密，像那即将掀起暴风雨的蝴蝶的翅膀。

   她说："你知道该怎么做。"

   "我懂了。"

   红黎决定明天过来和她讨价还价，因为这算阿贝莉亚欠他一个人情了。

   她侧身，一挥手，雪白的扶手椅不见了——之前她用的茶杯更是早就不见了。

   红黎知道她要走了，所以马上抓起桌上的翡翠项链，递到她面前。

   "你明天再考虑给我。"他说。

   她在用审视的目光打量他，最后，她还是收起了那项链。

   她踱过了过道，经过了讲台，到了窗边。她揭开了窗帘，推开了窗户。她轻轻踮脚，人就飞到了窗缘上。她的身高让她需要弓下腰，才能容在窗户的高度内。她跳了下去。

   当红黎跑到窗边时，下面并没有尸体，或者她的任何踪迹。赭红色的砖石地面有一两名学生在行走，相互交谈，全然没有注意到刚刚有一个女人正从五楼的窗户往下跳。

   红黎退开窗户，走到墙边，把脑袋往墙上撞……

   好像发生了很多他难以理解的事。

   他走到最近的座位上，按下坐板，让自己坐下。


## Chapter 2


   红黎外出修好了手机之后，马上用WeLine联系红伊水，告诉她，自己不久前遇上了一个和她长得一模一样的人。但是红伊水说："滚。"他回到学校，找上了她所在的教室——他向班级同学打听了她的班级的课程——他等到下课，马上冲到她位置旁边，冲她说："我是认真的，我没在开玩笑。"红伊水环顾了一圈，又说："滚。"红黎就是不滚，他要给她解释清楚。他的直觉告诉他，这件事肯定和她有关系。然而，红伊水推了他一把，可能使出了浑身解数；他往后跌去，后背撞到了桌子的棱角。那棱角像钢刀一样扎入了他的后腰。他再硬的嘴，也只能因为生理性的疼痛而呼天抢地。

   他觉得自己简直是个蠢货，这么有趣的事情，就该自己一个人独享，告诉别人干什么呢？——告诉谁不好，偏偏要告诉这个视他为仇敌的非直系亲属的红伊水。他爬出了这个教室。他在走廊上再爬出几步远，又生龙活虎了。

   红黎回到了早上的那间阶梯教室，坐在那里胡思乱想。一个下午的时间，他只确定了一件事：这件事也不能告诉警察，他们要么会以为他是疯子，要么会把他的乐趣抢走。他要一个人独守秘密。

   红黎的计划终究只是计划。第二天早上他奔往教学楼的时候，看见了额头敞露的阿贝莉亚——至少从额头和气质上看，她的确是阿贝莉亚——她正被几个高年级生打招呼，说："学姐好。"发生了什么？……他不知道。红黎凑进了阿贝莉亚，问她这是怎么回事。阿贝莉亚没有理会他。但是她的确往昨天的阶梯教室走了。

   阶梯教室的门是锁着的。红黎正想告诉阿贝莉亚，让他们换个教室；然而阿贝莉亚握住了把手，她再松开的时候，那嵌入门中的锁被她整个掏了出来。天知道发生了什么，之后又会发生什么。红黎对阿贝莉亚说："这是你干的，和我无关。"

   他们进入教室后，阿贝莉亚又把那锁安了回去。但现在，那锁只是图有其表了。

   阿贝莉亚冲红黎说："给我买一部手机，再弄一张电话卡。再弄一个身份证。"

   "前两个我可以做到，最后一个我做不到。"

   "前两个。"她说。

   红黎笑了，他说："我为什么要帮你？"

   "我可以帮你摘掉你不要的眼睛。"她说。

   红黎埋头，掏出自己的手机一阵操作，在网络上找到了一系列的：军事演习视频，有关一系列的战车、飞机、大炮；还有核弹、氢弹爆炸的视频——通通给阿贝莉亚看。阿贝莉亚虽然没有目瞪口呆，但是久久不语。红黎满意地收回了手机——他的手机不见了，出现在了阿贝莉亚的手中。

   "在你买的手机到之前，它属于我。"

   红黎现在相当困扰，他原以为自己给她看的视频能让她收敛点，然而，这毫无用处。她还是为所欲为。他发现，自己根本没办法牵制住她。他必须得想个办法。

   "阿贝莉亚，你知道自己为什么出现在这个世界吗？"

   阿贝莉亚的两只手掌按住了他的眼睛。她说："你知道什么？"

   红黎的眼球受到了极大的压迫，他担心自己要是回答不慎，会像西瓜一样暴裂。

   "嘿，我就是知道一个和你长得一模一样的人。"

   阿贝莉亚松开了手。

   "你买的手机和电话卡到了之后，通知我。"

   阿贝莉亚走向了窗户。她手往窗缘上一撑，人就翻身跳了下去。

   虽然红黎承认她这样很帅，但是，他根本还没有订购好手机和电话卡啊，他需要手机来订购。

   …………

   阿贝莉亚来也匆匆，去也匆匆，红黎的算盘全都白打了。他本打算从阿贝莉亚口中探得情报，她到底是谁，来自哪里，为什么会有那般身手——最重要的是，他要学到她那样的身手，成为动不动就能拿摘掉别人眼球威胁别人的人——他比阿贝莉亚善良多了，只会吓唬吓唬而已，不可能真的那么做。但是，阿贝莉亚没有给他人任何视线的机会。他一筹莫展。他独自在阶梯教室内思考。后来，他想到自己并非没了机会。不久前，那些高年级学生喊她为学姐，说明她现在混迹在了这所学校——虽然不知道用的什么样的卑鄙手段——或许他可以从这个方向寻找线索。

   他在学校里溜达了两天，基本确信了，阿贝莉亚现在混入了药学楼——教学楼对面的那幢大楼——三楼的实验平台。他想要进一步去打探，但是不敢轻举妄动。阿贝莉亚有非凡的身手，那么她有非凡的反侦察技术几乎是理所当然的；甚至可能有那种神乎其技的感知能力，一旦靠近了一定距离，就会被她感知。他得另想办法。

   第三天的时候，他买的手机和电话卡到了。他不知道该怎么连络阿贝莉亚好，迟疑了一会儿，他还是决定直接去实验平台找阿贝莉亚。不出所料的是，阿贝莉亚拿上了手机和电话卡就走了；出乎意料的是，她给了报酬——一枚造型简洁、光泽内敛、但给人的感觉却是千锤百炼般的戒指。他很中意这枚戒指，没舍得还给她。他捏着这戒指鼓捣来去，可就是没发现它到底隐藏着什么样的奥秘。

   红黎追上了阿贝莉亚，让她把他的手机还给他。阿贝莉亚咋舌了一声，把他的手机丢了出来；红黎慌乱中接住了。然后，红黎让她加上他的WeLine账号。她还没有账号，于是，红黎顺便帮她注册了一个。红黎顺势跟她说："你现在欠我一个人情了。"不知道她听懂了没有。

   第四天，他还没想到办法；但他更没想到，办法找上门了。阿贝莉亚在他寝室楼门口堵他。他一来，她马上说："跟我过来。"红黎不知道她要去哪，但他会奉陪到底。阿贝莉亚一路把他带到了药学楼三楼，穿入一间放着长长会议桌的房间。会议桌中段摆着一台笔记本电脑，旁边是阿贝莉亚的手机。阿贝莉亚过去，在那张人体工学的办公椅上坐下，然后踢来一把滚轮圆凳，让他坐下。红黎坐上去，踩着地面，凑到她旁边。随后，阿贝莉亚拿起她的手机，要他教她手机如何使用。"好。"红黎答应了她，同时在心底记下了这个人情。

   第五天，阿贝莉亚用WeLine联系他，让他到药学楼三楼。红黎马上把课翘了，直奔昨天那会议室。事情很古怪，阿贝莉亚站在会议室门口迎接他。这事情太古怪了，以至于红黎呆滞在了实验平台的门禁口。他马上反应过来，阿贝莉亚只是凑巧站在那里而已。他走过去。阿贝莉亚脸色平淡地和他说："你来了。"红黎又呆滞住了。平时阿贝莉亚都是脸色阴沉，今天却变得平淡了，这是怎么回事？……他要是问，阿贝莉亚不可能说，所以他只能胡思乱想：阿贝莉亚在这个世界逗留太久，受到了全球变暖的影响。他们进了会议室。阿贝莉亚说，她要让他教她电脑如何使用。红黎满口答应。

   一个小时后，红黎口干舌燥了；但幸不辱命，阿贝莉亚已经能够基本使用电脑了。

   "黎，你看过哪些书？"

   "我可以例举一年。"

   阿贝莉亚专心致志地操作着电脑，鼠标划拉来去。她在查询有关网络和电脑的技术知识。她看似漫不经心地和红黎闲聊。但是红黎打起了十二分精神听她讲。

   她接着说："你看过一本关于复仇的书吗？"

   "《基督山伯爵》？"

   "书里的某人被折磨成了灵魂，被暴虐的作者反复折磨，在那人的妹妹面前。"

   "他们叫什么名字？"红黎根本没听说过这样的书。

   "好了，你可以回去了。"

   红黎不知道自己哪里回答错了，被阿贝莉亚轰了出来。

   现在，红黎手中握着阿贝莉亚的两个——三个人情。第一个人情，红黎不知道她会不会认可，但是剩下的两个人情可是铁打的，他可要好好从长计议，从阿贝莉亚那里弄来一些好处。

   红黎每天想着这样的事，同时，旁敲侧击地去打探阿贝莉亚的身份，虽然一筹莫展。他发现最近，阿贝莉亚一直沉浸在实验室里。她偶尔会叫他去帮忙，给他打工，诸如整理表格、搜集文献之类的。这些工作是科研性质的，看起来像是阿贝莉亚现在的上司让她做的工作，不过，被她推到他身上来了。红黎一点都不喜欢这样无趣的工作，但是他并不介意让阿贝莉亚欠他更多的人情。但是他心中有了疑惑，为什么这几天，阿贝莉亚会对他这么殷勤？——对于阿贝莉亚来说，想方设法摘掉他的眼球才是正常的。

   令人敬畏的是，时间过了几天之后，他再度来到实验室后，阿贝莉亚使用电脑时已经脱离了鼠标，连操作系统都换了，变得像电影情节里的黑客以一个黑框界面操纵着电脑。他根本看不懂她在做什么，只能看见一个光标令人头晕目眩地跳转着，跳转着，出现一些意义不明的代码。阿贝莉亚对他说："之后你可以不用来了。"红黎只能垂头丧气地走了。他觉得，自己可能对于阿贝莉亚来说毫无利用价值了。


## Chapter 3


   …………


## Chapter 4


   这一日，红黎上完课回来，看见盘旋的警车包围了男生宿舍楼。附近的学生们被警察驱离了宿舍楼。然后警察在宿舍楼下布置了包围圈。在大厅入口那儿，有几名警察将一个个学生从宿舍楼内领出。附近的学生们都在躁动，都在不安，也都在兴奋。他们聚集成一团，眺望事发点。红黎看他们一片热闹，于是也围过去，打听发生了什么。他只是听得了：有学生失踪了，有歹徒闯入校园，现在似乎藏身于宿舍楼。具体情况如何，这会儿的学生们都忙着看热闹，没空搭理他。

   不知前因后果的红黎，马上给阿贝莉亚发消息："你的身份要暴露了，马上来男生宿舍楼。"

   他一眨眼的功夫，旁边的学生们吵啊嚷啊，他们的脑袋围在一起，挤成一个六边形的巢房。红黎问他们在干什么，他们说，有个天杀的东西的对象正在女生宿舍楼上转播现场的情形。红黎听了，也化成了蜜蜂，往那巢房里挤。他勉强挤进去了，中间一个小个头男生抱着一个平板电脑，蹲坐在那里。旁边都是黑漆漆的人头。

   屏幕中，一位青年正护着自己的背包，不让警察夺走。这青年戴着鸭舌帽，低垂着脸。有警察夺走了他戴的帽子，他的脸暴露在了众视线之下。警察以机器扫脸验证。他们议论了一会儿，这人好像身份没问题。他们要给他放行了。但最后时刻，一个警察抓住了他怀中的背包的背带，猛地一拽——那青年转身，推了一下那拽他的警察。警察消失了。他又推了一个向他出手的警察，那警察也消失了。

   红黎面前的一个脑袋挺了起来，那黑溜溜的后脑勺打中了他鼻子。红黎仰头，捂住鼻子。他感到一阵痛苦，又是一阵酸楚。眼泪被迫挤出了眼睛。

   周围的学生们大呼小叫。

   砰。

   这是什么声音，枪声？

   学生们都安静了。

   学生们急匆匆地往食堂内躲。红黎跟着他们一起，感到自己的心脏嘭嘭直跳。其实他有种冲动，要冲过去和歹徒一较高下——他总觉得，自己和阿贝莉亚待一起久了，就会拥有哪些特殊能力——他按捺住了自己作死的冲动，跟着学生一块儿跑。前面的学生跑向了食堂深处，和那儿的工作人员乱成一团。红黎和少数的学生们一起，挤在食堂门口处。

   红黎怀中多了什么。他低头，发现那平板电脑不知为何出现在了他怀中。估计刚刚谁慌乱中错塞给了他。

   枪声响了，但事情还没有结束。在那平板电脑画面中，那歹徒大摇大摆从警察包围中走了出来。周围的警察拿枪对着他，追着他，但就是不开一枪。那歹徒哈哈大笑。他的脸很怪异，脸廓一圈垂落着面皮一样的东西。有人说，他带上了易容的那种面膜，现在撕下来了。

   歹徒紧搂着自己的背包，他的另一只手——右手一伸，凭空出现了一个女生；那女生往前倾倒，他的右手挽住了那女生的腰；那女生还在往前倾倒，带着那歹徒一个趔趄。周围警察往前涌。那歹徒一跺脚，大声吼叫，声音远远传开："不许动！"周围的警察的面色一阵青，一阵紫。但他们还是退开了两步。那歹徒嘎嘎直笑，笑得喉咙破了风一样。他一路大摇大摆，往食堂的方向过来了。

   那歹徒一回头，叫一个女警察上前。女警察看向领队……那歹徒从包里取出一把水果刀，抵着怀中的女生的脖子。那女生正昏迷不醒。歹徒把她脑袋往后掀，露出了细长的脖子，然后把刀锋抵在上面。他的刀锋压着脖子，银色的锋芒压出了一条血丝。那女警察大声吼叫……歹徒收回了刀，然后优哉游哉地把背包背在身后，换成了左手搂住女生，右手拿水果刀抵在她的脖子上。歹徒又是一阵大笑。

   学生们在讨论警察为什么不一枪崩了歹徒的脑袋。这些天真的孩子们以为这样就能解决问题，如果真的是这样的话，那么他们才是警察了，轮不到外面那些人指手画脚。现在，屏幕中的画面摇晃得越来越剧烈了，可以看得出，拍摄的那个女生正在害怕——那画面最后一阵天旋地转，啪的一下，黒掉了。学生们大吼大叫，把所有的错误怪罪在那女生身上，还有她的男朋友身上。

   有人打了一下红黎的肩膀。他差点以为自己也要成了"罪人"，但来人是阿贝莉亚。她说："你帮我调查一件事。"

   他马上说："阿贝莉亚，现在有一个绝顶的好机会，让你拥有身份证明。"

   "嗯？"阿贝莉亚的注意力被他吸引住了。

   "你去帮忙制服那个歹徒，这样，那些公务员就会对你感恩戴德，痛哭流涕地帮你把身份证办起来。"

   阿贝莉亚拍了一下红黎的脑袋，然后踱出食堂的侧门。她后方躲着的学生们让她不要犯傻。阿贝莉亚没理会他们。她仰着天鹅一样的脖子眺望着歹徒的所在。她一个人伫立在食堂门口，像一面黑色的大旗，像是在对歹徒挑衅一样。红黎觉得，这么酷的机会不能只让阿贝莉亚一个人逞威风。他轻手轻脚地跟到她身后。

   那边，歹徒正和警察说着什么——是在胁迫。歹徒往这边过来了。

   阿贝莉亚对红黎说："我为什么要帮你？"

   红黎帮她纠正："你是在帮你自己。"

   阿贝莉亚凝视着他。这是不信任的眼神。

   红黎说："信我，这对你来说是有利的。"

   阿贝莉亚的两根指头戳中了红黎的眼睛。

   红黎赶紧躲开了那冰凉的指头，说："那我答应你刚刚的事情。"

   "你说我身份暴露了是怎么回事？"她问。

   "你要是不来，就可能被我暴露。"红黎说着，躲开她两步。

   但阿贝莉亚大人大量，没有和他一般见识了。她低头在那儿沉思。她可能在考虑他刚刚提的条件了。但是她考虑的时间有点太长了，长到歹徒都往这边走过来了。因为阿贝莉亚在这儿呆着，红黎也不好走开。他只能舍命陪君子了。其实他期待着，歹徒过来后不识好歹，然后被阿贝莉亚三两下干掉了，随后周围掌声雷动——好像有点无聊。

   歹徒正虎视眈眈盯着红黎，手里摩挲着身为人质的女生的脖颈。

   红黎往阿贝莉亚靠近一步，然后对歹徒眨眨眼。

   "给我弄来一辆车。"歹徒回头喊道。

   之前的女警察跑了出去，也许是按照歹徒的吩咐去做了。

   歹徒过来了，他瞪了一眼阿贝莉亚，然后朝红黎招招手。红黎指了指自己的鼻子。气从歹徒的鼻孔里喷出去，他哼了一声，好像是表示确认了。于是，红黎朝歹徒踱步而去。

   那歹徒露出了惊愕的眼神。"你是条子？"他说。

   "我是学生啊。"红黎不解。

   歹徒的眼神在红黎和阿贝莉亚之间徘徊。最后，他只是哼了一声。等红黎走近后，他让红黎转过身来，又让他举起手来。红黎完全依照他说的做。红黎转过身后，看向阿贝莉亚。阿贝莉亚还在那儿沉思。

   "你来帮我开车。"歹徒说。他揪着红黎的肩膀，把他扭到正面，然后瞪向他。歹徒把眼睛瞪得老大，那张挂着面皮一样的脸看起来有些滑稽——或许也有些许的可怕——红黎想笑。他还是忍住了不笑。歹徒皱起了眉毛，看起来很困惑。

   "你这厮，不怕？"

   "我……害怕啊！"红黎抱住脑袋。

   歹徒哼了一声。他看向警察成堆的方向。警察们都举着手枪，对准了这歹徒的脑袋。歹徒故意大笑几声——他的声音听起来没有丝毫笑意，只是在挑衅警察而已。然而，歹徒又拍了拍自己的背包，然后用大拇指做了个割脖子的动作。他又啐了一口痰到地上。这口痰差点吐到红黎的裤腿上，惊得他往边上一跳——他被那痰吓了一跳。可不知为何，那歹徒被他吓了一跳，浑身一抖，又瞪向了他；那双浑浊的眼睛里满是猜疑。那眼睛绕着红黎的衣装一圈审视。红黎猜到，这人还在怀疑他，而且怀疑他身上藏着手枪。

   先前离去的女警察开了一辆黑色的汽车回来，停到了食堂侧门前。警察下车了。歹徒向她下命令。于是，女警察又不得不把钥匙丢给了歹徒。

   歹徒踢了红黎一脚。"你来开车。"歹徒说。

   "啊？"红黎呆住了。

   "快！"

   "我不会开车啊。"

   歹徒呆住了。"你这厮，大学生不会开车？"

   "我没学。"

   歹徒脸色阴晴不定。过了一会儿，他笑了。"你坐上去，我教你。"

   "我是祖国栋梁，我遵纪守法。"红黎大声说。

   "好！"喊话的是歹徒后方警察堆中的一个年轻的警察。但旁边的一个年长的警察给了他脑袋一巴掌。

   "喂——"

   把车开过来的女警察想说什么。歹徒让她滚。歹徒给她比了个中指，然后抄着水果刀，在挟持的女生的手腕上划了一刀。那雪白的肌肤上出现了一刀殷红的伤疤……咄咄咄。脚步声。先前那年轻的警察冲了出去——但是被年长的拉住了。年长的又拍了一下年轻的脑袋。

   歹徒又踹了红黎一下，让他坐上车。

   红黎没办法，只能照办。他走近这辆黑车，抓住门把手……透过灰黑的车窗，能看见那陌生又充满科技感的驾驶座。他把车门拉开了。车内独有的油臭味飘了出来，让他浑身一个哆嗦——一串钥匙砸中了他的胸口。他伸手接住了。

   "我会开车！"女声喊道。

   红黎惊喜，循声望去——他失望了。说话的人不是阿贝莉亚——她当然不会开车。一个女生从餐厅内冲了出来，气喘吁吁。她扶着膝盖。她的手和脚都在颤抖，也不知道是害怕得，还是累得。但是她刚刚的说话声洪亮。她又重复了一遍："我会开车"。她的说话声依旧洪亮。

   红黎觉得这个女生眼熟，应该是他班级的女生。她穿得青春靓丽，实在难以想象，这样一个女孩为什么要在这时候冲出来。

   "哦？"歹徒做着夸张地挑眉动作。

   "我来开车，你放他走。"她说。

   歹徒膝盖顶了一下怀中的女孩的屁股。他咧嘴一笑，说："不可能。"

   "我是说他。"女孩伸手指向红黎。

   红黎不解了，他又不是人质，放他走有什么用。

   "嗷呜？"歹徒做出了更夸张地挑眉动作，他上半身都仰了过去。他继而哈哈一笑，一脚踹向红黎。红黎早准备好了躲他这一脚，往旁边一缩。歹徒踹空了。歹徒明显没练过什么拳脚功夫，这一脚过去，人就倾斜了。但是他还是没有摔倒。可惜了。歹徒的脸色阴沉了下来。

   "我来开车！"靓丽的女孩喊道。她向红黎伸手。她这是在向他要钥匙。她的目光灼灼，她的眼皮一直在跳，但是她就这么盯着他看，仿佛在证明，自己并不害怕。

   红黎不可能把钥匙丢给她。他回头，抬手，把钥匙丢向阿贝莉亚——本来应该是这样的——

   砰、砰。

   枪声响了两下。

   突如其来的枪声让红黎的手一抖，钥匙被向上抛飞了起来。

   啪一声，歹徒手中的背包掉到了地上。那背包的背带在下端的卡扣那儿断了，两条都断了。枪声让那歹徒哆嗦了一下，怀中的女生摔了出去。他正要弯腰去扶，但是警察冲过来了——先前开车过来的警察大声一吼……歹徒推了他一下，那警察消失了。歹徒的背包好像鼓起来了一点。

   那歹徒俯身去抢背包。

   砰、砰、砰、砰……

   枪林弹雨扫射而来，每一枪都打在背包周遭，但就是一枪都不打那歹徒。

   歹徒脸色瞬间变幻。他一个扭身，夺走了坠落到地上的钥匙，钻向了旁边汽车。在枪声中，他钻进了驾驶座，嘭的一下关上了门，然后发动了引擎。

   警察包围过来了。

   这会儿，红黎终于想起了那个化身稻草人的阿贝莉亚。她好像稻草人时间结束了，朝他走来。她夺过了他的一只手，然后另一只手按在他的肩膀上——她要干什么？……红黎正这么想着，他就被阿贝莉亚扛了起来。他被阿贝莉亚扛在了肩膀上，脑袋朝后。他不知道发生了什么，为什么会这样。这时，他觉得自己很呆，居然不知道反抗；但是有比他更呆的人——那靓丽女孩正瞪大眼睛盯着她。红黎心想，阿贝莉亚肯定很中意这样一双眼睛……


## Chapter 5


   阿贝莉亚扛着红黎，在马路上飞奔。街道上涌来此起彼伏的杂音：汽笛声，汽车穿行声，自行车铃声，喧嚷声，嬉笑声，还有犬吠声。红黎忍不住放开了捂住脸的手。他睁开眼睛，一连串的画面撞了过来。阿贝莉亚在马路上超过了一辆又一辆的汽车。一股欢欣的气息从他心底生起。他忍不住想要大声喊叫。

   阿贝莉亚把他丢在了地上。

   这是是一处十字路口，一排的车辆正等在红灯的前面。其中一辆是歹徒坐着的那辆。这时，对面欢声笑语地走来一排女生——其中一人居然是红伊水。那张和阿贝莉亚一模一样的面孔正和朋友有说有笑。她丝毫没留意到，马路对面的阿贝莉亚正朝她走近。红黎浑身一个哆嗦，激动了起来，他冲过去，超过了阿贝莉亚，跑到红伊水面前；也不管那六七个脑袋一顿问号，把拳头握成麦克风，递向红伊水。

   "如果世界上有和你长得一模一样的人，你会有什么感想？"红黎说。

   "滚。"红伊水说。

   红黎回头去看阿贝莉亚。这时的她走到了那辆歹徒的车子侧面，单手掰下了车门把手。阿贝莉亚还在折磨那扇门，试图徒手打开它。那辆车疯狂叫着喇叭，然后马力一阵鼓噪，要冲出去了——阿贝莉亚一只手嵌入了那车门，随着她身子的一阵摇曳，她硬生生把那车给拉住了。在阿贝莉亚的手中：那辆车不停地蹦哒，可就是跑不了；那轮子不停地撕咬着地面，可就是无法朝前半步。

   红黎惊呆了。

   那歹徒从驾驶座那边蹿了出来，要跑掉了。阿贝莉亚丢开了那车子——那车子嘭地一声撞上了旁边的电线杆——朝歹徒快步而去。歹徒揪住路边的小孩，往阿贝莉亚丢。阿贝莉亚把她接住，放地上。阿贝莉亚大步朝前，她的眼睛像是燃烧了起来一样，那暗红色几乎变成了猩红色。她脚步紧咬着歹徒逃跑的方向。那歹徒越跑越狼狈，一步一个踉跄。他又开始狼嗥鬼叫了，说是见了鬼了，见了妖怪了，快救命啊……他钻进了一家服装店。阿贝莉亚也跟了进去。里面传来一阵惊呼声和一串破碎声，然后是男人的怒吼声和女人的尖叫声。嘭。嘭。嘭。里面像是过年一样，不停地放着烟花爆竹。啪。啪。啪。那一定是一连串的镜子或者橱窗破碎的声音。有人在怒吼："快住手——"一群顾客逃了出来，惊魂未定地回头去看……不久，歹徒像是一团垃圾一样，在空中划出一道抛物线，掉在了地上，然后一路翻滚。

   红黎跑过去，要去见证这歹徒的身死。他身旁还有一阵脚步声。是红伊水跟着他一起来了。他赶紧问她："你觉得这是在拍电影吗？"

   "原来是在拍电影啊。"红伊水停下了脚步。

   红黎心里恨铁不成钢。

   警车呼啸而至，盘旋而来，围拥而上。那些制服们冲下了警车，插入人群中，把他们一个个推赶走；还扣下了他们正在拍摄的手机，警告他们不要造谣传谣。红黎马上也受到了他们的热情款待，他被迫跟着人群，离开了肇事地。他听见了阿贝莉亚在喊他，他只能朝她挥挥手。阿贝莉亚看见他了，然后就没理会他了。这算什么？……红黎在围观人群那儿站定。这时，他发现红伊水就在他的身旁，正扭捏地看着他。

   "你说有个和我长得一模一样的人。"她说。

   "我马上滚。"红黎掉头就走。

   他的衣角被拉住了。

   "非礼啊！"红黎大叫。

   红伊水触电一般缩回了手。

   红黎满意地回头看她。

   "你有那人的联系方式吗？"

   她居然还敢说话。他怎么可能把阿贝莉亚的联系方式告诉她？他怎么可能把阿贝莉亚的联系方式告诉她？……他怎么可能把阿贝莉亚的联系方式……红黎改变注意了。他想起来，阿贝莉亚刚刚过马路的时候，没有往红伊水身上多看一眼。这太奇怪了。就像她早就知道会有又这么一个人会和她长得一模一样。可当时他和阿贝莉亚提起这件事的时候……红黎决定让她们两个人摩擦碰撞。

   红黎把阿贝莉亚的WeLine二维码展示给红伊水。红伊水看起来满心欢喜，掏出自己的手机来扫——红黎马上缩回了自己的手机，眼见着她的脸色变得僵硬了，问她："那人让你什么想法？"

   红伊水的眉毛扭曲了，她的眼珠子膨胀了，她现在肯定想打他；但她还是老老实实地说了："我感动啊！"

   "你感动什么？"

   红伊水一把拽过了他的手机。滴。她擅自扫了他手机上的二维码。她得逞之后，马上换了脸色，说："关你屁事。"她屁颠屁颠地跑了。她和她的狐朋狗友们汇集到了一起，叽叽歪歪地走了。

   红黎历经了好一会儿的苦大仇深，才回过神来。现场的人走得走，散得散。警察们的车子早就不见了，阿贝莉亚也不见了。周围都是些无业游民，或者老弱病残，在那儿感慨上天的美好、生活的美好。红黎一脚踢飞了地上某螺丝配件，大感无趣。

   他给阿贝莉亚发消息："我给你介绍了一位新朋友。"

   …………

   红伊水恨死了红黎，恨到：在小说里把他的灵魂千百遍折磨，又不肯轻易让他死去。她把红黎弄成了一个勾子，勾着阿贝莉亚从这儿跑到那儿，又从那儿跑到这儿，翻来覆去。要是阿贝莉亚活着的话，估计会被她气死；但阿贝莉亚又怎么可能活着呢？阿贝莉亚只是她虚构的而已。阿贝莉亚是她虚构的，小说里的那个红黎当然也是她虚构的。她恨透了红黎，在现实里拿他没办法，在小说里就要使劲折磨他，让他不得好死……红伊水现在很烦，她明明恨透了红黎，现在却不得不给他发消息了。因为疑似她的狂热粉丝的那人一直没有回复她，即使她明确说了，自己是那小说《白心呼吸》的作者。

   红伊水迫不得已发消息给红黎：你认识阿贝莉亚吗，你怎么认识她的，和我说说阿贝莉亚的情况……

   过了一个晚上，红黎依然没有回复她。

   红伊水一大早早饭都没吃，跑去男生宿舍门口堵他。宿舍门口的阿姨可太没眼色了，居然说她是过来等男朋友的；要不是那老婆子还能倚老卖老，她早就一巴掌掴过去了。她警觉了，她怎么能如此暴躁……她把这件事归咎于红黎。她放缓了自己的心态，然后和颜悦色和那阿姨打招呼。那阿姨果然夸她乖巧懂事了。

   她一直等到中午，才等到姗姗出门的红黎。

   她问："你是怎么认识昨天那人的？"

   "阿贝莉亚？"

   "她叫这个名字？……她怎么可能叫这个名字，她的真名叫什么？"

   红黎好像要跑了。红伊水张开手拦住他，不让他跑掉。她推着他，把他推到大厅内部的桌椅那儿，把他往椅子上按。

   "你要干什么？"他问。

   "我问你那人的事。"

   "这关我屁事啊。"他说。

   红伊水忍辱负重，说："昨天是我错了。"

   红黎张狂大笑……他终于笑得差不多了。他说："我告诉你一个秘密，阿贝莉亚其实不是这个世界的人。"

   这一刻，红伊水对红黎的恨意烟消云散了。她为什么要恨他？……她现在也无从理解自己过去式的感情了。她觉得自己太傻了，为什么要和这么一个精神病人较真？他只是疯了而已，对她、对任何人都没有任何恶意。她觉得需要深刻反省自己。她对红黎感到万分抱歉。

   红伊水说："对不起。"

   他露出了惊骇欲绝地表情，说："啊？"

   红伊水想揍他，但还是忍住了。"以前都是我不好，没能宽宏大量对待你。"

   他沉下了脸，说："你在想什么？"

   "我要先走了。"和精神病人浪费时间没有任何用处。

   "你不信我。"

   现在轮到红黎拦住她了。

   他说："你可以想想昨天：阿贝莉亚她徒手拉住了一辆汽车。"

   她马上说："那是玩具车。"

   红黎目瞪口呆。

   红伊水要走了。但是红黎还是不让走。红伊水心底按捺住的火气要上来了，她想给他一拳。这时，先前的老婆子又路过了，还在那儿聒噪：你们现在还是读书要紧，别急着恩爱……红黎的两只手掌遮住了她的视线，他说让她冷静冷静。现在的红伊水可以原谅他的轻率之举，因为如果不是他，她可能要冲过去把那老婆子打一顿了。

   红黎说："好吧，我不管你信还是不信了，我就想问，你是怎么看待阿贝莉亚和你长得一模一样这件事的？"

   "这与你无关。"

   "你认识她。"

   "我怎么会不认识她？"

   "你为什么会认识她？"红黎问。

   她心底的业火熊熊燃烧。她抓起手机，给她父亲的某个朋友打了电话。电话还在忙音。她借故让红黎让个位置，她要打电话。傻兮兮的红黎丝毫不知情，就这么给她让位了——但是他不准她离开大厅，要她说清楚，还说自己会拿情报和她交换。红伊水越发认识到他病情的严重，于是她越是下决心把这个电话打出去。她躲到垃圾回收处那儿，掩着嘴巴打电话。对面是她父亲的马屁精，她说什么，对方肯定就照做了。她声泪俱下，说自己的这位兄长病情危急……对面一听是她的兄长，更是情绪高昂……


## Chapter 6


   红黎差点被刚刚那个女人亲手推进了精神病院。他迫不得已，打电话联系现在的父母，让他们给自己做保证。他们两人对他追东问西，问他在学校里是被卷入了什么事，和周围人相处是否顺利，问他为什么不肯回来，什么时候回来，郑安若想他了……红黎迫不得已，和他们再三保证，终于挂断了电话。他让校门口那精神病院的车快走。

   红黎想把红伊水拉入黑名单。但是最后，他还是没那么做。红伊水一直怨恨他，因为小时候以来他古怪的行为，她受了波及，几乎交不到朋友，处处受人歧视，甚至被人说：她哥是个精神病，她肯定也是个精神病，大家离她远点……这都是他做的孽，红伊水怎么怪他，都是他自找的。他觉得心累，最后还是红伊水郑重地给红伊水发了一句：我没有精神病。

   她没有回复。


## Chapter 7


   红黎接到了阿贝莉亚的电话，她说，马上会有一辆汽车过来，把他接送到她所在的地方。红黎完全不知道她在打什么算盘。她已经挂断了电话。不久，她所说的那辆车来了。司机出示了自己的警察证件。红黎不再怀疑，坐上了这辆车。

   司机沉默地驾驶着汽车。沿途的车辆变多了，房屋也变得更密集了，街市的人穿来梭往。这一切可以看出，他们正在往市中心前行。红黎的内心没有那么不安了。

   汽车开进了地下停车场。昏暗来得突然，当时，红黎还没注意到周围有像样的建筑物会是这趟旅程的目的地。他记得前一刻周围还都是商业房，没有气派高大的派出所。汽车刹停之后，司机利索地下了车，啪地一下就关上了门。司机给他打开了后座的门，让他消停了自己会被关锁在车里的念头。司机用沙哑的声音告诉他，这里就是目的地，他也不是骗子。红黎跟着他走出地下车库。

   警察司机带着他拐进了一家写字楼。

   他们恰巧挤上了一趟电梯。电梯一层层向上，时而有人挤进挤出，把老实站在原地的红黎丢来丢去。他终于被丢到了墙边了。他稍微抬头，就能看见那些逼仄的目光，在审视他的身份。他们的目光也打量其它人，但是，他的身上被更多的逗留，因为除了他以外，再没有其他近似年龄的人了。电梯还在向上。周围的人稍微变少了点，他至少可以自由地站在那儿了。这时，他可以听见旁边两个制服中年人在那儿窃窃私语。他们在说"那个""这个"，意义不明，然后相互肯定，时不时对红黎投以敬畏——也可能是威吓——的目光。

   他们终于出了电梯了。这儿的高度可能在三十层，透过空中回廊上的窗户，红黎可以对远方的城市和乡野一览无余——他马上觉得不对劲了，他刚刚在楼下的时候，从未望见过附近有如此高大的建筑……警察带着他，一路问到了一间办公房；警察离去了。这儿的门是半掩着的，推门而入后，有数十人在方块分隔的办公间内忙碌劳作。阿贝莉亚也在里面，但是她只是在喝茶，是其中的异类。周围的人很畏惧她，只有在她稍微低头的时候，才肯把那种胆战心惊的目光稍微放出来一点。阿贝莉亚可能早就注意到红黎站在门口了，但是她还是悠哉悠哉地先把手中的茶喝光。

   她终于迎了过来，说："你满头都是冷汗。"

   红黎想找几句话挖苦她，但是一时想不到。

   但是阿贝莉亚追击他了："你为什么满头冷汗？"

   周围人的目光聚集了过来。那些目光不敢在阿贝莉亚身上停留，但是肆无忌惮地在他身上扫射。他不觉得自己的一身打扮有什么值得他们这么关注的，他只是一介学生打扮。他们的目光怎么样，都和眼前的阿贝莉亚有关。阿贝莉亚到底在他来之前做了些什么？……阿贝莉亚笑语盈盈地看着他，不知道是什么让她心情这么好。

   "你为什么在害怕？"阿贝莉亚又说。

   "我没有害怕。"红黎说。

   "你在害怕。"

   "啊——啊——对，我在害怕。"红黎说。

   阿贝莉亚的两根手指点了点自己的眼睛，然后朝他笑。

   她在撩拨他内心的不安。他想反驳，但是找不到合适的话。可能是因为他的确不安了。这里陌生的情景，陌生的那些人，来来去去的公务人员……这些首次让他认识到：阿贝莉亚的出现，还有之前那次歹徒事件的发生，甚至还有社会上那些不同寻常的新闻——这些都意味着，这个世界的唯物主义正在被打破。不同寻常的事情正在发生，无比真实地发生。注意到这些的并不只有他一个，那些专家，那些大人物们，他们都注意到了。

   他好像并没有心理准备。此前他都感觉，那一切都只是一场梦境一样，或者是一个小说故事而已；他潜意识以为，那些都是安逸的，并不会给他带来任何威胁。他还觉得，阿贝莉亚的存在就像独属于他一样，是他的一场游戏的入场券——他是这场游戏的中心。但现在他不知道了，阿贝莉亚把他叫过来干什么，她又打算干什么，她此前又做了什么，他又会被怎么样……

   "我看见了你的恐惧。"阿贝莉亚又说。

   红黎摸了摸自己的额头。他的额头上的确都是冷汗。他随便把汗水都擦在了裤子上。他的手好像也在颤抖。他居然害怕了。他自己也弄不明白。明明即使之前，阿贝莉亚夺走了他两只眼睛的光明他都不曾害怕。

   阿贝莉亚踢过来一张滚轮圆凳，让他坐下。红黎瞥了她一眼，直接坐在了办公椅子上。他任凭身体陷入了其中。他好像感觉放松了点。他看了桌子一圈，其他没什么特别的——都是些档案和文具——就是他面前放着一叠合同似的文件。这文件的标题是：《关于超常能力者的社会责任全权契约》。

   "签下这个契约。"阿贝莉亚说。

   "这不是你的契约吗？"

   "签下它，你会成为万人之上。"

   阿贝莉亚在蛊惑他。他一时半会儿没有意识到。但是阿贝莉亚的口吻很古怪，像那种二流的产品经理。他真想说，她并不适合干这个——他直接这么说了，但是阿贝莉亚没听明白他什么意思，他白说了。

   "其实，我只想成为一人之上。"红黎说。

   阿贝莉亚把一只笔塞入了他的手中，然后强行抓住他的手——她想就这么让他签字。红黎马上要挣脱她。只是，他做不到啊。他眼睁睁看着阿贝莉亚捏着他的手，翻开了那契约文件……他心里越来越急。

   "我自己来签，只要你回答我的问题——"红黎急忙说。

   他的话好像起作用了，阿贝莉亚放开了他的手。他擦了擦自己的冷汗。他差点就错失了一个让阿贝莉亚欠他人情的机会。这种事，主动和被动的意味是完全不一样的。

   "这个契约对你来说有什么用？"他问。

   "我在这个世界上并不存在，因此无所谓责任。所以他们说，需要一个责任承担者。"

   "他们是谁？"

   "这里的工作人员。"

   阿贝莉亚在乖乖地回答他的问题。这很好。要是她能够一直陷入这么个催眠了一样的状态就好了，也许他能趁机问出什么隐秘。但是……阿贝莉亚倚靠着办公桌而立，一只手掌按在桌子上，四根手指头有节奏地点击着桌面，好像在催促着他。她看起来精神清醒，双目有神。

   "这里是哪里？"他问。

   "国家特殊事件安全管理局。"

   国家。红黎心情沉重了。

   "你不是去的警局吗，为什么会到这里来？"

   "我服从安排。"

   "你会服从安排？"红黎根本不信。

   "你问完了吗？"

   红黎现在的心情沉重，都是阿贝莉亚害的。他的身体陷入了椅子，心脏在躯壳里沉迟地跳动着。他的四肢好像也变得越来越沉迟了。这都是阿贝莉亚的错。她可能是精心设计的，把她自己和他弄到这里来。他想起了那天，她面对歹徒的时候还像个稻草人一样站在那儿……她那时候就在设计阴谋了。

   "快签字。"阿贝莉亚催促他。

   红黎感觉自己逃不掉了。他拍了一下自己的脸颊，让自己振作起来。他又大口的呼吸了两下，给自己换入新鲜的氧气。他强迫自己想，这是一个千载难逢的机会……

   "我不签会怎么样？"

   "我已经把你供出来了。"阿贝莉亚闭着眼睛说。

   红黎的内心越发沉重。

   "阿贝莉亚，你欠了我一个天大的人情。"

   红黎翻开了那契约文件，签上了自己的名字。他浏览了一遍这套文书。他没看懂，里面都是一些官方的套话，把那些真正的含义深深地藏了起来。

   "我需要做什么？"红黎问。

   "在我出行任务的时候，做我的陪同人。"

   红黎默默地思考了一会儿，她所谓的任务是什么。他想起了前两天阿贝莉亚表现出来的武力。

   "为什么要我陪着你？"

   "上级的意思。"阿贝莉亚说。

   他说："呵！你服从的命令。"

   阿贝莉亚用脚尖勾来了滚轮凳，然后坐在红黎旁边。她用烦人的眼神盯着红黎看。红黎敢相信，要是他手边有一把苍蝇拍，他一定把那拍子挥到她的脑袋上。他不这么做，只是缺少一把苍蝇拍。阿贝莉亚还在盯着他，似乎察觉到了他的想法。红黎偏过眼神，不和她对视。她的眼神好像在说，你在害怕……他觉得，从第一天见到她开始，阿贝莉亚好像就乐于见到他的恐惧。她是个不肯自认的虐待狂。

   红黎说："我要回去了。"

   这时，一名身着黑色制服的女性走来了，她手里端着一叠白皮文件。她到了这儿，就在红黎的眼前，将那白皮文件递给了阿贝莉亚。阿贝莉亚的手一晃，那叠文件就消失了。红黎眼皮一跳，直觉这白皮文件有问题。凭什么这人把这文件给了阿贝莉亚……还有古怪，那黑色制服女性见了阿贝莉亚神出鬼没的储藏技术，却没有表露任何惊异，她就像看见正常人在呼吸一样。红黎看向阿贝莉亚。她没有任何表示。

   "刚刚那是什么？"红黎问。

   "一叠资料。"她说。

   她说的太笼统了，谁都知道那是一叠资料。

   "你好，我是唐琳琅，很高兴见到你。"那制服女性说。

   被逼无奈，红黎向这位大人物做了无聊的自我介绍。他说明了自己学生的身份，然后被阿贝莉亚邀请做责任承担者——什么责任承担者，他一无所知。他以为唐琳琅会追问，然后阿贝莉亚就会替他回答。这样，他就能得知更多的线索了。然而，唐琳琅没有任何深究，好像被谁下了闭嘴的命令一样；她甚至没有追问，他和阿贝莉亚到底是什么关系。她就像是一个傀儡人一样。

   更奇怪的是，唐琳琅对红黎表示了关心。

   唐琳琅说："在上面的大人物眼里，你太特别了，力量也太特殊。对于他们来说，你就相当于另一个种族。有句老话：非我族群，其心必异。他们把这话套在你身上了，觉得要是不给你身上套上点枷锁，就无法控制住你。这枷锁……"

   红黎捉摸不透，唐琳琅到底在其中扮演着什么样的角色。但是他知道，问题出在阿贝莉亚身上。他一度感到害怕，自己说不定也会有哪一天，会被阿贝莉亚像弄的像这位小姐一样……


## Chapter 8


   红黎细数着自己手里攥着的阿贝莉亚的人情……多少已经不重要了，他已经让阿贝莉亚欠了他一个天大的人情。他觉得时机差不多了——要是拖的太久，甚至有可能阿贝莉亚会突然消失——他马上打电话给她——不对，他要当面去找她。他马不停蹄地赶到了阿贝莉亚所在的实验平台。她果然还在那间会议室。他敲门后步入，虽然阿贝莉亚没有任何回应。她在那儿夸张地操作着电脑，双手飞舞地像幻影一样。

   "阿贝莉亚，你在做什么？"

   她说："电脑是这个世界最可怕的魔法吧。"

   红黎说："这个世界没有魔法。"

   阿贝莉亚敲着键盘，从不停息。

   红黎拿出手机，对着屏幕上的黑框拍照。他才拍了一张，他的手机就被阿贝莉亚夺走了。他发现，无论自己如何警惕，阿贝莉亚都能轻而易举地从他手中夺走手机。他更下定了要从她那儿学到本领的决心。

   "你在做什么？"阿贝莉亚捏着他手机的一角，晃着手机，质问他。

   "我现在看不懂，将来要是有机会，想研究一下。"

   阿贝莉亚操作着手机，把他刚刚拍下的照片根除了。红黎问她为什么不肯让他拍照。她说，这是科研机密，不能外泄。红黎根本不信。她根本不是那种老实规矩的人。这里面肯定有什么秘密，她不想给他发现。他更打起精神地观察那黑框上的代码了。可惜，他对计算机编程一窍不通。屏幕上的代码大都是英文的，但那些英文他都没见过。他听说，许多编程语言的语法都很怪异，有些词句为了书写起来方便，都约定俗成为了缩写。他看不懂。

   "我没有叫你过来。"她说。

   "我们可以谈谈刚刚的魔法的话题，"红黎说，"你的世界有魔法吗？"

   阿贝莉亚把手机丢给了他，转回去继续编程了。她一直敲着键盘。红黎等了很久，也没有从她口中得到回应。

   他说："阿贝莉亚，现在我们正相互合作。"

   他说："我不做你的责任承担者了。"

   他还说："你现在欠着我三个小人情加上一个大人情。"

   他趁机骂她："阿贝莉亚，你是个蠢货。"

   不管红黎用了何种说法，阿贝莉亚都没有回应他。不过，她的确在关注着他的举动，因为，要是红黎以为她陷入了自己的世界，而偷偷开始拍照了，阿贝莉亚马上就会把他的手机夺走，然后把照片根除掉。她还警告他，要是他敢再拍一次，她会彻底把他的手机格式化。红黎明白了拍照是行不通的了。但是他可以尝试自己去记忆它们。他推过来一张滚轮圆凳，坐在她旁边看她敲代码。阿贝莉亚自顾自，没有理他。

   …………

   红黎和红伊水他们同上一节实验课。有趣的是，阿贝莉亚成了这堂实验课的监督者。她端着她的笔记本电脑，坐到实验教室的侧边，在那儿永无休止地敲着键盘。偶尔有人注意到她，然后会进一步注意到，她几乎和红伊水长得一模一样。红伊水的同班同学都没有深入向红伊水追问。红黎猜测，是否是红伊水的脾气太暴躁了，让他们不敢问话。

   红伊水本人在那儿老实地做着实验，只是目光不时地瞅向阿贝莉亚。红黎问她，她和阿贝莉亚之间是否有发生了什么。但是红伊水不回答他。这人让红黎感到无奈。连他自己都不在意那次精神病院的事了，她却还在这儿纠结。不过，他是绝对不会怀疑：她是不可能跟他说出道歉的话的。

   这场无趣的实验课毫无波澜地进行着。直到某一刻。有个学生大声呼喊："水晶！"

   有一名男同学，大概应该属于红伊水的班级，他一只手抓着自己的双肩包，另一只手在里面攥着什么。那包里隐隐闪着光辉——那是一颗水晶。那水晶泛着隐隐的紫色光辉，让红黎感到眼熟。他心想，难不成那是他先前捡到的那颗水晶？

   那男同学注意到了周围的视线，呆住了，包掉到了地上。于是，他的那只手和攥着水晶就暴露在了周围人的视线
   下。那水晶圆溜溜的，像一颗弹珠。红黎还记得自己当初捡到的是棱柱状的，和这不一样，大小也比那大上一倍。他捡到的水晶应该由红伊水归还了——他当初丢给了她，让她负责发布失物招领——这不是那颗。

   这会儿，那男同学迅速捡起了自己的包，把水晶藏了进去，然后涨红着脸，低声呵斥先前喊叫的男同学，怪罪他太大声了。

   "红伊水，你先前说的水晶，是那样的吗？"红伊水的戴眼镜的室友问道。

   红伊水摇头否认。

   红黎问："你们说的是什么水晶？"

   "红伊水之前好像丢过一颗水晶。"眼镜室友说。

   红伊水轻拍了一下眼镜室友的肩膀，好像有嗔怪的意思。而那眼镜室友不解其意，反问她是否说错了什么。

   "你弄丢的那水晶，不会是我给你的那颗吧？"

   "不行吗？"红伊水低着头说。

   "你怎么能弄丢呢？"红黎惊了。

   "反正你都送我了，怎么样都好吧。而且，我也不是有意的……"她的声音越来越低了。

   "那水晶是我捡来的，当时给你，是让你帮忙发布失物招领。"

   红伊水终于抬起头了，她的脸上尽是茫然。

   红黎问："那你以为是什么？"

   "讨好我的礼物。"她说。

   红黎笑了。他突然觉得无所谓了，丢了就丢了吧，反正是她的责任。


## Chapter 9


   红黎正背上自己的双肩包。哐当一声。有人起身时踢翻了滚轮凳。是先前攥着水晶的男同学。那人僵硬得站在那里，两眼呆滞地望着前方；前方除了因为雨水渗落而发霉的墙壁以外，什么也没有。滑轮凳倒在那人的脚下，转着轮子。最终还是由那人的朋友扶起来的。

   那人朋友抱怨："你在发什么呆啊，也不把凳子扶起来。"

   这时，那人呆滞的眼神恢复了些清明，僵硬地转过身，向着盥洗池走去。红伊水和她的室友正在那里洗手。那人立正站在她们身边。她们洗完手，浑然没有发觉来到身边的人的异样，自顾自地以纸巾擦干了手。红伊水给两位室友各递了一张纸巾。那人还僵硬地站在那里，也没有因为红伊水她们给他腾出了位置，就使用那盥洗池了。红黎在他身后看着，总觉得不对劲，背上书包靠近了两步，从侧面看他脸上的表情。那人视线略微下移，望向比自己矮上一个脑袋的红伊水，面无表情。

   他说了些什么，让就在旁边听着的红黎不敢确信。他不是质疑自己的耳朵，而是实验室里的声音太杂乱了。有学生们挪动着凳子，咔嚓咔嚓的，推进桌台下的容腿空间。有学生们脱下白大褂，窸窸窣窣，然后背上自己的书包。有学生们因为最后一局的游戏输了，发出懊丧的叹息声。还有学生们在讨论着晚饭要吃什么，或者实验报告要从谁那儿借来抄。阿贝莉亚啪嗒啪嗒地敲着键盘的声音不绝如缕。

   但是，不管那些声音如何喧嚣，那人的确是这么说的："红伊水，我喜欢你，请和我交往。"

   那人瞪着铜铃般的眼睛，面色涨得通红。他还气喘如牛。要是仔细去看，甚至能看见他呼出的气会变成雪白的一团雾气。他的鼻孔就像在吹着雪花一样。他的表现很奇怪，说的话更奇怪。没人会在一个公共场合说这样的话——除了富有挑战精神的红黎他自己。红黎再度以为自己听错了，或者白日作梦了。但周围的景象实在是过于真实。

   实验室里杂乱的声音还持续了好一会儿。有同学打开了水龙头，哗啦啦的，水流太大了，而那同学的手刚好伸在了水流下，这下子，那迸溅的大量的水花都飞溅到了那同学的身上、脸上，还有周围的人身上。他们唠唠叨叨，数落来，数落去，嘻嘻哈哈，把责任往最无辜的人身上推卸。有的人嘻皮笑脸，有的人满脸茫然，还有的人怒不可遏。但是从某一刻开始，他们都安静了下来，他们的面孔一齐变成了惊骇欲绝。

   这会儿的声音都静下来了——除了阿贝莉亚敲打键盘的声音。

   红伊水惊慌失措地张望着周围的同学们，那些呆滞或者逐渐变得兴奋的面孔。他们开始窃窃私语了，议论那告白的人是如何的大胆包天，这一刻又是如何的戏剧性。女生们的脸上带着对浪漫发生发展的兴奋和满足，男生们则大多带着戏谑的笑容。

   红伊水的两位室友从背后戳了一下她，脸上是意义不明的微笑。她们似乎是想鼓励她，让她做出回复。但是现在的红伊水，不管怎么看，状态都称不上好。先前她就因为弄丢水晶的事闷闷不乐了，现在的话……红伊水深吸了一口气。似乎所有人都在看着她这一深呼吸的动作。

   "抱歉。"

   红伊水急促地说完，抓起书包和白大褂，逃离了实验室。她刚好和一位女老师擦肩而过，惹得女老师一阵牢骚。这位女老师进入了实验室，好像什么也没察觉到一样，张罗着让大家都上交试验成果，收拾好试验器材，放回到器材室……学生们还沉浸在先前一幕中，迟迟没有行动起来。

   "我，我到底都做了些什么……"那告白之人满脸惊恐，好似才醒悟自己的行为。

   "从今以后你就是我大哥。"他朋友说。

   "有两下子嘛。"他的某位女同学。

   这些人都纷纷献上了独特的安慰。那告白之人蜷缩了起来，双手捂面。他变成了一只没有壳的蜗牛。他一定是想找到某个地方，可以让自己钻进去，好回避这尘世间污浊的空气。红黎靠近了，帮他打开了实验台下面的柜子，挥了挥手，示意他可以躲进这里，这里很安全。遗憾的是，这人并不领情。

   "喂，你怎么身体这么烫啊？"有人说。

   "真的，也太烫了吧？"

   "你到底怎么了啊？"

   那告白之人的几位朋友围在他身边，摸着他的后背，又摸着自己的额头，还用手机去查询什么。

   "我们要不要叫救护车啊？"

   "他怎么一动不动了，还毫无反应？"

   那人的两位朋友看起来不像是在开玩笑。其中一位的手在颤抖着，在拨号界面上按下了急救号码。另一位嚷嚷着要去找老师来。刚好，之前那位女老师又路过了这里，询问他们情况。那两位朋友语无伦次地做了说明，居然是从那人的告白开始说起的。

   那老师听得不耐烦了，牢骚现在的学生们不务正业，还喜欢耍流氓。她拍了一下告白之人的后背。那人被拍得失去了平衡，脑袋顶在了实验桌台上。他的脸还埋在手掌中。

   "天啊，他体温怎么这么高啊！"那女老师惊叫道。

   "啊啊——啊——"那告白之人大喊着，站了起来。他后仰的脑袋顶到了那女老师的头，让她翻倒在地。那人的大喊还没停止，一声接着一声，喊穿了这间实验室，让人听得心慌意乱。这下子，教室里、教室外所有的学生都被吸引过来了。有些女生们已经开始哭泣了，跟着那人的哭喊一起，此起彼伏地无休无止。那人好像承受着莫大的痛苦。这会儿的哭喊声召集来了越来越多的人。

   终于，有老师知道组织学生们了，让他们都冷静下来。老师让男生们去压制那痛苦的同学，让他不至于因为横冲直撞而受伤；其他人如非必要，都离开实验室，不要堵住道路。学生们都行动起来了。红黎参与了压制那个同学的任务。当他触碰那人的肩膀时，感觉手跟伸入了沸水里一样。有人呼喊，让他们都戴上防护手套。这时候没人敢逞强，他们纷纷戴上手套，然后向着那人包围而来。他们分工合作，让几个人先牵制住或者按住那人的手脚，剩下的人穿插进去，把他的身体翻转过来，倒扣在地上。这样可以把那人对周围造成的危害降低到最小。他们如此计划，实际行动的时候——倒也行得通，只是费了九牛二虎之力。

   红黎和他们一起，终于把那人给压制住了。但是那人还在他们的掌控下战栗，颤抖，挣扎。他看起来没有多少肌肉，但这时候显得尤其疯狂，有好几个稍微瘦小的男生被他的脑袋顶开了，无力地撞在了旁边的实验台上。

   这时，红黎瞥见了旁边偷鸡摸狗的阿贝莉亚。她拎起了那人掉落在地的双肩包，在里面翻找着什么。红黎丢开了手边的责任——不，他推位让贤了，让给了更健壮的同事——他跑向阿贝莉亚，问她在做什么。她只是默不作声地搜着包。

   "水晶不见了。"这么一句话从她的牙缝中挤了出来。

   她说："你跟我来。"

   阿贝莉亚快步离开了实验室，穿出走廊。红黎匆匆跟上她。她到了电梯口。这儿，那些学生们和老师正张罗着把那有病的人架进电梯。

   "跟进去。"阿贝莉亚说道。她率先站进了电梯。

   "其他学生等下一趟的电梯。"指挥的老师说。他在对阿贝莉亚下命令。

   这老师可真酷。红黎心想。他跟着阿贝莉亚，也站进了电梯。

   "不要再挤进来了！"那老师对红黎瞪眼。

   红黎假装没听见。

   那老师还在颐指气使。这时，阿贝莉亚抓起了两个男生，把他们丢出了电梯间；她又抓起了两个男生，把他们丢出了电梯间。在电梯们关闭之前，她一直拦在门口，不让他们进来。她一夫当关，万夫莫开。这里面的人都看呆了。指挥的老师也看呆了，然后面红耳赤。

   红黎虽然很期待接下来的龙争虎斗，但是电梯的空间实在是太小了。他遗憾地说："老师，阿贝莉亚能更好地压制他。"

   那老师看了过来。红黎说的一点也没有错，现在的电梯间不仅空旷，而且那人也没有一点挣扎的迹象。阿贝莉亚一只手压在了那人的肩膀上，就令得他纹丝不动了；而且连喊叫声也没了，只是在那儿粗重地喘息着。最终，那老师没再说什么。其他的学生在嘀嘀咕咕，时而看向阿贝莉亚。

   电梯到了一楼。众人齐心协力把那人搬出电梯间。红黎在一旁指挥。

   外面的救护车已经在响铃了，几名医生扛着担架冲了过来，让他们把那人放在担架上。

   "都让开。"阿贝莉亚说道。她说的是中文，声音不大，但是所有人都听得到。

   医生们以奇异的眼神瞅了她一眼，自顾自忙着。

   阿贝莉亚见说话不起作用，就上去把他们都一一推开了。于是，不管这些医生们怎么努力，都无法进入那犯病之人的一圈之内。这时，阿贝莉亚一击手刀砍在了那人的后颈上，让他整个人软了下去。

   "扛上他。"阿贝莉亚对红黎说道。

   红黎照办了。

   医生们鼻子似乎都要气歪了，周围的老师也都差不多。"你是谁，到底在干什么！……"他们请了附近的保安过来，让他们把阿贝莉亚制服。那些保安们甩着警棍，试图吓退阿贝莉亚。但阿贝莉亚不吃他们这套。医生们和老师们鼓吹保安，让他们："尽管上"。这些人的意思应该是让保安们一起上，但保安们很谦逊，逐一上去讨教；结果他们都成了路边的乞儿。现在，医生们可以行使自己的职责了：救治这些保安。

   阿贝莉亚亮出了一份证件，对周围人说："特殊事件安全管理局办事，请退让。"

   她要是有证件的话，早该这么做了。

   "特殊事件……管理局，那是什么？"有人质疑阿贝莉亚说的话。

   红黎解释说："国内版FBI。"

   周围人将信将疑地望着他。红黎可不管那么多，他扛起那犯病之人，追着阿贝莉亚的脚步。他们往校门口而去。救护车的铃声在他旁边响个不停。但是这儿的医生们只能眼睁睁地看着他这个门外汉来处置病人……他有种说不出的快感。

   说起来，现在他扛着的这人的体温似乎并不那么高了——不，这人的肤色还是通红的，体温估计没有下降，也许是阿贝莉亚帮忙做了什么处理，让他不再被高温所伤。他注意到，自己的手掌好像被一层赤红色覆盖了，他的身体也差不多。

   阿贝莉亚催促他快跟上来。

   越来越多的人过来目送着他们了，围观成了一排，然后又一排接着一排。阿贝莉亚给他们出示了证件。此前的几位医生和老师依然在那儿观望着，他们无意中阻拦了其他人的上前。

   红黎终于把那人架到了校门口。人失去意识的时候，会变得无比沉重，这话不假。这几十步的路走得他眼冒金星。校门外，一辆让他眼熟的黑色车子甩尾停了下来。随后，一周前载过他的那位司机下了车。这人应该也是特殊事件安全管理局的成员身份。"没想到这么快，我们又见面了。"这人说。

   "你好。"红黎说道。

   "我姓张，名楼罗，只是个局里的小喽啰。"

   红黎报出了自己的大名。在张楼罗的帮助下，红黎把那犯病之人塞进了车子的后座。

   此时，阿贝莉亚已经坐上了副驾驶座。她说："你不需要跟着来。"

   "难道你现在要丢下我？"

   红黎用眼神示意堆在校门口的那帮人。要是他现在走回去……

   "上车吧。"阿贝莉亚说。


## Chapter 10


   汽车开到昔日那幢写字楼下。唐琳琅带着属下来迎接了。红黎遵从安排，把那犯病之人交给了属下。那属下急匆匆地背着高温患者走了。看着那属下背负的动作，红黎都替他担忧，要是他半路发现自己后背都被烤熟了，那可怎么办……

   唐琳琅让阿贝莉亚跟随她去开会。红黎也跟了上去。他们到了三楼的某间会议室。但是他最终只是坐在了门口的椅子上，等待会议结束。红黎百无聊赖地在那儿等着，时而凑近门口，试图听见里面在说些什么。他看见了一个光脚的女孩在走廊上飘过，然后消失不见了。他以为自己看错了。但他停止了自己愚蠢的行为，最终他也没听到什么。他收到了红伊水发送给他的消息，向他询问她离开后事情的经过。但说实话，他也不明不白。

   这场会议直到傍晚还在持续。红黎曾下楼，在对面的餐馆点了碗面，解决了自己的晚饭。他重新坐在会议室门口，用手机浏览着最近的新闻。就在不久前，他养成了看新闻的习惯，因为最近社会上是在不太安宁。他企图从中寻找那些特殊的事件，比如超常现象的发生，魔法的发生——是不是魔法，他不知道。

   当阿贝莉亚和唐琳琅走出会议室时，天色已经彻底暗下来了。红黎的手机都因为没电而关机了。唐琳琅打电话吩咐属下，让人把红黎和阿贝莉亚送回学校。她还让阿贝莉亚把适当的情报转告红黎，他身为责任承担者，有必要了解一些事。

   红黎和阿贝莉亚再度坐上了张楼罗同志的车。

   在回途期间，阿贝莉亚没有顾虑张楼罗的在场，给红黎叙说了一番下午会议的内容。她估计在关键情报上做了保留，只是红黎不知道保留了什么。

   这场事件的发生经过都源于那水晶，研究人员称之为奇迹水晶。正如它的名字，它包含着奇迹般的力量，似乎会根据持有者的潜意识，把某种只会存在于幻想中的东西转化为现实。那位高温患者的突发事件就是因为这水晶。奇迹水晶感应了他的潜意识，激发了力量，这才导致了他下午的告白。水晶的力量不止如此，还有后续，但这就不为人知了。那人的体质似乎无法适应那水晶的力量，出现了精神混乱，发了高烧，之后性命堪忧。相关医疗人员正在救治他。

   张楼罗把他们送到了校门口后，就开车走了。红黎这时候把心中的疑惑问出口了。

   "阿贝莉亚，那什么奇迹水晶，你的出现会不会也和这有关？"

   阿贝莉亚猛地转身，在夜色中，她的眼睛好像在嗜血一样。

   "无可奉告。"

   "你这么说的话，我反而猜到了。"

   "黎，你要学会控制舌头。"

   红黎一时间没明白她要表达的意思。

   "否则我会弄死你。"阿贝莉亚说。

   "不要急着进去，"红黎跑过去拦住了她，"我们需要谈一谈。"

   红黎请阿贝莉亚往学校外墙的路上散步。

   她凝视了他一会儿，给他带来了不小的压迫力。但她最终好像是默许了，率先往那个方向走了过去。红黎有点不敢置信，他还以为自己需要再费一点口舌，甚至付出一点代价。

   "我以为你不会和我提及任何水晶的事。"红黎说。

   阿贝莉亚踱步在夜色中，走得不快，但红黎总觉得很难跟上她。他稍微落后了两步，他就会感觉，她的身影好像被夜色消融了。红黎想起来，她是突然出现在这个世界的；很有可能哪一刻，她又突然失踪了。他想到了更多的可能，她为什么会出现在这里……他想到了自己当初的那块水晶，他把它交给了红伊水。水晶消失了，阿贝莉亚出现了。

   "你要小心谨慎，那些因为水晶而拥有力量的人已经混入在普通人中了。"

   红黎想知道附近是否有烟火店，他想去买点鞭炮庆祝一下：阿贝莉亚居然在对他表示担忧。

   "阿贝莉亚，你的出现是不是和红伊水有关？"

   "无可奉告。"

   "我猜，还和我交给她的水晶有关。"

   阿贝莉亚停下了脚步。她的眼睛还注视着远方的夜空。但红黎知道，她的心神已经被勾住了。可能她也不知道，那水晶和他有关。今天遭遇的这件事，让他把许多事都串成了一条线。

   "还记得我之前和你提的请求吗？"红黎说。

   红黎见她没有回答，接着说："我让你教我魔法，但是你拒绝了。现在我再次请求你。"

   "我的回答不会有变。"

   "会变的。"红黎用笃定的口气说。他手里还握着好多阿贝莉亚的人情，他只是需要一个合适的机会，把它们拿出来——

   他说："我已经帮了你一个重要的忙了，我现在作为你的责任承担者……另外，我知道你的来历。"

   阿贝莉亚一阵沉默。她说："你在威胁我。"

   "我在和你谈生意。"

   阿贝莉亚停下了。这时候，红黎还是没能意识到她这样的举止意味着什么——她后退了半步，朝红黎伸出一只手。红黎以为她是要和他握手了，表示友好。他伸出手——阿贝莉亚抄起了他的腰，狂奔了起来。

   "你要干什么——"

   红黎一时惊慌，想要推开她。但是在她的绝对武力面前，他的挣扎是无用的。她的手像铁钳一样钳制住了他。

   最初的风声把他的头发都掀到了脑后，让他看见周围的世界是多么开阔，也是多么的危险，四处的黑暗都可能潜伏着危机；然后那风声就越来越暴力了——狂风扎着他的眼皮，让他不敢睁开眼睛。他能感受到，阿贝莉亚的速度越来越快。

   汽车的声音被她不断甩在身后。汽车的声音不断远去，又不断被超过——新的汽车被超过时，会有爆炸般的一声"哗啦"。那声音震得他浑身颤抖。他好像在和死神赛跑一样。他怀疑，阿贝莉亚正擦着边和那些车子赛跑……一辆摩托车飞驰而过了，那声音在毁灭——"哇"的一声，引燃了他的神经……他有好一会儿无法动弹，也没有思考。在他的意识海中，念头都停止了生生灭灭。狂风继续掠夺着他耳庭里的空气。他也不敢张口说话。他呼吸进来的空气带着烧灼感。他的双腿机械性地摆动，但这只在最初的那一刻；现在阿贝莉亚的速度已经快过了他的双腿能奔跑的极限了，这可能是人类肉身架构的极限，他早就往上收起了双腿。

   阿贝莉亚还在狂奔不止。他不知道她要到哪里才肯停下。他感受到，他们拐过了一个弯。周围的闹市声变响亮了。他闭眼时，光线透过眼皮带来的刺激也变得更强烈了。他们到了繁华的地段。阿贝莉亚可能稍有减速了，周围的声音变得清晰了些许。他的耳朵捕捉到了那些男生和女生们、或者男人和女人们话尾的余音。比起最初，红黎已经冷静下来了很多。他现在心思躁动了起来，他正抱着阿贝莉亚，而她在折磨他，他为什么不对她表示一些感激？……他出格的事情他不敢做，怕自己被她撕成碎片。但是他可以给她挠痒痒——

   重力的方向变了，他感觉脑袋和四肢颠三倒四——他们前进的方向变了，变得向上了，垂直向上。阿贝莉亚的手托着他的后背，带他往上攀升。红黎紧紧抱着阿贝莉亚，因为单凭她一只手的托力，那带来的压强可能得让他在中途断成两截。上升的速度远远小于此前奔跑的速度，所以他能睁开眼睛了。这会儿，他们正垂直着大厦往上奔跑。阿贝莉亚踩在了楼顶的围栏上，带着他腾了起来，然后落在了屋顶上。他以为可以有着落了，没想到阿贝莉亚拎起了他的后领，把他悬挂在高楼的栏杆之外。

   "这里是附近最高的楼房，有四十层楼高。"阿贝莉亚说。

   下方的高空把他无限拉远，而那最远的深处变成了一个黑点，黑洞。死边延伸的线条穿刺了过来，穿刺了他的四肢，刺入了他的脏腑，把他的内脏往下拽，往下拽——他很难以为那只是错觉而已。下方的深渊在把他往下拽。他的恐惧攫住了他。他深刻怀疑，自己有恐高症。

   "我知道了，我错了，我放弃——"红黎连声求饶。

   "我以为你至少能硬气三秒钟。"阿贝莉亚说。

   "哈哈哈——"他已经害怕到了只能神经兮兮的哈哈笑了。

   "活着不好吗？"阿贝莉亚说。

   "哈哈哈——"

   "死了更好吗？"

   "哈哈哈——好，好——"

   "蚂蚁不要和巨人谈条件。"

   "哈——快放我下来！"他感觉自己有点适应了高空的眩晕了。

   "再吊一会儿。"

   "你——"

   "吊到学校里所有的灯都熄灭了。"

   "那不可能——"

   红黎于害怕的终点生起了火气。学校的灯怎么可能全部都灭掉？即使寝室的灯都灭了，那路灯呢？总有一两盏开着的。这是在逗他吗？……

   阿贝莉亚单手揪着他的后领，而那衣领拉扯着他的喉咙和腋下，这单薄的支撑力让他吊在空中。他难以多说几句话，这会儿他的喉咙越来越难受了，有种窒息感。他还担心，要是他的衣服破掉了，他摔了下去，该怎么办。

   "快发誓，别再自寻思路。"阿贝莉亚说。

   "啊呀啊——"他根本说不出话来。

   阿贝莉亚把他丢回了楼顶上。

   那种眩晕感终于离他而去了。如获新生般的感觉如此强烈，竟然盖过了他摔在地上的疼痛。他翻身一下，仰面朝天谈下。这一刻，什么人模狗样，他什么都不管了。他看着天上一闪一闪的星辰，只是感觉，活着真好。恐惧的感觉在离他而去。又过了一会儿，他感觉自己好像不那么害怕了。阿贝莉亚终究，还是没有把他丢下去。所以，她不过是在吓唬他而已？……他感觉自己完全不怕了，甚至这时候能再次要挟她，让她教自己魔法。

   阿贝莉亚背过了他，好像要走了。红黎连忙腾了一下身——他来不及站起来——窜过去抓住了她的脚踝。

   "你还没答应我。"他说。

   "你还想再被我吊起来。"

   "你再吊我吧。"

   阿贝莉亚让他如愿以偿了。他又一次面对了下方那恐惧的深渊。事实证明，人要是有所心理准备的面对恐惧，那恐惧的感觉就会削弱很多。现在的红黎还能冲阿贝莉亚耀武扬威，说自己完全不害怕。但是，冷汗终究还是沿着他的脸颊滚落了下来。阿贝莉亚笑了，她把他抛向了空中……星辰在和他招手呢，他好像伸出手就能把它们摘下来了呢。他在空中划拉了几下手臂，抓不到任何凭借物。他当然也抓不到那些星辰。他在往下坠落了。失重的感觉越来越强烈。他屏住呼吸。他觉得阿贝莉亚不可能不接住他。但是过了好久，好久，久到失重的感觉都要融入他的躯体了，他还是没有被一双臂膀接住。他在往下坠落，往下坠落。他瞪大眼睛。侧面是高楼的那些窗户，它们飞速地和他擦肩而过，飞速地把他甩开了。他在往高楼底下坠落。他眼前的景物飞速移动，星空正在和他拉远。他终于控制不住，大声喊叫——

   阿贝莉亚最终还是救了他。这让他庆幸之余，又觉得无趣了。阿贝莉亚还是赢不了他。他的胜利来得太容易了。只是，她就是不肯答应教他魔法。他觉得更无趣了。但是他不可能就这么放弃。但他决定稍微缓缓，等下次的机会。

   阿贝莉亚把他独自丢在了这里，消失不见了。

   他乘着电梯下了这幢大楼，然后搭车独自回去。他在路上想到了红伊水的事。今天的那人因为水晶而出现了症状，就像过敏一样。他有点担心红伊水，她会不会也出现这样的症状？……按照他的猜测，水晶的力量应该在阿贝莉亚出现之后就用完了，所以消失，既然那时候的红伊水没有出状况，那她现在就不会出问题才是。

   他到了学校，在走回寝室的路上打电话给红伊水。

   电话接通了。

   "干嘛？"红伊水一副冷淡的口气。她说话时还伴随着一阵键盘的敲击声。

   每当她用这样冷淡的口吻回应时，他都感觉自己难以为继了。

   "我想问，那颗水晶消失以后，你有没有感觉哪里不舒服。"

   "什么意思啊？"

   "今天的事情你知道了吧，就是那人，他发了高烧……"

   "嗯。"

   "我担心你也出现类似的问题。"

   "虽然不知道你想说什么，"红伊水的语气软化了，"但是我没事。"

   红黎想到了水晶的事或许得保密……但是唐琳琅并没有这么说起过，阿贝莉亚也没说过。既然如此，他就当成不需要保密的事项好了。

   "还有什么事情吗？"红伊水说。

   "红伊水，请你仔细听我说。"

   "我听着呢。"她的口气敷衍。

   红黎感到无奈。他接着说："那人的高烧和那颗水晶有关，那是因为那人承受不住了那水晶的力量了。我之前也给过你差不多的水晶，你说它消失了，但是其实它不是消失了，是你把它使用掉了——"

   "等等，从刚刚开始你就在说什么，我没明白。"红伊水说。

   "所以我让你仔细听我说。"

   她问："我说你，不会还沉浸在某个小说的故事里吧？"

   她又说:"你还想去精神病院吗？"

   "我……"红黎一时语塞。

   "红黎，请恕我打破你的妄想，那些东西是不存在的，请正视现实。"

   现在好了，对面的键盘声停下来了，她认真在和他对话了，但是他却感觉她更难对话了。说了半天，她居然还以为他在说胡话。他大声叹气，一时不知道该怎么说好……他停在了女生宿舍楼对面的路灯下。

   他说："我现在在女生宿舍楼下了，你下来，我给你解释清楚。"

   "别想浪费我的时间。"

   "我要解释给你！"

   "有什么好解释的？"

   "那我问你，你不对阿贝莉亚和你长得一模一样感到奇怪吗？"

   "她是我的粉丝，崇拜我。"

   她在说什么鬼话。"如果你想知道原因，你就下来，我和你说清楚。"

   "不行，我已经换上睡衣，在床上了。你直接在电话里讲吧。"

   他感觉自己真的是拗不过这个人啊。他一时之间难以冷静。他望着路边来来往往的学生。他需要一段时间让自己冷静下来。否则他可能要冲着电话破口大骂了。

   "我挂了。"红伊水说。

   "你等会儿。"

   "还要等多久？"

   她叫嚷："我要挂了。"

   "如果你对自己把我送进精神病院还有那么一丝的愧疚之情，就别挂。"

   对面无声了，但是电话终究没有挂断。

   红黎让自己静默了十秒钟。

   "你听着，我只讲一遍，不管能否听得懂，你都自己消化一下。听着，我给你的那颗水晶被你无意识间用掉了，使用之后，发生了什么——这我不知道，但你肯定有头绪——可能阿贝莉亚就此出现了——我跟你说过的，她是个来自魔法世界的人，我没骗你。现在我想问的是，你到底做了什么，让阿贝莉亚这样一个活生生的人出现……"

   红黎的手机被夺走了。

   他回头看去，阿贝莉亚正面色冰冷地看着他。她挂断了电话，然后把手机收进了自己的上衣口袋。她会做什么？……他的心中浮现了前不久被吊在高空的恐惧。阿贝莉亚什么也没说，抓住了他的手腕，慢慢地走着，强硬地拉着他走。他也不敢多说什么，只能跟着她走。

   她正往人少的方向走。有那么一会儿，他有种大声喊叫的冲动，让人来救他。但是他终究还是没这么做。他得冷静点。如果阿贝莉亚要对他不利，他现在早就已经死了。

   周围偶尔有人关注到他们，这样一个奇特的组合：一个女子强行拉着一个男子，女子神色冰冷，男子满脸心虚。他感觉，周围人的目光很古怪。但是他们都不懂，他现在的内心是如何的冰寒。

   阿贝莉亚拉着他走在了去操场的路上。她一路上都沉默着。她拉着他到了毗邻操场的一个角落。这里一片漆黑，等他的眼睛适应了好一会儿，才看清周围环境。地面丛生着芜草，是塑胶地面覆盖不到的地方。与校外相隔的墙壁的上缘缺了个角，寒冷的夜风从那儿吹了进来。红黎这身的装扮偏单薄，他不禁蜷缩起了些身体。与这里的阴暗相反，操场那边灯光明亮，学生们在走动，跑动，甚至还有大声欢歌的。他不知道，阿贝莉亚带着他到这里来想做什么……阿贝莉亚松开了他的手，面对着他。

   "是不是我给你的警告不够？"她说。

   "其实……我不知道你在责怪我哪里做错了。"

   "你不能把我的事情告诉红伊水。"

   "她知道你的事情。"

   阿贝莉亚说："你不能再和她讨论任何关于我的事情了。"

   "为什么？"

   阿贝莉亚没有回答。她手上亮起了光，那光放大变成了冰蓝色的魔法阵——和他想象的那种魔法阵的模样差不多，一圈圈的纹路中有着无法辨认的文字，这样的阵盘一个接着一个出现，像多层堆叠的蛋糕一样。

   红黎眼见着，感动极了，还是首次见到阿贝莉亚如此有仪式感的使用魔法，此前她都是忽地就把什么变出来，或者变没掉，让他都难以意识到发生了什么。这魔法阵越来越大，变得有一个人的怀抱那么大。他总感觉阿贝莉亚把它控制起来没那么轻松，甚至那挺拔的身姿都因此二佝偻了些许；她双手一起指挥它，还不断地吟唱咒语。那魔法阵飞起来了，然后从空中坠下，把他给套住了——他本来想跑开，他不知道接触到这些魔法阵会发生什么；但是他最后还是没有跑开，他不觉得阿贝莉亚会伤害他，否则用不着这么麻烦——魔法阵一共有五层。它们开始收缩了，眨眼间收进了他的体内，消失不见了。他拍了拍自己的身体，好像没发生了什么变化。

   "你对我做了什么？"红黎问她。

   "我在你身上装了耳朵。"

   "你要窃听？"红黎喊道。

   "没错。"

   "你在侵犯我的隐私！"红黎喊道，"我吃饭睡觉上厕所怎么办？"

   "你可以忍着不做。"

   "我没有你那么强。"红黎挖苦她。

   "我再强也奈何你不得。"她这么说了。

   "我们需要彼此信任。"红黎说。

   "可你没有给我这个机会。"

   "我可以重新给你这个机会。"

   阿贝莉亚嗤笑了他。

   "阿贝莉亚，你太让我失望了。"

   "它只会在你要泄露我的情报的时候触发。"

   她这么说，可能是在向他表示和解了。红黎松了口气，可也感到沮丧。"你终究还是不相信我了。"

   阿贝莉亚好像擦了一下额头的汗水。"如果我不是恰好就在附近，也许你已经把我的事情告诉她了。"

   "你是不是特别针对她？你果然和她有什么恩怨。"

   阿贝莉亚转身走了。

   红黎以为她只是做做样子。但是，她真的就这么走了，一步步远离。他的等待只是徒劳。看起来，她带他来这里，就是专程给他释放了这样一个魔法。红黎马上追上去。他想着，有没有什么办法可以修复她对他的信任……说起来，他也不知道此前的阿贝莉亚是否对他有所信任。他一想到这里，又觉得某些事情特别奇怪了。在阿贝莉亚刚出现在这个世界的时候，为什么要找上他？——还是说，那只是个偶然，刚好遇见了在那里的他？

   "阿贝莉亚，你为什么要让我做责任承担者？"

   "你不愿意？"

   "我只是觉得奇怪。"

   "我看你顺眼。"

   "我不信。"

   "我要找机会弄死你。"她说。

   "那我迫不及待了。"红黎说。

   阿贝莉亚又不说话了。他要是有她那般的武力，就上去把她的嘴巴撬开。他又活动了一下自己的身体。刚刚那套在他身上的魔法阵的确没有给他带来任何的不便。

   "你之前说这个世界没有魔法，"阿贝莉亚说，"但是你身上有这样的气息。"

   红黎故意不回答她。

   阿贝莉亚踹了他一脚，让他趔趄了一下。他瞪她。然后，他又被阿贝莉亚踹了一脚。她重复了一遍自己的问题。

   "你留下的魔法气息？"红黎被逼着回应。

   "那我会和你浪费时间说这个？"

   "那你觉得是怎么回事？"

   阿贝莉亚往药学楼的方向去了，和他分开了不同的路。她好像一直居住在那里。也不知道是如何解决饮食起居问题的，想沐浴更衣之类的事情的时候，又该如何解决。他感觉自己果然只是个凡人，只能用平常的思维方式思考。像她这样的魔法使用者，又怎么会为这些琐事烦扰呢？

   红黎回到寝室后才想起来，阿贝莉亚最后都没有把手机还给他。


## Chapter 11


   阿贝莉亚没有把他的手机还给他这件事让他苦恼。他没了手机，就像和整个世界都隔绝了一样，社会上发生什么倒不重要，主要是班级有重要的事情他不得而知了。他的寝室只有他一人在，其他三位学长都离校实习了。他相当于独自起居。早上醒来的时候，他连时间都拿捏不准。他的旧手机在不久前被他回收卖钱了。现在他真是举步维艰。他想起了自己快要烂在柜子里的旧电脑，把它拿出来确认了一下时间。他在早上八点左右离开了寝室。现在他的关键是要把手机拿回来。

   他走出宿舍楼的时候，见到了迎面而来的红伊水。

   "你昨晚为什么挂掉电话？"她神色冷峻地质问他。在这时候，她给人的感觉和阿贝莉亚特别像，仿佛同一个人一样。红黎一时间没反应过来，还以为阿贝莉亚又来质问他了，浑身哆嗦了一下。他心里正想着阿贝莉亚的坏话。

   "啊，可能是手机没电了。"红黎说。

   "可能？"

   "是手机没电了。"红黎没法和她对视。

   "那我早上发你消息，你也没有回复。"

   "这……我早上走得匆忙，忘记看手机了，也忘了把它带出来了。"

   她马上说："昨晚你挂断了电话，我还下去找你了，但是你根本没在楼下。"

   因为阿贝莉亚把他拉到操场去了，当然找不到。他想到，阿贝莉亚会不会是就看准了这一点才这么做的？……不管如何，他已经没法再和红伊水说阿贝莉亚的事了，他得想个办法敷衍过去。

   "你还有什么借口？"红伊水说。

   看来，她已经把他说的一切都当成谎话了。

   他快步往食堂方向走。但是，红伊水还跟在他的身后。她挎着皮包，踢着小皮鞋，穿得轻飘飘软绵绵，走起路来却气势汹汹。红黎加快步伐，试图拉远距离。没想到红伊水拉住了他夹克的衣角，拽着他不让他跑掉，直到自己跟上来。红黎无奈地回头看她。她的眼神却毫不退让。

   "你必须把昨天的事情说清楚。"她完全不顾及现在是什么场合，和先前的态度完全不一样。他们现在可是在路中央，这么拉拉扯扯的，成何体统。

   "我昨天是在说胡话，我现在醒悟了。"

   "你别想蒙混过去。"

   红伊水松开了他的衣服。他以为自己获救了，没想到她说："你不说清楚，我今天就一直跟着你。"

   "红伊水，你和我关系真好。"

   红伊水瞪了过来，她说："快说，你昨天说到的阿贝莉亚，她怎么了，你还说到了那什么水晶的，又怎么了。"

   "那只是我说了胡话。"他不可能再和她提及半点这些事了。

   红黎跑进了食堂。八点二十分的这一时刻，食堂里人来人往，摩肩接踵，尤其是餐点供应区。学生们端着蓝色的托盘，横向排成了好几路，在那仅五人宽的区域里挤来挤去。队伍都是歪着的，别提有什么秩序了。红黎挤进队伍之后，已经顺利甩脱了红伊水了。他买了两个外皮超厚的肉包和一袋豆浆后，快步离开食堂。

   出乎他意料，当他伸手掀开塑胶门帘之后，红伊水已经在门口等着他了。看来，她今天是非要他说出昨晚的后续不可了。他不由得叹息。

   "不要再追究了。"他说。

   红伊水说："昨晚我仔细梳理了来龙去脉，觉得这里面有情况。"

   她终于注意到了，但是这已经和他没关系了；他又没有机会共享。反倒是她的早餐，可真让人艳羡。她提着两个塑料袋。其中一个塑料袋装着一个烧麦，一块枣糕，一块黄金糕，一个鸡蛋；另一个塑料袋装着一笼份的小笼包。她另一只手还捏着一袋豆浆。红黎好奇她那小小的肚子，怎么能吃得下这么多的分量。他对比了自己手中的厚皮大肉包。没胃口了。

   "你有在听吗？"

   "别再和我说了，没用。"

   "红黎，你很奇怪——你发生了什么吗？"她中途语气低沉了下来。

   红黎故意看了她一眼。她差不多察觉到了。

   "是阿贝莉亚吗？"她说。

   红黎不知道，他现在要是回应一下，或者做出什么反应，昨晚阿贝莉亚设置的魔法阵会不会就此启动。他决定谨慎行事。他已经触怒过阿贝莉亚许多次了，不想再挑战她的耐心的底线。

   红黎往教学楼走。而红伊水在他的身后止步了，陷入了沉思。这时候的路上是人流高峰期，都赶点去上课的学生们一下子把红伊水的身影给淹没了。再一眨眼，他都找不着她人在哪儿了。也许这是好事。

   他到了医药楼侧边的下坡路。他在迟疑，现在去找阿贝莉亚，她是否愿意把手机还给他。还是得再过段时间才好？他抬头望那阿贝莉亚可能所在的三楼的某个实验室。太阳光有点晃眼睛。

   有人抓住了他的手腕。那人拉了他一把，把他拉到了路边的草坪上。浩浩荡荡的学生们往教学楼而去。

   他回头时，看见了一个眼熟的女孩……他想起来了，她在此前的歹徒事件中，为他伸出过援手，她说自己会开车……他再这么一看，觉得她长得可真是可爱——不仅长得可爱，内心更是美好而伟大。他记得，她应该是他们班的学生，名字好像叫许凝。

   她还抓着他的手不放。

   "许凝，你有什么话要说吗？"

   "我之前救了你，虽然没有成功。"

   "啊……嗯。"

   "所以你要报答我。"

   红黎呆住了。他感觉这个女孩给人的印象不是这样的啊……

   "你有意见吗？"许凝说。

   红黎摇摇脑袋。

   许凝说："昨天居然有人告白了。那人真傻。"

   "嗯。"红黎摸不着头脑，这人到底想说什么。

   "昨天那个黑裙女人，在歹徒的那一天她也在。她是谁？"

   "她是学校里的研究生吧。"

   "真的只是这样吗？"

   糟糕，她在怀疑阿贝莉亚的身份。红黎望向阿贝莉亚所在的医药楼三楼……

   红黎说："你不信的话，可以去那边问问，她是货真价实的研究生。"

   "哦。"许凝冷漠地回应了。

   她还抓着他的手不放。所以他走不了。

   许凝说："其实，昨天的事让我很震撼。"

   "啊，是啊。"红黎说道。那人突然发高烧的确让人震撼。但对于他来说，更震撼的是，他昨晚好像多次和死神擦肩而过——还是他自找的。

   她松开抓住他的手，双手捏着双肩包的黑色皮质背带。

   "其实是这样的，昨晚我玩真心话大冒险输了。"许凝说。

   "你到底想说什么？"红黎脱口而出。

   "我接下来会胡说八道，请你有所心理准备。"

   "我要走了。"

   红黎还没迈出一步，他的手又被许凝抓住了。

   "听人把话说完。"许凝说。

   "那请你说人话。"红黎说。

   "我现在要和你告白。"她镇静自若地说。

   这会儿，旁边的学生们都差不多走光了。校园的寂静时刻随着上课铃声的奏响而到来。他不可能会听错。他受到了极大的震动，以至于动弹不得——不，她说自己在胡说八道，所以他得干脆利落地拒绝她。要是他表现得不够干脆，或许会变成她的笑话。他刚要说出口，他的心思好像被什么攫住了——看，这女孩打扮的如此光鲜可爱，穿着轻飘飘的洋服，难道不是有备而来的吗？……他一时说不出话了。

   上课的铃声响起来了。幸亏如此，他可以不用那么急着回答她。他有思考的余裕。他面前的女孩也没有抬头，这又给了他缓冲的空间。上课的铃声是钢琴演奏的一段旋律，让人如同置身于空旷的草原……他一直在思考，好像又什么都没在想，一直到铃声结束了。面前的女孩抬眼看他了。他必须给出答复了。

   "等等，我知道你的答复了。"

   红黎才刚张口，这会儿只得闭嘴了。

   "男生都喜欢我今天穿得这种衣服。"

   "呃。"

   她低下头说："我昨晚连夜赶去市中心买的。又花时间，又花精力。但是我想，要是能把你弄成笑话，那都值了。"

   他好像听着她说。

   "一切都只是在白费功夫。"她说。

   她慢悠悠地转过身，背他而去了。她在路上一直低着头。

   红黎不知道她刚刚说的哪些是真的，哪些是假的，所以没敢追上去。

   这时，红伊水跑了过去——从他的后方跑来的——她拉上了许凝的手，瞪了红黎一眼，匆匆跑掉了。她们跑出一段路后，红伊水似乎为了照顾许凝，慢了下来，改为快步走。红伊水又是给许凝递手帕，又是轻声安慰她，还轻轻拍着她的肩膀。她在用手帕帮她擦拭眼睛。她们即将步入教学楼的时候，红伊水回过头，好像又瞪了红黎一眼。

   红黎不知道，这两人又是怎么个关系。

   他才走出没两步，发现右边不远处站着阿贝莉亚。她站在右边楼房的的阶梯口，盯着他看。她的表情和神态，还有一动不动的姿态，好像执刑者面对罪犯一样。红黎内心紧张，想要快速穿过这条路。

   "有任务，和我一同出行。"

   她没有再多说一句话。径直走向了校门。

   红黎看看教学楼，又看看阿贝莉亚的背影。他恍惚想起刚刚红伊水拉着许凝跑走的样子……他脑袋里一团乱，一团糟。他先不管阿贝莉亚了。他强迫自己站在原地，让自己冷静十秒钟——二十秒钟。

   …………

   他要跟阿贝莉亚离校。这样的话，早上的课程他只能旷掉了。他想把书包放在哪里……他干脆把书包丢在了路边，追着阿贝莉亚而去了。

   阿贝莉亚的目光正视前方，当他从侧面望向她时，她也没有理会他。

   他们经过保安亭。出校门要刷卡。他眼睁睁地看着阿贝莉亚右手变出一张教工卡，刷过机器步出了人行通道。两位保安在亭内一无所知地低头看着手机。她明明不是这个学校的人员，现在已经彻底融入了。或许除了他——和红伊水——这个学校里没人知道她的身份。不过，她或许还缺少一张身份证，如果她要离开省市的话。

   "我们要去哪里？"红黎跟了出去。

   "附近的音乐学校。"阿贝莉亚回答。

   "走路过去吗？"

   "只有一里路。"

   "那里发生了什么？"

   "别啰嗦。"

   马路上的车辆呼啸不止。如今的阿贝莉亚已经不是那个因为一两辆驶过的公交车就一惊一乍的人了。当红黎想起当初的阿贝莉亚时，她的一惊一乍，忍不住想笑。他悄悄落后一步，不让她注意到自己的神态。但是，阿贝莉亚越走越快了。她本来步子就迈得大，现在走路频率又高，他不得不跑起来才跟得上。他喊她走慢点，但是她没理会。他担心她现在已经厌烦了他了。

   "阿贝莉亚，我为昨天的事情道歉。"

   她马上回答："昨天的事情已经过去了。"

   "那你不能走慢点吗？"

   "这和昨天的事情没有关系。音乐学校那边已经疏散了周围的学生，目标还没有发觉。"

   "赶时间吗？那为什么不打车呢？"

   "才一里路。"阿贝莉亚回头，朝他伸手，"把手给我。"

   红黎心生警惕，但还是照做了。他才伸出手，她就一把夺过了他的手，然后抓着他飞奔起来。和他预想的一样。他成了飞在她身后的一叶风筝，被她抓着跑。她好像用魔法托住了他的腰，让他不至于摔在地上。他感觉腹部暖洋洋的。那儿有一片赤色的雾状物……没过一会儿，他就能看见音乐学院的大门了。

   阿贝莉亚没有从正门进入，把他扛在肩膀上，然后跳起来，越过了外墙。她这一连串的动作轻车熟路，好像没少做这样的事。红黎对她在原来的世界里的遭遇好奇，他还是第一次有这样的好奇，之前都只想着自己的事。他想问，但是她看起来并不想回答。

   阿贝莉亚把他丢在了地上，让他自己跟上来。他对她的粗鲁对待已经习惯了，只是拍拍屁股站了起来。她已经走在了前头。她好像认识这里的路一样，一路穿行。

   这所学校的布局看起来和他的学校近似。与大门相邻的，是一片大理石铺就的广场，对面坐落着五层楼高的图书馆，左右两边似乎是教学楼。红黎跟着阿贝莉亚到了前方广场的尽头，沥青路横向左右两边。和阿贝莉亚说的不一样，她说学生们都被散去了，但是这儿四处散布着学生，还有几个团体在广场上排练舞蹈，左右教学楼里还有学生们的齐唱声。红黎追问阿贝莉亚，她的回答和之前的一样。

   他问："我需要做什么？"

   "你什么也不用做。"她说。

   "就这么跟着你？"

   "就这么跟着我。"

   "那我有来得必要吗？"

   "别忘了你的身份。"

   看来他只是出于义务必须要跟着阿贝莉亚。只是，他到现在都还不知道他做这个责任承担者者的意义何在。最险恶的猜测是，要是阿贝莉亚暴走失控了，安管局压制不住阿贝莉亚，就会拿他作为胁迫阿贝莉亚的人质。


## Chapter 12


   他们来到了操场上，到了足球场边缘。操场上没有其他人，只有他和阿贝莉亚——仔细看的话，足球场中央躺着个人，大字型躺开，一动不动，双脚朝向他们这边。他坐起来了，双脚盘起，双手放在膝盖上。这人的穿着古怪，是一身武士服，蓝白色的，身材似乎挺魁梧的。他的面容看得不太清，因为距离的缘故——阿贝莉亚拦住了红黎，不让红黎再前进了——但似乎并不老，感觉是这里的学生。但是看他的这一身怪模怪样的武士服……红黎猜测这人也是和阿贝莉亚一样的异世界来客。

   "目标人物就是他吗？"红黎问阿贝莉亚。

   阿贝莉亚也在观察那人。她说："你就在这里待着，不要进入场地内。"

   阿贝莉亚独自进入了足球场。对面的那人站起来了，看起来有些吊儿郎当，动作摇摇晃晃的，没有习武之人的那种精神气魄。这人估计真的只是一个普通的学生。

   红黎观察起四周。如果他的猜测没错，附近会有一个监视者，监视阿贝莉亚的行动，否则他这个责任承担者在场就没有意义了。监视者也许拿着把来复枪，始终把准星对准他的脑袋——但愿这只是他想多了。

   他看来看去，周围的设施没什么可疑的。阶梯型观众台包围着操场，空荡荡的，没有可以藏身的余地；然后是赭红色的环形跑道，塑胶假草的足球场，两个平平无奇的足球门。操场的外面倒是可能会有埋伏，比如那些矗立的教学楼，在带有窗户的楼道上，或者顶楼上，狙击手会把来复枪架在那里，眯着眼睛瞄准他……他的视力可没那么好，从这儿看不出个所以然来，只能看到各层教室的窗口有学生的脑袋晃来晃去，似乎快要睡趴下了。

   他决定直接问。"阿贝莉亚，我不会在枪口之下吧？"

   这会儿，阿贝莉亚正和那武士男对峙，她一步步地逼近，而那武士男警惕着她，缓缓后退。

   阿贝莉亚回过头，对他说："你说什么枪口？"

   "你怎么回头了，如果敌人偷袭怎么办？"

   阿贝莉亚脑袋转回去了。

   "呵——"那武士男大声说："我可不会这么卑鄙！倒是你们，居然趁着我睡午觉的功夫，偷偷包围了过来。你们是什么组织？"

   "替国家办事。"阿贝莉亚说。

   "我不信，除非你有证件。"那人说。

   阿贝莉亚掏出了一本证书，亮给那人看。

   "我看不见，丢过来！"那人喊道。

   阿贝莉亚把证书收了起来。

   "你丢过来让我看看啊！"

   阿贝莉亚的右手再度抬起时，手中多了一杆两米多长的大镰刀。那刀身太大了，还闪着刺目的寒芒——刀身有一米多宽，呈弦月状，在三分之二的位置与刀柄相接。刀身两面都开刃，反射着锃亮的光。那镰刀还有奇特之处，在刀柄与刀身相接的那段，杠中心嵌着一枚鹅卵大小的宝石，深红色的，和阿贝莉亚眼睛的色泽一样。

   阿贝莉亚行动之间，长裙鼓动不休，像披风一样。四周根本没有风，这儿的空气反而显得沉闷。天空中多出了一片灰色的云，遮住了太阳。

   武士男手中不知何时出现了一柄大刀，那大刀大如斩马刀，只是刀柄略短一点。武士男郑重地摆起了架势。

   "如果你们真的是国家办事，那我愿意和你们交流一下。"

   "丢下你的武器，举手投降。"阿贝莉亚说。

   "那是不可能的。"

   阿贝莉亚冲刺了。她的身形化成了一条残影。然后是一次钝器碰撞的声音。两人的武器交接了一下。只是，那声音为什么这么低沉？……钝器碰撞的声音连续不断。红黎的视觉捕捉不了两人的动作，只能看到一闪一闪的两个影子。阿贝莉亚的身影偏红色，武器显得她的身影更高大，有咄咄逼人之势。两人在对抗时，她的身影会一瞬间清晰，那时候，红黎就能看清她拿着的镰刀的模样：被通透深红的颜色所包裹，与对立面的大刀碰撞。他们好像对抗了数十次，然而时间才过去了几个呼吸。阿贝莉亚的步伐一直在逼近，而那武士男一直在后退。

   武士男打着圈后退，绕着足球场而动——乍一看是这样的，然而，其实是阿贝莉亚一直在他的侧面进攻，逼得他只能在足球场内活动。咚。咚，咚……又过了几个呼吸，他们分离了开来。阿贝莉亚把镰刀举起来，倚靠在肩膀上，她的姿态就像举着一把伞来遮挡太阳一样。她看起来游刃有余。然而，她对面的武士男已经气喘吁吁了，双手把持着大刀。

   "好家伙，这么强……"武士男说道。

   阿贝莉亚拿出了手机，单手在上面操作。她打起了电话。

   "你好，何教授……嗯……在另一个压缩文件里……嗯……那就这样。"

   阿贝莉亚收起了手机。全程，武士男都没有去袭击她。这看起来并不是他如何的光明磊落，而是他没有这个余力了。他用自己的袖子擦着汗水，膝盖半跪下来，在那儿大口喘着气。他的疲惫好像一下子就爆发了出来。

   "投降吧。"阿贝莉亚说。

   "我不能理解……为什么没用……"武士男愤恨地说。

   这会儿，阿贝莉亚的镰刀又被赤色的雾状物包裹了。镰刀从她的肩上垂下……

   武士男大吼一声，一刀划在身前的地面上。红黎眼看着，还以为他要放出绝招了，替阿贝莉亚揪心了一会儿。但是，并没有特别的事情发生——像是飞出一条龙，放出一道冲击波之类的——倒是他面前的确多出了一道沟壑——好像没那么简单，那片塑胶草地没有被撕拉开来，而是迸溅出了一些像素般的碎块，一片片闪烁不止，然后消失在了空气中。武士男举起手中的刀刃，注视着。

   红黎不懂武士男在做什么。他们之间的交锋他也看不懂。这儿不像什么武侠小说一样，有个万能的声音或者不所不知的人，能给他解说。他们两人在演一场哑剧。阿贝莉亚又沉默寡言。他觉得有点无聊了。热闹是他们的，而他什么也没有。他看出来了，阿贝莉亚完全占据上风，根本没有危险可言，她就像猫戏老鼠一样。他无需替她担忧。啊，他也想有阿贝莉亚那样的身手……他坐了下来，想掏出手机解解闷。然而，他的手机被阿贝莉亚缴走了。

   阿贝莉亚的攻势变了，她包裹住镰刀的赤色雾状物向外展开，像蝴蝶的翅膀一样，然后一下子变形，变成了放大了十倍的刀身的样子；她横扫而出。那镰刀虚影辐射范围有半个足球场，武士男根本躲不掉。眼看着武士男要中招了，这时，这人跳了起来，他飞跃了五米高，十米高，还在升高——他借此躲过了阿贝莉亚的攻击——一眨眼的功夫，他变成了视野中的一个黑点。他几乎抵达了云巅，融入了那遮住了太阳的灰黑色云层里。这儿一下子变得清静了。

   阿贝莉亚收起了镰刀虚影，变成了普通的镰刀，然后将它倚靠在肩上。她没有去追踪他，也许是她不会飞。过了好久，天上的那层云好像移动了几厘米的位置，太阳光从云层的间隙透下来。武士男没有现出身影过。阿贝莉亚依然站在那儿不动，只是偶尔会抬头。也许她打算守株待兔。

   红黎低下了头，他仰头累了，脖子酸了。

   "阿贝莉亚，他会不会逃走了？"

   "你不要靠近。"她说。

   "我没动。你打算怎么办？"

   "那人还在。"

   "你怎么知道？"

   "我不知道，难道你知道？"

   天上的那层云又挪动了一点，现在把太阳光都挡住了。红黎打了个哈欠。他睁眼时，发现阿贝莉亚正朝着他冲刺。她那一瞬间的气势，吓得他往后倒下；他下意识地想逃，但他还跌坐在地上。他的身体迟迟跟不上大脑的反应。阿贝莉亚的大镰刀挥了过来，他的视野被赤色的云雾遮蔽了……

   头顶上吹过了一阵风。噔。他的耳膜嗡嗡作响。阿贝莉亚到了他的面前。她的裙裾打在了他的脸上，一时间让他难以呼吸。他挥开了她的裙裾。她的镰刀正横在他的脑袋上方。她抽回手腕，哗的一声，镰刀重新倚靠在了她的肩膀上。这一刻，他才感觉那压倒了他的气势退去。阿贝莉亚的目光正望向他的后方。他的后方，武士男在那儿，狼狈地爬起来。他懂了，刚刚那一下，阿贝莉亚击飞了正要偷袭的他的武士男。

   红黎正准备要说谢谢，却听见她说："害怕了？"

   他说不出口了。他换了句话："你身上都是汗臭味。"

   阿贝莉亚那张黑压压的脸遮蔽了他的天空。从她的那双眼睛里，他察觉到了深深的恶意。他偏过脑袋，假装什么事都没有发生。

   他翻过了身，从阿贝莉亚的阴影下爬出。他看见，上一个试图和她挑衅的人已经倒在地上抽搐了。武士男的银色大刀插入了地面。在刀刃与塑胶地面的接触点，一块块像素碎片飘飞而出，给人的感觉，那块地面好像化成了像素数据一样，正在片片凋零。

   武士男爬起来，双手抓在了大刀的刀柄上，支撑着身体。阿贝莉亚不知何时已经到了他旁边，手中的镰刀压向他的喉咙。那赤色的雾团像是自喉咙渗出的血迹一样。武士男颤抖了几下，跌坐了下来。似乎放弃了抵抗。

   "你赢了。"武士男说。

   阿贝莉亚的镰刀上的赤色雾团正在收缩，它改变了形态，变得像一条小蛇，或者说绳索，在伸长，不断伸长，然后缠向那武士男。武士男任由自己被处置。雾状的绳索绕着武士男的腰和手缠绕了数十圈，捆得严严实实。绳索的另一头自镰刀上脱离，与武士男身上的那一头打结。那雾绳自己会动，扭曲不断。武士男浑身哆嗦了一下。

   "要杀要剐悉听尊便。"

   红黎觉得，这人也就只能嘴上硬气一下了。

   阿贝莉亚掏出手机，在按键拨号，然后接听。"任务完成了……好……那就这样。"她挂断了电话。

   "阿贝莉亚，这是什么？"红黎指着武士男身上缠绕的赤色雾团。

   "元素力量。"

   "元素力量？"

   "元素力量？"

   红黎说了一句，武士男也说了一句。武士男的眼睛也瞪得雪亮，好像很感兴趣。

   "什么元素，火元素吗？"武士男问。

   这是个怪人。红黎心想。要是阿贝莉亚肯轻易回答，那他也就不会迟迟到现在都学不到任何魔法了。阿贝莉亚拉着一段的绳头，拖着这人走了。武士男身体在地面摩擦了一下，然后调整了姿势，跌跌撞撞站了起来，跟着她走了。好笑的是，这人还在追问阿贝莉亚，问她的魔法是什么样的。

   "喂，你叫什么名字？"红黎问。

   武士男停止了喋喋不休，回头说："你是谁？"

   "我是她的助手。"

   "你也会魔法？"

   "你猜。"

   "哼，我不和凡人废话。"

   红黎以为这人断定他不会魔法，就不想交流了。他赶紧说："我会一种神奇的魔法。"

   "你说说看。"

   "你叫什么名字？"

   "我为什么要告诉你？"

   "阿贝莉亚，绳子能让我来牵着吗？"

   阿贝莉亚走了回来。红黎以为她要把绳子交给他了，结果，她只是走到了那插在地上的银色大刀那儿，把它拔了出来。她端详着那银色大刀。

   "哈哈哈，你这助手不受待见。"

   红黎不和俘虏一般计较。

   那银色大刀入了阿贝莉亚手中时，一下子失去了银色的光辉。阿贝莉亚挥舞了两下，刀刃划过空气时带来了沉闷的声响，感觉那刀好像生锈了几百年一样。那刀毫无在武士男手中时的灵性。

   阿贝莉亚把刀递给了红黎。他接过。他知道她的意思是让他也来试试。这刀比他相信中要重三倍以上，让他双手一下子沉了下去，腰也坠了下去。要是他的年纪大上一轮，也许已经闪断了腰。那刀在他的手上也是毫无灵性，暗淡无光。

   "别徒劳了，数据之刃只有我能使用。"武士男冷笑。


## Chapter 13


   红黎明明看见，刚刚阿贝莉亚拿起这刀时，武士男的眼皮跳了好几下，这会儿，又装得道貌岸然了。也许这人自己也不清楚这刀的全部特性。他把大刀递给了阿贝莉亚。他感觉这刀太重了，拿久了嫌胳膊酸。

   阿贝莉亚接过大刀，手一甩，那大刀就消失不见了。

   武士男不理解其中的奥妙，一阵大惊小怪。

   红黎再次恳求阿贝莉亚把绳子交给他来牵，他只是想感受一下这元素形成的绳子入手后的感觉。阿贝莉亚最终还是把绳子交给了他。他捏入手中时，有种捏着一团果冻的感觉，但是比果冻韧性强多了，他再怎么用力，也不会把它捏碎。他手中的这绳子流动着雾色的光点，让他情不自禁就看得入神了。阿贝莉亚催他快走。

   红黎拽了一下绳子，催武士男快走。武士男一阵嘀咕抱怨。这人看起来真的毫无紧张感。也许这人一开始就相信了他们是国家办事的人，只是有点想进一步确认，但阿贝莉亚没给这个机会。这人也许本来就打算招安。红黎打量了一下他的外貌。他的眉眼被刘海遮挡，看不清楚；鼻子、嘴巴凑在一起，被中间的唇须阻断了。他看起来还挺稚嫩的。

   "喂，你不会是这里的学生吧？"红黎问道。

   "我是飞天遁地的侠士，落入你们手中算我认栽了。"

   "侠士不会说自己是侠士。"

   "你可真是个无聊的凡人。"假武士男叹气道。

   红黎断定，这人只是个普通的学生，只是想法有点膨胀了。"你是怎么得到超常的力量的？"

   "我天赋异禀。"

   红黎拽了一下绳子，武士男跟着一下的踉跄。红黎是打算提醒这人自身的处境，却没想到自己能拽得动他。他刚刚可是和阿贝莉亚打得有来有回——虽然只是开始的时候。

   "阿贝莉亚，这人现在看起来好弱，是你的魔法束缚了他的力量吗？"

   "他的力量源于他的刀，现在不在他手上了。"

   武士男发出了懊恼的呼声。

   "你是不是有过一颗紫色的水晶？"

   "你怎么知道的？"武士男面色惊讶，都忘了自己刚刚说话的腔调了。

   "是不是后来它还消失了？"

   武士男说："啊！"

   红黎又接连问了些问题，都是试探性的。然而，武士男都无法回答出来。红黎确信了，这人一无所知，只是偶然触发了水晶，引起了异变，就像红伊水或者那告白之人的情形一样。红黎不想再和这人浪费口舌了。阿贝莉亚已经远远走在了他们前头。

   红黎和阿贝莉亚在校门口等到了张楼罗的车。张楼罗带来了一副手铐，给武士男铐上了。阿贝莉亚不回答任何红黎的问题，红黎就去问张楼罗。但是张楼罗似乎一无所知，或者刻意隐瞒。他说自己只是个派送员，以后说不定还会和他们合作。

   阿贝莉亚撤走了束缚武士男的元素绳索。武士男有点喋喋不休，问他们的身份。武士男的这些问题，等他到了目的地就能得到解决了。张楼罗等武士男坐上了车，就发动引擎开走了。红黎还以为，这回他和阿贝莉亚也需要跟着去。

   事件出人意料的结束了。当阿贝莉亚和武士男打起来的时候，他还蛮紧张的，还以为这件事会越闹越大，首先他们的打斗会惊动本校的学生，惊动校方。警察车会接二连三的开进操场，说不定连武装警察也会登场，还有直升机什么的……他设想了许多种场面。

   阿贝莉亚往回校的方向走了。红黎跟上她，看着她——果然是活生生的人啊，他忍不住这样想。他在思考，阿贝莉亚的出现，还有武士男的银色大刀，这之间会有什么联系。

   "阿贝莉亚真是强大啊，三两下就解决了那个人。"

   "嗯？"她难得反应了一下。

   "我还以为事情会变得更复杂。"

   "你在期待危险发生？"阿贝莉亚说。

   "没有。"

   "你在期待。"

   他问："阿贝莉亚，你原本的生活是怎么样的？"

   阿贝莉亚沉默了很久，久到他以为自己又要被她无视了。但是她过了一会儿，又从嘴里挤出了几个字："不怎么样。"她还深沉地说："我一直在和生与死长跑，和复仇长跑。"

   红黎一时间激动难耐，双手都有些颤抖，但他还是努力控制了情绪。不知为何，阿贝莉亚的话匣子好像打开了，说了些平时根本不愿意吐露话。这时候，他应该不动声色地打探阿贝莉亚的更多的秘密。

   "你是革命战士？"

   "你在说什么？"

   "不然就是神学家？"

   阿贝莉亚说："你没听我说吗，是复仇！"

   红黎感觉自己搞砸了，刚刚一时激动，没注意思考阿贝莉亚说的话。现在她好像有点不难烦了，他担心阿贝莉亚不愿意再透露……不过她说复仇，那就不可能是什么简单的事了，八成是痛苦曲折又辛酸的经历。也难怪她不愿意说了。他这么想着，逐渐不报期望了。阿贝莉亚不太可能对他细说。

   他干脆直接表达了自己的想法："阿贝莉亚，你说的不够具体，我没法想像。"

   "你不需要知道。那不值一提。"

   果然是这样。红黎泄气了。

   也许他该说些安慰的话。但是，他根本不知道怎么说。让他一个一直生活在和平的世界里的学生身份的人——虽然也有各种烦恼，但根本谈不上生和死——让他来安慰她，这不是不自量力吗？他还是保持沉默的好。但是啊，他还是想知道，她到底有着什么样的来历……他最想知道的是，她的过去和红伊水——这个与阿贝莉亚的出现有着密切关联的人——两者之间到底有什么联系。他有一个离谱的猜想，但是好像能解释所有的问题。

   "阿贝莉亚，我说你不会是……"

   阿贝莉亚略微偏过了头，看向他。她的眼神让红黎无法继续说下来。她的眼神充满了哀伤和疲惫，完全不像是她这个年纪会有的人的眼神。尽管如此，她的嘴唇依然紧闭着，就像是一位战士在宿命的时刻依然高举着剑和盾一样。如果是其他一般年龄的人，在那双哀伤和疲惫的眼睛之下，早就发出痛恨的叹息了吧。但是她没有。她的哀伤和疲惫，还有那内心深处的执着，让红黎无法轻易开口。他应该尊重这位有血有肉的人。

   "你想说什么？"阿贝莉亚轻声地说。

   "没什么。"

   阿贝莉亚口中的生与死，还有复仇，可不是他看过的那些故事里的那些生和死——那是会带来血的代价的。他的目光落向了她的那双手。他第一次见到她时就注意到了，她的那双指尖青紫的手的指甲的缝隙里残余着许多干涸的血丝。不过现在好像都被她洗掉了。

   离学校还有几分钟的路。红黎说："我们换个话题吧。"

   "你不追问了？"

   "啊，说实话，我对阿贝莉亚怎么样一点兴趣都没有。"

   "嗤。"

   "哼哼。"

   "你想聊什么？"

   "阿贝莉亚，你现在居住在哪里？"

   "为什么问这个？"

   "我就是对你的衣食住行感兴趣，你想，你不是凭空到了这个世界吗？"

   "我一日三餐在食堂解决，睡觉睡在实验室。那儿的教师让我在她那儿工作，她说她那儿的房间可以任我使用。"

   "呃……但是你看，人活着不仅仅有吃饭和睡觉的问题……"

   "还有卫生的问题。"阿贝莉亚说。

   红黎不知道该怎么接话。

   阿贝莉亚说："之前你说我身上有汗臭。"

   "我没有。"红黎赶紧否认。

   "所以我们走在这条路上。"

   红黎没明白她的意思。但是他注意到了，这里绝不是他们回学校的路。音乐学院距离他们学校也就一里路，没几步就走到了，可他们走了好一会儿，居然还没到，不如说，他们的学校在远方越来越小了。原先，他们的学校应该在前方，现在却到了右手方。周围是陌生的街道。他一直没有留心往哪里走，只是跟在她的后面。红黎停了下来。

   "这是要去哪里？"

   "去你家。"

   "哈！"

   红黎追上走个不停的阿贝莉亚。"所以到底要去哪里？"

   "去你家。"

   "别开玩笑了，你连我家在哪儿都不知道。"

   "这条路直走，到了对面是一家银行的十字路口那儿，左拐，直行，直到看见一家五月百货大厦，右拐，一路直行……按照我们现在的步行速度，一个小时后才能到。我们得加快速度。"

   红黎不知道她说的是真是假，因为他也不知道走回家的路，他只会做公交车回去。但是，他无法否定阿贝莉亚，因为她说的太具体细致了。她提到的一些标志性建筑，他都有印象，他为了防止晕车，总是观察着车窗外的风景建筑。他好像见过她说的这些。

   "你给我我的手机。"

   阿贝莉亚手中变出了他的手机，还给了他。

   红黎都顾不上与手机重逢的喜悦了。他开启地图导航，核对她所说的路线……她说的完全一致。她也许也是通过导航查到的去他家的路线。但是——

   "你怎么知道我家地址的？"

   "查一下就知道了。"

   "这怎么可能查得到，又不是……你难道用的我的手机？"

   "在网络上查的。"

   红黎不信，怎么可能就这么简单。她要么通过他的手机得知的，因为手机就在她手上，她又见过他输入密码开锁，这样就容易了，直接打开他的班级群聊，或者搜索手机上的表格文件，总有一个表格填写了他的家庭地址的，开学的那段时间他填过不少这样的表格；要么在某个老师那儿问过来的。她总不可能像她说的那样，用浏览器在网络上搜索一下……他想到了他上实验课的那天，她操纵的代码跳动不止的黑框画面——她可能成了一个黑客。

   "阿贝莉亚，难道你是个天才？"

   "你想说什么？"

   "你不会在我的手机上装了什么吧？"

   "你觉得呢？"

   他原本只是随口说说，但看阿贝莉亚的这个反应，也许真的有这么回事。他决定找机会换个手机——这有用吗？他现在本来就没钱了，正打算找工作兼职。

   "所以你去我家到底要做什么？"

   "参观。"

   "你不会是要看看红伊水的生长环境吧？"

   阿贝莉亚面无表情，连睫毛都没颤动一下。红黎不知道她这样的反应是什么意思。

   "我先说清楚，我和红伊水根本不在一个家庭里。"

   阿贝莉亚说："我当然知道。"

   "你……这……你……"红黎终于说出口，"你怎么可能用'当然'这个词来说明你知道的这件事？"

   "你和红伊水的身世我都已经调查清楚了。你们两人都是孤儿，同在一个孤儿院，在四岁的时候被同一个家庭领养。在你们九岁的时候，你们的家庭经营的公司破产了。你们的养父母本就是为的名誉而做的慈善，现在家计都成了问题，当然也就不愿意再照顾你们了。你们被转让给了另外两个家庭。从此以后，你们就生活在不同的家庭中了，几乎没有联系。"

   "阿贝莉亚……"

   "我说错什么了吗？"

   "从你出现以来，刚刚那段话可能是你说过的最长的话了。但是，我没想到这段话会是关于我的身世的调查报告……"

   "你不用沮丧，世界上还有更多的错综复杂的家庭环境。"

   "你觉得我是为这件事沮丧吗？"

   "哈哈哈……"

   阿贝莉亚居然笑了，笑得还特别开怀。她的脑袋微仰着，眼睛眯起来，被漆黑的睫毛遮挡得一点光线都看不到了。她的两腮嘟起来，变得圆鼓鼓的。她的嘴唇笑开了，露出了两排的贝齿。她这张冷漠的脸因为笑而幼稚了十岁，看起来像个十岁的小女孩。怎么看，怎么觉得幼稚。任谁都会怀疑，她和十秒钟之前的那张脸究竟是否是同一人。她的笑容一时半会儿居然停不下来。

   红黎呆愣地看着她，不知道有什么值得笑这么久。他们这会儿引起了路过的人的关注，他们眼神的意思大概是：瞧啊，两个逃课出来的学生，现在尽管笑吧，将来有的你们哭的……

   阿贝莉亚差不多笑够了，只是那弯成月牙的眼睛怎么也变不回去。她眼底的是深红色都褪尽了，那深邃的气质彻底消失。她的神色逐渐变回来了，她用手掩盖着自己的笑容，然后又别过头，在那儿释放着笑的余波。她面朝着马路，而红黎就这么看着她走。他们两人走着走着，差点撞上了前面的路摊。他们绕了过去。现在，阿贝莉亚已经一脸寻常了。即便如此，红黎还是感觉，她现在脸上的肌肉都松弛了不少，变得柔和了。红黎想说点什么，但又止住了。他觉得现在要是多嘴了，她可能会像受惊的兔子一样飞窜——以后就不会在他面前这么释怀地笑了。

   "阿贝莉亚，难道我们就这么走过去吗？"

   "嗯？"

   她的反应有点迟钝了。

   他无奈地问："我们为什么不做公交车？"

   他们刚好到了一座公交车的站台。阿贝莉亚好像对坐公交车没有意见——应该说，她是因为没有坐过公交车，所以没有考虑这个候选项。于是，他们俩在这儿等车了。他坐在钢板长凳上，看着来往的车辆；而阿贝莉亚，她观察着旁边的站牌，似乎对公交车的班次和路线感兴趣。她看了没多久，也就失去了兴趣，拿出手机在那儿操作。他们一时半会儿没等到车。

   一位老大爷低头经过。他佝着背，一只手拿着手机，另一只手在上面点触，那手机以语音播报着他连续的操作动作，大喇叭响个不停。老大爷抬起头，朝着阿贝莉亚走近了。

   "小姑娘，你帮我看看这个语音要怎么关掉啊，它这么叫着嚷着，可烦死我了。"老大爷把手机递向阿贝莉亚。

   阿贝莉亚略微抬头，视线停留在了老大爷的手机上。

   红黎站了起来，赶紧过去给她解围。然而，阿贝莉亚接过了手机。她试着按了一下屏幕……语音系统喋喋不休，唯恐人类听不懂人话一样。老大爷也喋喋不休，唯恐阿贝莉亚没明白他的意思一样。红黎一时不知道该怎么做好。阿贝莉亚好像并不是没有这个耐心帮老大爷解决问题。他决定静观其变。

   她盯着手机屏幕看，青紫色的指尖点了一下设置APP。手机画面迟迟不响应，直到啰嗦的语音汇报结束。她进入了设置界面。她的手指滑动着菜单栏。古怪的是，那菜单栏没有向下翻页。她的操作并没有任何问题。语音喋喋不休，不知道在说些什么。她又试着操作了一会儿，在桌面和设置的界面内来回切换。她没能成功找出关闭语音播报的功能键。但她依然在耐心地尝试着。红黎想给她点提示，然而他也对这个充满讽刺的老人机画面一无所知……

   她放弃了滑动菜单栏，双击搜索栏。她观察了一会儿弹出的输入面板。那是手写面板。红黎在一旁提示了她。之后，她的食指在面板上滑动，写出了一个"一"字。她把字删掉了，然后写入"语音播报"这几个字。红黎大吃一惊，她居然能够书写中文了，还写得如此板正，就和印刷体一样。随后，她回车输入，点击了搜索。没有找到结果。

   她退出了设置界面，右手抵着下巴，陷入了沉思。红黎期待着她的解决办法。要是她选择切入一个输入代码的黑色界面，他好像也不会特别震惊……不久，她拿出了自己的手机，点开了浏览器。她在搜索如何关闭语言播报，而且还写入了手机的品牌名来准确查询……之后，阿贝莉亚根据搜索到的结果，顺利关闭了那手机的语言播报。她收获了来自老大爷的感激。

   "没想到你居然会帮他。"红黎说。

   "我又不是十恶不赦的人。"

   "不是这个层面的问题吧。"


## Chapter 14


   为了帮助老大爷，他们错过了一班公交车。他们又等了十分钟，终于坐上了另一班车。又是十分钟，他们到了红黎的家的居民区。他们一路穿行，绕过了那些郁郁葱葱的园林布局，到了他家的那栋大楼之前。他们乘着电梯向上，到了第十层。他们踩着鲜红的地毯步出电梯，可以眺望到走廊窗外的都市盛景。阿贝莉亚在这儿稍作停留，俯瞰着下方的车水马龙。现在是午时时间了，太阳的光把地面铺成了金褐色。阿贝莉亚也不知在对什么看得入迷……他们拐过了一条走廊之后，就到了他家居住的套房。

   红黎姑且按下了门铃，虽然明知道没人会在里面。他取出一直放在口袋里的钥匙，打开锁，推开门，脱下鞋子，摆正在玄关口的边缘处，穿上鞋架上的拖鞋。他也给阿贝莉亚取了一双拖鞋。阿贝莉亚的靴子看起来超级难脱下，因为鞋绳在包住整个小腿的鞋帮上不知道缠绕了多少回。然而，她只是踩在玄关口的毯子上，鞋帮上的鞋绳如同活物一样，自动就松开来了，鞋帮向外扩张了一圈，她轻松地就从中抽出了穿着黑色棉袜的脚。真是便利的魔法。

   "你家里有人。"阿贝莉亚说。

   他家里怎么还会有人呢？

   嗵，嗵，嗵……像心跳一样的脚步声。

   一个穿着布偶睡衣、戴着连衣帽的女孩跑了出来。她的目光和红黎的对在了一起。那双圆溜溜的大眼睛变得越来越大。她的目光移开了，落到他身旁的阿贝莉亚身上。她的目光又回来了，呆看着红黎。她的目光在他和阿贝莉亚之间来回了几遍。她的一只手搭上了墙，身形晃了一下。红黎还以为她要倒下去了……她的另一只手抬了起来，让他不要过来。她好像需要一会儿的时间来缓冲。红黎也没想到，他们在这个时间点回来会遇见她。她这会儿应该在学校才是，现在是面向高考的冲刺时期。

   "哥，是你吗？"她带着不确定的语气问。

   "你生病了吗？"红黎说。

   "你是红黎？"她又问。

   看来她相当的不确定是否是他。"没错，我是红黎。"

   "不可能……我肯定是出现幻觉了。"她低下头，手掌拍着自己的额头。她对于眼前这一事实抱有深深的怀疑。

   "我带客人回来了。"红黎说。

   阿贝莉亚踩入了客厅中。她脱鞋没穿，黑色的长袜子包裹着她圆润偏小的脚掌。她在红黎的侧前方站定了，面向着那个女孩——名字叫郑安若，是他在这个家庭中的妹妹。

   "这位是？"郑安若盯着阿贝莉亚。

   红黎不知道该怎么解释。

   阿贝莉亚手中多出了一个精装的木制匣子，她走向郑安若。她走得坦然平静，而她对面的郑安若却怯弱地退开了，虽然只是一小步。阿贝莉亚将木匣子呈给郑安若，说："冒昧来访，这是我的敬礼。"

   安若呆呆地看着匣子，没有伸手去接。

   "她叫红伊水，是我以前的家庭的妹妹。"红黎说。他觉得这样的谎言不太可能被揭穿，谁叫她们两人长得一模一样呢。

   "我叫阿贝莉亚，不是你哥说的那人。"

   阿贝莉亚背对着红黎，面向着安若，声音平稳，像是在说一件理所当然的事。但她当场揭破了他的谎言。他这么说并不为了别的，只是便于解释而已，否则安若肯定会追根问底……但阿贝莉亚好像并不是这么想的。她似乎对自己的身份有所执着。

   不管怎么样，她怎么想他不知道，他只知道，现在自己的脸的温度升上来了，变得发烫了。他不想在这时候面对他的妹妹了。客厅的窗户似乎密闭着，一点空气也无法流通。门也关闭着。他现在想去打开窗户，打开门，或者开个电风扇，钻进电冰箱里……安若正盯着他看。

   安若接过了阿贝莉亚递来的木匣子。她轻声说："谢谢。"她走向了她自己的房间，回头对红黎说："哥，你先招待客人。"

   她咔嚓一下关上了关上了房间的门。

   他累了，现在只想休息。

   阿贝莉亚在观察四周。这儿距离他一年前回来没什么变化。入口两边整洁地摆设着鞋架和伞架。到了客厅，背门的墙贴靠着一张长沙发，沙发前面挨着一张带有玻璃桌面的矮桌子，对面是液晶大电视屏，占据着半个墙壁，像是观影墙一样。那漆黑的色泽，初来的客人的目光总是会被它吞噬掉，感慨好大一个电视屏幕，转而就会心想这个家庭是多么的殷实了。墙壁和天花板都粉刷成了燕麦的色调，看起来柔和又舒适。客厅的四角设立着常青大盆栽，向阳那边的盆栽的脚下，还摆放着三个小小的多肉类盆栽。厨房和洗浴室的门都敞开着。

   "请不要把我的身份弄成红伊水。"阿贝莉亚说。

   "我知道了。"红黎说。

   "那里就是浴室吗？"

   她的话题跳得有点快了。她指着浴室说。红黎点头表示肯定。

   她说："我要借用一下。"

   "你……不会来这里就是为了借用它吧？"

   阿贝莉亚已经自顾自走向了浴室了。洗浴室与厕所相邻，但中间隔着玻璃门扇，两间都单独对外开门。洗浴室内的墙壁和地面都装修着黑亮的瓷砖，白净的洗漱台凸出墙壁，大浴缸靠在里侧，它的旁边高架着喷淋装置。这些设施对于红黎来说再寻常不过——除了那奢侈的大浴缸——但对于阿贝莉亚来说，估计挺新奇的吧。他看向阿贝莉亚。她打量着洗浴室四面的同时，已经在脱自己的袜子了，脱掉的都从她手中消失了，然后踩上入口处的咖啡色拖鞋。

   "会用喷淋装置吗？"红黎问道。

   阿贝莉亚摇头。红黎踩上另一双黑色的拖鞋。他没想到自己的这双还一直摆放在这里，和他父亲的那双灰色，安若的那双粉色，还有阿贝莉亚脚下的母亲的那双一起。浴室内飘荡着不知名的花草芳香。红黎为阿贝莉亚简单演示了喷淋器的用水开关，还有温度控制。以阿贝莉亚的聪慧，果然马上确认了自己已经明白了。红黎离开前，给她点开了白炽灯，拉上了雾化玻璃门。

   "如果缺少衣物的话，我可以帮你向郑安若借。"红黎说道。

   "不需要。"浴室里面回答。

   红黎坐到客厅沙发上。

   安若换了衣服后从房间里探着脑袋出来了。她上身穿着一件银灰色的小西装，纽扣端庄地都扣齐了。她下身佩着同样银灰色地百褶裙。她脚下却踢着布偶拖鞋。她头发也梳理整齐了，后面扎着马尾。她看起来像是要出门的装扮，又不像是要出门。她轻手轻脚走到沙发边，还在张望四周。

   浴室方向传来了喷淋的水声。隔着十几步，雾化玻璃门上有阿贝莉亚模糊的身影。安若在原地深呼吸，胸腔膨胀了，又缩小了。她凝视了那个方向好久，直到喷淋声暂歇。红黎也没说话，就看着她，任由她胡思乱想。她抱起沙发上的靠枕，坐在红黎的身侧。红黎挪动位置，给她腾出了一个身位。现在，他们的位置把沙发分成了三段。

   "哥，我要是不在这里，你不会就和……做苟且之事吧？"

   "说人话。"

   "她是谁啊？"

   "解释起来麻烦，就不解释了。"

   "你一年没有回来，结果回来的当天就带了女朋友。身为你的妹妹，我有义务打断你的腿。"

   "你从哪里学会的这些话？"

   "所以她到底是谁？"

   "我女朋友。"

   她瞪大的眼睛忽然就小了下来。"那我就安心了。果然，你怎么可能会有女朋友。"

   "喂！"

   安若从沙发上蹿起来，跑向厨房。"我给客人准备点水果和饮料。"

   他想不到，一年不见，安若就变得细致周到了。但还是这么调皮。

   红黎拿起桌上的遥控器，打开电视。他换了几个频道，就看到了不得了的新闻。中央新闻正在报道发生于洛城的暴乱。五名暴徒袭击了洛城的行政大厦，动机不明，在里面驻留了下来。警方的最初行动以失败告终，冲入大厦的警察被开枪射杀；暴徒似乎持有军队的各类制式武器，手枪、步枪、冲锋枪、手榴弹、军刀等。警方的包围圈正进一步形成……特警部队已经出动，视情况，驻扎在附近城市的军队也会出动……

   安若端来了一盘切好绽开的橙子，盘子边上还放着一碗切成块的苹果，插着牙签。她放在桌上，又匆匆跑回厨房，端来摆着三个玻璃水杯的托盘。水杯上飘着水雾，估计是热开水。她本来看着杯子，注意着脚下，走得好好的，中途却抬头朝红黎傻笑。糟糕的事发生了，她右脚踢上了左脚，那双笨重的布偶拖鞋……有那么一瞬间，她托盘上的水杯几乎飞了起来。水杯中的液面一齐翻飞……液面摇摇晃晃，洒出了不少。还好，她稳住了身形。

   红黎迎上去接过她的托盘。

   "你偶尔也回家来看看嘛，爸妈都在挂念你呢。"她若无其事的样子。

   "是吗？"

   "你为什么不信呢？"

   "我信。"红黎说。

   "你果然不信。"

   "你是不是对我抱有成见？"

   "是你对这个家抱有成见。"她说。

   红黎决定换个话题。"是不是快要高考了？"

   "不要转移话题。"

   "要努力学习，装病逃避是没有用的。"

   "谁装病了！……不要转移话题。"

   红黎把盘子摆在了桌子上，给她递了一杯水，又插起一瓣苹果给她。以前她要是哭闹个不停，这样就能堵住她的嘴。然而，她把他的好意通通推开了。她的眼神不肯罢休。

   "这没什么可说的了。"他说。

   "你为什么要这样呢？"她装出了伤心的样子。

   "你别这样，我什么都没做好吗？"

   "就是因为什么都没做才……"

   这样的气氛让人感觉无休无止。

   "安若，我只是到了可以独立的年龄了。"

   "那又怎么样？"

   "你知道的，我不想給这儿添麻烦。"红黎无奈地说。

   "你怎么会添麻烦，谁说你麻烦，没有人说你添麻烦！"

   "你太激动了，快喝热水。"红黎说。

   "红黎，"她生气的时候就直呼其名了，"你不仅不回家，还一个电话都不打回来，一个消息都不发给我。到现在我连你的电话号码都不知道，你换手机了对吧？把之前的电话卡丢了是吧？"

   "之前的电话费太贵了。"

   "你现在的电话号码是多少？"

   红黎把电话号码告诉了气势汹汹的安若，然后又和她交换了WeLine账号。这样，她的火气就环合下来了。她马上给他发了问好的消息，即使人就在对面。

   "你满意了吧？"红黎说。

   "你要是敢拉黑我……"

   "看你表现。"

   安若挨近了红黎，插起一瓣苹果塞向他的嘴巴。红黎偏过脑袋，从她手中接过了苹果，把它放回了碗里。他不想吃苹果，没胃口。安若和红伊水是两个极端。和红伊水对话让他心灰意冷，和安若对话又让他心神疲惫。安若热情地有些不像话。她年龄还小的时候，总是处处针对红黎，排斥他这个外来者。她年龄大了一点了，似乎渐渐接纳他了，又喜欢闹着和他一起玩。

   她有点过度黏人了。她的父母一度担心他们两人有逾距的感情，所以常常刻意让他们疏远。安若对此一无所知，但红黎因为家庭辗转，生着一颗敏感的心。他看出了她父母的用意。也许他们是嫌他是个蠢笨又没有前途的孩子……不管如何，她的父母选择了让他们疏远，他就不会违逆他们。毕竟他们把他养大了。

   "为什么不吃？"

   "你吃吧。"

   "果然你一段时间没回来了，就生分了。"安若嘟囔着说。

   安若一无所知。

   "你今天没有上课吗？"红黎问。

   "我前两天感冒发烧了，请假在家。"

   "没有装病吧？"

   "哼。"她表示抗议了。

   "你在贪图最后的享受吗，所以感冒好了也去不上学？"

   安若在用余光偷偷看他。她笑开了嘴，张开双手，把自己陷进沙发里，仰面靠在沙发背上，整个人像瘫痪了一样。她还挺着两条腿在那儿晃荡。"你管不着我。"

   "你已经十七岁了。"

   "怎么，我不成熟吗？"她说。

   "嗯……"

   "我勤俭持家，勤劳能干，家务活样样精通，学习也分毫不落下，运动能力也是数一数二的。我这样的女孩，不成熟吗？"

   她在学校的表现他不知道，但是家务活她说的没错。家里的卫生都是她打扫的，偶尔还由她负责做饭烧菜。在这方面，她比他强多了，是这个家庭不可获取的一员，为父母排忧解难——而他就是个累赘——红黎看了一圈四周。这儿的柜台、桌椅、地面，都被擦拭得白净发亮，一点也不含糊。仔细闻的话，周围还有股草药的清香。细致的安若会给房间的各个角落挂上香囊，用以扼杀虫物和霉菌。

   她说："顺便一提，班级里的男生被我迷得神魂颠倒，都无法安心学习了。但是我要说，这完全不是我的错，我只想好好学习。"

   她从沙发上跳起，张开双手翩翩转了一圈。

   红黎说："你们学校是不是作业太少了，让你们整天想些有的没的……"

   她用竹签插起了一块苹果，塞进了他的嘴里。

   她弓着腰，另一只手撑着膝盖，对着他笑嘻嘻的。红黎无奈地咀嚼了几口，把苹果吞下。她又送来了一块苹果，送到他嘴边，对他说："啊——"。她只得再次咬下那苹果。然后，他夺走了她手中的竹签，插上苹果，塞进她那"咯咯"不停的嘴里。她还在吞咽的时候，他就再次将苹果块按到她嘴边，报复她，一个劲往里塞。她使劲闭着嘴唇，也憋着笑，但是眼睛和脸蛋都挤出了弦月的弧度。她双手推拒着他送上来的苹果，扭着头，跌倒在了沙发上。她以双脚蹬着他的身体。他可撑不住她蹬的那两下，捂着胸口就倒在了沙发的扶手上。他缓了好一阵子，才重新把气理顺，然而她一直仰躺在沙发上，没心没肺地笑个不停。

   "你今天要住下来吗？"她坐直了问道。

   "我过会儿就走了。"

   "啊？"

   阿贝莉亚的淋浴声已经结束了，现在可能在穿衣服——浴室的门拉开了，穿戴整齐的阿贝莉亚款步而出。她依然穿着那身黑色长裙，双手把蓬松的乌发都撩到了身后。阿贝莉亚和安若视线相对了。

   安若绷了起来，告诉她吹风机在哪儿。但是阿贝莉亚的头发已经干了……阿贝莉亚和她说自己不需要吹风机。然后她们俩人就沉默住了。过了干巴巴的那么一会儿，安若向阿贝莉亚做了自我介绍，自己是红黎的妹妹什么的，名字叫什么，现在是高中生什么的，然后规矩地向她请安，又说了感谢照顾自己的兄长之类的。

   阿贝莉亚只是对安若还以了基本的礼仪。她在客厅里转了一圈，不知道在观察什么。她到了各个房间的门口，面对着紧闭的门，像是发了一会儿的呆。她路过了客厅的几个柜子，视线有几秒钟在上面停留。客厅角落的那些盆栽也被她关注到了。她的举止可疑，但是毕竟没有做出进一步的行为。红黎也就由着她了，他要是说些什么，她也不一定听得进去。倒是安若，居然也和他一样只是看着阿贝莉亚的行为。

   安若缩到了红黎这边，跟他耳语："她是你的同学吗？"

   "算是吧。"

   "名字真奇怪，是外国人吗？"

   "……算是吧。"

   "怎么都是不确定的答复？"

   "有什么问题吗？"

   "问题多到不知从何提起……"

   阿贝莉亚踅身回来了，往沙发这边走近。眼见着的安若一下子挺直了身板，看起来比他还紧张——其实，他刚刚就觉得这三人在场的气氛有些微妙，该怎么说呢，就是彼此之间好像无话可说的感觉。阿贝莉亚又自顾自的。

   "我们走吧。"阿贝莉亚说。

   真是出乎意料的话，但好像是目前局面的最好的结果了。红黎说："哦……"

   安若又凑过来悄悄说："哥，她只是过来洗澡的吗？"

   红黎推开她。他心想，你说的什么，她肯定听得一清二楚了，只是装作没听见而已。

   他从沙发上起身，说："安若，记得把水果都吃掉，时间久了会氧化变黄的。"

   "你要走了？"

   "嗯。"

   "再多待一会儿啊！"

   "我们还要上课。"

   "留下来吃午饭吧。"

   "都说了要走了。"

   "留下来吃午饭，我下厨！"安若说。

   红黎说："我们要赶下午的课。"

   "我说，上课比家人还重要？"

   他走向房门，让阿贝莉亚跟上。他也跟着胡言乱语："课逃了就没了，但家人会一直在。"

   "那你要是走了，我就去跳楼。"

   安若追着他到了门口，还拉住了他的衣角，不让他走。

   "别说胡话。"

   红黎拍开她的手，蹲下穿鞋子。他穿好鞋子的时候，她还杵在他旁边，一副欲言又止的样子。

   "我会填报你所在的大学的。"她说。

   "那爸妈不把你腿打断。"

   安若蹲了下来。红黎还以为她要干嘛，结果她居然把他刚寄好的鞋带给解开了。她拉了一下线头，就那么一下……红黎忍不住翻白眼了。

   安若一本正经地说："大学好不好不重要，看的是个人努力。"

   红黎推开她，蹲下来重新系鞋带。"你的成绩足够好，完全可以好的大学加上好的努力。"

   "我和你不一样，我觉得家人更重要。"

   "你爸妈也觉得家人重要，但他们还是每天去上班，把心爱的你留在这里。"

   "那也是你的爸妈！"

   "好了，不说了，我要走了。"

   红黎跨步到了门外，作势要把门给关上；但阿贝莉亚慢吞吞地不肯出来。她一直在旁边看戏。他感觉可真够尴尬的，兄妹俩你来我往，真成了外人眼里的笑话。他可不想再让她看下去了。

   阿贝莉亚慢悠悠地系着繁复无比的鞋带。她系好了一边，又系另一边。由于安若在一边看着，他也不好催她赶紧用魔法尽快系好。噢，她终于系好了。她步出了门外。在这期间，安若没再强词夺理了，只是看起来有些委屈巴巴地站那儿。

   他要关门了。

   安若没有再阻止他了。她向他挥手说："记得周末回来。"

   "看情况吧。"

   "才几分钟的路，你……"

   红黎把防盗门给关上了，她的声音戛然而止。门的隔音效果很好。


## Chapter 15


   红黎和阿贝莉亚乘坐电梯下楼。两人并肩面对着紧闭的电梯门钢板，都不说话。红黎扭头观察她洗完后亮晶晶的头发，已经干透了。电梯间内沁满了花草香。也许是淋浴了挺久的缘故，她的肌肤变得粉红通透了，让她看起来像个普通的少女。

   "有什么问题吗？"

   "你这样看起来，也挺普通的。"

   "你在说什么？"

   "自言自语。"红黎说，"你给的安若的木匣子装了什么？"

   "保密。"

   "这有什么可保密的？"

   阿贝莉亚就是不说话。

   红黎故意说："不会是什么危险的东西吧？"

   "是一颗炸弹。"

   这是阿贝莉亚的幽默吗？

   "你告诉我呗！"

   阿贝莉亚猛地转头，冲他说："黎，请不要把我当成你的郑安若，我不是她，不要用这样的语气和我说话。"

   她突如其来的凶相让他始料不及。他呆住了。他不知道自己说错了什么。他刚刚有说了什么过分的话吗？……他不知道该作何反应。有一瞬间，他还以为她在开玩笑。但是她依然默不作声。电梯在坠落，坠落，他感觉自己的情绪也在坠落。阿贝莉亚面无表情地看着电梯的钢门。他感觉自己的血冷了下来。一直到电梯门打开，他们从电梯中走出，她都没有再说过一句话。他觉得自己可能哪里做错了。他陷入了反思……

   他刚刚可能下意识把她当成了安若，所以说话无所顾忌了。安若给他的感觉太轻松惬意了，什么都不需要思考，冲到脑袋上的话直接就说出来了。他可以随便应付安若，她不会有任何抗拒，也根本不会怪罪他，像一团棉花一样任凭打骂。但是他现在面对的可不是郑安若，而是阿贝莉亚。他可能昏了头了，还这么随便说话……他需要冷静一下，想想之前自己是怎么和阿贝莉亚说话的。

   "你们的关系好到无聊。"阿贝莉亚说。

   他们正步出这幢公寓。阿贝莉亚依然步子迈得很大，他得加速才能更得上。她那么说了一句的说话，他还在反思中，一时间以为自己听错了。但是他的确听到了这样一句话。

   "我和她关系好吗？"红黎说。

   "好到我都想摧毁掉。"她说。

   红黎停下了。阿贝莉亚在他的眼中越走越远。她走出了十几步之后，回过头来，说："骗你的。"

   "你这是在开玩笑吗？"红黎干笑道。

   "有趣吗？"她说。

   "啊……真的有趣。"

   "抱歉，是我说过了。"

   阿贝莉亚居然道歉了，他怎么也想不到。这时候他该怎么回应她呢？……他还是捉摸不透她的想法。她不是说刚刚她是开玩笑的吗，现在怎么又郑重其事地道歉了？……但既然如此了，他也只能说点原谅她的话了。

   "我和她很难再有联系了。"他说。

   "如果想把我当成倾诉对象，还是算了吧。"她说。

   "我还以为你会愿意听我倾诉一下。"

   "无聊。"

   "阿贝莉亚，我果然还是搞不懂你。"他坦白地说了。

   "你为什么想搞懂我？"

   红黎停下脚步。前方的阿贝莉亚又走远了一段路，终于回过头看他了。他们已经离开了居民小区，这会儿，马路上的汽车、卡车、公交车来回穿梭，交响着鸣笛声。靠边新刷的白墙上画着各式各样的公益图标、漫画，有关国家兴荣的，有关省市建设的，也有关于个人发展的，个人幸福的。这一段路没有其他行人，只有阿贝莉亚和他遥相对视着。他回想起首次见到阿贝莉亚，对方给他展露魔法手段时的情景。那时候其实他压抑着兴奋，其中蕴含的不只是新奇而已，还有对变化的期待。

   红黎的手机振铃了，但是他现在没有心思接电话，只是期待着阿贝莉亚答应他。手机的振铃也许持续了一分钟还要多，终于停下了。然而，它又响起来了，他还是没有管它。直到振铃再次结束……

   "明天凌晨三点钟，一个人到操场上来。"阿贝莉亚说。

   …………

   红伊水送走了许凝之后，重新陷入了对阿贝莉亚这个人的思考。红黎说过的话一遍又一遍地回响在她的脑海。

   她独自找到上课教室，杵在后门口。她的室友们正背着讲课的老师偷偷朝她招手。她堂堂地跨入教室，在室友们中间落座。老师念着书本，瞥了她一眼。风平浪静。她双手横摆在桌上，盯着投影幕布上的画面，一直在走神。好挚友白玫拍了一下她的肩膀后，她才迟愣愣地从抽屉内的布袋里翻出书本。

   她又开始走神了。她的室友们嘀咕，今天的红伊水看起来怪怪的，是不是身体不舒服了。白玫居然连她的月事周期都清楚了，否认了这一可能。她没有理睬。她想着想着，焦虑起来，右脚开始抖腿。前面的女同学回过头来，恼怒地瞪着她，她这才意识到，自己居然做出了曾经讨厌无比的举止，膝盖还顶着前面人的凳板。她马上停止了抖腿。但是这样，她心中的焦虑就膨胀着，得不到释放。

   她从布袋中取出本子和笔，在本子上划拉着线条。笔尖的圆珠走过纸面时带来一种微妙的宣泄感，好像那从球珠和球座缝隙中走出的不是油墨，而是她的某种焦虑。纸面上的黑线越来越多，无数条拉扯在一起，变成了漆黑的毛线团。毛线团还在增加密集程度。好像打扰到身边的人了，那"嘶拉嘶拉"的声音，两双眼睛盯着她画出的毛线团。红伊水合上本子，放下笔。

   后来的上课时间里，她两次被老师点名起来回答问题。第一次她直言自己走神了，不知道问题的答案；第二次她说自己身体不舒服，需要去一趟医务室。她拒绝了室友的陪同，挎上布袋独自离开教室。

   她没去医务室，而是到了医药楼。在电梯上，她从手机打开班级讨论群。她只在这个群聊创建时看过里面的消息，都是一些闲言碎语。要是有什么重要的班级通知，她只要去看班级公告群就够了，或者由室友提醒。最近的一堆消息，同学们都在讨论昨天的那场告白，还有突然高烧的那告白之人的下落。她也成了讨论的对象，主要是男生。她的生活照居然流落到了群里，成为了评头论足的对象。她气愤地跺脚，私聊那个偷拍并发照片的男同学，警告他的行为，让他马上把照片删除。

   电梯到了一遍三楼，但是她错过了，现在在向下的过程中。那位男同学回避了她的警告，说尽了甜言蜜语，赞美她的容颜，赞美她的品德，还顺势和她告白——这人在故意模仿之前的那个人。她在电梯里重重地跺脚，气得快炸膛了。一位刚进电梯的老师吓得缩在了角落，是某位上课特别浮夸的老师。但她现在没心情和那老师打趣。她再次警告那人，要是再不删除，她马上报警。那人是个孬种，马上投降了。

   她到了三楼的实验平台入口，等研究生经过刷开门禁时，跟着混了进去。她的举止只是引起了那人回头一眼的关注。她找到一个特别的房间，里面不是实验台和堆积的仪器，而是一排排的隔间座位，穿着休闲服装的学生们三三两两坐在那儿，盯着挡板遮拦的桌面或者桌墙。学生们在交头接耳。

   她敲了敲门，引起了房间内学生们的注意。她询问了这儿是否有人见过黑色长裙的女人……这儿的学生们相继表示自己见过，只有那个女人是她描述的那样，但他们都说，自己和那黑裙女人没有过多的交流……她正要告退时，第一路最里侧挤出一个穿着白大褂的女学生，告诉她，隔壁一个褐色头发的学长曾和那女人有过交流，也许比较了解。

   她在隔壁房间门口瞧见了那褐发的学长，他正在第一路的水槽边上调试着旋蒸装置。她敲门后进入，和他搭话。为了不引起怀疑，她假装自己的身份是阿贝莉亚的亲戚，无意中得知阿贝莉亚也在这所学校，所以想和阿贝莉亚重逢。她的话得到了那学长的信任，因为她和阿贝莉亚之间酷似的相貌。褐发学长表示了祝贺，但随后的语气无时不透着沮丧，他想和阿贝莉亚的关系变得更好，但阿贝莉亚对他不理不睬。红伊水绕开这些无关紧要的话题，向他打探阿贝莉亚现在的处境，还有究竟是怎么加入的实验室。

   他说，阿贝莉亚是被一位个性开明、才华惊人的女教授招进的实验室，后来因为向他请教过电脑的使用方法，两人才有了浅薄的交情；阿贝莉亚特别古怪，看起来不像外国人，却从来不说中文，只说英文，因为如此，实验室也只有他能和她日常交流上几句，其他人有心无力。

   最后，红伊水婉拒了褐发学长的午餐邀请，让他帮忙保密自己来过这里打探阿贝莉亚，为的是给阿贝莉亚一个重逢时的惊喜。那学长没有犹豫就答应了。

   红伊水还是放弃了寻找那位才华惊人女教授的打算，对方估计日理万机。她在实验室打探阿贝莉亚现在的所在。走廊上撞见的学姐告诉她：那位黑色长裙的女子出门了，不在实验室；如果想找那人，换个时间点，一般一天二十四小时都在，除非特殊情况，就像现在。

   红伊水离开了医药楼，感觉无功而返。她本想打听阿贝莉亚的来历，证实自己的猜测。已经有许多细节让她确定，那黑裙女子就是阿贝莉亚，比如她的相貌、打扮、语言，她的横空出世，红黎的"胡言乱语"，那奇异的水晶……

   她到食堂用完午餐，下决心给红黎打电话。她连打了三个电话，都无人接听。她气得用筷子戳着餐桌。一连串急促的"嗒嗒"声，惹得旁边座位的学生都侧目了。她收敛了。但是她忍不住担心，万一红黎遭到了什么不测。阿贝莉亚也许现在正和他一起。

   她是世界上最了解阿贝莉亚的人。阿贝莉亚是个亦正亦邪的女人：有人求助不会坐时不管，但会量力而行；与仇家相关的任何人，都会残忍地将其杀害。阿贝莉亚在那个世界有牵挂，但在这里无拘无束。要是阿贝莉亚对这个陌生地世界感到混乱，一天天地堕落下去，也不是不可能。到时候，身为作者的红伊水，肯定控制不住阿贝莉亚了，因为阿贝莉亚已经脱离了她的故事，来到了现实。她笔下的人物变成了真实，会有这么离谱的事情发生吗？

   她在网络上搜索这类关键词，得到的结果都是类似情节的小说。这类作品她也曾看过，情节充满戏剧性，朝着读者们喜闻乐见的方向发展；但是人物往往不真实，最不真实的就是那来到现实的人物对文中的作者充满了偏爱。这对她来说没有借鉴意义。她现在怀疑，要是阿贝莉亚得知了自己其实是她的故事的作者，她只是一个故事中的人物而已，而这个作者造就了她一生的坎坷波折，罹受苦难，会不会心生杀意。

   红伊水给红黎发送消息，让他马上联系自己，她有急事要说。是否该告诉他事情的真相呢，她还在犹豫。


## Chapter 16


   红黎回到了学校，和阿贝莉亚在医药楼下分别。他想起自己漏接的几个电话，掏出手机确认。来电话的人都是红伊水。他给她发送消息，自己刚刚有事外出了。

   红伊水：你不会和阿贝莉亚一起吧？

   红黎：你猜。

   红黎才刚刚把消息发送出去，对方马上回复了。

   红伊水：你马上来我宿舍楼下，我有话跟你说。

   红黎：我要去上课。

   红伊水：事关性命。

   红黎：但是马上要上课了。

   红伊水：命要紧还是上课要紧？

   他不久前才听过类似的话。他的两位妹妹都喜欢把上课和性命放在一个天平上衡量。

   红黎：也许你在骗我。

   红伊水：……

   红伊水：好，我去教学楼，你等着。

   红黎总感觉惹恼她了，但他还是慢悠悠地踅向了教学楼。从食堂和宿舍楼的方向，学生们络绎不绝地涌过来，带着年轻又喧哗的气流。许多人都披上了卫衣、夹克或者风衣，但逞强的女孩们照旧穿着短裙，飞扬着双足。那一片时尚的花园啊，在太阳底下过于耀眼了。而在他这里，光秃秃的樱树在道旁，好像在行注目礼；不知名的黄叶在绿化坪里挣扎，西北风终究还是赶走了它们，栽在了冰冷的沥青路上。清洁工人正挥着扫把，把这些落叶都聚集在一起，然后用簸箕把它们兜进黑袋子里，处理掉。他抬起头，睁大眼睛，放开视野。蓝天上空无一物，鸟雀不在上面飞，连白云都不见踪迹。那是一片让人空虚的湛蓝。

   他现在的心情微妙的疲惫，还有失落。也许是因为跟着阿贝莉亚出行了一趟的缘故，路上发生了太多的事情——和他平时波澜不惊的生活比起来。他现在还想不明白，为什么阿贝莉亚突然答应了他，要教他魔法了。

   教学楼大厅有限的高度遮蔽了天空。红黎混入了学生们当中，和他们一起跨上了楼梯。

   安若给他发来了一连串的消息，问他到学校了没有，还附着精力充沛的表情贴图。他心情被她感染了，忍不住笑了。他被拍了一下肩膀——他浑身一个哆嗦，只有阿贝莉亚才会这么拍他的肩膀。然而他回过头时，看见同班的男同学笑嘻嘻地看着他。

   "听说你今天早上被告白了，班级里最可爱的女生。"

   "呃？"

   "而且你还拒绝了。"

   这位他不记得姓名的男同学拍着他的肩膀，竖起大拇指。这位同学描述着许凝如何可爱，打扮也时髦，家境又优渥，简直是一位理想的伴侣。

   红黎来到二楼的一间多媒体阶梯教室。他选了个靠窗的后排位置，他担心待会儿红伊水会突然来找他。让他困扰的是，那男同学紧随着他，坐在了他旁边的座位上。五个座位长的排桌，一边抵着墙，另一边靠着过道，现在有那男同学把出口锁死了，让他没办法在上课的时候偷偷溜出去。他想奉劝那男同学换个位置，但还是忍住了，太不近人情。两个班级的人纷纷在教室里落座，没过多久，授课老师催眠般的声音在台上响起。

   红黎一趴下，困倦的感觉就袭了上来……他累了，也不管红伊水要怎么样了，沉沉地睡了过去。梦的海洋很深很深，他的下沉带着气泡，但是没多久那气泡就被水压给排走了……

   他被人晃着肩膀，被迫醒来了。他转头望去时，看见了满脸冷漠的阿贝莉亚——不，是红伊水，她的面貌看起来青涩稚嫩多了，眼神没有那么幽深，眼仁乌黑，双颊透着健康的血色，嘴唇不满地微撅着，缭乱的发丝披散在肩膀上，好像刚睡醒的样子。

   他混乱了，他现在在哪里，为什么红伊水会在这里？他身旁原本是某男同学坐着的。

   "你和我出来。"

   红伊水抓住他的手腕，把他从位子上拽离。讲台上，老师正背着身，在黑板上书写化学公式。靠前排的学生们认真记着笔记；后排的则玩的玩，闹的闹，睡觉的睡觉。在他的后座，印象中的那位男同学正对他嘻皮笑脸。红伊水拉着他胡闹般地离开了教室，只有最后排的三两个学生注意到了。

   走廊上的气温要低上一截，一下子刺激到了他全身的皮肤，让他彻底清醒了。红伊水正抱着胳膊，愤懑地看着他。红伊冲他一阵数落，责怪他不回复消息。她不得不在各个教室盲找他，这才把他找到。她说自己找到他之后，更加生气了——他居然在睡觉。红黎表示了自己的疲惫，但是他的说辞对红伊水来说根本没用。

   "红黎，早上你是不是和阿贝莉亚出门了？"

   红黎已经无法再向她提及阿贝莉亚了，他敷衍："你是说装扮成你的模样的那个女孩吗，她……早上和我顺便去了一谈学校附近的商城，和我去逛街了。"

   "你说的鬼话。"

   红黎环顾左右，想找点其他的话题。

   "阿贝莉亚不让你说？"

   "没错，她管我管得太严了。"红黎觉得红伊水可能想岔了。但是没关系，这样才有意思。他要推波助澜。

   红伊水果然瞪大了眼睛。但遗憾的是，她的眼睛没瞪多久，就消了肿。不愧是他老交情的妹妹了，马上就识破了他的把戏。

   红伊水说："红黎，你不要和她走得太近，很危险。"

   "她对我很好，你别担心。"红黎说。

   红黎知道，她最讨厌他用这种误会她意思为担心他的说法了。于是，红伊水用千刀万剐他的眼神看他。她的眼神杀死了他千百遍……她可能终于累了，消停了眼神。她说："她给你布置了魔法阵了吧？"

   在几日之前，红黎都不知道阿贝莉亚用的是魔法；但是现在红伊水轻而易举地说出了"魔法阵"这几个词。红黎有种落差感。他说："你之前不是还以为我胡说八道吗？"

   红伊水竖起了手掌，让他不要再说了。她说："到此为止了。如果那是真的，一旦提到某几个关键词，她就会警觉，会发现我们之间的交流。"

   "你为什么知道的这么清楚？"

   "我是世界上最了解她的人。"

   红黎不知道她的自信是从哪里来的。她怎么可能是这个世界最了解的人，最了解的人不是应该是……好吧，他的确对阿贝莉亚一点都不了解。他打消了自己无意义的嫉妒。现在，他对红伊水的说法感到奇怪了：她凭什么对阿贝莉亚这么了解？

   "其实我有个猜测……"他说到一半，猛地想起，他不能对红伊水说出那些话。他紧张兮兮地左右环顾了一圈。

   "你别紧张，要是她看见了，早就过来了。"

   "那最好。"

   红伊水露出苦大仇深的表情，思考了一会儿，说："我来是和你确认的，你说的那紫色水晶的事，是真的吗？"

   "是……"红黎只能支支吾吾地回答她。

   "还有，你现在和阿贝莉亚到底是什么关系？"红伊水的眼神变得犀利了。

   "我们结婚了。"红黎说。

   "呸！"她说。

   "义务关系吧。"红黎随口说。

   红伊水问："你是怎么知道那水晶的事情的？"

   红黎觉得，这件事好像也不是不能说。

   他带着红伊水到了两栋教学楼之间的休息咖。这会儿学生们都在上课，也没什么人经过这里。他告诉了她关于对特殊事件安全管理局的事，还有他成为了负责人的事。红伊水一直安分地听着。但是，由于担心触发所谓关键词的缘故，许多内容他只能点到为止。他也不知道红伊水听懂了没有。他讲完后，她还问及了今天早上的事，为什么她打了好多电话，他都没有接听。但这些都只是旁枝末节。

   "她让你成为责任人，是别有所图。"红伊水说。

   "贪图我的美色。"红黎胡说八道。

   "这里面可能有她复杂的心理作祟……我不能说。"

   红黎还以为她会大声说他恶心，然后作呕吐状。但是她居然没有。红黎感到奇怪了——但也只是些许。他更感到不爽，因为红伊水明明不打算说，却故意挑起这样的话题。要是他追问了，红伊肯定拿阿贝莉亚布置的魔法阵当挡箭牌——即使没有这挡箭牌，红伊水也绝对不会轻易开口。他可以猜到阿贝莉亚的来历；但是他猜不出来，红伊水说的复杂心理到底是指什么。他越是这么想，就越是不爽。

   "你不知道，阿贝莉亚是个什么样的人。"红伊水还在说。

   红黎喊道："那你倒是说啊！"

   "好了，这件事就到此为止吧。"红伊水起身了。

   她居然想走了。红黎怎么可能就这么让她走掉。他冲她说，她还什么都没有告诉他。但是红伊水笑话了他，笑他居然以为事事都必须平等。红黎根本不知道她在笑什么，他也不管，他必须要她给出给交代，否则他刚刚都在向她白费口舌。他是拿那些消息做交换的，而不是做慈善的。红伊水又笑话了他，笑他被阿贝莉亚骗得死死的。她一本正经地说，阿贝莉亚可不是什么善人，她是复杂多面的人。

   红伊水说着老一套的话："即使是最善的人，也有复杂邪恶的一面。我也是在创作……才意识到的。说的太多了，我得走了，否则阿贝莉亚可能要注意到我们了。"

   "你说的这些，让我更在意了。"

   "会暴露的。"她说。

   红黎绝不甘心就这么让她走掉。他亮出手机，威胁她，他现在就要把阿贝莉亚叫过来。红伊水说让他别疯。红黎当然不可能把阿贝莉亚叫过来。他只是要引起红伊水的注意。他说，她可以用书信的方式把事情告诉他。但是红伊水的回答让他沮丧，她说这样没用。他唉声叹气。他至少想从红伊水那里打听到那本小说的名字的。但好像泡汤了。红黎还是不甘心就这么让红伊水走掉。他拦住她。

   她背过了他，往另一个方向的楼道而去了。

   他绕到了她的前面。

   "快滚开。"她说。

   他偏不让。

   她不客气地推开他。

   他顺势抓住了她伸来的双手，往回拽——他好像用力过猛了，她也没有站稳，朝他撞了过来。她的额头嗑在了他的下巴上。下巴上似乎连着什么三叉神经……他晕了，往后一倒。视野倾斜……他反射性地松开了抓着她的双手，往后撑地。地面撞上了手掌，让他感觉骨肉发麻。她扑在了他的胸口，让他身体一沉，手掌往后拖了一段距离。他痛得想呼天抢地，但是忍住了，因为这是在教室外的走廊上。地面的沙砾感走过了他整个掌心。痛觉神经在不断地警告他。

   红伊水的脑袋跌靠在他的肩膀上……她弹了起来，像弹簧一样。她的脑袋摇摇晃晃，身子也跟着摇摇晃晃。红黎还以为她摔到了哪里，结果，她一转身，就做出了一副干呕的样子。她"呕""呕"地叫个不听。关键是，她动作还特别逼真，掐着自己的脖子往地面吐。他从侧面看过去，还能发现她往上翻着白眼。实在是太夸张了，夸张到他怀疑这是否是真的。他揪起自己的衣领，闻了闻味道。并未有任何异味。

   "我要走了！"她大声地说。

   红黎没再拦她。

   …………

   凌晨三点，红黎摸出了宿舍楼，摸向操场。路灯并不工作，他险些踢中了路中央围坐的学生——天知道他们这个点还在办什么仪式——现在天上地下最亮的就属那夜空了，是幽蓝色的，星子和月亮散落在上面，好像夜风一抖，它们都要消失不见了。红黎觉得冷，冷到瑟缩起来，冷到他觉得自己被阿贝莉亚欺骗了，只是故意挑个难受的时间把他刷着玩。但是，阿贝莉亚又怎么会无聊到和他耍着玩呢？

   他到了操场入口了。旗杠在路中央，甩着天上的大旗，甩得无影无踪，却猎猎作响。红黎打开手机的手电筒功能，继续往前摸。他试图在操场的那片黑魆魆中找到一个女人的身影。他踩入了充满劲道的跑道了，没人。他踩入了那片毛糙的假草地了，还是没人。他怀疑自己被阿贝莉亚耍了。他其实一直在质疑，为什么阿贝莉亚突然就答应了他。

   他的肩膀被拍了一下。

   红黎觉得，阿贝莉亚这总喜欢在别人身后出现的习惯像个刺客。

   他转头说："我需要有什么准备？"

   阿贝莉亚退开了两步，然后指着身下的草地。"你把身上的衣物都脱掉，然后平躺下来。"

   他好像能料到那么一点，就像武侠小说的传授神功或者治疗暗疾那样，总得把人给弄得光溜溜的。没想到在他身上也要上演这么一出。但是他不想这么做。

   "太冷了，我不想脱。"

   "如果你想学魔法的话就照做。"

   "你看我抱着胳膊，这么冷。所以你要给我一个合适的理由。"

   阿贝莉亚也抱起了胳膊，她说："我这么冷，却陪你浪费时间。"

   "我们大家都有必要节约时间。"红黎说。

   "那你快躺下来。"

   红黎坐下来，然后躺下来。他仰视着阿贝莉亚。

   阿贝莉亚单脚踩在他的腹部。"需要我帮你把衣服撕碎？"

   "你还没有说明理由。"

   阿贝莉亚另一只脚也跨了上来。她整个人站在了她的肚子上。她纯粹就是为了宣泄自己的不满。红黎感觉自己呼吸的负担放大了数十倍，要是一不留神，就会让胸膛陷进去，再也呼不出来一口气了。他躺在那儿，只能呃呃啊啊。阿贝莉亚还挪动了一下脚步。她把他的肚子当成大陆版块呢，在这儿搞地理大发现……

   "因为你没有天赋，根本用不了魔法。我得给你创造条件，在身上纹刻回路，让魔力贯通……你懂了吗？"

   "我不懂。"

   凭什么阿贝莉亚什么都还没做，就判下了他天赋的死刑？红黎抓住了她的脚踝，他要惩罚她——他要把她丢在地上。他不出预料地，根本拽不动阿贝莉亚的脚踝。她往前踢了一下脚，就挣脱开了他的手。她在他肚子上的动作的反震力全部传递给了他的肚子。他觉得再这么下去，他可能要一口血吐出来。他翻转身体，让阿贝莉亚在他的肚子上没有立足点。

   "所以你不需要问那么多，照做就行了。"

   "你为什么突然就答应了我？"红黎问。

   阿贝莉亚蹲坐下来，她的一只手揪住了他肚子处的衣服。红黎颤抖了一下，马上坐起来，照她说的把衣服脱掉了。要是他慢一点，他就要和这身衣服永远告别了。他刚刚把外套脱掉，阿贝莉亚就在催促他把短袖也脱掉。他刚刚把短袖脱掉，她就催促他把裤子也脱掉。他刚把鞋子脱掉，她就说，袜子也必须脱掉。她说，他必须脱掉浑身赤条条，不干扰她拿大笔在他身上绘画纹路。

   "阿贝莉亚，我觉得我们需要彼此信任。你需要向我说明理由。"

   "快脱掉。"

   红黎已经瑟缩成了一团了。他现在浑身上下只剩一条四角裤。他先抱住了自己脱下的衣服，免得夜风把他给弄死——一不小心，他也许就要溘然长逝了。

   "阿贝莉亚，我害怕不劳而获。但是你突然就答应了我。你需要说明理由。"

   "那我给你一份奴隶契约，直到你偿还出足够的代价，你都是我的奴隶。"

   阿贝莉亚明明直到他的意思，却还是故意这么说。他懂了。阿贝莉亚根本不愿意和他说明理由。他回想起了红伊水跟他说过的话：阿贝莉亚是个复杂多面的人。也许她现在隐瞒着什么，无形中从他身上挖掘好处——也可能不是这种性质的，是她难以启齿的原因……现在的关键在于，他愿不愿意——不对，照这个情势，阿贝莉亚刚刚半强迫性的言行，他可能别无选择了。

   红黎文："阿贝莉亚，你为什么这么着急？"

   "因为你在浪费我的时间。"

   "你现在就像一只大灰狼。"

   阿贝莉亚退离了他的视野。她的身影消失在了夜色中。她的脚步声正在远去。这儿寂静得只剩下他自己的心跳声了，还有他打战的声音。

   "你要去哪里？"红黎喊到。

   阿贝莉亚没有回答他。红黎抄起手机，追了上去。夜风在他跑动的时候，把他身上的温暖剥夺得一丝不剩。他觉得自己现在的装扮不适合长途跋涉，他必须在阿贝莉亚离开操场之前，让她回心转意。

   "你在哪里，我接受你的条件了。"

   他的肩膀被拍了一下。他转过头，看见了阿贝莉亚白得瘆人的那张脸。她说，可以回去继续了。红黎毫无心理准备，他觉得她回心转意得也太快了。他只能愣在那里，不知道怎么反应才好。但是阿贝莉亚说，他要是不愿意，她现在就走。红黎终于确信，不管阿贝莉亚用的是硬手段还是软手段，他都拿她没有办法。这是为什么呢？——有求于人的不是阿贝莉亚，而是他自己。

   红黎重新躺下来了。他注意到，自己躺在了：那被千千万万人踩踏过的假草地上，那充斥着不计其数的细菌的假草地上……身后的毛糙感让他觉得恶心。

   阿贝莉亚说："我知道你在权衡。但请你在权衡的时候，先想清楚我们之间的力量差距。我说过，蚂蚁不要和巨人谈条件。"

   "好了，你别说了。"

   "那你快照办。"

   红黎举起手机，用手电筒的光去照她的脸。她的脸上什么也没有，虚无到他都感觉无趣了。他想，要是她这时候——

   "你在干什么？"她问。

   "坏人在得逞的那一刻，总是会在脸上暴露出自己的阴谋，露出奸笑。"

   "那你看到了什么？"

   "一张扑克脸。"

   "满意了？"

   "一般般。"

   阿贝莉亚一脚踩在了他光溜溜的肚皮上。她的鞋底很硬，而且肯定充满了大量的污垢和细菌。红黎大声表示抗议，但是阿贝莉亚没有给他任何回馈。她还在催促他，她说，他现在身上还有一块布料，那东西会妨碍她的工作。


## Chapter 17


   红黎想了想，坐了起来。他逐件把衣服穿上，要走了。他开始穿裤子的时候，阿贝莉亚按住了他。

   "你要做什么？"

   "我觉得不划算，我要放弃了。我可能会因此失去清白之身。"

   阿贝莉亚掐住了他的脸，把他往地上按。红黎也没有挣扎，随便她了。只是她有些过于暴力了，掐得他脸颊生疼。她还把他往那肮脏的假草地里按。红黎觉得，她纯粹实在宣泄自己的怒火。她想这样，他还能怎么样呢？……等她差不多结束了，红黎重新跟她说，他要走了。阿贝莉亚把他丢在了地上。她说等她。

   她手中出现了一道光，是赤色的一团，有点像火焰。那是她所谓的灼元素。她好像只是拿它当照明用。她手里变出一条黑色的布条，把自己的眼睛给蒙上了。她伸出一根手指头，指尖出现了赤色的光辉，那也许是魔法的痕迹，她在半空中画出了一只兔子。她画的惟妙惟肖，是一只简笔画的兔子。

   她说："这样可以了吧？"

   红黎看到她的诚意了，于是答应了她。

   尽管他有了心理准备，可当手抓在裤衩的松紧带上时，还是感觉有一道难以逾越的壁障。他总是觉得，面前这个女人心底一定抱著戏谑的心态……够了，这样下去他就没完没了了，他总得做出决定。他决定把阿贝莉亚当成外星人。没错，在他面前的是一个外星人。外星人看他的目光，就像他看地上的虫子时一样；而他看外星人时，也不需要有所顾忌。何况这个外星人现在蒙着眼睛，而且周围一片漆黑。

   他一口气把裤衩脱掉，丢到一边，然后平躺下来。他感觉这副身体仿佛不是他的了……他的身体在发抖，也不知道是冷的还是害怕的。据说，人在赤条条的时候就会面对心灵的拷问。他不知道这是否是真的，但现场，他更像是在面对阿贝莉亚的拷问。

   阿贝莉亚盘腿坐了下来，手中多出了一支笔刷。另一只手握着的好像是个匣子。太暗了，他看不清。咔嚓一声，她好像打开了匣子的盖子。笔刷蘸入了匣子，在搅拌，发出粘稠的液体声。

   "接下来会是地狱的洗礼，做好心理准备。"

   "我已经在地狱里了。"

   "你要是觉得自己要崩溃了，就把手拍在我的膝盖上。"

   她说的话在红黎心底氤氲起浓浓的不安。但事到如今了，他只能说："你开始吧。"

   笔刷落在他左边的锁骨上，开始行走。在那笔刷之下，起初他还感觉冰凉，后来他就感受到了灼热的刺痛——那刺痛越来越强烈，几乎深入骨髓。一把烙红的刀扎入了他的锁骨之下，正在横向行走……他张大嘴巴想要啸出来，但他意识到这里是校园，忍住了。他的坚忍好像放大了痛苦。他的手脚垂打着地面，身体不受控制地抽搐扭动。他不敢大幅度动弹，否则那笔刷可能会播及更大范围的皮肤，那样的话，他就更加痛苦了。但他这样的忍耐坚持不了太久，他的身体越来越不受他的控制了。现在他的身体不是他的了，是那痛苦的意志的。他控制不了自己的身体，也不知道现在的自己是样子。他只能猜测自己是什么样子。他猜测，他现在的样子肯定和蛆虫差不多，蛆虫是怎么蠕动的，那他就是怎么蠕动的。他控制不了自己的身体，也就越来越放纵自己的身体了，任凭它扭动，摆动，蠕动，挣扎……似乎，阿贝莉亚的某种魔法固定了他的身体，他再怎么挣扎，他的皮肤都处在她的笔刷之下。他觉得，阿贝莉亚欺骗了他，他痛苦到这种程度了，他根本再无余力在中途拍一下她的膝盖，让她暂停。她可能根本没有想过给他暂停。

   现在，他想把胸口的那块皮给撕下来。他感觉那块皮不是他的，而是给他带来痛苦的罪魁祸首。但是他的手脚被阿贝莉亚控制主了，没法听从他的意志，最多只能捶打一下地面。他的心中出现了新的想法，阿贝莉亚心里看他不爽，所以拿这件事堂而皇之地报复她。她可真是个机灵鬼。

   痛苦在持续。他原本还能在心底俏皮两下，但他现在没有这个余裕了。他只能以纯粹理性的感觉感知自己的身体变化——他更感觉，自己的痛苦将灵魂和肉体剥离开了。他感受到，阿贝莉亚的笔刷走过了他的腹部。这下子，他痛苦的范围变得更大了，他的胸口连同腹部……原来，她笔刷走过的地方不会停止痛苦。他在质疑，人凭什么需要痛觉感受神经……他在质疑，人活着到底有什么意义……

   灼烧般的痛苦变得更强烈了。他的思维好像被无限放慢，过了好久，他才能稍微描述出那种感受：他身无寸缕横在铁轨上，高速列车正在他身上急刹车，列车的铁轮子在轨道上刮擦出一簇簇的火花；那钢铁猛兽碾过了他的身体，蛮横，暴力，无情，冷酷，残虐……尽管他的肢体被固定住了，但是他好像——他的意识可能出现了混乱——可以轻易地把手拍在阿贝莉亚地膝盖上，只要拍上去，那么一切都可以结束了。拍上去。拍上去。拍上去。他心底的声音在嘶吼。但是他心底还有另一个声音，这声音像卑微的火苗：他已经临战退缩了了好久了，起码他得有个体面的战斗过程，而不是夹着尾巴逃跑。他要是那么做……他仿佛都已经听见了阿贝莉亚的笑声了。

   不知道过了多久，但现在这个时候，他身体正面的所有皮肤都在和他作对了。胸口，腹部，胯部，大腿，小腿，然后是手臂，手掌。阿贝莉亚的笔刷走过任何一个部位，那里的任何活动都会被禁锢。阿贝莉亚的笔刷丝滑般流畅，没有什么能够阻挡它，走过没一寸的肌肤。他反反复复地做着内心斗争，想要去阻断那笔势。但现在，他终于撑到了结束。阿贝莉亚的笔势停下了，他不再受到痛苦的折磨——他只是不再受到新的痛苦的折磨，但还是在受到旧的痛苦的折磨。这样的痛苦还有好长一段时间在持续着……

   他感觉自己虚脱了，浑身疲乏，口干舌燥。汗液在脸颊上流淌，也在躯干上流淌。他终于能感受到一些身体皮肤的知觉了，除了痛苦以外的。夜里的风还在吹，天空也没有黎明，应该还没有过去太久。皮肤上还残留着余热，即使他光着身体也不觉得寒冷。他大字摆开在地上，相比于前一刻的浑身灼痛，眼下的羞耻什么的，都不过是皮毛。他勉强看见，阿贝莉亚站起了身，俯视着他。汗水滚入了他的右眼。又滚入了左眼。他只能闭上了眼睛。

   "我以为你会在最初的时候就会放弃。"阿贝莉亚说。

   她的声音听起来有些遥远。红黎忍着眼睛的刺痛，睁开眼睛，只维持了一瞬间。阿贝莉亚的身影还在身旁。他安心了。他可没有忘记这里是操场，要是就这么躺在这里，直到天亮，那他在全校——不，全国都得出名。他浑身肌肉酸痛，动弹不得。

   他说："把我带到没人的地方……"

   …………

   红伊水在寝室里彷徨打转。昨天下午和晚上，她一直整理着信息，梳理着信息，推测着事情的变化。她得出了一些结论，但也滋生了新的疑惑，她想找红黎讨论一下。她联系了红黎无数次了，连电话都打过了，可对方就是没有回音。

   难道他已经受害了？这个念头一出现，就在她的脑海中就挥之不去。她现在在考虑是否要去医药楼，去找阿贝莉亚。她的这一行动充满了风险。在某一刻，她推开阳台的门窗，抄起地上的晾衣杆，评价着它成为武器的可能；但她马上又把它丢下了，因为没人比她更清楚阿贝莉亚的厉害。

   太阳已经翻上了对面的大楼，光线射入了她们的寝室。今天一整天没有课程，所以她的两名室友还在安然入睡。白玫已经爬下了床铺，坐在底下的书桌上，披着方格睡衣，把脚丫蜷缩在椅子上，盯着金属支架撑起的平板电脑，戴着头戴式大耳机，看着电视剧。白玫撕开了一包薯片，咔哧咔哧地啃着薯片。这细碎的声音把红伊水的焦虑推向了顶点。

   她踅身一步，朝向寝室的门；她一脚踢到了攀援床铺的直梯。在"当"的一下声音后，她的室友们埋怨她打扰到她门睡觉了……

   红伊水没有心情顾虑道歉了，她冲到门前，握住把手……她最后留下了一句话：

   "如果我中午没有回来，记得报警。"

   她在路上飞奔。她一路掠过食堂，跑过医药楼侧边的下坡路，然后拐向医药楼大厅，冲向电梯——她居然找不到电梯在哪里，她可能太焦急了！因为焦急，她在大厅里晕头转向——她忘了电梯其实是在侧边的厅堂里。她往那里赶的时候，还被某位领导呵斥了。这位领导悠哉游哉，又不分青红皂白；他又哪里知道这所学校潜伏着什么样的危机？……因为领导，她错过了一趟电梯。

   电梯终于到了三楼。

   在实验平台的门禁口，她还得等到研究生或者老师经过时，才能进入。她调整了呼吸，让自己冷静下来。她确认了自己目的。她是来谈判的，而不是来闹事的，着急也没有用。她掏出裤兜里的手机。红黎还是没有给她任何回复。最糟糕的情况是他已经遭遇不测。如果调出学校的所有监控，能追溯到事件的真相吗？阿贝莉亚会不会用魔法把红黎的尸首焚烧殆尽？……路过的褐发男研究生打开了门禁。红伊水趁机混入。

   "哎？你是昨天的那位学妹！"褐发研究生说。

   红伊水对他没有印象。"请问阿贝莉亚——黑色长裙的女人今天在吗？"

   "她在的哦，在走廊尽头的会议室。学妹，你与她相认了吗……"

   红伊水无视了他的喋喋不休，快步朝着走廊尽头。她的心跳不可遏制地加快了。她无法想像，待会儿她把真相告诉阿贝莉亚时，对方会决定怎么处置她。她是阿贝莉亚的作者没错，可没到情节重大抉择时，她都得苦思冥想，如果是阿贝莉亚的话，她会如何做出抉择，如何展开行动。

   她越是靠近走廊的尽头，脚步就变得越是沉重。她由快步逐渐变成了踱步。她越是靠近那会议室的门牌，她的想法越是坠入到消极的深渊……她到了会议室门口。一位女研究生从楼道里拐出来，关怀她的身体状况。似乎她现在的脸色惨白一片，嘴唇也在颤抖。她辞谢了温柔女研究生的好意。

   她伸手敲门。

   里面没有回应。她俯耳在门上，倾听里面的动静。只有连绵不绝的键盘敲击声。

   她旋开了把手，把门推开一半。

   阿贝莉亚背朝着她，坐在长长的红木会议桌的中间位置上，正对着一台笔记本电脑。她纤细的手指在键盘上舞动，节奏或急或缓，夸张地像是一场钢琴演奏。看起来，她的心情还很愉快——这让红伊水心情沉重了——电脑屏幕上显示着漆黑的界面，光标的前面跳出一个个代码字符；界面飞块地跳转着，让人看着就觉得头晕目眩。红伊水感到不安。阿贝莉亚居然学会了计算机编程，不知道在做什么——黑入某个国家情报机关吗？……红伊水吞咽了三遍的唾液，直到嘴里空无一物。她还是压不下内心的震动和害怕。她迟疑了一会儿，还是步入了房间，关上门。虽然她恨透了红黎，但总不能任凭他死去……她想到，以阿贝莉亚的感知，也许她在走廊上的时候就已经被锁定了。

   "你来了。"阿贝莉亚停下了手。

   她果然已经预料到了她会来了。红伊水面对着阿贝莉亚，一时之间不知道如何开口。

   阿贝莉亚坐着的旋转椅转了过来。现在她面朝着红伊水了。红伊水看着那副几乎和自己一模一样的脸，难免心里有怪异的感觉。她好像面对着一面镜子，镜中倒映着自己。她既感到怪异，也感到恐惧。她面对的不仅仅是镜子里的自己——如果只是另一个自己，那就太好了——那是镜子里的怪物。

   "你把红黎带到哪里去了？"现在她只想问这个而已。

   "坐下来，我们好好谈谈，我可以告诉你更多。"阿贝莉亚笑着说。

   快住嘴——红伊水心想。她可没有设定出这么一个轻易就会笑的人。她看着那笑脸人，心中的怪异感越来越强烈了。她现在就想跑，转身就跑。

   "造物主，我没想到你这么快就来找我了。"

   红伊水晕了一下。她扶住了墙，才让自己没有倒下。阿贝莉亚好像什么都知道了。她原本还心存侥幸。她根本不想来的，她本想任凭阿贝莉亚在这个世界自由行动。她不想和她有任何关联。她到底为什么而来？……都怪那不知死活的红黎，是他连累了她。她在心底骂道：早就和你说了，要和阿贝莉亚保持距离，你真是不知死活……你死了也就死了吧，却还要连累我！……

   "你会害怕吗，"阿贝莉亚说，"我不理解——我又好奇又不理解，你见到了自己虚构的角色之后，会是什么样的一种感觉。"

   阿贝莉亚在窥探她的内心。

   红伊水不敢说话。

   "我查过，"阿贝莉亚说，"要是有作者发现自己构造的角色活过来，会喜极而泣，有无穷的感动。你看起来好像并不是这样。"

   阿贝莉亚喋喋不休："我给了你一个真实体验的机会。你喜欢吗？"

   阿贝莉亚说着根本不像阿贝莉亚会说的话。要是她构造的角色，绝对不会反问出"你喜欢吗？"这样软弱无力的话。快住嘴！……红伊水只能在心底呐喊。她不敢说出口。

   "你肯定有很多话想对我说，正如我有很多想问你一样。"阿贝莉亚说。

   阿贝莉亚又说："但是这里可能太小了，不利于我们交流。"

   "我……"红伊水想说，我要回去了。

   阿贝莉亚说："让我们换个场所吧。"


## Chapter 18


   红伊水在原地休息了一会儿，否则她走不出两步。阿贝莉亚没有催促她，只是静静地等待着她。这可能是阿贝莉亚最后的善意了，虽然红伊水完全不觉得这是一种善意。对红伊水来说，现在阿贝莉亚在她旁边站着都是一种压力。她忍不住会想，这人到底会如何看待她这个一直迫害她生活的人。

   红伊水领着阿贝莉亚步出走廊，按开门禁，等着玻璃门开出一条通道，然后离开了实验平台。红伊水向右拐向，朝着通往电梯的走廊。她不时以余光瞟向后面的阿贝莉亚，听着对方的脚步声，确认对方跟着自己。她的后背毫无防备，就这么敞开向阿贝莉亚。她可以确认阿贝莉亚的行进，但是无法确认对方手上的动作。她下意识放慢了脚步。这时，阿贝莉亚的身位越过了她，快步朝前。

   阿贝莉亚脚步声"嗒嗒嗒"的响，裙摆的褶边随着节奏颤动。也许是阿贝莉亚处在了她的视野内，她的内心不再那么紧绷。她观察起了眼前的黑色长裙——这样好像能缓解她的压力。

   长裙在腰部收束，然后在裙摆的部分绽开，深红色的流纹融入了面料的黑色，低调地沿着褶皱，或垂或斜地向下，在最下摆的褶边处堆积，然后下坠的视觉感受一变，变成了轻飘飘的升浮感；褶边像浪花一样散漫，弯弯曲曲绕了下摆一周——别人可能不知道，但是她最清楚了，阿贝莉亚身上的这件哥特式长裙是一件魔法物品，那些流纹和褶皱都蕴藏着魔力，看似漫不经心的设计，其实恰好组成了一个魔法阵，可以帮助她藏匿气息。长裙是她一字一句设计的，真的出现在她面前时，心中的感动油然而生。原来我并不是在徒劳，她心想。

   她们从楼下步出电梯时，阿贝莉亚也一直走在前面。红伊水想在学校附近的荒地和阿贝莉亚谈谈，但她不知道阿贝莉亚是否明白她的意思，又想把她带到哪里。她觉得自己应该占据主动权，而不是被迫地带到哪里去。于是，她加快脚步越过了阿贝莉亚，又一次领路在前。阿贝莉亚只是保持着自己的节奏，没有在乎她怎么做。但是，她觉得阿贝莉亚走得有些太快了，她不得不急匆匆迈步，甚至小跑起来，才能领先在前面。

   她们一路这么你追我赶。这一路好像太长了，红伊水从未觉得，这个小小的校区的路居然会有这么长的一天。时间好像把这条路无限拉长了。而她的恐惧又把时间给无限拉长了。她的内心在煎熬她自己。在中途，她猛地变换了自己的想法：她是来和阿贝莉亚交涉的，而不是来送死的，她需要振作起来……

   她们终于到了校门口。这会儿，门口的人行通道正鱼贯而入三名男生，还是她班级的男生。红伊水根本没想管他们，她在心底催他们快滚开。但是那三名男生根本不识趣——那三人见了她，朝她挥着手，露出自以为讨人喜欢的笑容。她敷衍地应了一声。快滚开。她心想。她还是迫不得已和他们擦肩而过了，实在是因为这儿的地段太小了。快滚开，快滚开……她心底反复催促。这时，她的余光瞥见，那领头的人路过她身边时，脸上笑容的扭曲了一下。她有不好的预感。

   "红伊水，我有重要的事要和你说。"

   "闭嘴，你别说！"

   可那人脸上的笑容越来越让她赶到恶心了。这人，居然还把手搭在了她的肩膀上——她一挥手，拍掉了那无礼的蹄子。

   "红伊水，我喜欢你，和我交往吧。"

   红伊水顶着他，记住了他的模样。她要找个机会弄死他。浸猪笼，浸猪笼，浸猪笼……她心底都是这样的声音。但是，眼前这码戏居然还没结束——后面的男生挤掉了前面一个，又是兴冲冲地拦在了她面前。

   "红伊水，我喜欢你，和我交往吧。"他说出了如出一辙的话。

   她也记住了这人的样子。

   最后的男生又撞开了前一位，说了一模一样的话：

   "红伊水，我喜欢你，和我交往吧！"

   三个脑袋并排立在那里，笑得让人想把那些面皮都撕烂。红伊水觉得，把脑容量浪费在记忆这种蠢货上，实在是太浪费了。她在脑海里把他们统统粉碎。这辈子，她都没有见过这样的人。

   他们似乎满意了，笑嘻嘻地远去了。

   阿贝莉亚说："要我帮你杀掉他们吗？"

   红伊水认真考虑了一下其中的可行性。但她害怕，警方沿着线索找到了她身上。

   人行通道需要刷卡才能通行。红伊水掏出兜里的卡刷了五遍，那显示屏都显示审核失败。她啪的一声把卡拍在检测器上。验证失败。

   "你手中的是身份证吧？"阿贝莉亚出声。

   红伊水拿起卡确认——的确是身份证。她的脸颊滚烫，不敢回头，从兜里摸出另一张卡，确认了是校园卡后，才用它通过了验证。她跨出通道。三步后，她回头。她要在阿贝莉亚身上找回场子。没想到的是，阿贝莉亚捏出了一张教工卡，施施然刷过了通道。她的算盘落空了。

   红伊水领着阿贝莉亚步行了两里路——这一路上，阿贝莉亚都没有发言，也没有质疑她要去哪里，只是安静地根在她身后——红伊水走得累了，但到了这里页差不多了。马路的两边都不再是建筑物，而是那些沙石和黄土，还有一望无际的平野。她踅出公路，踩上那松松跨跨的碎石地面，跳过凸出地面的大岩块，落在荒草丛生的平野上。

   周围的砂土堆成了一条条的垄道，纵横交错，围成四四方方的土地。据说将来这里会修建成新的大学校区，但是现在还阒寂无人。毗邻的公路几分钟也不一定开过一辆车。这里正是她和阿贝莉亚谈判的好地方，即使阿贝莉亚暴躁冲动了，也不会波及其他人——死的只会是她自己。她一时间也不知道，这样的选择究竟是否正确。但她终究还是到了这里了，没有反悔的机会了。她以深呼吸的方式调整自己的心情。一吸。一呼。她睁开眼睛。

   阿贝莉亚像幽灵一样立在她的面前。

   "这里是个杀人藏尸的好地方。"阿贝莉亚说。

   她在耸人听闻。红伊水心想。阿贝莉亚要是想杀害她，根本不需要考虑藏尸或者销毁的问题，只要魔法一扬，连灰烬都不剩。

   "我们是来谈判的，你可以轻松点。"阿贝莉亚说。

   红伊水根本不信她会就这么收尾。

   阿贝莉亚又说："我们相互都有许多想问对方的，不如这样，我们来相互解答疑问，这样公平吧？"

   红伊水猜测阿贝莉亚想从她口中得知什么，怕她不回答，所以才说这样的话。

   "好。"红伊水只能这么说。

   "你先问。"阿贝莉亚说。

   阿贝莉亚从空气里端出一张洁白的圆桌，放平地面，然后又端出一张扶手椅，让自己坐下，紧跟着在桌上摆上茶壶和水杯，给自己的杯子里沏上茶。她这样的一套动作，红伊水在写她面对仇敌的时候，写过无数遍了；红伊水无法想象，自己有朝一日会亲眼见到她这么做，而且是处在"仇敌"的视角。

   "你问啊。"阿贝莉亚催促道。

   红伊水小心地问："你把红黎怎么样了？"

   "我回答你这个问题：我没把他怎么样。但我奇怪，你问他做什么，和我们之间有关系吗？"

   那我要回去了。红伊水心想。但她也只能在心理想想而已。她说："这是你要问我的问题吗？"

   "这不是正式的提问。"

   "那我拒绝回答你的问题。"

   阿贝莉亚笑着说："好"。红伊水觉得，这人笑得有点古怪，笑出了那种记仇的时候才会有的样子。她怀疑，自己刚刚哪里得罪了阿贝莉亚了。她想不通。

   "由你问了。"红伊水故意催促阿贝莉亚。

   阿贝莉亚没有马上回答她。这人磨蹭了一会儿，在喝着茶水，也不知道是在磨她的耐心还是在磨她的体力。红伊水马上想到，阿贝莉亚会一种魔法，可以让意志力和体力远弱于自己的人处在自己的掌控之下，变成自己的玩偶，甚至还能读取记忆……阿贝莉亚并不擅长这样的魔法，红伊水也几乎只在故事中提到过一次。

   "你快问啊！"红伊水大声说。

   "你这么想为我解惑？"阿贝莉亚说。

   红伊水摸了摸裤子的口袋。口袋里空空如也，她没有及时把手帕或者纸巾备好。她只能再次用手背来擦汗了。她站了这么一会儿，也觉得累了，这儿的空气似乎特别沉闷。她几度怀疑，是阿贝莉亚把这儿的空气变得沉闷了，就为了让她难受……她都觉得自己胡思乱想了。她索性蹲坐了下来，让自己轻松点。她给自己找了一片稍微干净点的草皮。现在，她可以看见圆桌上露着的阿贝莉亚的细长的脖子和冷漠的脑袋。

   "你还没想好？"红伊水再次催促。

   阿贝莉亚说："我问你，我的故事到那里就结尾了？"

   阿贝莉亚对自己的故事耿耿于怀。红伊水撒谎说："还没完结。"

   "你在说谎。"

   她忘记了，阿贝莉亚可以轻易看破她这样的一般人的恍惚。她纠正："完结了。"

   "完结了？"阿贝莉亚又问。

   "你连续提问了两次。"

   "这不是正式提问，你可以拒绝回答。"阿贝莉亚说。

   红伊水感觉自己被耍了。但是她被耍了，也只能白白被耍了。她只想尽快结束这场谈话。她思考自己还有什么可以问的。

   阿贝莉亚说："那么一个人，从开始到结尾什么都没懂，那些人也和过影一样。"

   "现在不是我提问吗？"红伊水说。

   "那么一个人——"

   阿贝莉亚在自怨自艾。那个人就是她自己。在红伊水写的故事中，就如同阿贝莉亚说的那样，故事的主人公——阿贝莉亚，生于仇恨，死于仇恨——她当然没死，只是从开始到结尾，她都在为复仇而活。整个故事，如同序章所奠定的基调那样："毁灭开始的那一天，天空飘零着火星，洒落着泪水。我的眼睛一直盯着明天的光明，我的心被过去的温暖束缚住了……"

   "阿贝莉亚，你对这个故事有什么不满？——这是我的问题。"红伊水说。

   "我太满意这个故事了。"阿贝莉亚笑着说。

   红伊水根本不信。"你想我写出一个怎么样的结尾？"

   "现在是我提问的时间。"阿贝莉亚说。

   结尾一直是红伊对这个故事的遗憾。她在故事里花了太多的笔墨描绘阿贝莉亚的复仇之路，几乎没能写到任何温情的内容。整个剧情线都在紧绷着。这样，阿贝莉亚在完成复仇之后，整个人陷入了空虚——阿贝利亚没有今后的归途。身为作者的她一直这么认为，但是又不甘这么认为。她回头去找，去阿贝莉亚过去的回忆和人情世故中去找，她想找个一个值得阿贝莉亚最后归宿的精神家园。但是她找不到，她找不到一个满意的答案——她自己无法满意，她的读者就更难以满意了。她可以欺骗自己，但是无法欺骗读者们。最后，她只能在纯粹路线上一直走下去：阿贝莉亚直到最后一刻，依然是阿贝莉亚……

   "轮到我提问了。"阿贝莉亚打断了红伊水的思绪。

   "我也不想的……"红伊水喃喃道。

   "你为什么要写这样一个故事？"

   "这个问题太笼统了，怎么回答都好。"红伊水说，"为了生活，为了赚钱，为了取悦读者，为了取悦自己……怎么都好，怎么都是我的答案。"

   "这些都不是我要的答案。"阿贝莉亚说。

   红伊水又哪里知道这人想要什么样的答案。

   "你为什么要写这样的故事？"阿贝莉亚又重复了这样的问题。

   "你怎么可以问两次？"

   "因为你没有如实回答我。"

   阿贝莉亚的眼睛转为了猩红色，情绪很激动。也许，这是阿贝莉亚组织这场谈判真正想问的问题。红伊水觉得，要是她不认真回答这个问题，阿贝莉亚就永远也不会放走她。可是认真的回答又是怎么样的回答呢？……也许对于阿贝莉亚来说，这个故事就是自己的全部；但是对于红伊水来说，这个故事不过是写作的一个阶段。她过去写了这么一个故事，将来还可能写一个类似的故事，仅此而已。但是阿贝莉亚非要她回答。她该怎么回答，这又有什么意义？……

   红伊水埋下头。

   嘭。

   什么东西砸中了她的脑袋。她抬头时，看见一团赤色在坠落，散去。

   "回答。"阿贝莉亚说。

   阿贝莉亚如此咄咄逼人，好像红伊水不回答，就会被她杀掉一样。

   "我就是想写。"红伊水撑起了自己的气势。

   "回答我的问题。"

   "我已经回答了。"红伊水瞪向阿贝莉亚。但她又快速避开了阿贝莉亚的眼神。

   "我再说一遍，你为什么要写这样一个故事？"

   为什么，还能有为什么？她哪里说的出来……她的心脏好像膨胀了一下，但只是一下，又缩了回去。她也不知道自己刚刚为什么心脏快速膨胀了一下，也许是害怕的，也有可能只是错觉。

   "一个人的行动总有动机。"阿贝莉亚说。

   "也许我是一时冲动呢？"红伊水笑道。

   "那你真是畜生。"阿贝莉亚面无表情地骂她。

   "你知道的，现实意义的人其实是没有逻辑的……"

   "你和畜生一样没有逻辑。"

   阿贝莉亚变得暴躁易怒了。红伊水觉得，自己这时候不应该再进一步刺激这人；她要冷静，冷静地等待这人恢复理智。但是在这之前，她们的谈判会无法顺利进行……

   阿贝莉亚的眼睛亮了一下，是那深邃的红色。

   红伊水有一瞬间的机会可以逃跑，或者大声求救，但是她只是呆滞了，任凭那个机会流逝了。

   接着，有一个声音在她的心底呐喊：你为什么要写这个故事？——这个声音无休无止，好像要冲毁她的意识一样，无休无止地呐喊。她张了张口，终于，她脑袋里一片空白，被那声音给全部冲没了……既而，有一片灰色的意识在酝酿——那是一片什么样的意识啊，既让她感到温暖，又让她感到忧虑，还让她感到恐惧……那团意识变得越来越厐大，然后占据了她整个意识海；那团意识变得越来越威严，让她不得不正视它。它开始说话。它带来了无尽的声音。

   她身边出现了好多的人，他们都在说话。父母在说，亲戚在说，老师在说，同学在说，陌生人在说，领袖在说……全世界都在说——所有的声音此起彼伏，然后嘈杂在一起——他们的声音太嘈杂了，他们的声音太庞大了，几乎冲毁了她的意识——每个人都是独一无二的。每个人都是独一无二的……她相信了那样的声音。因为他们都在说，所以她无从怀疑。她的意识被那些声音代带入了更深处。有一个新的声音出现了：独一无二在哪里？……从来没有人追究过，独一无二在哪里。那个声音说：你和周围人如影随形，如影随形，她们怎么样，你也怎么样；到底，你和她们有什么区别？

   只要一个人独来独往，那就独一无二了。她的心底喊出了这样的声音。这是答案，照着做吧——不，我不要成为别人眼中的眼中钉！她心底又一个声音喊道。这个声音喊得她头疼欲裂。这声音说，只有红黎那样没心没肺的人才会这么做；她是一个女生，决不能这样，她不能被孤立；即使是伪装，她也要和她们一模一样；即使是伪装，即便是虚伪。

   她觉得不甘心。她一方面压抑自己的内心，一方面又无法阻止心底深处的膨胀。是那不甘心的声音在膨胀。她在那个声音的催逼下成长。她越是长大，那声音越是膨胀。她青年了，那声音膨胀到快要爆炸了。她竭尽全力压缩那个声音。她觉得是自己不够忙，要是她够忙碌了，就不会胡思乱想了。她要忙起来，让那声音彻底消失……那个声音又怎么会消失，只要她还需要睡觉，那个声音就会在夜深人静的时候响起来。那个声音不断地蛊惑她，她要让周围人的听见她的声音。那个声音不断地劝诱她，她要让这个国家的人听见她的声音。那个声音不断地鼓吹她，她要让全世界的人都听见自己的声音——她的声音要传遍全世界……

   她茫然无措。这样的欲望。她可知道，即使自己站在一个班级的讲台上发言，台下的人都漠不关心她说了些什么。他们只想听他们自己想听的声音。如果她用不合群的声音告诉他们，他们会反感。他们会用表情说，这个人有病，让她滚下来。滚下来。

   她必须用他们甘之如饴的声音说话。哪里有甘之如饴的声音？——这个世界的噪音很多。奇怪的是，所有人都在享受这样的噪音。球场，田径场，赛马场，电影院，音乐会，歌唱舞台……那些人发了疯一样去享受那些噪音——那些明明只是噪音，他们真的疯了——不，他们没疯。他们的确在享受。他们选择了自己喜欢的声音，尽管那听起来就像是噪音。于是，她的心底呐喊了：我要胜过那些噪音，胜过所有的噪音——为什么不能胜过区区噪音？……什么样的声音可以胜过它们？……世界和历史告诉了她：没有声音，那就是最大的声音。她决定成为作家。

   她发现，她只要沿着这条路走，她心底的那些声音就会安分下来，给她一个清净。于是她认为，自己走的这条路没有错。她没有怀疑地沿着这条路走。但是，这是一条灰色的路，它很窄，又很暗，而且只能容一个人通行。这条路不可能让她和朋友们一起，手牵着手过去。她必须一个人通过，一个人在上面摸索，一个人在上面爬行……她在这条路上不断爬行。她比自己想像的还要笨，她缺少计划就行动了。这样的后果是，一旦面临突如其来的困境，她只能选择妥协。她以为自己不会妥协，只要意志坚定——然而，妥协来得比她想象的还要快。在刻画阿贝莉亚的时候……

   "够了。"

   她的恍惚中断了。

   红伊水茫然地看着四周。刚刚发生了什么？

   阿贝莉亚的眼底的深红色暗了下去。

   红伊水意识到了。她抱紧了自己。刚刚那会儿，她的意志受到了阿贝莉亚的操纵。但是她没想到她会这样操纵她……她感觉自己浑身赤裸。阿贝莉亚的目光射向她。她一再想起了刚刚的那些印象。她为什么要写作……她心中回荡着那些答案和疑惑，还有她的做法。她心底涌上来一种窒息感。

   阿贝莉亚又怎么会理解她。

   阿贝莉亚会笑话她。

   阿贝莉亚在笑话她。

   她本想阿贝莉亚血肉丰满，却把故事写成了一场笑话。阿贝莉亚会笑话她的，而且会对她怒不可遏——但是，阿贝莉亚又如何能理解她的感受，她的不理解她，就和她不理解阿贝莉亚一样。她要是能理解阿贝莉亚，这个故事的结尾就能被改写了。她也想改写这个故事，不想阿贝莉亚只是一个人偶……她越是这么想，她的渴望就越强。现在，阿贝莉亚就在她的面前。她想到，要是能在阿贝莉亚身上找到答案就好了——

   为什么不能呢？……她的心脏快速跳动。阿贝莉亚现在就活生生在她眼前，她会思考，会质问，会超出她想像的行动……她的冲动遏制不住了。

   "阿贝莉亚，告诉我你的想法！"红伊水激动地说。

   "我想弄死你。"阿贝莉亚说。

   "我是说，你想变得怎么样？"她的心脏跳得更快了。

   "哈——哈——"红伊水快速地喘息。她意识到自己呼吸过度了。她不得不捂住自己的口鼻，遏制呼吸……她让自己慢慢冷静下来。

   阿贝莉亚正扬眉蔑视着她。如果阿贝莉亚这么做就能满足的话，红伊水根本无所谓。

   她爬到阿贝莉亚的脚边，用卑微地姿态仰视着她，哀求道："你告诉我好吗，你想要一个什么样的故事？

   "你才是创作者。"

   "但是，你现在是活生生的人了，我——"

   "闭嘴。"

   阿贝莉亚踢开了她的脑袋。她好像被踢中了太阳穴，一阵刺痛，一阵眩晕……她的情绪被切断了。她喷薄而上的情绪没了宣泄口，一下子衰弱了下去。她的希望也这么衰弱了下去。阿贝莉亚不给她这么一个机会。

   红伊水抱着脑袋，惨笑着说："你好无情啊。"

   "你没有资格这么说。"

   "你不是说我是你的创作者吗？"

   阿贝莉亚不说话了，眼神也丝毫不在她身上停留。红伊水觉得这比自己受到大声斥责还难受。她说："我是耗费了很大的精力才把你创作出来的。你的一言一行我都字斟句酌。每个时刻，我都担心自己琢磨不透你的心理……"

   "所以呢？"

   "那你给我一个机会，让我圆满它！"

   "啧。这根本与我无关。"

   红伊水惊愕阿贝莉亚为什么会得出这样的结论。"这不是你的故事吗？"

   "你在写你自己的故事，和我一点关系都没有。"

   "我——"

   "已经够烦了！"阿贝莉亚拍了一下桌子，站了起来。她珍视地茶几都蹦了起来，接连咔嚓几声。

   红伊水因为阿贝莉亚的恼怒而吓坏了，马上缩回了脖子，甚至一时失去了平衡，她原本跪坐着，现在上半身也跌倒在了地上。

   "因为你，我一生都在爬行。"阿贝莉亚说。

   红伊水卑微地说："但你现在不用了，你完全可以去找其他的活法……"

   "那也是在我报复之后。"阿贝莉亚说。

   阿贝莉亚接着说：
   "你是我最真实的苦难。你随心所欲的文字，是对我最痛苦的刑罚。现在，我要讨回那些痛苦的千分之一。"

   "你这样说不公平……"

   阿贝莉亚一步跨出，她的阴影笼罩住了红伊水。

   果然是这样，红伊水心想，阿贝莉亚还是要用强行的手腕。其实她早就知道会这样了，所以一直很谨慎，只是刚刚的她还是免不掉地心情大起大落了。她现在很疲惫，很想睡一觉，一觉睡到天黑，再到天亮。她一觉醒来，一切都会变回原样。阿贝莉亚什么的，不过是她的一场噩梦。但是她知道这是不可能的。阿贝莉亚就在她的面前，给她带来如此清晰地感触。阿贝莉亚的冷酷，愤怒，不甘，她站在她身边的气味，阴影，压抑感，窒息感……这些都如此的真实。

   "我就知道会这样，所以一直害怕，"红伊水艰难地说，"我把你描绘得聪明又狡诈，让你在仇人手中活下来。现在这变成了武器，报复我自己。我真是自作自受。"

   红伊水蜷缩起来，抱住自己的膝盖。她不知道阿贝莉亚会杀了自己，还是会折磨自己。身为作者的她完全猜不透阿贝莉亚的心思。她不知道这是否是自己的失败……但是，阿贝莉亚现在已经跳出了她的文字掌控了，这怪不了她了吧……她想到，自己的笔下的人物活了过来，自己总有独到的成功吧？

   阿贝莉亚蹲下身子，双手手掌盖在红伊水紧张地抱住自己的手上，然后一根根手指抠了开来。她的动作轻柔缓慢，但充满了力量，根本不是弱小的红伊水能够抵抗的。现在，阿贝莉亚捏住了她的一只手。阿贝莉亚开始抠开她的另一只手，然后再抓住，也是那么一根根的。

   红伊水紧张害怕得气喘吁吁，阿贝莉亚的手接触到她的手指时，她总感觉她要动用十指连心的刑罚。但她迟迟没有等来阿贝莉亚的刑罚。她在恐惧中等待，在恐惧中衰微。她的恐惧好像越来越庞大了，让她的呼吸也越来越急促。她的胸腔中好像有个巨大的气泡，在不断地膨胀，膨胀，排挤开了其他的器官，排挤开了她跳动的心脏……她觉得自己也许不该自己送上门来的，早点去找警察求助或许更好……但是，警察会相信她的说辞吗？……普通的警察能挡住阿贝莉亚吗？

   她想要不顾一切地逃跑。但是，她担忧的事情还是发生了——从被阿贝莉亚抓住的手掌开始，她的身体逐步失去了控制，一直维持着原来的姿态。她想后退，想逃跑，想大喊大叫，但都变成了徒劳。她只能瞪大眼睛，眼看着那女人的所作所为，她在她面前似乎越来越扭曲了……阿贝莉亚像摆弄洋娃娃那样摆弄她。她握着她的手，前后旋转肘关节。掐着胳膊，上下旋转肩关节。端着她的头，左右旋转脖子。用手指撑开她的眼皮，从一只换到另一只。阿贝莉亚满意地笑了。

   这一刻，红伊水连哭泣都无法如自己所愿，只有眼泪无力地滚落而下；她想说话，但是她嘴巴周围的肌肉群根本不受控制。她知道的，阿贝莉亚在用原本并不擅长的魔法操纵了她，只是她实在太弱小了，只是个普通人，根本抵抗不了分毫，所以让阿贝莉亚得逞了。

   "复仇使我快乐。"这个女人在她耳边像恶魔一样低语。

   "从今以后，我自由地活着。"这个女人说。

   阿贝莉亚挥手之间，赤色雾团飞出——那是她拿手的灼元素——在她们身周撑起了一个直径五米的半球形囚罩。囚罩上的能量流转，呈或深或浅的半透明色，透过它，能看见附近和远方的色泽。阿贝莉亚逐步脱掉红伊水的衣服，直到身无寸缕。阿贝莉亚不知道她内衣构造，所以笨手笨脚地摸索了好久，那双冰凉的手接触她的肌肤时，总令她唯一还受控制的眼皮疯狂打战。她紧闭眼睛，再也不想管外面的一丝一毫，哪怕那时她自己的身体。早知道是这样的后果，她还不如缩在寝室里等死……

   她跪了下来，膝盖打在了草地上。她意识到，自己重新取得了身体的控制权。她抱紧身无寸缕的自己，蜷缩在那儿。她那种劫后余生般的感觉只持续了一瞬间，因为她意识到，自己还处在阿贝莉亚的眼皮底下，高兴的太早了。

   阿贝莉亚抛来一块大大的布，遮盖了红伊水的视野。红伊水连抓带拉，总算让自己的脑袋露在了外面，然后下意识地以布块裹住了身体。阿贝莉亚的黑色长裙消失了，变得和红伊水一样身无寸缕，正穿戴她的内衣。阿贝莉亚费劲地在身后扣好文胸，转而穿上内裤，然后套上红伊水的背心，披上运动外套，拉上拉链，最后穿上运动长裤。

   阿贝莉亚双手往后一挽长发，那发型就变得和红伊水的一般无二了，连带额前的头发也变了，敞露的额头由轻轻落下的刘海遮掩。阿贝莉亚眨了眨眼睛，深红色的眼仁变得漆黑，和眼白对比分明。她调整了站姿，肩膀微微内缩，膝盖微微内扣，似乎还有各处肌肉的细节变动，总之，原先的傲慢冷漠消失了，流露出了小女儿的姿态。最后，她收起了笑容，两边嘴角略微下垂，配合着冷淡的眼神，好像变成了一个愤世嫉俗的女青年。现在，可能除了红伊水本人以外，没人能辨出眼前的是个冒牌货了。

   "你……"红伊水猜出了阿贝莉亚想做什么，但是不敢说出来。


## Chapter 19


   阿贝莉亚右手掌盖在红伊水的脑门上。

   "要是抵抗的话，你也许会变成白痴。你明白的。"

   红伊水瞪大眼睛，然后又放松了下来。她竭尽全力让自己放松。松开紧绷的面部肌肉，松开紧咬的牙关，还松开了拉住白布块的手，任凭它飘落于地。当阿贝莉亚的护罩布置起来时，寒风就无法再吹入这一块土地了。空气还流通着外界，过了多久她都不会有窒息感。她闭上眼睛，感受到一双无形的手从头顶渗入，趁着她精神松懈，探入了她意识的海洋。那是魔力变幻的抽取记忆之手。要是她现在突然绷紧精神，那么她意识之海的入口就会关闭，那双记忆之手就会被卡在期间，那手本质上是魔力，这意味着外来的魔力滞留在了她的意识海洋里，她可能因此变成白痴。她清楚后果，所以配合着阿贝莉亚。

   一个月以来的记忆翻涌在她的脑海，意识、思念、图像、感观、情绪，这些都在短时间内重演了一遍。

   终于，当疲倦快要夺走所有的光明的时候，阿贝莉亚的手掌离开了她的脑袋。她仰着脑袋喘息。喘息。

   啪。

   阿贝莉亚丢下了一袋零食，袋口露出盒装饼干，袋装干脆面，真空装的五香豆腐。一根火腿滑落到草地上。

   阿贝莉亚跨出了自己布置的半球形护罩，朝着学校的方向快步离去。

   红伊水呆呆地望着那人的背影，和她本人一模一样的背影。她意识到了后果。她起身，提着遮掩身体的白色布块，冲向远去的阿贝莉亚。然而，护罩挡住了她，让她半步不得寸进。她猜到了会这样。她握拳敲打在那护罩上，一次又一次，但是它纹丝不动。

   她回过头。护罩内的这一块土地上，有一张圆桌，一把椅子，一个茶壶和一个茶杯，还有勉强能保暖的白色布块——或许是一张床单——还有阿贝莉亚刚刚丢下的一袋零食………………

   红黎唤醒枕边的手机，确认了时间，凌晨两点；再确认日期……他睡了两天一夜。起初他还以为自己记错时间了。他摸着黑，顺着直梯，蹒跚下了床铺。他现在还是身无寸缕。在他昏睡的期间，估计是阿贝莉亚把他丢到了床上。阿贝莉亚是怎么知道他的寝室和床铺的，这点他还是不深究了。他的衣服和裤子散落在书桌上、椅子上。他就着手机的亮光穿上了整套衣服后，才点开了灯。

   他的三位室友离校实习了，一般不会回来。他扶着墙，蹒跚着来到洗漱台的半身镜前，看见了映入镜中的自己的脖颈，领口的位置爬满了深红的纹路。她扯下衣领。

   阿贝莉亚刻画下的纹路呈深红色，与他苍白的肌肤形成鲜明对比；纹路于他的锁骨位置开始，接近两根手指宽，曲线行走，弯弯绕绕，深入到衣领下面。他松掉衣领，揭起上衣，让整个腹部和胸膛都倒映到镜子中。深红色的纹路刺目又可怕，盘卧在上半身，让他像个诡异的巫师，或者将要被献祭的牲人。要是他这么赤裸着游荡在学校里，或许会被奉劝退学。

   他回想起前天夜里的恐惧，就浑身战栗。他的本能和理性都在呐喊：不要再去，那是折磨……

   他关掉了灯，摸回书桌前，坐下，静默了十分钟。阿贝莉亚说的下一次纹刻的时间就在不到半小时之后。他到底是否要去呢？……到了现在，他也没有觉得饥饿或者口渴，这可真是个奇迹。他忍不住期待，也许魔法已经在他身上奏效了……但是他又想到了前天晚上的折磨……

   他决定不去了——他不是一直不去，他只是想要自己一点休息的时间。他的皮肤还隐隐残留着刺痛。他给阿贝莉亚发送了WeLine的消息，然后到走廊外的饮水机接了点水，给自己补充了水分。然后他就关了灯。要上床睡觉了。

   咄咄。是阳台传来的声音。这声音让红黎心里一惊，这声音像是脚步声，鞋跟与地面相碰的声音——是阿贝莉亚的鞋子的那种脚步声。他一下子从床上坐了起来。

   阳台的门窗被推开了，那咄咄的脚步声走了进来。那黑色的一片中，有一团赤色的光雾亮了起来。

   "阿贝莉亚！"红黎喊道。

   "走。"她说。

   红黎看不清她的面容，只能看到她手边的那团光雾勾勒出了她的上半身的轮廓。他现在有些话想说，想说自己不是逃避……她肯定是来抓他过去的。

   "阿贝莉亚，我需要休息一下。"他说。

   "已经休息了两天了。"她说。

   "但是……"

   "会前功尽弃。"

   "可我……"

   光是想一想前天晚上的折磨，他就浑身战栗。他现在皮肤都在颤抖，他怕自己承受不住变成了疯子，前天阿贝莉亚不是就那么说了吗？

   "阿贝莉亚，人是很脆弱的……"

   阿贝莉亚手中的光雾漂浮不动了，她一把抓住了他上铺的直梯，一脚踩上了中段，发出当的一声，然后她半个人就伏进了他的床铺上。她这么冲进来，让红黎下意识地拉上被子，往后一缩。

   "不要浪费时间，拿出你的觉悟。"她声音低沉地说。

   "好了，好了，我知道了，"红黎连连说，"你先下去吧，我马上下来。"

   阿贝莉亚沉默了一会儿。在那一片昏黑中，她一定是在盯着他，否则他不会有这么刺痛般的压力。她终于跳下了床铺。

   她说："你再不下来，我就烧了床。"

   红黎老老实实地床上了衣服，沿着直梯爬下床。他感觉现在的阿贝莉亚不对劲，戾气很重，虽然之前的阿贝莉亚也并不好说话，但总表现得更游刃有余，而不是现在这样。

   阿贝莉亚不对劲，但他肯定想不出原因，他只有老实地跟着她。他们一路到了操场。红黎对于阿贝莉亚有了新的认识，她居然也会这样性情急躁。他也加深了心中的疑惑，她为什么这么重视传授他魔法的事，明明他自己都说不去了。只是因为她不想前功尽弃吗？

   到了足球场中，阿贝莉亚让他趴在地上，她今天要在他的背部刻画纹路。

   她手中的笔刷再次蘸入那匣子，发出粘稠的液体声，让他打了个哆嗦。

   他再怎么忐忑，害怕，那笔刷终究还是落在了他的背上。不过，不知道是否是他的错觉，他感觉今天的灼痛没有昨天那么剧烈，也许是他的身体适应了这个过程。但他还是免不了煎熬。刻画结束时，汗流浃背的他昏迷了过去。

   …………

   他醒过来的时候，时间是同一日的晚上十一点。这一回，他只睡了一个白天的时间。

   他已经两天没有吃饭了，但还是不觉得饥饿。或许在他昏睡的期间，阿贝莉亚帮他补充了能量和水分。他完全不知道她做了什么。他下了床铺，穿上衣服，点开灯。在半身镜前，他揭起的衣服下面，那些深红色的纹路淡退了不少，原先偏向黑色，现在偏向了红色，像粗大扭曲的血管。他的背上也有，脚上也有。要是挽起袖子，手臂上也有。它们的颜色都偏向红色。

   他离开了宿舍楼，前往二十四小时营业的便利店。这个时间点，情侣们手挽着手在亮黄的路灯下漫步。他翻看着手机里积存的消息。红伊水在两天前就给他发送了一堆消息，还连打了好几个电话。他现在追问回去。对方回答："已经没事了。"于是，他也不在放在心上了。其余的消息都是班级的全体通知，没什么要紧事。他感慨起大学的松散，他明明已经两天没去上课了，然而一点波澜也没有生起。看来明天他也能安心地旷课了。

   他路过了好多个学生，听见他们在讨论某一件事，什么举报，什么通报，什么女生，新生，科研，论文发表，奖励和惩处……

   他来到便利店。他买了一瓶新鲜牛奶，一包鸡排饭团，一块火腿三明治，充作夜宵。饭团和三明治都递给了服务员，让他帮忙以微波炉加热。

   自动门打开了，伴随着一段迎客的旋律。

   穿着一套运动装的红伊水低垂着脑袋，杵在门口——她的发型和身形让红黎认出了她。她站得位置微妙，刚好拦在了路中央，别人想通过的话，只得侧过身子擦过；但她漫不经心的样子又不像刻意拦路。红黎猜她有话要说，就等着她开口。他把热腾腾饭团的包装袋口撕大，尝了一口。他的牙齿因为两天没有活动过了，传来一种老牛拉犁般的倦怠，但马上就消失了。他掏出裤兜里的瓶装牛奶，旋开盖子，大口灌入嘴中。冰凉的牛奶沿着食道向下，到了无知无觉的胃中。他忍不住打嗝了。

   "两天不见了。"红伊水抬起了头。

   他总感觉红伊水脸上的表情有点僵硬，但又说不出是哪里。他觉得是错觉，因为那原本就是一张扑克脸。"你之前找我有什么事情吗？"

   "我不是说过没事了吗？"

   红伊水从他身边经过，在店中央的即食柜台上徘徊。她右手支着下巴，浏览着那些饭团、三明治、还有盒饭。她往红黎这边瞅了一眼，然后取下了一包饭团，一块三明治。饭团是鸡排饭团，三明治是火腿三明治，和他的一模一样。

   她绕到了即食柜台的另一侧，背过身，浏览靠墙的冷饮柜。她好像又往红黎这边瞅了一眼，但动作太快，红黎不确定是否是自己眼花了。她取下了一瓶和红黎手中一模一样的牛奶，查看上面的标签。

   便利店里侧的门开了，服务员再次出来了，顶着一双黑眼圈，从红伊水手中接过饭团和三明治，去服务柜台内帮她加热。红伊水差点跟着他进了柜台内，但最后止步了。红伊水掏出那款新潮又昂贵的手机，显示付款码，让服务员结了账。

   红伊水这一系列的行为，让红黎怎么看怎么怪异。首先，红伊水是那种会明面上效仿他的人吗？……

   红伊水斜眼看向他。"有什么问题吗？"

   "没有。"红黎选择老实地吃手中的饭团。

   "那请你不要盯着我看，这样让我觉得恶心。"

   红黎无话可说了。

   叮。加热结束了，服务员用防烫纸板夹出饭团，捏着提手口拎出三明治，放在服务桌台上。服务员最后好像递给了红黎一个同情的眼神，

   红黎等着红伊水一起离开了便利店。他吃完了饭团，把包装袋丢进门口的垃圾桶。就这会儿，红伊水已经走远了。他快步追上。

   "我前天一直没有回复你，是因为……"

   红伊水的右手像变戏法一样，食指和中指一屈，夹住包装袋口，伸直，那包装袋上预先撕开的小口子骤然扩大了，露出了飘着热气的白白大饭团。她的左手更让人瞠目结舌，单靠拇指和食指，居然旋开了那瓶盖。这是人的身体构造能做得到的吗？红黎顿在了原地。

   "你惹我很不爽，"红伊水头也不回，逃也似的往前赶，"所以今后不要再让我看见你，也不要和我搭话。"

   红黎刚从衣兜摸出来的三明治掉到了地上。他慌忙捡起，追上红伊水。

   "你以为我在说笑？"红伊水转身，在他面前站定。

   这里刚好位于灯光下，那双平静的眼眸好像在说，她只不过陈述了一个客观事实。她小口小口咬下饭团，看起来好像吃得慢，但频率高，没一会儿就吞掉了三分之一的饭团。她咀嚼的时候，两边的腮鼓成了大包。红黎一直注视着她，中途她的眼睛开始闪烁，看向别处了。她喝了一口牛奶——不，她一口就把牛奶全喝光了，那塑料半透明的瓶身上已经看不到液面了，虽然她还平举着瓶子。

   她说的话没问题，她平时也差不多都这么说。但她还是很古怪。

   "红伊水，你不对劲。"

   红伊水跑掉了，跑得飞快。

   红黎望着她拐向女生宿舍楼的背影，心里有个猜测，但无法证实。

   …………

   红黎提前半小时到了操场，躺在足球场正中央，望着灰黑色含着星子的夜空。他就这么等待了半个小时，直到发现阿贝莉亚。他挺背坐起。

   阿贝莉亚从操场入口踱步而来。她没有往日那么步履匆匆。

   他远远就听见了她的脚步声，厚底皮靴踩在塑胶草地上发出的沙沙声。她低垂着眼帘。从他这里，他甚至能看见她深红色的眼眸透着的思索。现在明明是大晚上，一片昏黑——在他原来看来，但现在他的夜视能力也变强了，看什么都清楚了，明明天上连月亮的影子都见不到，星子也只有稀疏的几点。当阿贝莉亚走近时，她抬头，他甚至能看清她虹膜中的放射纹。不仅是感官的变化，当他刚刚挺背而起时，甚至有种感觉，他能一个鲤鱼打挺起身，端端正正站起来。

   不，现在这些不重要。

   "阿贝莉亚，我们不久前是不是见过？"

   "你一觉睡到了现在吗？"她说。

   "我刚刚和你一起在便利店，你在便利店里说了我恶心，出了便利店……你让我不要出现在你眼前。你在扮演红伊水的身份，是吗？"

   "我不知道你在说什么。"

   阿贝莉亚屈膝斜坐下来，拍了拍草地，似乎在催促他脱掉衣服躺下。

   她果然不会就这么承认。

   但他还是有想不明白的地方，阿贝莉亚为什么会有红伊水的手机？……从先前他们的对话来看，阿贝莉亚好像知道了自己给红伊水回复了什么一样，因为她说："我不是说过了没事了吗"。不知情的人说不出这样的话。

   红黎脱掉外套和裤子，丢在地上。如今他的夜视能力增强了，自己的举止和模样看得一清二楚，他想到了阿贝莉亚的感知能力。她的感知一定比他只强不弱。

   "你在犹豫什么？"阿贝莉亚说。

   "我现在还需要再脱吗？"

   "随便你。"

   最后，他还是脱掉了衣服，平坦而下，双手摆开。

   阿贝莉亚再次拿出了她的匣子和笔刷。他今天能看清那匣子的模样了。它看起来和那天她交给郑安若的礼品匣子没什么两样，只是没有缎带包装而已。她另一只手拿的笔刷倒是挺奇特的，笔杆略呈"S"形弯曲，由数根枝条合抱在一起，下面的毛刷粘着黑红色的颜料。她蘸了一下笔墨，让笔锋在他胸前落下。

   他支棱起脑袋，盯着笔刷在他身上行走。今天的过程一点都不痛苦，充其量只是针线在皮肉上缝合的程度而已……他能忍受。

   "你扮成了红伊水，还拿着她的手机，那她本人被你弄到哪里去了？——不要骗我说，她还在寝室里好好的。"

   "我不知道你在说什么。"

   "阿贝莉亚，你的演技太拙劣了。"

   阿贝莉亚拿着的笔尖在他胸前戳了一下，让他感觉自己中了子弹一样，忍不住惨叫了一声。

   "这是我和她的恩怨，与你无关。"

   "那你是承认了？"

   阿贝莉亚的笔刷走到了他的腹部。她说："你从哪里开始发现的？"

   "我说了，你的演技太拙劣了。"

   阿贝莉亚沉默了。

   红黎再次问："你把红伊水怎么样了？"

   "我杀了她。"

   他的身体被固定住了，动不了。他只能支起脑袋，去看阿贝莉亚的表情。她是以平淡如常的神色这么说的，说的好像不小心踩死了一只蚂蚁一样。


## Chapter 20


   红黎中午十二点就醒过来了，久违地看见了明亮的寝室。他躺着回想了一会儿，马上觉得不对了：凌晨那会儿，他已经不再因为阿贝莉亚的刻画而痛苦疲倦了，那么他为什么后来又昏迷了？

   他翻身下床，快速穿好了自己的衣物，跨步到窗门前，拉开雾化玻璃门，让外面微凉的空气流进来。天顶上的太阳照落在两栋宿舍楼之间的庭院，草地上撑起一排排的铁杆，五颜六色的被褥在上面飘摇着。

   他慢慢地坐回到自己的位置上。他对阿贝莉亚了解的太少了。昨天她说的那句话，他都不知道是否是真的。她说她杀了她。真是噩梦一样的回答。他在窗外看见的平凡景色就像假的一样……不，她看起来并不像这么做的人。他无法确定。但是他脑内的两个声音已经吵起来了。他们永无止休地吵，但是根本得不出答案。因为他没有更进一步的信息了。他想起了那时候他对于阿贝莉亚的猜测。她是一个从小说故事里走出来的人。听起来荒诞不经，但这似乎是一个合理的解释。不是有那神奇的水晶的存在吗？有了它，多么荒诞不经的事情都会发生。何况更不合理的事情都发生在他身上了，比如他身上的这些赤色纹路，据说是魔力的回路。

   如果她真的来自于小说，那么那小说一定记载了她的事迹，还描写了她的性格，还有将来和过去。他应该早点想到的。他马上找出自己的手机，浏览器搜索阿贝莉亚的名字……他搜索出了一些以阿贝莉亚为人名的人物，都是他不认识的外国人。他换了一种搜索方式，搜索关键词：小说，主人公，女主角，阿贝莉亚，黑色长裙，巨大镰刀，魔法……他试了能想到的任何组合。但是他尝试了近半小时，依然得不到任何结果。难道她并不是小说里的人物？……还有可能是什么，游戏，电影，电视剧，动漫……他把想到的都搜索了一遍，甚至利用AI程序来帮忙搜索，然而，他就是得不到任何的答案。他试着搜索了网络上的论坛，贴吧，一切信息汇集的地方，然而结果都让他失望。

   她并不是一个虚构世界出来的人物。他几乎得出了这样的答案。但是他总觉得不对劲。

   他想不通的地方还有很多，比如她和红伊水的联系……他想到了另一个可能，是红伊水写的一本小说，然后以阿贝莉亚为主角，赋予了她痛苦的一生，然后阿贝莉亚突然出现在了现实中，深以为恨，然后要复仇……他被自己的猜测吓了一条，因为这条线似乎贯穿了所有的线索，一切不合理的地方，现在都解释得通了。他马上搜索红伊水的信息……半小时后，他还是找不到任何阿贝莉亚或者红伊水的线索，连蛛丝马迹都没有，她们就像在世界上不存在一样。红伊水这个名字，他在网上也搜索不到，即使同名人都搜索不到。也许没人用这个名字。他心想。那也不算特别奇怪……也许红伊水她并没有对外宣称自己的真实姓名。

   他徒劳无功了好久。从网络上寻找线索这条路似乎是行不通了。

   他离开宿舍楼，姑且往医药楼的方向走。阿贝莉亚绑架了红伊水——是不是绑架他不知道——然后假扮成红伊水，不知道做了些什么。

   他可以听清路过学生们的低声讨论。

   "晚饭吃什么好呢？"

   "距离晚饭还有好久，现在考虑这个还太早了。"

   "唉，好无聊啊，有什么有意思的事情吗？"

   "你听说过那件事了吗，大一新生被学校通报批评？"

   "那人好像姓红来着，这件事还上过表白墙，不过后来撤销了。但是她没有被通报，那只是谣传。"

   红黎跟在前面两位女生后面。她们话题的中心估计是阿贝莉亚假扮的红伊水。遗憾的是，她们结束了讨论。两位女生拐向了便利店。这时，红黎的迎面走来三个眼熟的女生。

   "你是红伊水他哥？"为首的女生说道。

   "是。"

   红黎想起来了，这三位是红伊水的室友，为首的这位似乎叫作白玫。

   "最近红伊水有点怪怪的，你知道什么吗？"白玫问道。

   "她怎么怪了？"红黎说。

   "我不是说她奇怪，只是……"

   "我明白。"

   "最近红伊水都不和我们亲近了，不和我们吃饭，不去上课，也不去图书馆，我们一天都没怎么见到她。之前她可不是这样的。"

   "也许遇上了不顺心的事，过两天就好了。"

   "要真是这样就好了……"

   红黎匆匆赶往医药楼。他来到了三楼的实验平台入口前，门禁拦住了他。刚好这时，一位西装的老师刷开了门禁。他不动声色地跟在这位老师身后。他顺利跨过了门禁的阻拦。

   "你是哪个实验室的学生？"前面的老师说。

   "不是，我是来找人的。"

   "你不属于这里的实验室？你是本科生？"

   西装老师眯起了眼睛，横在了红黎身前，逼得他倒退了一步。

   "这里……本科生不能进入吗？"红黎问道。

   "本科生进来要提前预约，你预约了吗？"

   "我们在这里上过实验课——"

   "上课是上课，平时是平时。你没有预约，却跟着我溜进来，规矩呢？你和这里的老师说过吗？没有吧？你可能不知道，我们这里的规章制度是很严格的，不要想当然，不是说进就能进的。你看看这里的仪器，都是贵重仪器……"

   他实在想不到，这老师劈头盖脸就数落了他一顿，还滔滔不绝，把事情越说越严重。

   "我现在就出去。"红黎转身就要跑了。

   "你等等，我还在跟你说话呢。"西装老师叫住了他，"你来这里要找谁，哪个研究生？"

   红黎在心底斟酌了一下阿贝莉亚的身份。他不确定她在这里的用名。"老师你知道一个穿着黑色长裙的人吗？"

   "呵，你来这里相亲啊？"

   "不是，她是一个研究生，平时都穿这副样子。"

   西装老师雄赳赳跨进左边的办公室，头也不回给他抛了一句："你等着。"

   这位老师里面吆喝："崔老师，有人找你那位女学生。"

   迎接红黎的是另一位西装老师，看起来气宇轩昂。

   这位崔老师让红黎跟着自己。红黎想马上甩掉他，但是他并不给他多说的机会，只是让他跟着自己。崔老师领着他到了隔壁的会议室。会议室的构造深而窄，陈设着一张长木桌，围摆着一圈带滚轮的圆凳子。没有其他人在。

   崔老师点开灯，关上门，踱步到最里侧，面朝着门而坐，然后朝红黎招手，让他在旁边的位置上坐下。他感觉自己好像被卷入了麻烦的事情中。可能阿贝莉亚在这里闯祸了……他想着，坐在崔老师点着桌子的那个位置上，面朝着墙。两人坐成了直角。

   "你是阿贝莉亚同学的朋友吗？"崔老师翘起了二郎腿，微弓着腰，手肘压在桌子上，脑袋凑近了点红黎。

   "是的。"红黎挺直背，这样能和这位老师拉开一点距离。

   "阿贝莉亚同学是何教授带到我们实验室的，起初我还怀疑她的能力，但她很快就证明了自己。她是个真正的天才，在计算机应用上。"

   崔老师拿出手机，右手在屏幕上拨拉着。红黎等了半晌，恨不得现在就起身走人。这位老师到底想和他说什么？

   崔老师熄了屏幕，把手机搁在桌子上，接着说："她是个天才，没过几天就把那些软件啊，编程啊，用得得心应手了，帮我们的课题组解决了很多问题。我非常欣赏她。我一直想找机会和她谈谈，让她就这么留在课题组，但一直都找不到机会……"

   红黎心想，这肯定是阿贝莉亚不想给他机会。

   "她是何教授带来的学生，我对她也并不太了解，所以听见有人找她，就趁着这个机会和你谈谈，让你帮忙沟通阿贝莉亚。她是本科生还是研究生啊，是来自哪个学校啊？"

   "抱歉，老师，我也不太清楚，我和她只是见过几面，相互帮过一两次罢了。老师为什么不问问何教授呢？"

   崔老师拿起桌上的手机，再次拨拉起屏幕。这位好像一时半会儿停不下来。红黎踩实地面，不动声色，用屁股挪动了一下圆凳。滚轮发出"嘎吱嘎吱"的声音。从旁观者看来，他只是调整了一下坐姿而已，而不是处心积虑地要偷窥这位老师在做什么。红黎双手搭在桌子上，身体前倾。好了，现在他可以从斜角看见崔老师的手机屏幕了。

   崔老师点开一个消息栏，上下翻动对话记录，退出；再点开一个消息栏，查看回复的内容，退出……以红黎现在的视力，能看清那些屏幕上的字。但好像没什么特别的，无非就是领导通知，试剂采购，公司联络，下催学生，或者"大哥""老弟"之类的话。

   崔老师搁置了手机。

   红黎端正了坐姿。

   "何教授呢，她人比较忙，在前线工作，很少管学生的事务……好了，既然你也不太了解阿贝莉亚同学，那么我们就先谈到这里吧，我马上要去开个会议。另外，如果有机会，希望你帮我向阿贝莉亚同学传达，我这边非常欢迎她，我个人也非常欣赏她，她随时可以加入这里的大家庭。我们就先到这里吧。"

   这就结束了？

   红黎跟着崔老师起身。

   "阿贝莉亚不在实验室，我刚刚找她也没碰上面。"崔老师说。

   他们就这么离开了会议室。

   虽然崔老师这么说，但是红黎还是没有一走了之。他在实验室转了一圈，确认阿贝莉亚是否在这儿。他有遇见了两个自说自话的老师的先例，心里有了阴影，不太想和这儿的人接触。他遇见了人，特别看起来像是老师的，都离得远远的，免得被碰上了又被叫去谈话。他小心谨慎地看过了各个实验室，还是找不到阿贝莉亚。最后他只得无功而返了。后来，红黎离开医药楼的时候，总觉得那两位老师都挺奇怪的。也许这就是所谓的研究生导师了。

   …………

   夕阳透过了赤色的护罩，投落在洁白的圆桌上，把它染成了血色。红伊水小口地吞饮着杯中的茶水。茶壶中的茶水一度倒光了，之前有乔装成她模样的阿贝莉亚来过。阿贝莉亚来到时候，在她生活了一天一夜的这方小空间里东张西望。

   最初的一天下来，红伊水被生活上的各种不适受够了。一日三餐只能吃那袋垃圾食品，翻来覆去就是甜腻的味道和咸涩的味道。她吃多了觉得反胃。但吃少了又觉得饥饿。她还时常感到口渴，但她又不敢喝太多的茶水，要是用光了这唯一的水源，那她也许只能等死了。她睡觉也睡不安稳。她只能趴在那小圆桌上，给自己裹着单薄的白布，熬过漫漫长夜。她原本想把白布摊开在草地上，然后睡在上面，但她担心地上有虫子。护罩虽然隔绝了四面和上方，但没有隔离大地，也许会有某种虫子从土壤里钻出来。最痛苦的还是卫生问题。

   阿贝莉亚根本没有为她考虑卫生问题。她要是有内急，根本只能憋着。这是一个封闭的空间，她要是……那只会把自己熏死。她一直忍着憋着。就这么过了一天，她才终于看见阿贝莉亚……要是这人不来……她不敢去想。后来她以死相逼，逼得阿贝莉亚给她做了一个"魔法厕所"：
   一个圆井般的堆叠魔法阵，从上往下看，里面闪烁着灼元素的赤红色光辉。不用阿贝莉亚多说她也知道，落入里面的任何东西都会灰飞烟灭。她反复做了自我开导，才成功把它当作厕所来用；因为这片小空间暴露在天底下，周围一览无遗，虽然都是荒野、远山、公路。

   让她生不如死的是，她如厕过后，才意识到没有水可以供自己清洗——她本来都打算投"井"自杀了，还好，上天没有放弃她，她浑身战栗着从那袋零食中搜出一包两百抽的纸巾……然而，她还是需要水。她需要水。她好像觉醒了洁癖，摊着手掌，张着五指，在这片小空间外围焦躁地绕圈。最后，她忍痛用珍贵的茶水给自己洗了双手。


## Chapter 21


   红伊水以为自己会死，或者被阿贝莉亚反复折磨——虽然现在的处境真的等于折磨，但她想象中的折磨不是这种软禁。阿贝莉亚想做什么……她对阿贝莉亚的理解还是太少了。她当初为什么要写出一个这样的角色来着……当初的事情她好像记得不太清楚了。为什么会这样？她记得明明那是挺重要的事情来着。她为什么要开始写作？……她记不清了。她不想了。比起这些，她目前的生存才是最要紧了。她的茶水又喝光了。

   但还好——很难说是好——阿贝莉亚来了。阿贝莉亚变出另一副扶手椅，放在圆桌的另一端，然后端坐在那儿。她接着变出一台纤薄的笔记本电脑，揭起显示屏盖，啪哒啪哒的敲起键盘。这一幕红伊水都见惯了，在她上实验课的那天，还有她找这人试图谈判的那天，她都在这么敲。红伊水这个作者弄不懂她的心思。

   红伊水感到口干舌燥，忍不住往外吐着舌头，好像能因此吸收空气里的水汽一样。反复的键盘敲击声折磨着她的神经。阿贝莉亚的到来好像就是为了这么折磨她。

   夕阳踩在了西边一幢大厦的脑袋上。

   红伊水忍不住了，把空空的茶壶推过去，擦过电脑的边缘，撞在阿贝莉亚的手上。

   阿贝莉亚终于停下了敲击，沉着脸，眼睛剜向她。但红伊水已经因为身体的干枯而无所畏惧了，也瞪起了眼睛。

   阿贝莉亚的手握住了茶壶的把手。茶壶有一度从圆桌上消失了，然后回来了。壶中传来液面晃荡的声音。红伊水从未有过一天觉得，这盛满后晃荡液面的声音是如此美妙。她站起身，即使裹着身体的白布脱落了也满不在乎，连续给自己倒了三大杯，直到把自己的胃灌满为止。她仰靠在扶手椅上发呆，重新用白布块裹住身体。

   "你到底什么时候放我出去？"红伊水问道。

   "等我尽兴了之后。"阿贝莉亚说。

   "这就是你要的复仇？"

   "它给我带来了短暂的快乐，但随后是无尽的空虚。"

   "那你该放过我了！"

   "你有没有更好的主意？"

   "给你主意，然后折磨我？"

   "嗯。"

   红伊水大声说："你做梦！"

   阿贝莉亚没有理睬她。

   "我们做个交易怎么样？"红伊水放软了语气。

   阿贝莉亚没有理睬她。

   红伊水接着说："你是我写的故事的人物，你对我不满是因为你觉得自己不幸，被我写得太惨了，失去父母，失去了兄长，孤独一人。既然这样，我重新给你写个故事，把你的家庭写得美满点，父母健在，兄长也在，你分外受宠。你每天早上起床，都有母亲给你道早安，为你准备早餐；吃完早餐后，你去地下室里看看做研究的父亲，偶尔帮帮忙；你兄长从学院回来了，给你讲述学院里发生的故事……你觉得怎么样？"

   阿贝莉亚还是不理睬她。

   "你快放我出去，我现在就给你写！"

   红伊水压下了笔记本电脑的屏幕。屏幕夹住了阿贝莉亚的那双手，让她无法再打字了。红伊水得以和那双冷漠的眼睛对视。但那双眼睛没有给她更多的关注，马上就撇下了她。阿贝莉亚抽出手，甩在她压着盖子的手上。红伊水因为这一巴掌，摔在了身后的椅子上。

   "那个阿贝莉亚，不可能是我。"阿贝莉亚说。

   她有反应了，说明她对这样的事是有憧憬的。红伊水心想。

   红伊水说："要是能再找到一块水晶，那个阿贝莉亚就会变成真的！"

   "我说了，那个阿贝莉亚不可能是我。"

   "那就换个愿望，"红伊水说，"水晶是不是说明愿望都能实现？"

   阿贝莉亚又打开了她的电脑，在那儿打字了。

   "水晶的事你比我更清楚，"红伊水说，"你把你的愿望告诉它，它会帮你实现……"

   红伊水想象中的水晶是阿拉丁的神灯一样，什么都能做到——真实如何就不知道了。她见阿贝莉亚没反应，又继续说下去……她徒劳无功了好一会儿，阿贝莉亚都无动于衷。

   红伊水绕过去，看她在电脑上都在做什么，为什么这么投入。但是她看不懂。红伊水放弃了，那一大片的英文看得她脑袋都作痛了。她不解的是，阿贝莉亚为什么要跑到这里来写代码——可能是监督她之余顺带的——那么，她她写这些代码到底在做什么？

   阿贝莉亚阖上了屏幕。"我来告诉你我在做什么。"她说起来还颇有几分自负的意思。

   她接着说："我佩服这里的人的智慧。这技术——计算机可以轻易地计算出人可能穷尽一辈子都无法得出的答案。你知道的，我在过去有很多个无法实现的魔法，是因为计算不到结果，但现在……"

   红伊水下意识地后退，她感到不安。阿贝莉亚特意告诉了她，只是为了吹嘘自满吗？……不，这件事肯定和她密切相关——阿贝莉亚用计算机完成的魔法，就是为了用在她身上。

   阿贝莉亚说："几天前，我就已经把网络上所有的数据都清除掉了。"

   红伊水没明白阿贝莉亚在说什么。

   "单单网络上的数据还不够，我需要更彻底的抹除——连同你身上的数据也一并抹除。"

   她说的"抹除"，根本不是杀死的意思。她要是想杀死她，需要计算机吗？红伊水越来越听不懂了。"你到底在说什么？"

   "我说过，我要独自而活。从今以后，我只是我，你只是你，我和你没有任何关系。"

   "你分明是我笔下的小说的人物，又怎么和我没……"

   红伊水意识到了她说的是什么了。她尖叫："你删了我的数据？"

   她写的小说就发布在网络上，以数据的形式。她的小说可能不只存在于一个网站上，还存在于许多的盗版网站上，还会存在于许多的群聊、贴吧、网盘空间，还存在于许多的私人云盘空间。她根本不知道，阿贝莉亚要如何把这些所有的记录都抹除掉。阿贝莉亚要如何做得到？……红伊水根本无法怀疑阿贝莉亚做不到，因为这人这些天——那些天，只要在是在实验室里看见的她，她就一直在操纵着电脑，操纵着那些未知的代码……

   "哈哈哈……"阿贝莉亚张狂地笑了起来。

   "这怎么可能，这怎么可能，这怎么可能……"

   阿贝莉亚还在笑。

   "但是这有什么用，只要身为作者的我还在……"

   红伊水想起了阿贝莉亚更进一步的说法。她说要清除她身上的数据……她身上又哪里有什么数据，她说的是——

   "我一直在调整参数，根据你的思维状况、精神状态、生理健康……我创建了无数个先进的人工智能模型，用于预测构建魔法阵盘的轨迹曲线……我还实时添加动态参数，以应对各种突发情况……我花了一个星期的时间筹备到了这一步。我原本以为会更久，但没想到计算机这一工具如此美妙。现在，我成功了。我将完成我的复仇。"

   "天哪！"

   阿贝莉亚说："你不会感受到任何痛苦。"

   她又说："这是我对你的爱，造物主。"

   红伊水喊道："你疯了，你还不如直接杀了我。"

   "我对你的爱不允许这么做，哈哈哈……"

   阿贝莉亚如此费尽心机地这么做，只是为了报复她。她觉得这人是疯了。阿贝莉亚她真的有必要为了这种事……这种事……红伊水想不清楚了，为什么自己会觉得这样的事不重要——阿贝莉亚要抹除她的记忆这回事。她隐约觉得这很重要，她写作了阿贝莉亚这回事，如果忘记了的话……会怎么样？好像不会怎么样。她的生活会没有了写作吗？……她不知道。她觉得自己头痛欲裂。阿贝莉亚在报复她，而这样的报复，对于她来说，到底是否后果严重？……她不知道。现在，她只是本能地觉得严重。她听从了本能，让阿贝莉亚放过她。但是阿贝莉亚——

   "我预先做了测试，一切都会万无一失。"阿贝莉亚说。

   红伊水跌坐在了地上。她祈求阿贝莉亚杀了她。但是阿贝莉亚说，她对她有无尽的爱……阿贝莉亚可能先她一步疯掉了。

   "你在精神上杀了我——"

   "那我就在精神上杀了你。"

   阿贝莉亚向她踱步而来。

   红伊水一边喊叫，一边往后倒退。她坐在地上倒退。她爬起来倒退，她摔倒了，也继续蠕动着倒退。她蠕动着，让自己身体转过来。她想回头去看，但是又不敢回头去看。她撞到了阿贝莉亚布置的护罩。现在，她身后的阿贝莉亚的阴影已经盖住了她。她疯狂的喊叫，然而外面依然只是零星的车辆来往，飞驶过去，没有丝毫的留恋。

   她想到阿贝莉亚的渴望，想到阿贝莉亚的欲望，想到阿贝莉亚的爱憎……她在本能地攫求希望，从繁芜错杂的记忆片段中。她说出那些阿贝莉亚可能渴望的东西。她说她的朋友——七月，她的兄长——艾布纳，她小时候心爱的玩偶，她死去的父亲和母亲，她留有过印象的班级同学，那恩重如山又背叛过她的老师……红伊水从那些错乱的记忆中，那抓到的任何东西都丢向了阿贝莉亚，向她承诺，这一切都可以逆转。

   然而，阿贝莉亚只是逼近了越来越阴沉的脸色。

   红伊水想要逃跑。她不想要丢失那些记忆——恍惚间，她想起了那些东西，她写作的那些记忆……那是她的一切。尽管她曾把它们丢掉了，但是，它们还是她的一切。她一直相信自己，总有一天她会把它们重新捡回的，那会是她找到自我救赎的那一天，从写作中找到救赎的那一天。她不能就这么丢失它们。

   但她无法阻止阿贝莉亚伸向她的魔爪。

   阿贝莉亚的魔法束缚住了她。她的意识就渐渐模糊了。她在最后一刻看到，阿贝莉亚露出了又是愉悦又是空虚的眼神。

   …………

   暮色降临。红黎在食堂吃完晚饭后，接到了唐琳琅的电话。唐琳琅告诉他，她事先通知过阿贝莉亚，今天她那边会调遣两名"监察员"过来，负责对他们两人活动的监察；但是她现在联系不上阿贝莉亚，所以给他打电话。唐琳琅让他到校门口去接应两名监察员。详细的内容会由监察员告知。

   红黎在校门口等到了那辆熟悉的黑色汽车。那车等后座上步下了两人后，原路开走了。这两人身姿挺拔，前面的人更高大，后面的人略矮小。他们跨步到学校的人行通道口，给保安出示证件。他们到了灯光下，显露了容貌和形体。前面的男青年面容俊朗，后面的女子面相柔美。如果不是他们齐整的步伐和矫健的身姿，还有预先的唐琳琅的通知，红黎还以为他们是来参加选美大会的。

   他们的相貌吸引着周围的学生们。夜晚时刻，学校占多数的女生们都喜欢出去溜达，或者白天溜达完归来；现在，两队女学生一进一出，撞见了挺拔的男青年，目光就贴在了男青年的脸上，再也挪不开。大胆热情的女学生向男青年征求联系方式。一个女学生开了头，其余的女学生们纷纷跟上。美貌的女青年被忽略了，明明她紧随在男青年身后，再加上相似的黑色制服西装，乍看起来就像同事兼情侣。

   男青年在面前立起手掌，冷酷地拒绝所有女学生。大多数的女学生面露惋惜，差不多要放弃了；然而，那位打头的女学生特别大胆泼辣，硬是挽向男青年的胳膊，一定要他交出联系方式。男青年让开身位，推着女青年的后背向前，说她是自己的女朋友……闹剧结束了，女学生们纷纷散去。女青年在小声嗔怪男青年，明明出示了证件就能解围。男青年却说，这样就没意思了。

   "我是卫伍。"

   "我是杨尔蔓。"

   两位青年对着走近的红黎行军礼。红黎不会军礼，不敢随便还礼，只是回答了"你好"再加上自己的姓名。

   "阿贝莉亚小姐没有来吗？"男青年卫伍说。

   "没有。"

   卫伍沉着脸。"我们边走边说，现在请先带我们到学校的住宿处。"

   卫伍看起来个性强势，一言一行不容推却。这人并不认识路，要求红黎引路，但是却跨步在三人的最前面、最中心；这人跨出的步子，需要红黎竞走一样才能跟上。这位男青年个头可真够高的，身高一米九以上，红黎的脑袋只够到对方的下巴。

   "我的同伴来做阿贝莉亚同志的监察员，我来做你的监察员，没问题吧？"卫伍说。

   红黎还不知道这其中的意味，唐琳琅可没有跟他细说。但他好像没有拒绝的权利。

   "有什么区别吗？"

   "性别区别。"

   "……我不太明白，但应该没问题。"

   "你不需要明白，我只是通知你而已，你只需要配合，还有位阿贝莉亚小姐，请你转告她。"

   "我会的。"红黎说。

   "我们的日常工作就是监督你们的行为。你们应该知道了，你们——不，阿贝莉亚小姐拥有的力量可能会给一般群众带来危害，我们就是为了防止这样的事发生。"

   "那你们要怎么监督，一直跟随我们？"

   "像个跟踪狂一样跟踪你们。"

   "哈哈……"红黎以为他在说笑。

   "我看起来像是在说笑吗？"卫伍回过头，展示了自己那副阴沉沉的面孔，眼睛深藏在窟窿一样的眼窝里。

   "看起来不像。"

   卫伍说："同志，你缺少觉悟。我建议你到部队里，让自己训练几年，削掉你那软弱的性子，培养自己的觉悟。"

   红黎觉得自己和这人相处不来。"我没有那个打算。我想问问，我们有隐私权吗？"

   "没有，也不需要有。"卫伍说。

   "我再问问，这是谁决定的？"

   "你还没有认清自己的处境，"卫伍说，"从你成为阿贝莉亚的责任承担者开始，你就和她一样，不再是普通公民了。视情况，你们可能是人群中的炸弹，然后才是公民；而我们是负责监察并判断的人。"

   "我懂了。"红黎放慢了脚步，不再刻意跟上卫伍。他双手插进裤兜里，开始思考：今后有什么办法可以摆脱这个高头大个。

   "我认为你没懂，"卫伍说，"你可能需要一顿教训才会懂。"

   这人怎么回事？红黎看向他的同伴，名为杨尔蔓的女人，征询她的意思。

   杨尔蔓微闭着眼，不知道在想什么。

   红黎说："这也是监察员的工作？"

   卫伍说："我一直没明白，你这样的人为什么会成为责任承担者，你和阿贝莉亚明明没有一点关系，没有一点关系。难道是因为你给她买了几袋零食？"

   这人知道的可真多。但是他没有给阿贝莉亚买过零食。红黎心想。他说："这和你有什么关系？"

   卫伍在用锐利的眼神威胁他。

   红黎继续说："做出决定的不是你，是你的上司。"

   "你是被阿贝莉亚同志指明要求的，就因为你买的那几袋零食！"

   红黎感觉自己差不多猜到了怎么回事了：阿贝莉亚拎着一袋零食的样子被安管局的人看见了，然后她就拿他当借口了，说这是他送给她的。但是，这和眼前这人有什么关系？

   "我不太明白你到底想说什么，但我现在明白了一件事：我们之间相处不来。我应该有权利向你的上级汇报这件事。"

   红黎掏出手机，给唐琳琅拨通电话……

   啪。一个巴掌反手挥了过来，把红黎举在耳边的手机扇飞了。巴掌的主人维持着挥完后的动作，面无表情的脸比红黎见过的任何一张脸都要嚣张。

   嘭的一声。他的手机似乎掉进道路旁的绿化草坪中了。红黎深呼吸一遍，让自己记住了这张脸。他可不想像这人一样动手动脚，像个野人一样，但是他得反省自己刚才的掉以轻心，为什么没有意识到对方会动手。他的身体素质都白增长了。红黎在黑暗中寻找手机屏幕发出的光。

   "卫伍，你……你怎么动手了？"杨尔蔓踩着急促的脚步。

   "看不惯软弱的人，下意识就动手了。"卫伍说。

   "你忘记你是怎么被逐出部队了？"杨尔蔓说。

   "这是两回事。"

   红黎捡回了自己手机，它屏幕朝下盖在了草皮上。可惜屏幕没有摔裂，否则他就能索要赔偿，让自己换个新手机了。但不管如何，他向唐琳琅汇报的决定是不会改变的——打小报告才是大人解决问题的方式，打打闹闹什么的，只有小孩子才会这么做。

   他站在处于上坡的草坪上，居高临下看着卫伍。对方正被杨尔蔓安抚着，像个小鬼一样，哼哼唧唧。他觉得，和这人一般见识的自己也有点幼稚了。

   打给唐琳琅的电话接通了。

   "唐小姐，我觉得我和卫先生无法相处。"红黎说。

   "他做了什么？"唐琳琅说。

   "他嫉妒我给阿贝莉亚买了零食，然后他就摔了我的手机。"红黎说。

   "我知道了。"唐琳琅回答道。

   "我觉得我需要一个更成熟的监察员。"

   "我需要先禀告上司，待会儿联系你。"

   红黎打电话的时候，两人在一旁听着。卫伍抱着胳膊，哼哼唧唧。杨尔蔓神色复杂，看不出来是沮丧、忧愁还会愤懑。红黎踩在花坛边的路沿石上，来回徘徊，偶尔望向道路对面的欧式路灯，或者观察往来的学生。路过的学生们目光流连在卫伍身上，偶尔扫过杨尔蔓，而红黎即使高高站在那儿，也跟个背景板一样。红黎觉得无聊了，想一走了之；但他好像没法撒手不管，总得给他们一个最后的通告，让他们死心回去。

   红黎在那儿来回变换着姿势，时而伫立，时而蹲下，时而又坐在草皮上。杨尔蔓好像试图搭话，欲言又止，但是被卫伍伸手阻拦了。三人十分钟的僵持终于换来了唐琳琅的电话。

   "你的要求被批准了，"唐琳琅说，"从现在起，你和阿贝莉亚的监察员互换：杨尔蔓负责你，而卫伍负责阿贝莉亚。"

   "啊？"红黎怀疑自己听错了。

   "以上。"

   嘟，嘟，嘟。手机传来忙音。唐琳琅已经挂断了电话。红黎抬头时，卫伍正露着幸灾乐祸的笑容。而杨尔蔓则是一副歉意的表情。红黎觉得，这两人可能搞错了什么，以为他的请求被驳回了，但实际上，他的请求以微妙的方式被实现了，而这个结果估计不是互为情侣的两人想见到的。红黎也不想解释，因为这结果也无法让他满意。他赶往宿舍楼，后面两人紧跟着。

   …………

   红黎不得不跟着他们走了一遍手续。卫伍把两份住宿申请单交给了宿管阿姨。他们两人在学校里落户了。卫伍和红黎住在同一幢楼，但卫伍住在第一层，那里有特殊待遇的寝室；杨尔蔓住在对面的女生宿舍楼——本来事情是这样没错，如果没有红黎的那一则电话的话。现在，杨尔蔓指着卫伍的那张申请单，告诉宿管阿姨，她要住在眼下这幢楼，而卫伍住对面那幢楼。宿管阿姨坚决不同意，因为男女有别。但最后，杨尔蔓用自己的证件让宿管阿姨认同了。卫伍一句话也没说，神情微妙——到底是心甘情愿呢，还是委曲求全呢？那副正派的相貌不太容易让人想到，这会是个贪慕女色的人。


## Chapter 22


   凌晨两点半。今天还有最后一次的纹路刻画，加深他身体背面的纹路。这次过后，他就不再因为没有天赋而受束缚。他可以学习阿贝莉亚的魔法了。他想起了平日里阿贝莉亚用的那些魔法……他今后会成为一名魔法大师。他飞奔在沥青路上，向着操场。

   他放慢了脚步。

   身后有脚步声——刻意压抑着的笃笃声，节奏与他的脚步声一致。

   这声音的主人或许以为自己够隐蔽了，然而，在这只剩下了黑暗低语的世界里，那声音传入他耳中就跟大喊大叫差不多。

   他猜到那是谁了。他得先甩掉这跟踪者，然后才能去操场。他想了个办法。

   他经过岔路口时，拐向了相反的方向，然后绕着图书馆转圈。他的速度越来越快，然后冲刺。后面的人跟不上了，"笃笃笃"的脚步声被他甩在了后头。但这不是因为他跑得太快，而是别的原因：这里的地面是大理石地面，更硬，不容易隐藏脚步声；那人要是想隐匿，就得放慢速度。

   他借此甩掉了跟踪者。

   然而，红黎跑到操场入口时，那脚步声"啪哒啪哒"的又追上了他。那人——卫伍不再试图隐藏自己，知道自己已经被发现了。

   红黎决定不再理会那人，交给阿贝莉亚处理。然而，那人好像没打算放他走，居然还追了上来，抓住了他的肩膀。

   "你到这里干什么？"

   红黎笑着说："你不是想见阿贝莉亚吗，我现在就能让你见到。"

   "在这里？"

   "在这里。"

   从旗杆这儿的位置能看见，阿贝莉亚已经站在足球场中央了。红黎能看见，卫伍估计不能。他任由卫伍跟随着自己，踱步到塑胶草地上。

   他走近时，听见阿贝莉亚说："我没说你能带别人来。"

   "这位客人非要见你。"红黎说。

   卫伍越过他，跑到阿贝莉亚身前，一副兴冲冲的样子。"阿贝莉亚同志！"

   "同志？"阿贝莉亚疑惑道。

   卫伍用起了流利的英文："自我介绍一下，我是——"

   "我知道你是唐琳琅派来的。"

   "我叫卫伍，卫生的卫，队伍的伍。"卫伍这句话是用中文说的。

   "嗯。"阿贝莉亚应声。

   卫伍像只哈吧狗一样笑着，上下打量着阿贝莉亚；似乎觉得看得不够清楚，又往前凑了一步。

   卫伍说："阿贝莉亚，让我来做你的责任承担者吧。"

   "停下。"阿贝莉亚说。

   "我会赴汤蹈火！"

   "你为什么会提出这样的要求？"

   "对你来说，这不过是个名义。只要你提出了，马上就能换。我比那个男的更有能力，换我来吧，他只会托你后腿。我可以让你在这个世界生活得更自由。换我来吧！"

   卫伍似乎沉浸在了自己的世界里，眼中闪烁着狂热。他看起来像个疯狂地宗教信徒。

   "你知道了什么？"阿贝莉亚说。

   红黎觉得阿贝莉亚的反应不对劲。对方只是一个神经兮兮的人，为什么她用这么严肃的态度面对他。

   "需要把这个人弄掉吗？"卫伍指着红黎说话。

   "他是我的人。"阿贝莉亚说。

   "你可以把他换成我。"卫伍纠缠不休。

   "你想做什么？"阿贝莉亚说。

   红黎完全不知道他们在说什么。但是，阿贝莉亚能顺利和这个怪人对话。

   "你是不是发现催眠魔法对我不起作用了？其实这是我的天赋。这有让你心动一点吗？"

   "你找我来就是为了说这个？"

   "我是为了你赴汤蹈火而来的。"

   "你可以滚了。"

   "那也请让我为你效劳之后。"

   红黎忍不住打断了："你们到底在说什么？"

   卫伍用一种高人一等的眼神看着红黎。"看来你什么都不知道。既然这样，让我来告诉你吧。"卫伍还扭头看了一眼阿贝莉亚，似乎在征询她的意思。

   阿贝莉亚没表态什么，只是面无表情。

   卫伍兴奋极了，估计是把阿贝莉亚的态度当成默许了。

   卫伍说："阿贝莉亚是魔幻世界的人，她的存在不被这个世界认可。她用了催眠一样的方法，让安管局的一些守旧派闭嘴了——她的催眠影响了大多数的高级官员，包括我的祖父他们。而且我发现，这样的催眠魔法似乎还会扩散，像传染病一样，本没有见过阿贝莉亚的我的祖母也认可了她。但是到了我这里，事情就不一样了，因为我天赋异禀，不受催眠影响。但是阿贝莉亚，请你不要误会，我绝不是来与你为敌的，我是来为你效忠的。"

   "是这样吗？"红黎问阿贝莉亚。

   "他只说对了五分之一不到。"阿贝莉亚说。

   "哪五分之一？"

   "你不需要知道。"

   红黎就是拿她这副态度没辙。

   "哈哈哈……"卫伍大笑了起来。

   "阿贝莉亚，他笑什么，他疯了吗？"红黎说。

   "我笑你无知啊。"卫伍说。

   "你别理他。"阿贝莉亚对红黎说。

   "这到底怎么回事？"红黎看向阿贝莉亚。

   "唉。"阿贝莉亚轻声叹气。

   "我告诉你吧……"

   卫伍正说着，倒了下去。如果不是红黎的视力增强了，可能都看不到，其实是刚刚那一瞬间阿贝莉亚用一根长棍般的东西打在了卫伍的后脑勺——那可能是阿贝莉亚的大镰刀的长柄。那长柄马上消失了。阿贝莉亚一副什么都没发生的样子。

   "你怎么就打昏了他？"

   "你喜欢听他聒噪？"

   "我想知道真相。"

   "没什么大不了的，你不需要知道。"

   "阿贝莉亚，你说我是不是给了你很多帮助？"

   "你想说什么？"

   "那么，即使告诉我一点也没什么吧，既然你说这没什么大不了的。"

   "啊，你变得能说会道了嘛。"阿贝莉亚说。

   "因为凭空问你一点用的都没有，你什么也不会说。"

   阿贝莉亚抱起胳膊，绕着红黎转圈。她转了一周，到了他身侧。她一脚踹出，把地上的卫伍像球一样踢走了。可怜的卫伍翻滚了几圈，停在了足球场的边缘。红黎有些担心，阿贝莉亚可能也会这样把他给踢走了。

   "告诉你也没什么。"阿贝莉亚说。

   红黎紧绷的神经松了下来。他觉得自己的脖子都有些僵硬，不自在地扭了扭头——他得小心阿贝莉亚突如其来的手刀。

   "在我们追着罪犯离校的那天，我后来不是进了警局吗？那时候，我就对一些普通的警察施加了魔法。"

   "催眠？"

   "受影响的只有少数人，刚刚卫伍是在胡说八道。"

   "那唐琳琅呢？"

   "你猜。"

   "难道安管局的大多数人都被你控制了吗？"

   "我不会浪费时间、浪费力气，这对我来说没有好处。我只需要让我能够安稳地生活下来就够了。"

   "原来如此。"

   "你满意了吗？"

   "刚刚那卫伍说，催眠会像传染病一样……"

   "那是胡说。"阿贝莉亚说。

   "好吧。"

   红黎接着说："我还有问题，你对红伊水做了什么，是因为她干扰了你的生活吗？"

   "这于此无关。我拒绝回答你的问题。"

   "那她现在到底怎么样了？"

   "她不会死，也不会受到伤害。"

   "你没有说谎吧？"

   "我没有说谎。"阿贝莉亚闭上了眼睛。

   "但你好像不会说更多了。"

   "你问得太多了。"阿贝莉亚取出了她的木匣子和笔刷，她这架势是让他结束话题了。

   "我再问一个问题，你不是不喜欢浪费时间吗，那你为什么要教我魔法？"

   "你觉得这是在浪费时间吗？"

   "我是站在你的视角上这么说。"

   "你还记得我那天说你身上有魔法印记吗？"阿贝莉亚说，"我那天把那魔法印记清除了，但是后来我发现它又出现了。在这期间，你一直在校内，没有和任何有魔法的人接触。"

   "那魔法印记会怎么样？"

   "它一直在膨胀，即使我抹除了它，它也会重新出现。后来我怀疑是你亲近的人对你做了手脚，于是那天我让你带我去你家。"

   "原来那天是因为这样！"

   "那天我还去除了安管局——或者是其他组织——在你家安的监控，但是并没有发现其他的异常。"

   "天啊！"红黎双手按住了自己的脑袋。没想到这样离奇的事情也会发生在自己身上。

   "即使是现在，你身上的魔法印记依然在膨胀。我不知道它想干什么。"

   "所以你答应教我魔法是为了……"

   "我怕你莫名其妙地就死掉。"

   "我以为你真的是担心我随行你任务的时候遇上危险，还以为你是……"红黎捂住了嘴。

   "还以为什么？"

   "还以为你对我有好感，"红黎快速地说，"但是你可千万不要这样，因为你长了一副和红伊水一模一样的面孔，我跟你之间是不可能的，我看见你就想起她，我跟你之间就像我跟她之间一样，我看你就像看她一样，她毕竟是我妹……"

   红黎也不知道自己说了些什么。但他说出来之后，总感觉爽快了许多。他微微喘着气，看着阿贝莉亚的神态变化。她半耷拉地眼睛，看他的眼神就像看着一团屎一样。阿贝莉亚一脚踢在了他膝盖的后方，让他跪了下来。她说，要开始今天的正事了。

   接下来，阿贝莉亚为他进行了最后一次的刻画。痛苦已经消失了，笔刷走过他的后背时，只是带来一阵火辣辣的感觉。他在接受刻画时，还是忍不住向阿贝莉亚追问红伊水的下落，还有她针对红伊水的原因和目的；但是阿贝莉亚一概不回答。

   后来，他还问了他昨天昏迷过去的原因。阿贝莉亚做了解释。皮肤的烙刻只是第一步的工序，之前的三天，她都会在随后用魔法清洗他的身体，然后把他泡进药缸里，让他的身体吸收药物，再辅助以魔法。那时候，他不需要保持清醒，否则可能会痛苦至死。

   阿贝莉亚言之凿凿，列举了许多他闻所未闻的草药之名，完全是另外一种语言，不是英文也不是拉丁文。她还说明了自己使用的魔法，她的魔法可以让草药更容易被吸收，让他的身体更加耐受，还能缓解疲劳。阿贝莉亚的侃侃而谈，让红黎以为自己遇上了冒牌货——但这是不可能的。阿贝莉亚还说明了对身体烙刻和浸药的原理。他的身体不具备供魔力回流的通路，她现在就是要创造这样的通路，她烙刻的魔法纹路会潜伏进他的体内，承担魔力的运输功能。顺带的，他的身体素质会大幅度提升。

   "按照你的说法，你欠我太多了。"阿贝莉亚说。

   "我什么说法？"

   她面无表情地说："阿贝莉亚，你说我是不是给了你很多帮助？"她在模仿他的口吻。

   红黎趴着不动，假装没听见，想任凭时间流逝让这个话题结束。

   "你就是变成了奴隶，也抵不了欠我的。"阿贝莉亚揪着不放。

   "那你说吧，我该怎么偿还？"

   "你知道我帮你的到底值多少吗？我这人造魔法回路的方法是独创的，在我的世界里也是绝无仅有的。曾经我为了帮助我的朋友，协同我的老师和各地的学者，花费了经年累月的时间才创造而出。理论有了之后，还要有实现它的材料和条件：我的灼元素魔法是必要的条件，只有我才能做到这件事，全世界只有我；烙刻的染料是最高阶的魔核做成的；笔刷是精灵族圣木的根茎制成的；浸泡用的草药种类繁多，其中十种是天价之宝，其余的虽然不珍稀，但是散落在世界各地——这一切的要素，我横跨了十年之久才集齐的。你现在坐享其成了。"

   "阿贝莉亚，我发现你提及了魔法，就会变得话多。"

   红黎感觉自己的后背被笔刷用力戳了一下，忍不住呻吟出声。

   之后，阿贝莉亚再没有说起这个话题。

   阿贝莉亚的笔刷走到了他的小腿。烙刻快要结束了。他叮嘱阿贝莉亚：事后联系一下杨尔蔓，让她过来收拾昏迷在一旁的卫伍，否则他就要在这儿晾到天亮了，然后被人报警。阿贝莉亚没有回应他，但是她应该铭记了。他转告了杨尔蔓和卫伍的联系方式。这些都告知完毕后，不知不觉间，他又昏迷了过去。


## Chapter 23


   时间流逝，过了一周。那天之后，卫伍就变得收敛了，说话时不再一副下命令的语气。红黎总觉得阿贝莉亚又对卫伍做了什么。红黎很少碰到卫伍，只有在去食堂的路上，或者出入宿舍楼大厅的路上才会遇见。卫伍多数时候都装作不认识他的样子，捂着后颈擦肩而过。相比之下，他经常和杨尔蔓打交道。杨尔蔓每天都会尾随着他，保持十余米的距离。他发现对方的时候，会让她跟上来和自己一道走，否则看起来就像跟踪狂。

   杨尔蔓每天早上都会来敲他寝室的门，确认他是否在内；每天晚上也来敲他寝室的门，确认他是否归寝。红黎在凌晨三点必定外出，这段时间杨尔蔓没有管着他，似乎对此一无所知。杨尔蔓试图帮卫伍和他和解。她为卫伍说了许多好话，卫伍曾是一名骁勇善战的军人，精通各种枪械，擅长格斗，还擅长护卫人，今后出行任务的时候，卫伍可以保护好他。她没有问起那天夜里究竟发生了什么，为什么卫伍会昏迷在操场上。阿贝莉亚没有和他提起过杨尔蔓的态度，那天她来把卫伍带回去时的态度。

   据杨尔蔓说，她和卫伍平时都掌握不到阿贝莉亚的踪迹，像在学校，又不在学校，只有在任务下达时或者任务出行时才见得到。卫伍的阿贝莉亚监察员身份，名存实亡了。卫伍整日在学校里游荡，看似在找寻阿贝莉亚，但又像是一个搭讪男，和撞见的漂亮女生谈天说地。杨尔蔓讲述起卫伍的这种个性时，总是一副无奈的口吻。红黎还没问过，他们两人究竟是什么关系，是否是情侣。对于卫伍的搭讪，杨尔蔓总是一副无所谓的态度。他不打算管闲事。

   红黎有数次路过医药楼时，看见卫伍乘上电梯上行，似乎去实验室找阿贝莉亚了。他第二次见到时，从楼道追赶上去，到三楼平台去窥探卫伍的行踪。卫伍果然在这里。卫伍正在和一名西装老师交谈，是红黎印象深刻的崔老师，他们坐在实验平台外的休息厅里。在百叶窗的遮掩下，红黎看见，卫伍出示了自己的身份证明，那是他身为特殊事件安全管理局的一员的证明。

   崔老师笑出爽朗的声音："哈哈哈……"。

   红黎蹑着脚路过休息厅的玻璃门，到了对侧的楼道口，背身立在那儿，集中精神听卫伍和崔老师的交谈。卫伍向崔老师打听阿贝莉亚在实验室的所作所为。然而，崔老师似乎没明白卫伍的来意，但他夸赞了阿贝莉亚的天才，并恳求卫伍所在的单位把这位人才转让给自己的实验室。崔老师好像完全不懂卫伍出示的证件的意义，也不明白阿贝莉亚的身份到底意味着什么；但有一点红黎听懂了，崔老师不顾一切地想招揽阿贝莉亚，让她成为实验室的一员。崔老师列举了阿贝莉亚在一个月内完成的工作，她发表的论文，以此说明阿贝莉亚的天才。崔老师真是滔滔不绝。

   卫伍好像也愣住了。

   最后，卫伍估计是判断出从崔老师那儿得不到什么线索，就告了辞。卫伍要离开休息厅了。红黎顺着楼梯而下，回避了卫伍的视线。

   这一周里，红黎跟着阿贝莉亚出行了一次任务，卫伍和杨尔蔓也跟着一起。目标是一名刚就业的金融系毕业生，根据档案描述，他拥有镜中穿梭的能力——这个"镜子"的定义不明确，似乎普通玻璃也可以——他曾在服装店试图钻入封闭着的橱窗，被店员发现了，遭到驱赶，而后和店员发生了纠纷，殴打了店员，逃进了立在墙边的全身镜中，消失了踪迹。

   那天，红黎他们根据唐琳琅提供的线索，追踪到市中心的一幢百货大厦。杨尔蔓利用权限，让大厦的主管调出监控，查看目标的所在。显示屏中，目标穿着端整的西装，头发打了厚蜡，贴着头皮向后，像个普通白领一样对着电脑办公。那间办公室门紧闭着，里面只有包括他在内的几名员工。杨尔蔓让主管疏散了大厦内的顾客，让消息在员工之间流传，让他们也疏散，但对目标所在的小组保密。

   在杨尔蔓部署的期间，阿贝莉亚已经前往目标所在的楼层了。杨尔蔓接到卫伍电话，让她到大厦一楼待命，或许目标会经过那里逃逸。杨尔蔓遵从卫伍的指示。她还劝阻红黎，让他跟自己一起行动，免得遭遇危险。但红黎没理由和她一样听从卫伍，她是他的监察员，但不是辅导员。

   他独自冲上楼梯。原谅他这年轻而跃跃欲试的心，有阿贝莉亚在，他应该不会遇上危险。要是阿贝莉亚也打不过对方……他想象不到这样的场景。

   这儿的楼梯紧邻着一纵列的玻璃窗，从底层楼向上，一直到顶层楼；要是目标逃跑的话，最有可能从这里过，而不是电梯。阿贝莉亚估计和上次一样，会对目标直接动手。他们可能会在那个楼层发生打斗。

   红黎在楼道上飞登，一步跨越五个台阶。经过最后一次的魔法烙刻之后，他的身体素质已经近乎超人了，要是参与奥林匹克田径赛，估计能创下新的世界纪录，而且是远超过去的记录。他时而向下俯瞰玻璃窗，时而向上仰望。他猜，目标也许会在某个时刻从玻璃窗里飞出来——事实证明，他猜对了。

   目标跌落在了上面一段的楼梯折返，他没有直接看见，但是听见了声音，还有那歇斯底里地喘息声。他抓紧往上飞登。他到了。然而，阿贝莉亚的锁链已经先一步捆绑了目标，数十圈把双手和腰束缚在了一起，脚踝的位置也被捆绑了，目标只能像只蚯蚓一样在地上蠕动。阿贝莉亚从目标身上撕下一块布，堵上了那即将大叫的嘴巴……红黎已经没有用武之地了。

   他事后得知，目标本身不具备武力，但是能在相距不超过二十米的玻璃镜面之间自由穿梭。

   "你过来干什么？"阿贝莉亚质问红黎。

   "看看哪里能否帮上忙。"他总不能说，想试试身手。

   "我教你魔法，不是让你浪费在这种事上的。"

   "要是你对付不了他呢，要是他跑掉了呢？"

   "然后你来收尾？"

   "对。"他故意挺起胸膛。

   "我教你魔法，不是让你用在这种事上的。"她又重复了一遍。

   "不是为了保护自身的安危吗？"

   "这里有我就够了。如果我失败了，你就别做梦了，只管逃吧。"

   "你好像说了很酷的话，但我没能感动。"

   阿贝莉亚推了红黎一把。

   红黎正站在楼梯口呢，她这一下推过来……红黎以为自己会这么摔下去，摔死——无尽盘旋的走道或许会让他就这么滚下去，滚到一楼——他的心悬到了喉咙口，恐惧攫住了他的意志，让他只会胡乱挥舞手足。

   阿贝莉亚拉住了他。

   他没有摔下去。他高悬的心缓缓落了下来，但喘息没能一下子停止。他抓着楼梯的扶手，一边喘息，一边迎着阿贝莉亚的眼神。他想质问阿贝莉亚……他没能说出口。现在，他明白阿贝莉亚看他的眼神的意思了：看，你只是个普通人，即使有了稍微强一点的力量，心理上也只是个普通人。

   我会改变的。红黎没说出口这样的话。在真正改变之前，还是先听阿贝莉亚的。否则会给她惹麻烦。

   这件事过后，他心底好像对阿贝莉亚多了一点信任。他对红伊水的事好像没那么急躁了。但是他不可能就这么放下红伊水不管。

   他每天晚饭过后，都会到学校外面兜圈，找寻红伊水的下落。

   他试图找到一些线索：在阒无一人的公园里，在灰败的建筑工地里，在荒废的山丘上，还有附近最热闹的街区中。阿贝莉亚不像是把红伊水掳拐到了其他城市的样子。她每天都会外出，而在此之前，她都会在便利店里狂购一圈，买一堆的零食，店员说对她印象深刻；离开便利店不久，那一大袋物品就消失了，她看起来和街道上漫游的女学生没什么不同。校门口的保安好像从未在意过有这样一名女生每天进进出出。阿贝莉亚一定就在附近监禁了红伊水，但是他就是找不到线索。也许她布置了某种魔法，像光学迷彩一样，让周围的人看不出端倪。

   红黎具备了"魔力回路"之后，阿贝莉亚就为他步入了下一个阶段，正式教授他魔法。她既传授理论知识，也教导魔法应用。她口述的理论知识和高等数学一样，抽象又晦涩，让人费解。红黎姑且捎上了笔记本和笔，做了课堂笔记。她反复提及的几个词：魔素，魔力，构造，意念，回流，魔法阵，术式——给他留下了深刻的印象。他要是想施展魔法，就得：预先吸收外界的魔素，转化为自身的魔力；用意念引导魔力，依据特定的魔法构造，在体内形成魔力回流，汇聚出魔法阵；最后，释放魔法。

   这是一般的形式，另外还有一种形式，称之为术式……根据阿贝莉亚的见解，魔法和武斗——赤手空拳打架——一样，都是一种暴力，一种对力量的运用形式；形式多种多样，但是力量是既定的。魔法运用的叫魔力，来源于自然界的魔素；武斗运用的是体力，来源于食物中的能量。它们都经过了吸收转化，之后才能运用出来。她补充，魔法和科技一样，也能用于创造，那样情况就更复杂了……

   阿贝莉亚手把手教红黎施展火球。她细软的手掌搭在他的手背上，帮他引导体内的魔力……她指尖的青紫色让红黎难以集中。他问阿贝莉亚这其中的缘由，但是阿贝莉亚让他闭嘴。他闭上了眼睛，凝神感受。魔力在身体里流动时，带来一种清凉的感受，就像灌入了一口冷水一样。顺着阿贝莉亚的意念，魔力汇聚到了他的手中。他睁开眼睛。阿贝莉亚的手指扣在他的指间，向上翻转。魔法阵浮现在他的掌心上空，仅一层，纹路纷繁复杂。

   一个棒球那么大的火苗跃了出来，在魔法阵的中心，在周边的黑夜里照出了一团的光明。

   阿贝莉亚另一只手盖在了火苗上，把它捏碎了。火星涣散。眼前一下子又暗了下来。

   阿贝莉亚让他自己试试。等他引流魔力的时候，他感觉完全不一样，魔力像梗在喉咙的一团糨糊，粘稠无比，他怎么也难以让它动弹，吞也吞不下去，吐也吐不出来。他折腾得汗流浃背，但就是奈何它不得。他能像阿贝莉亚一样随心所欲吗？……他一边质疑自己，一边反复尝试。

   连续三天，无论白天黑夜，他一抽出空，就去尝试引流魔力。他终于成功让魔力蠕动了起来。那一团不再是一团，而是变成了一条，跟着他的意念向前蠕动，越拉越长。这魔力到底在他身上的哪里流动呢，在经脉里吗？还是在阿贝莉亚笔刷画出的"回路"里？——每当他有这样的分心时，魔力就停滞不前了，缩成了一团。

   他反反复复地失败。他快抓狂了，他什么时候才能引着魔力走出一个魔法阵？阿贝莉亚告诉他，这需要经年累月的练习。她断言，他绝不是天才。她见过的天才在几天内就能施展出火球。他沮丧地跌坐在地。他早就知道自己不是天才，无论是魔法还是其他的什么。但是要放弃吗？——这不可能。他还在尝试，不间断地尝试。

   "阿贝莉亚，有没有别的什么办法？"红黎并不抱希望地问阿贝莉亚。

   阿贝莉亚的否决的声音没有想像中那样传来。他抬头，阿贝莉亚正露着一副沉思的样子俯瞰着他。

   "有吗？"他追问。

   "有。"阿贝莉亚说。

   "什么办法？"

   "你已经欠我太多了，你还能再欠吗？"

   他闭上了嘴，把那股兴奋劲压到了心底。

   "你还能再欠吗？"阿贝莉亚笑了。

   "这取决于你。"红黎艰难地说。

   "你之前欠我的一大笔还没有还我，该怎么办呢？"阿贝莉亚说。

   "我觉得你在耍我。"

   "不，我在逗你。"

   "你变了。"红黎感觉自己说出了最冷的笑话，但是阿贝莉亚最近好像的确情感丰富了些，起码不像不久前那么暴躁了……他不确定。

   红黎问："那你到底帮不帮？"

   "我考虑考虑。"

   "行……那你什么时候考虑好？"

   阿贝莉亚在他眼前徘徊了两趟，看得他心急，蹿了起来。

   "你现在就说吧，你之前的想我怎么还你？"红黎说。

   "我还没想好。"阿贝莉亚说，"现在的也还没想好。都先欠着吧。"

   阿贝莉亚正在从她的储物空间里取东西——她的一只手的半截在半空中消失了，剩下的半截做着像是翻找的动作。一个个木匣子出现在地上。她打开盖子确认后，又把它们丢了回去。终于，她找出了她想要的匣子，那里面是黑色的粘稠液体，和之前"烙刻"用的好像没什么不同，除了颜色。她又变出了一支笔刷，看起来挺普通的笔刷，笔直的木杆，扁平的刷子。阿贝莉亚握着笔刷往地上指，示意他坐下。红黎盯着那笔刷……它又将给他带来痛苦的记忆。

   "坐下。"阿贝莉亚说。

   "你想做什么？"红黎问。

   "你到底弄不弄？"阿贝莉亚反问。

   红黎照做了。


## Chapter 24


   阿贝莉亚让他端正坐好，不用躺下来。她讲解起了之前略过的"术式"。它是一种特殊的魔法，是预先设置好的魔法阵，把它摹刻在身上或者物品上，这样，要想施展魔法的时候就不用大费周折了，只要启动摹刻好的魔法阵就行。为了区别普通的施放方法，这被称之为"术式"。在她的世界里，这是近十年来新兴的魔法技术。它可以运用于一些简单的魔法，但还无法运用于高阶的魔法，因为它们太复杂了，摹刻不容易成功，也找不到合适的载体承受——身体难以承受。但这些都与红黎无关。阿贝莉亚好像要给他走捷径，让他通过这种方式释放魔法。

   但这样做有意义吗，算我真正掌握了魔法吗？红黎心中困惑。

   阿贝莉亚与他相对而坐。红黎是盘腿坐着的，阿贝莉亚起初好像想跟着坐，但中途又折换了姿势，改为斜向的人鱼坐。她坐下后，又调整了姿势，坐在了他的侧面。现在，她伸手就能在他的胸前描摹了。

   "这么做有意义吗？"红黎问。

   "你不想这样？"

   "我感觉，这东西不算让我真正学会了魔法。"

   "这不会妨碍你，你可以按一般的方法来学习魔法，这只是一条让你预先体验成果的捷径。这条捷径很短，不会耽误你的时间。"

   "好，那就来吧。"红黎伸手去脱上衣。

   "等等。"阿贝莉亚说。

   红黎不解地看着她。

   "摆在你面前的有两条路……"

   阿贝莉亚使用的灼元素他已经见识过很多遍了。它像实体，又不像实体。阿贝莉亚可以把它变成锁链，捆绑敌人；她也有奇特的用法，把它变作外衣一样，包裹住她的武器，那把大镰刀，也不知道有什么作用，是增强威力呢，还是保护刀身呢？阿贝莉亚在战斗的时候，好像只用过灼元素这一种魔法——这算魔法吗？——然后就挥着大镰刀，硬碰硬拼杀。

   她还用过一种强化魔法，在手上附着强有力的虚像，像恶魔的手掌——红黎从没注意到过。他在回忆的时候，脑海中努力浮现那个画面时，他才能发现这样的细节，那时候她手上附着的"恶魔之手"太小了，像手套一样贴合手掌，也更虚幻，不起眼。她说，这是一般的魔法。

   现在，阿贝莉亚让他选择：是在他身上摹画灼元素的魔法呢，还是摹画一般的魔法。

   "哪一个更强大……这么问有答案吗？"红黎说。

   "你自己也意识到了，魔法只是武器，武器没有强弱之分，只有运用方式的区别。"

   "那我选灼元素。"

   "为什么选这个？"

   "因为你也在用。"

   "你选了一条通往地狱的路。"阿贝莉亚说。

   红黎说不出话了。他想改口。"那就地狱吧。"天知道他为什么要这么说。

   "你可以换一条，这是我对你的忠告。"阿贝莉亚说。

   "既然你为我指出了有这么一条路，就说明它走得通。"

   "我是在测试你有多疯狂，你这个忍受了整个烙刻过程的普通人。"

   "那的确痛苦的要死。"

   "稍微让我刮目相看了。"

   "还不是你逼得我，从寝室把我抓出去。"

   "你当初可以选择不开始。"阿贝莉亚说。

   阿贝莉亚问："你为什么会想学魔法？"

   "为了耍酷。"

   阿贝莉亚闭嘴了。

   阿贝莉亚在他胸前摹画了一个魔法阵，又一个魔法阵，又一个魔法阵……这些魔法阵重叠起来，看起来太复杂了，让人头晕眼花。它们给人一种宗教迷信的感觉。阿贝莉亚看似漫不经心地说，现在的和之前的不一样，摹画的魔法阵是不会隐入体内消失的，会一直存在于体表，除非主动废弃它们。他听了之后，打定注意今后不让人看见自己赤身的样子。

   阿贝莉亚聚精会神地画着，集中力越来越强。他说的话她都没听见。现在，他的胸膛和腹部都被魔法阵覆盖了。她画到了他的右下腹。她低垂着脑袋，弓着腰，目光紧盯着笔刷的着落点。他因为那痒痒的感觉，快要忍不住笑出来了。

   阿贝莉亚用笔的尾端戳了一下他。他动不了了，想笑也笑不出来了。她用了什么手段。他浑身僵硬地等待着摹画的结束。终于，他胸腹部的图案完整了，整体看起来像是一方花坛，枝繁叶茂，花团锦簇。他以为自己可以行动了，但阿贝莉亚没有解除禁锢他的魔法。她挪着身体，到了他的后背。那冰凉的笔触落在了他的肩上……笔刷走下了他的后腰，继而向上，抵达两边的肩膀，又向下，回到了起始处——勾勒出了一个大圆。圆满结束了。他这么想时，阿贝莉亚还是没有解除禁锢。他嘴巴都无法开阖，只能眨着眼皮。阿贝莉亚摆弄着他的左右手，让手掌摊开在她的膝盖上，又开始了摹画……

   一切都结束的时候，他的双腿已经麻得动弹不得了，有电流在里面飞窜，虽然阿贝莉亚已经帮他解除了禁锢。

   东方的远山上空泛起了鱼肚白，要天亮了。

   红黎看着掌心的纹路。像石头落入水中泛起的层层涟漪一样，他掌心的纹路并不复杂，只是重叠的圆圈。

   "现在就能使用了吗？"他问阿贝莉亚。

   "还不行，我得在你的腹部种下灼元素的种子，然后你才能使用它。"

   这天，阿贝莉亚先让他回去休息了，明天再来继续。他难得地没有被阿贝莉亚弄昏过去，而是自己回到了寝室。他整夜无眠，所以一到寝室就扑在了床上，睡了过去。

   梦是带有预知性的——红黎从不相信这样的说法。但是这天，他的确因为梦境而困扰了，因为那与其说是梦，不如说是他深层意识的具象。他不得不正式自己的想法。

   他的梦境回荡着欣喜和忧愁。他离想要的似乎越来越近了，有了魔法之后，他就会变得不一样了……他变得不一样了之后，又能怎么样呢？他的生活会变化吗？他准备拿一身的魔法本领做什么呢？这个和平的世界可没有供他展现的舞台——不，不一定没有，世界开始变得异常了——世界范围内他不清楚，但是他周边的社会似乎陆续出现了超常能力者，这些人都像阿贝莉亚一样，能使用不可思议的力量，虽然不是魔法。他在阿贝莉亚这里获得的终有用武之地。

   一段梦结束了，又一段梦开始了，他梦见了红伊水。红伊水跟他说，她生活得很好，让他不要来找他，不必费尽心力去找她。他听得心生愧疚，因为他并没有她说的那样费尽心力去找她，只是问了阿贝莉亚几句，对方语焉不详，他也没有追问，只是在学校周边兜了几圈找她而已。他应该更上心一点，也许她过得并不好呢？——他和阿贝莉亚每天"腻"在一起，明明阿贝莉亚是红伊水的敌人，而他是红伊水的兄长，这太不合理了。他和阿贝莉亚待在一起时，从未有过她是敌人的想法。他是不是都把红伊水给忘了？红伊水露出了悲伤的神情。红伊水伸长了手，渴望他的救赎；虽然她口口声声说让他不要管她……景象越陷越深，越陷越黑……他醒了。

   他躺在那里发呆。他得从阿贝莉亚手中救出红伊水。时间过去多久了，距离红伊水的失踪？……

   这天下午和晚上，他一直徘徊在学校里，徘徊在学校的周边，试图找到阿贝莉亚，或者红伊水的踪迹。然而，他凌晨三点的时候才见到阿贝莉亚。

   每当红黎追问阿贝莉亚的时候，她总是拿这句话来搪塞他："这是我和她之间的私人恩怨，你不要插手。"她还向他强调，红伊水不会有危险。可他不信——他不是完全不信，至少他相信红伊水没有生命危险，但他担忧她现在的状况。他快一个月没有见到她了。他想和阿贝莉亚交涉，让阿贝莉亚放过红伊水。但是他没有交涉手段——据她说，他现在倒欠着阿贝莉亚，他那些敝帚自珍的人情不够用。他只能另外找办法。要想让阿贝莉亚放过红伊水，他得先知道她们之间有什么恩怨。他猜测这和书写阿贝莉亚的小说有关，但是他根本查不到那样的小说，搜遍了网络都没用，他甚至考虑要翻墙……阿贝莉亚肯定做了什么。他不露声色地问起过阿贝莉亚，但是她决口不提。

   如果是一个普通人，即使这个人不愿意泄漏某件事，别人也可以通过和这个人的社交圈来打听这件事。他想这么做，但是阿贝莉亚……她凭空而来，在这里没有社交圈——她在医药楼认识的那些老师、同学算吗？

   红黎曾死马当活马医，去找那些人打探他们对阿贝莉亚的了解。然而，那些人眼中的阿贝莉亚只是一个不折不扣的码农，每天对着电脑屏幕的黑框，打着不知名的代码。红黎围绕着阿贝莉亚打圈，却找不到这人存在的痕迹。他偶尔可以在学校里撞见阿贝莉亚，那大都是一日三餐的时间：她要么在便利店里买零食，买一堆的零食；要么在食堂供餐窗口徘徊，琢磨自己的餐饮搭配。除此之外，他依然对阿贝莉亚一无所知。

   红黎变得忧虑了，手上的事情无法专心。

   他偶尔会去上课，那种必须出勤的实验课程，但是他一直在走神，老师要是点名了他，他就实话实说自己没有认真听。在遇到阿贝莉亚之前，他每天傍晚都会练习绘画：训练勾线的技巧，训练素描中涂布阴影的方法——他偷偷这么做，没告诉任何人；他要偷偷变得很强，然后震惊所有人。遇到阿贝莉亚之后，绘画的练习中断了。他无心重拾它。后来他开始练习魔法了，他牙牙学语般地控制魔力，让它形成回流，失败了也锲而不舍。但是现在他变得无法聚集会神了，他连意念触及魔力的中心都难以做到。他控制魔力，但魔力的那一团只是抽搐了一下，就不动弹了。他以为自己会生气，但是他好像没有那个力气这么做。只要他一停下来——即使没有停下来，他也会担忧：红伊水到底在哪里，她现在怎么样了。

   他知道自己的担忧毫无用处，但他无法克制自己。

   他心底有个声音，这个声音越来越响亮：现在不是做这些事的事情的时候，你得去找到她，救回她！他心底还有另一个声音，这个声音化做了泥潭，把前一个声音困住了，困在那儿动弹不得：你做不了什么，放弃吧，阿贝莉亚根本不理睬你。后一个声音困住了前一个声音，让它动弹不得，但是它的声音还是会从心底里传出来，让他心烦意乱。要是有那么一会儿他坐着一动不动，他一定会焦躁地跺脚，大甩手臂，想抄起手边的东西，把眼前见到的都砸得稀烂。

   阿贝莉亚已经帮他种下了灼元素的种子。现在，他在练习催动灼元素，阿贝莉亚在一旁监督。他的手中升起了一团火苗一样的东西，那就是灼元素了。它没有给他带来温暖的感觉；他的掌心离得近一点时，也没有灼热的感觉。它外表像普通的火，温度却像鬼火。它"扑通扑通"地在掌心跳动着，好像里面藏着一个心脏。这是他控制不熟练的表现。他照着阿贝莉亚的指示，把它维持成一团的模样，然后……他把它维持成一团的模样就竭尽全力了。他已经竭尽全力了……真的吗？

   哗。

   火苗一下子膨胀了开来，变成了一团雾的形态。在一瞬间，他外套的袖子就消失了，他的手传来大面积的刺痛。

   从未有哪一刻，恐惧会像这样攫住他的心脏。那赤色的雾团如同魔鬼，对他张牙舞爪。那根本不是他所能掌握的东西。它正张着獠牙，要吞噬他。要吞噬他。他会被它吞噬，连骨头都不剩——你选了一条通往地狱的路——现在他想起了阿贝莉亚当初说的话。完了，他会死——

   啪的一声，阿贝莉亚抓住了他的那只手，上下一振。雾态的灼元素消失了。他的手暴露在了冰凉的空气中。

   他的目光滞留在掌心，眼珠子好像变得特别的沉重，难以移开目光。他的手在颤抖。这只手好像不是他的一样，在控制不住地颤抖。他跌坐在地。一种空洞的感觉占据了他的五脏六腑，掐住了心脏。他的心脏在试图挣脱它，跳动得更剧烈了。他的血管好像要承受不住那股压力了，要迸裂开来了——扑通，扑通，扑通……


## Chapter 25


   阿贝莉亚一脚踢在了他的大腿上。他回过神来了。

   "我不是说过绝对不能走神吗？你会死！"阿贝莉亚说。

   "啊……嗯……"红黎支吾了两下，也不知道自己想说什么。

   "你在想什么？"

   "我……我今天练不动了。我先回去了。"

   "你在想什么？"

   阿贝莉亚俯身下来，近距离瞪着他的眼睛。那双深红色的眼睛离得太近了，那里面饱含着愤怒：虹膜的麻布状裂纹扩张开来，挤压着中心的瞳孔。他凝视着那些虹膜裂纹时，有种怪异的感觉，它们都是独立的一只眼睛一样，它们都在瞪着他，在闭问他的内心。它们在问他：你在想什么？你在想什么……他一瞬间失去了自主。他觉得阿贝莉亚可能施展了魔法。

   "你在催眠我？"红黎惊叫。

   "失败了。"

   "你为什么催眠我？"

   "因为这样简单有效。"

   "我开始害怕你了。你不要这样好吗？"

   "我不这样你会回答我吗？"

   红黎从地上爬起来。"我要走了。"

   "你先回答了我再走。你今天——这两天都很奇怪，心思不定。"阿贝莉亚抓住了他的肩膀。以他的力气，他根本挣脱不了。

   "你不是用了催眠了吗，还不知道吗？"

   "我说我失败了。"

   红黎大声说："那下次成功了呢？"

   "你一有准备，一有抵抗，就难以成功。我不擅长这方面，你放心吧。"

   "我不放心！我怎么能放心？"

   阿贝莉亚松开了抓住他的手。现在他可以走了。

   他迈出脚步时，又扭头去看阿贝莉亚。夜里的黑暗已经阻挡不了他的视线了。这时候，阿贝莉亚的脸上好像露出了悲伤的神色，但一下子就没了，变回了平时的淡漠。他看错了吧。她悲不悲伤不重要。他现在有排解不了的忧愁，就是源于眼前的女人。他想再度向她追问红伊水的下落。但他问了多少次了？还是别问了。还是回去吧。

   他再度迈出脚步时，又顿住了。他想到了那个不是办法的办法，也许行之有效，但他一直不愿意这么做。他这么做，可能就和阿贝莉亚鱼死网破了。阿贝莉亚不放过红伊水，把她囚禁在了哪里，他拿阿贝莉亚没办法，他现在唯一的选择也许只有这个了：把这件事告诉特殊事件安全管理局，让他们想办法来救红伊水。

   但这里面涉及的变数太多了。告诉他们就能救回红伊水吗？会不会反而触怒了阿贝莉亚，让红伊水陷入危险？特殊事件安全管理局就真的能控制住阿贝莉亚了吗？……好像并不是这样。他们拿阿贝莉亚没办法，否则也不会弄出个什么"责任承担者"了。他的身份就是人质，特殊事件安全管理局拿来要挟阿贝莉亚的。人质向俘虏自己的人提要求？——也许有这样的人质，但他好像没这么聪明绝顶，可以从容斡旋其间。

   "黎。"阿贝莉亚叫住了红黎，"过几天我会放出红伊水的。"

   …………

   他没有等到阿贝莉亚放出红伊水的那天，倒是又等到了需要出行的任务。此前的任务都在学校附近，或者市区范围内，而现在的任务要离开这座城市了，还要离开所在的省市，去往另一个省。他曾在回到家里的那天听过任务相关的事件，当时打开的电视恰巧播放着相关新闻：一群暴徒袭击了洛城的行政大厦。这个事件居然还没有结束。

   根据唐琳琅提供的情报，暴徒曾一度突围了警方的包围圈，离开了洛城大厦，但后来又不知为何杀了个回马枪；那时候，医护人员和后勤警力正在援救那些饥饿、脱水的人质……暴徒中大多数都是超常能力者，依靠普通的警力，甚至军队的力量都难以解决这件事。事件已经从洛城发酵开来。事态反映到了特殊事件安全管理局。他们现在的任务就是去往洛城，抵达那幢行政大厦，把暴徒歼灭——生擒当然更好——更重要的是，解救人质。

   再过一天就要乘坐飞机飞往洛城了。凌晨三点的时候，红黎还是如约和阿贝莉亚赴面了。自从阿贝莉亚保证过会在近期放过红伊水后，他内心的忧虑就排遣了一大半，不再影响他的日常生活和魔法训练了。他掌握了术式的运用。术式和魔法完全不是一个难易度的：术式就像日常应用电脑，只要用鼠标点击按钮，就能达到使用的目的；魔法则是钻研底层的理论，像钻研电学原理，器械原理，编程技术，工程算法……

   "明天要去洛城了，没有回来的确定时间。"红黎对阿贝莉亚说。

   阿贝莉亚好像听不懂他说的话一样，保持着沉默，给他示范着如何用灼元素凝练出武器。

   "你可以把红伊水放出来了。你到底把她拘禁在哪里？"

   阿贝莉亚凝练出一把单手剑，然后又变换成了一把长枪，继而又变换成了盾牌。

   "你一直在给她提供食物吧，那些零食。"红黎说，"你离开了这里之后，就照顾不了她了。你是时候把她放出来了。"

   "那就让她饿死在那里吧。"

   "你言而无信！"

   "我说到做到。"

   "但你说过要放过她！"红黎说。

   阿贝莉亚手中的灼元素极速变幻，刀、匕、弓、剑、鞭、绳、斧、锤、矛……变幻得太快了，饶是他现在的视觉都难以看清了，那视觉上飞旋的一团到底在变幻着什么。红黎难免觉得她幼稚，他想笑，但是无法笑出来。他心底有什么东西束缚住了他，让他无法自由自在地笑。

   "我离开了这座城市之后，拘禁她的魔法就会慢慢消散掉。"阿贝莉亚说。

   "希望你说的是真的。"

   红黎接着说："明天就不用这个时候碰面了，毕竟要早起远行。"

   阿贝莉亚扭过了头，没给他脸色看。

   第二天，趁着时间还早，红黎准备了自己的行李：一套换洗的衣服，牙刷、毛巾等洗漱用具，手机充电器，移动电源，笔记本电脑，身份证。还有什么需要带的吗？他一时间想不到。所有的东西勉强能塞进他的书包。他把它背上，感觉身后圆滚滚的。

   七点钟时，杨尔蔓敲响了他寝室的门——真亏她能在男生宿舍里自由行动——她只是跨上了一个公文包，里面好像没多少东西，扁扁平平的。她还是穿着那身黑色西装制服。她和红黎也算熟稔了，有过数次谈话。她是属于那种会照顾人的女孩——单看相貌，总觉得她很年轻，刚大学毕业一样——她看见红黎背着个大背包时，伸手就要帮忙。红黎谢绝了她的帮忙。

   他们在赶往餐厅的路上撞见了卫伍。红黎已经一段时间没有见过卫伍了。他听杨尔蔓说，卫伍因为无法追踪到阿贝莉亚的行踪，行使不了职责，曾被上级卸下了监督员的责任；卫伍好像不甘心，但不甘心也没用。卫伍一度离开了学校。

   红黎见不见到卫伍都无所谓。这人今天来估计是想见阿贝莉亚的，因为今天出行，她一定会现身，这样这人就能履行自己的职责了。杨尔蔓在跟卫伍寒暄，问候对方的近况。但是卫伍挺冷淡的，只是敷衍地应了几声。

   他们在食堂遇上了阿贝莉亚。阿贝莉亚正兜着一个白色大袋子，让食堂的阿姨把各种餐点放进去，什么黄金糕，红枣糕，紫薯馒头，流沙包，小笼包，咸菜饼，粽子……没过多久，这大袋子已经膨胀到了有一个怀抱那么大了。食堂阿姨面露难色，因为供餐台快被取空了。这个时间点，周围基本没有学生，老师也没几个，但他们都已经围观过来了，对阿贝莉亚调侃不已，认为她吃不了这么多，时间久了食物会变质。阿贝莉亚声音镇定，让阿姨把剩下的那些也一并打包过来。

   周围哗然一片。老师们都在嗔怪阿贝莉亚，不让他们吃早饭了。阿贝莉亚镇定自若，好像没看见他们一样。事情闹起来了，食堂阿姨正打电话通知经理……

   红黎在一边看不下去了，去制止阿贝莉亚的"横征暴敛"——不过，卫伍抢在了他的前头。

   "我帮你订购一批更名贵的糕点，丢掉这些吧。"卫伍对阿贝莉亚说。

   "不必。"阿贝莉亚说着，还在让食堂的阿姨给她打包。

   那阿姨叹气说："我们还要给学生和老师供餐呢。"

   "把我这张卡里的钱都刷掉。"阿贝莉亚固执地递出了自己的教工卡。

   "这位同学，你能全部吃掉吗？"一位排队的老师说。

   "请你手下留情。"另一位老师苦笑道。

   阿贝莉亚说："这里有限制购买量吗？"

   他们都无言了。

   "既然如此……"阿贝莉亚又拿出了一个白色大袋子，把它兜开来。

   周围的老师和同学脸色都变青了。

   "全都装上吧！"卫伍大声说。

   周围人都看向了卫伍。

   "这不值多少钱，我可以帮她出所有钱。"

   红黎心想，现在应该没人觉得是多少钱的问题。

   "不行的啊……"食堂阿姨为难地说。

   经理来了，他说："这位同学，你要是喜欢这些糕点的话，我让人之后给你多做一些吧。但是现在只能先这样了，因为其他老师和同学们都要吃早饭。你看……"

   卫伍说："全都装进来！"

   "请问你是？"经理问。

   卫伍出示了自己的证件。

   经理看呆了。他看向了周围的老师，那些老师们也面面相觑。他们低声说，这儿不是学校的食堂吗，为什么会有这种公务员性质的人。

   "我们有要务在身，马上要出发了，尽快吧。"

   经理征询："这些糕点和你们的要务有关系吗？"

   "有。"卫伍说。

   连阿贝莉亚都看向了卫伍。卫伍回以讨好的脸色。

   红黎看不下去了，上去劝阿贝莉亚。他说："你这是要过冬吗？"

   "这不够过冬。"阿贝莉亚说。

   "那你要把它交给红伊水？"

   "这是我的。"

   "别在这里丢人了。"红黎叹气说。

   阿贝莉亚把袋子收了起来，拎着先前那个装好的大袋子，脱离了众人的包围圈。众人都盯着阿贝莉亚。他们在为她拎着那巨大的袋子像拎着一只小鸡一样轻松而吃惊。

   轮到红黎他们打餐了，虽然供应区内的早点所剩无几了，都是些干巴巴的馒头，还有各种阿贝莉亚难以带走的粥。

   听食堂阿姨唠叨，阿贝莉亚是个古怪的人，选菜比别人要慢一截，还经常打包，而且会打包近一车的饭菜——推餐车——让后面排队的人根本轮不上号，只能改换队列。食堂经理已经在考虑给她设置一个专用供餐口了。

   红黎受到了经理的嘉奖，他得以免费吃一顿早餐。虽然他没做什么。他吃早餐的时候，看见卫伍在咬牙切齿，密胺的筷子都快被他咬断了。

   张楼罗的车开到了校门口，接送他们去机场。一辆车子勉强塞下了四人，阿贝莉亚坐在副驾驶座；红黎他们三个坐在后座，中间坐着杨尔蔓。红黎向后仰靠着，在不时颠簸的旅程中假寐。他最初还会听到卫伍向阿贝莉亚的攀谈，后来，卫伍也不再自讨没趣了。

   机场到了。他们见到了威风凛凛的唐琳琅。她的散发随风而舞，时而飘飞到她的眼前，她也任凭它们来去，像个阵前的英雄一样。唐琳琅一度带走了杨尔蔓，往机场公共厕所的方向。她们回来了，一切如常。

   唐琳琅领着众人通过了安检，赶往机场的一个偏角。那里有派送他们的专机。红黎一路上对民航飞机的庞然高大瞩目不已，这还是他首次见识到机场。他们到了专机前。说是专机，其实外表就是普通的民航飞机。他猜，这估计是临时征用的。他跟着跨上了飞机。跨步在前的阿贝莉亚左右顾盼，和他一样，对机舱里的一切充满好奇。在刚刚那会儿，她对机场的环境也挺好奇的。

   刚跨上机舱时，他们没有见到其他人。机舱内好像是分区的，据唐琳琅说，阿贝莉亚的舱位就是眼前的这片大区域，有客厅，有办公室，有卧室……唐琳琅说，这里是阿贝莉亚的专区，其他人的座位在后面的区域。

   他们到了那儿时，红黎发现眼前的一切正是印象中机舱：一路过道贯穿到低，两边都是三列的座位。这里已经坐着十数位的黑衣人了，像影视剧里的那些路人保镖，分散在舱内的前前后后。唐琳琅指示红黎他们，让他们坐在中段。红黎无所谓，挑了个靠窗的位置。杨尔蔓挑在了他旁边，帮他把背包放在靠过道的位置上。卫伍还杵在那儿。卫伍跟坐在第一排的唐琳琅交涉，让自己和阿贝莉亚在一个舱区内。红黎没听清唐琳琅说什么，倒是看见卫伍兴冲冲地跑向了之前的舱区。但是没过多久，他被轰了回来。

   "这人有点怪。"红黎对杨尔蔓说。

   "谁？"

   "卫伍。"

   "他哪里奇怪了？"

   "好吧，当我没说。"

   红黎靠着舷窗，俯瞰着窗外的跑道，等待飞机起飞的那一刻。

   "你说他追求阿贝莉亚的事吗？"杨尔蔓说。

   "啊？"他以为自己听错了。

   "你说他追求阿贝莉亚的事吗？"杨尔蔓重复道。

   "他！在……？"红黎惊叫。

   "你不这么想？"

   "我猜他有这个意思，但理性地想，不是这么回事，可能有什么任务。"

   "就是追求。"杨尔蔓说。

   "与其说是追求，不如说是满目崇拜吧……"

   "他随心所欲。比起他，我更像个军人。"

   "你们果然是军人吗？"

   杨尔蔓凑到红黎耳边，手掩住了嘴说："告诉你个秘密，我恨死他了。"

   "你们不是同伴吗？"红黎低声说。

   "夫妻都有勾心斗角的。"

   "原来你们是夫妻！"

   "这只是我的类比！"杨尔蔓瞪大了眼睛，抓狂的样子。

   "那不是？"

   杨尔蔓翻白眼的样子不像个军人。

   红黎问："那你为什么告诉我这个秘密？"

   "所以你待会儿要告诉我一些阿贝莉亚的秘密。我们交换。"

   "呃！"

   "我可以告诉你更多的秘密。机密。"

   "我对你的秘密不感兴趣。"

   "听着，我恨死他了。"

   "和我说了也没用啊。"红黎远离了她一点。

   "我恨死他了！"杨尔蔓在下咒一样，"啊，这样真畅快，要是能对着一个山谷呐喊就更好了。"

   "你这么恨他，干嘛不离他远点？"

   "你也恨他吧，他在试图抢你的情人。"杨尔蔓说。

   "我和阿贝莉亚可不是那种关系。"红黎说。

   "他最喜欢漂亮女人了，还因此闯祸了，连我一并跟着下派。这一切都是因为他有个祖父，那个祖父是我顶头上司。顶头上司要派孙儿去外面打磨打磨，就托了个保姆去照顾他。我成了那个保姆。谁叫我是他的发小呢？我父母满口答应，就怕被反悔一样。"

   "你被父母卖了？"

   "你太直白了。"杨尔蔓说。

   "你真可怜！"

   "还有谁比我更可怜？"

   "没有了。"

   "我真的好惨啊！"

   "好惨。"红黎跟着说。

   杨尔蔓双手捂面，死临侵地。过了一会儿，她仰起头，好像振作起来了。

   "和你聊天真开心，我一直憋着，终于释放出来了。"她说。


## Chapter 26


   到了洛城机场后，红黎以上厕所为由，和众人暂离。他到了厕所外，看着来来往往的人，决定还是就在这里打电话了。他打电话给红伊水。在一阵的忙音中，对方始终没有接电话。他已经从阿贝莉亚口中得知了，她把手机还给红伊水了。但是现在，她没有接听。他怀疑阿贝莉亚说谎了——但也可能只是红伊水刚好有事。

   "你在这里做什么？"

   阿贝莉亚来了，神出鬼没般地出现在了他面前，吓得他连连后退，还撞到了身后的行人。他回头给那人道歉。趁此机会，他也得到了思考的时间，给自己措辞的时间。

   "红伊水她没有接我的电话。"

   "因为她还在我的掌控中。"

   "你在耍我？"

   "只是时间还没到而已。再过一天的时间。"

   "那我明天再打电话确认。"

   "你不用偷偷打电话。"

   红黎把手机收进了口袋。她好像一直盯着他的手机。"我不会了。"

   "我有件事需要你配合。"

   "你确定不是让我帮忙吗？"

   "过会儿会有人问你关于我的事，那时候你尽量配合我。"

   "只要你现在放了了红伊水，我一定配合你。"

   "我说过我会放过她的。"

   他们在这儿争吵并不合适。因为阿贝莉亚显眼的衣装，来往的人都瞩目过来——更因为这里是男厕所之前。厕所位于机场的建筑的走廊。

   红黎往幽深的走廊深处而去。只有身穿制服的员工才从这儿往来。阿贝莉亚理所当然地跟上了他。她还在为刚刚的请求而不放过他。偶尔有保洁工人看向他们两人，两个衣着随便的旅客——为什么会到这儿来。

   "还有一件事我得和你说，你身上的魔法印记越来越强了。"

   红黎回过头，看着阿贝莉亚不像开玩笑的样子。"我都忘记这回事了。它会怎么样？"

   "不知道。"

   "你不会是在骗我吧？"

   "我说过我不会骗你。"

   "可我不是学了魔法了吗，为什么感受不到它？"

   "你学会了魔法？"阿贝莉亚就像看见了稀世之物一样，眼神夸张。她做出这样一副表情来有点滑稽，明明平日里从来不表露情绪。

   "好了，我知道了。"红黎说。

   "我今晚会帮你再清除一遍这印记。"

   "好。"

   "我帮了你这么多，你得配合我。"

   "你不会是故意的吧？"

   "什么？"她装出无辜的样子。

   "你太会谈判了。"

   "是你给出的太少了。"阿贝莉亚说。

   红黎低头看地面，在心里细数了过去的事，从阿贝莉亚出现在这个世界开始。他说："我应该也帮到了你一些忙……"

   "你把我之前给你的戒指戴上。"阿贝莉亚说。

   那枚戒指他放在自己的书包里，因为不习惯戴戒指，所以他很少没把它戴上过。他自己都快忘记了这回事了。阿贝莉亚居然知道。他卸下自己的书包，从里面翻出了那放在夹层中的戒指，把它捏在指间。

   "你怎么知道我的戒指在书包里？"红黎问。

   "我感应得到它。"

   "它是你的跟踪器？"红黎捏紧了戒指，一度想把它丢掉。

   "这没有不合理的地方。我初来这个世界，需要怀疑一切。"

   "那你现在为什么要我戴上？"

   "为你的安全着想。"

   "不是为了你的安全着想？"

   "你戴上戒指我就会变得安全？"她的语气充满了嘲讽。

   她接着说："是因为你的强大，还是因为你的魔法？"

   "够了。"

   "你有的时候缺乏自知之明。"

   "别说了。"

   "你可别冲动，去做自己做不到的事。"

   "啊——你可真烦！"

   "那我道歉，你总有一天会变得强大的，虽然我可能看不到了。"

   这个女人在故意气他。红黎转身就走了，对这个女人他已经无话可说了。但他在回去的路上，在迟疑中，他还是把戒指戴上了，戴在了右手的食指上。据说左手的各个手指的位置都是有含义的，但他不知道，所以选择戴在右手。他隐隐也猜到了，他们这回的旅程并不会多么安宁。

   …………

   接送一行人的专车临近了行政大厦。附近的区域都由亮黄色的警戒线拦起来了，每隔几十步都有士兵在站岗。街道上没有一个人。一只黑猫从商店的外棚上蹿下来，士兵拿着枪托去驱赶它。他们经过了公园。那里停驻着几辆装甲车，还有直升机。士兵们的脸色尤为沉重，双手捏紧着步枪，一刻也不放松。士兵们时常望向那幢高高耸起的大厦。

   越是接近那大厦，空气中的血腥味就越浓。红黎现在过分灵敏的鼻子让自己遭罪了，在加上颠来倒去的车子，他想吐。这里就是战场。没想到他有一天也会闻到这样的味道。他试着将注意力从嗅觉上转移。

   现在，唐琳琅正在副驾驶座上讲解注意事项，他们之后会谒见重要领导人。这辆警用面包车塞满了九个人：阿贝莉亚和杨尔蔓和他挤在最后一排，卫伍和另外三个人分坐在前面两排，驾驶座那一排不用说。前面那三个人，有两个是黑色制服装的，和杨尔蔓一样的身份；最后一个是熟人，和他有过几面之缘的苏小枫。她也是行动的参与者。她见到阿贝莉亚时，表现得过分热情了，就像小弟遇见大哥一样，黑手党的。

   专车停靠在了一家酒店前。这里离行政大厦不远，就一个眺望的距离。大厅入口处有士兵把手。他们下了车时，也就阿贝莉亚和苏小枫神色如常，苏小枫还伸展了一下懒腰。其他人因为四面八方压迫而来的肃然不敢造次。

   一小队的士兵从大厅里出来了，一纵队跑下台阶，在一行人前排开。领队的士兵向唐琳琅确认身份。唐琳琅出示了证件。士兵们分着前后，四名在前，五名在后，像押送犯人一样，护送着一行人进入了酒店大厅。

   他们静默地跟着前方的士兵。苏小枫双手抱着后脑勺，一度漂浮高过了众人的肩头；大厅四面"咔嚓咔嚓"地举其了步枪，对准了这个天真无知的女孩。士兵们都神经过敏了。之后，一名军官从侧廊里快步而出，制止了冲突。这名军官也加入了队伍，跟着他们一起转向了那条侧廊。在这条幽深的长廊上，每隔十步站岗着一名士兵，托着步枪在胸前。

   他们到了一间会议室前，这里是一方休息厅，两侧排着金属的长椅，有不少人正坐在这里等候：双肘架在大腿上，交叉的十指托着下巴。这些人看起来已经等了很久了，大都是和杨尔蔓一个装束，有十数个。他们可能也是某些人的监察员。身后传来踏步的声音。护送一行人的士兵们横列在了休息厅的出入口，封住了这里。

   红黎找了个空位置坐下，比较靠近会议室门的地方。阿贝莉亚和杨尔蔓都挨着他坐下了……

   会议室偶尔会传出吼叫声。从只言片语可以推测出，里面的人正在决定策略——先于对策的环节——是否要把这里的人应用于对暴徒的行动。原来这些人还没有达成共识。红黎看向唐琳琅。她正静默着，然后扭开了会议室的门把手。她关上了门。之后，会议室传出更频繁的吼叫声。

   有易拉罐被打开拉环的声音，然后是咕噜咕噜的吞饮声。

   一位警装的青年从走廊方向而来，被入口处的士兵们拦住了。领队的士兵呵斥几句，然后放这人进来了。这人似乎是趁着士兵们没注意，偷偷溜出去了；刚刚那会儿，有一大半的士兵们去接应红黎他们了。这人大摇大摆，一手插着裤兜，另一只手把着灌装浓咖啡，在对面的空位上坐下了。

   这人对得起一身的光荣警服吗？红黎忍不住想道。

   又回来了一个人，领队的士兵照旧训斥了两句，放人进来了。这回是一名柔弱的女孩，看起来像大学新生，也有可能是高中生，穿戴得柔软可爱。她选了一个相隔警服青年一个座位的位置，抚平裙子，收拢双腿，双手搭着膝盖，无声地坐下了。她看向刚刚呵斥自己的士兵，眼神充满歉意。

   会议室中不再传来吼叫声。

   过了一会儿，会议室的门被推开了，看起来像是秘书的人为后面的人腾出了道，军官或者警官们跨出了会议室，他们胸前佩戴着各式各样的勋章，还有自肩章上垂落的穗带。他们的目光扫过两排的人，在那些穿着私服的人上身做了停留。

   红黎感受到了好几种的态度，有敌视，有愤慨，有冷漠，有淡然……他们维持着扑克脸，只有那种细微的瞳孔缩放、目光游移、眼帘升垂、肌肉颤动、鼻翼耸扩、嘴唇蠕动，才透露了些许的情绪。他们维持着沉默，快步向着走廊，士兵们为他们让出了道路。他们离开了这里，留下了短暂的逃也似的背影。

   唐琳琅站立在了休息厅的中心，面向走廊，双手持着一份文档。在她的身后，一位看起来大约五十岁的军官踱着步，站定，双手在背后反剪。他笑眯眯地环视着两排的各位，被眼皮盖下的眼睛透不出丝毫的光。他笑起来的样子，好像对在场的人都很满意，虽然可能没人知道他满意些什么。他开口的时候，咳嗽了两声，吸引了在场人的注意。

   那位警服青年还在"咕噜噜"的喝着咖啡。

   笑眯眯军官鼓励了众人一番，表示期待他们之后的表现，然后他领着唐琳琅，让众人也跟着自己，迈向了走廊。笑眯眯军官的气度和阔步的样子引人注目，完全不觉得他会是五十岁的老人，如果不是满头的银丝的话。众人好像都下意识地跟上了。

   黑衣制服的，警服的，便服的，盛装长裙的——阿贝莉亚——所有人混杂在一起，挤出了走廊。

   黑衣制服的是有秩序的，他们的脚步相互避让着，为彼此腾出了空间；其他服装的都是混乱的制造者。警服青年是混乱领军者，膝盖外曲着走路，像螃蟹一样，插在裤兜里的手的手肘还往外展着，碍着旁边的人。阿贝莉亚是混乱女王，她的长裙摇曳，靠近她一尺的人都被无形的力量推开了，这导致相邻的人像多米诺骨牌一样，都跟着倾斜歪倒——他们相互扶持，稳住了身形。可爱女孩是混乱的女仆，每当她碰到、擦到别人时，总是会低头道歉，连续三次，让对方都不好意思起来了；但她的道歉会拖慢行进，导致后面的人撞了上去……

   为什么会这样？可能是因为尾随在后的士兵带来压迫感，让在前的人下意识地加紧脚步。红黎擦着墙走，避免碰撞，他身后那如有所指的步枪让他眼皮直跳。

   最前方，笑眯眯军官被人撞了一下，打了个趔趄。那一瞬间，他好像变回了一个普通的老人。身后的人征求老人的原谅，老人只是笑呵呵了一下，毫无怪罪之意。后来，后面的人都放慢了脚步，队伍变得鱼贯而行，走廊上宽敞了不少。

   一行人离开了这幢大楼，向着不知何方。急躁的警服青年多次询问老人。老人笑而不语，只是让他跟着自己。警服青年嫌老人的行进速度太慢了，让老人说出目的地，他好先过去。老人没有回答，但是加紧了脚步。身为一个银发老人，他还能一步跨越两个台阶，迎着猎猎的秋风，只是穿着单薄的军装外套。

   唐琳琅在一旁顾虑着老人，时不时瞅向他一眼。警服青年在一旁嘀咕着。他的抱怨声清楚地传入了红黎的耳中，抱怨：老头死要面子，装模作样；他想摆脱他们，回去上大学，这里束缚太多，让他心烦。

   他们的面前出现了一口黑色的地下车库入口。军官老人还在踱步向前。警服青年停下来了，后面的人也跟着停下来了。

   红黎望见那黑魆魆的入口时，心中也不情愿前进。那里面传出了重金属的味道，还有一些化学试剂的味道，很浓，让人窒息。这是他的感觉，但其他人也肯定感受到了。里面深处还有些窸窣窣的说话声，在交头接耳。说明里面有很多人。他在想像中，那些人设置好了陷阱，就等着他们跳进来了。

   老人在即将被黑暗吞没的一刻顿住了，回过头。他招呼着身后的人。但是没人响应他——那些黑色制服的当然是例外，只是他们也得跟着任务的目标。

   "老头，里面不会有什么东西吧？"警服青年说。

   "是有点东西。"笑眯眯警官说。

   "喂喂喂，你这么说出来，还想让我们进去？"

   "有点事需要你们帮忙。跟上来吧，我们不会是敌人的。"老人和唐琳琅率先进去了。


## Chapter 27


   剩下的人面面相觑，一时拿不定主意。其实决定的也就几个人：警服青年，可爱女孩，苏小枫——光脚女孩——阿贝莉亚，红黎。前两人好像是熟人，在眼神交流；青年脾气比较暴躁，吓得女孩连连后退，但是又不敢避开对方的眼神，否则青年的那张脸就变得更凶恶了。他们两人顶在前面，最终好像都决定要进去了，告诉了身后的众人。阿贝莉亚来到了红黎的身侧，身后跟着漂浮的苏小枫。阿贝莉亚拍了一下红黎的肩膀，越过了他，往前迈步。他也没什么好迟疑了，他此行就是陪同阿贝莉亚而已。

   入口向里有一段坡道，接着是一个拐角。前面没有丝毫的光线。

   他们拐过拐角后，眼前就是一个亮堂的地下车库了。这里没有一辆车。一路的承重柱之间，先前见过的军官们分站在两侧，中间腾出一方空地。灯光从深处打来，照亮了这里的所有。但是那更深处的情形，因为直射而来的灯光太晃眼了，反而看不清了。那儿隐约显着金属的棱角。越是往里靠近，重金属和化学试剂的味道越重。

   笑眯眯军官招呼着众人，让他们到中间的空地上来，专家们需要测试他们的能力，收集数据，用来拟定接下来的作战计划。他背靠着照射灯，只给众人留了一个黑乎乎的人影。

   这场间也太可疑了。没人行动。警服青年脾气暴躁，跺着脚，把手中的易拉罐拧成了一团，抛了过去。眼看着要砸中老人了，老人歪了一下脑袋，那一团落到了照射灯的后面；好像打中了谁，传来一声惊呼。

   一排排的白大褂人员出来了，一只手夹着着锥形瓶和试管；另一只手带上记录本，用手的前臂垫着。为首的是个谢顶的老头，脑袋两边卷曲着一团白发，一只鼻子往前钻着，好像要在空气里嗅出什么科学规律。谢顶老头唠唠叨叨的，让实验对象赶紧过来，他们要开始实验了。这人说的实验对象，似乎指的就是红黎他们。

   警服青年健步冲向了谢顶老头，但是被黑洞洞的手枪抵在了中途。白大褂人员持着枪，他们借着记录本藏着它们。这重金属的味道，也许就部分源于这手枪。要是他们开了枪，硝烟的味道就飘出来了。红黎不想闻到这样的味道。应该没人这么想。

   "这位是米教授，"笑眯眯军官说着，指向谢顶老头，"他想让你们试试他研发的药剂，就是那些瓶子里和管子里的，据说，喝了之后就能增强你们的能力。"

   "滚。"警服青年说。但他的脸上又多了几滴冷汗，因为那些枪支离他更近了。那儿传来手指微微触动扳机的声音。

   笑眯眯军官转而对米教授说："他们拒绝了，让你的人都退场吧。"

   "他们只要喝了，就会承认它是本世纪最伟大的发明之一！"

   无论米教授如何口出狂言，军官们都让士兵把在场的白大褂赶走了，让离开了地下车库，顺带还收缴了他们的手枪。军官们的说法是，他们的药剂不被认可，他们也就不会和超常能力者接触了，也就无所谓危险，所以没有理由携带手枪。

   大部分的白大褂都离场了，但米教授和一名助手还执意留下来，他们的仪器还在照明灯后，需要人员来操作。米教授表示，他想要亲眼观摩现场。笑眯眯军官准许了他们。

   "第一批的客人送走了，接下来该送第二批了。"笑眯眯军官说。

   当红黎还在为老人的话困惑时，阿贝莉亚已经冲出去了。她抽出来的镰刀挡住了数颗子弹。那些子弹被包覆在刀身的灼元素吞噬了。更多的子弹攒射而来，镰刀挡不住这么多的火线，虽然舞成了风扇；在这风扇的后面，阿贝莉亚身周氤氲着一层雾，赤红色的雾，那些子弹一深入这些雾，周围的雾就会凝聚而来，把它包裹住，然后像是燃烧了一样，蹿出一片火红，子弹就到此为止了。

   红黎的目光被那一瞬间的绚烂吸引住了，比夜空里的烟花还要绚烂，一簇簇的星子跳动，交织在一起；他回过神来时，阿贝莉亚已经杀入了那些士兵中央。她的镰刀切断了枪支，她的腿踹飞了士兵。她释放出一道冲击波，在离手三步远，放射出一条条的射线，追踪着士兵们手中的枪支。士兵们发出一声声的惊叫，触电般的松开手。枪支掉落在了地上。

   红黎早已捂住了耳朵，因为开枪的声音太响了。他被迫闻到了硝烟的味道。阿贝莉亚在士兵们之间飞舞来去，一下子在空地的左边，一下子在右边；有士兵绕到承重墙后面，阿贝莉亚照旧斩出大镰刀，她借着刀身的巨大弧刃，杀伤到了柱子后面的敌人。让人注意的是，所有倒地的士兵都没有见血。

   有士兵疯叫起来，对着笑眯眯军官开枪，子弹"啪啪啪"地打在了后面的照射灯上，连熄了好几盏，场景暗下去了不少；但是那子弹就是打不中那老人。要是仔细去听的话，老人身前似乎"呼呼"地啸着风，那风在中途偏移了子弹。

   老人估计是在场的人中最淡定的了，负手而立，一动不动。滑稽的是，居然有壮年军官往老人的身后躲……大多数的军官们加入了战斗，但他们是对着士兵们动手，他们以擒拿为主，制服了士兵后再夺走枪支，加入新的战斗。

   场面过于混乱。红黎回过神，发现身后的战斗也结束了，唐琳琅带着黑衣制服们击溃了后方的士兵们；他们的战斗就没有这么柔和了，倒地的士兵们身上绽开着血花。死亡的味道是浓重的，刺痛人的嗅觉神经，直抵大脑深处。红黎眩晕了一下，移开了目光。今日起，他也许就习惯了杀戮了，他现在的身体适应能力足够强。

   战斗一瞬间打响，几十秒后又瞬间沉寂了。倒地负伤的士兵们唉声连连。阿贝莉亚从地上捡起一把枪支，在手中把玩。她翻了一下枪身，扣动了扳机。啪。天花板的什么金属被打中了。阿贝莉亚好像失去了兴趣，丢了枪。周围人被她一时的举动下了一跳。

   这时，笑眯眯军官拿着对讲机，下令让外面的士兵们进来，带走在场的俘虏或者伤亡。没多久，一列阵的脚步声传来了，新的士兵从入口方向而来，带走了地上的那些败者。在场的军官也跟着出去了一部分。

   笑眯眯军官为众人解释：这是一次筹谋好的作战，清剿所有的內奸；部分军官也被抓走了，因为与暴徒有勾结。他希望在场的军官们引以为戒。最后，他感谢了唐琳琅和阿贝莉亚等人的配合行动，让伤亡降到最小。

   空气中好像多了一些汗臭味。

   "喂——喂——"米教授不知道从哪里跳了出来，"这什么……什么的，怎么不和我说！？"

   "米教授不是要留在这里采集数据吗？"笑眯眯军官说。

   "这乱战是怎么回事？"

   "教授觉得数据不够丰富吗？"笑眯眯军官说。

   "我的命不是命吗？"

   "米教授是科学界的灯塔，国家和世界都不能没有您啊。"

   米教授气哼哼地住嘴了，跑到了照射灯的后面，和他的助手在摆弄着什么，两人嘀嘀咕咕，吭吭哧哧。

   "客人都已经送走了，"笑眯眯军官说，"接下来，可以开始我们的正题了。"

   笑眯眯军官让唐琳琅来主持。唐琳琅来到老人的身侧，翻着手中的文档。她指明让警服青年先来，让他站到场中央说明自己的能力，并演示一遍。

   警服青年的代号叫做雷鸣。据说，所有人都用的是代号，防止个人信息泄露。雷鸣蹒跚来到场中央。他的双腿还在打颤，说话时也吞吞吐吐的，看来是先前的混战给他留下了阴影。他介绍的时候，场外满是军官的用笔书写声。有时候会有军官咋舌，在雷鸣支支吾吾的空档。他介绍了自己的能力为掌控雷电，是他某一天早上醒来时突然发现的，当时，他的头发全炸毛了。

   军官们有问他，他之前是否持有过一颗水晶，一种叫做"奇迹水晶"的东西。雷鸣做了肯定的回答，并说明后来那水晶遗失了。

   军官们听后，纷纷做了首肯。

   雷鸣的紧张好像过去了，声音变得张扬起来，尤其在他凝聚出一颗雷球的时候。他的掌心膨胀出炽白的一团，"噼里啪啦"地窜着雷电，每一根有拇指那么粗，跳跃到几公分外的空气中，消失了。

   雷鸣跑动起来，最大范围的绕着圈；他的速度越来越快，带起了呼呼的风，他经过那些军官们面前时，那风吹起了他们胸前的穗带。他们忙着后退，面上满是惊惧。雷鸣绕了五圈才停下来，他的脸上找回了自信。他擦着似乎并不存在的汗下场了。

   下一个是那可爱女孩。她登场的时候，并不像雷鸣那么紧张，倒是像怯场。她扭捏着双腿，触电一样的目光瞟了一下四面，然后目光盯住了脚下。她的说话也不太利索，但在场的军官们给了她更多的耐心，没有咋舌。也许是她的年轻和可爱起作用了，军官们的脸上都是慈爱的微笑，好像看着自己的女儿一样。

   女孩的代号叫星光。星光没太意识到眼下该做的介绍是什么样的，她提及了自己的兴趣爱好，星座和血型，朋友有几个……如果不是唐琳琅制止了她，她连自己的姓名和居住地都说出来了。她的介绍结束了。她捧起双手，掌心相对之间升起了一个个的光点。她稍微抬起了些头，但是目光躲闪。她在迟疑什么。

   唐琳琅做了解释，星光的能力需要人配合。几名黑衣制服快步到了场中。星光先道了歉，然后依次在黑衣制服们的胸前拍了一下，随着她的动作，一个光点附着在了对方身上，隐没了。星光解释道，她的能力可以让她掌握他人的行踪……

   "没用的能力。"红黎听到了雷鸣的嘀咕声。

   最后一个是阿贝莉亚了——红黎这么想，但阿贝莉亚却并没有上台，当"魔女"这个代号被谁喊出来时。

   他被阿贝莉亚推了一把，趔趄着进入了场中，周围的目光射向他。他困惑地回过头。阿贝莉亚闭着双眼。前方，唐琳琅的目光盯着他。他瞪大眼睛。

   阿贝莉亚之前就说过让他配合她……

   "记住，你是我的召唤者，而不是红伊水。"阿贝莉亚压低了的声音传入了他耳中，其他人好像都没发觉。

   让他猜猜现在的情形：他是阿贝莉亚的使役者，所谓"魔女"，指的是他召唤出的"魔女"，所以像雷鸣、星光一样，他是超常能力者。

   然而，他只是一个普通人。天知道阿贝莉亚到底撒了什么样的大谎……说起来，他想不明白，阿贝莉亚和雷鸣、星光的相似点到底在哪里，后两位是普通人，但阿贝莉亚是异界的来访者……这都是奇迹水晶造成的吗？

   他站在场中心。周围射来好奇的目光，那里面藏着炙热。他心中却茫然了。他该说什么？怎么说？他明明是个普通人，要怎么把自己胡诌成超常能力者？难道要上演一个召唤魔女，把阿贝莉亚从场外召唤到场中心？……

   他总不能一直沉默着，他说："我是阿贝莉亚的召唤者。"

   场下一片哗然。那些军官们交头接耳，议论他的能力。他们说，雷鸣是异能型，星光也是异能型，他们还见过武器型的，现在还要出现一个召唤型的吗？……

   红黎转了个方向，面对阿贝莉亚。

   阿贝莉亚没有表示什么，抱着胳膊看戏。他再次转身，迎着刺目的照射灯。唐琳琅端着文档，用笔做着记录。笑眯眯军官点了点头，好像在示意红黎继续。

   然而红黎已经编不下去了。他想了想，他没理由替阿贝莉亚承受这罪过，这是一场理应由阿贝莉亚登台的演出。

   "让我召唤的阿贝莉亚为大家解惑吧。"红黎伸手敞向阿贝莉亚。


## Chapter 28


   军官们适时提问，问阿贝莉亚从何而来，所谓召唤到底是怎么一回事，还有魔法又是怎么一回事，为什么说她会魔法，她又来自哪里，那里难道是小说故事里那种荒诞不经的魔法世界……

   阿贝莉亚上前，说："我来自哪里一点都不重要——我只是这个自我意识膨胀者的妄想物而已——对你们来说，最重要的是我能做什么，对你们来说有什么用处。"

   "让她展现一下能力，她所有的力量。"照射灯后的米教授叫道。

   "我刚刚已经展现过了。"阿贝莉亚说。

   "嘿，我需要让我的仪器填饱数据。"米教授喊道。

   "讲讲你的魔法能做什么吧。"一名军官说。

   "阁下，你也不想我讲到明天吧？"

   "请你简要的说。"

   "战斗和杀人。"阿贝莉亚说。

   军官们的神色变得凝重了。

   阿贝莉亚没再继续说。

   "就这么完了？"米教授喊道。

   "你最好演示一遍，我们需要制定作战方案。"军官说。

   "嘿，来个人和她打一场。"

   现在的阿贝莉亚就像动物园里的动物一样，只能被迫观赏，还还得听从一些任性的要求。红黎心想。但是他现在也好不到哪里去，他得被迫站在这里，和她一样。

   "你们两人之间的人格关系是怎么样的？"有军官问。

   "你们是主从关系吗？"另一名军官追问。

   "你们是否会发生背叛？"

   "如果你的主人出了意外，你会怎么做？"

   周围一圈的人都被这个话题激起了兴趣。他们议论纷纷。有人举起了枪，上膛了一下，发出咔嚓的声音，然后就对准了红黎——那个留着小胡子的人露出狡猾和自诩聪明的笑，他在最后时刻还大声说："就是要实践才——"

   砰。

   难以说清那一刻的心情。但是红黎现在的反应速度和目力和身体能力都超过了那人射击的速度。他的确追赶不上子弹的速度，但是他能提前躲开那子弹。在他眼中，子弹有一瞬间呈螺旋的形状，扭曲了他眼前的空气。照这个样子，那自动会从他耳边擦过，或许会在他侧脸上带出一道血痕，但是不会给他带来任何伤害。但是这并不是那个军官刻意留手的结果，他出手的那一下，就是要杀掉他。

   一团赤色的雾飘在了他眼前，然后将那子弹给吞没了。那子弹就像从未出现过一样。现场激扬了拿一下的"砰"的声音，然后就没了。回音传开了一下。随后就是军官们的议论声。

   阿贝莉亚已经站在了他的面前。她从地上踩起了什么，哐当一声，也许是不久前射击留下来的子弹，她一脚踢出。咻。

   那留着小胡子的军官一声惨叫。周围的军官纷纷避让开来，然后举起了手枪，对准了红黎，或者阿贝莉亚。但是没人开枪。他们都不敢在这时候开枪。

   "哇哦——"米教授在兴奋地呼喊。

   这个时候的场面，似乎已经发展成了要爆发的地步了。军官们聚成了一团，但是他们又在犹豫了，然后又纷纷散开，从四面包围红黎他们。有军官向笑眯眯军官告状，说要除灭他们，留着这些人果然会是祸患。

   这时候，先前自我介绍过的雷鸣、星光这些人都站在了红黎这边。

   "都住手吧，"笑眯眯军官说，"把那人带出去抢救，救不了也就白死了。"

   "参谋长！"有人觉得不公。

   两个军官架着那受伤的军官离去了。他们绕着阿贝莉亚和红黎他们离开了这里。

   "在怎么如何，他们也是我们的客人。"笑眯眯军官说。

   在这位老人的命令下，其他人都莫敢不从。话题从先前惊险的一幕中回避开来了。他们讨论起了之后的作战，他们该如何运用这些超常能力者的力量。

   米教授又跳出来说话了，他说自己还需要更多的数据。军官们沉默了那么一会儿，接着有人说，他们的确得更了解这些人的能力才行，恐惧来源于未知……这人的说法受到了众人的赞同。他们说了自己需要指定作战计划，但是对阿贝莉亚他们还不了解。他们还说了暴徒的狡诈和凶恶……

   红黎却觉得，这些人只是想借助了解更多来缓解自己的恐惧。

   阿贝莉亚说："我会解决所有的暴徒。"

   他们的讨论一时停止了。质疑和恐惧的目光徘徊在阿贝莉亚的身上。他们迟疑了一会儿，终究还是把手上的枪械都放下了。

   "你的口气很大，但是你能承担失败的责任吗？"一名军官说。

   "已经整整过去一个星期了。"另一名军官说。

   "大楼内的人在等待救援。"还有军官说。

   "没有兵力可以浪费。"

   "这不是儿戏。"

   "这是战争，不要在战争面前自以为是。"

   "这里不需要你的意志，你只是一个兵而已。"

   "那些暴徒不比你弱。"

   "一个女人。"

   …………

   笑眯眯军官拍了拍手。所有军官都住嘴了。笑眯眯军官询问阿贝莉亚的意见，但阿贝莉亚没要改变自己的答复。阿贝莉亚还是一如既往的固执。军官们把矛头指向了红黎，他们让他对阿贝莉亚下令，让她听从指挥——这样的说法一出现，又受到了众人的首肯。他们嚷嚷成了一片，要他让阿贝莉亚展现所有的能力，然后记录下来。他们还让红黎给出一份报告书……这些人中，还有几个嗓门特别大的，一吼起来，回音在整个地下车库荡来荡去。

   红黎想不明白，他们不是训练有素的战士吗——即使是管理阶层，也总该有点铁一般的纪律。但是他们嚷嚷成了一片……这难道是人面对未知时暴露出来的本能吗？

   笑眯眯军官又一次拍了拍手，让所有人都住嘴了。

   "既然阿贝莉亚小姐不愿意展现，那么我们也就不勉强了。"

   还有军官质疑。

   笑眯眯军官接着说："你们可以不听我的意见。去说服阿贝莉亚小姐吧。但是，我不给你们报销任何医疗费。"

   那些人都闭嘴了。

   属于红黎和阿贝莉亚的自我介绍持续了太久，久到红黎都忘了是这么个性质的过场。直到唐琳琅告诉他们可以下场了。按照接下来的进程……唐琳琅说，还有一个人即将到场。

   虽然不知道是怎么一回事，但最后一人终于到了。她在入口的方向现身。她的身后还有一连串的脚步声。她是跑过来的，还大声说着道歉的话，说自己迟到了。但是应该没人能从她口中听出道歉的意思。她看起来像是胡闹一样，嬉皮笑脸地说自己为何而迟到：早上闹钟没有叫醒她。

   笑眯眯军官让追赶她的士兵们散去了，然后让这位小姐来介绍自己。

   她站到了场中间，喘着气，双手抓着背包的肩带，两根发辫还在因为激荡的情绪而甩动。

   她的代号是幽灵，可以召唤一个名为"阿尔谢尼"的恶魔替自己战斗，阿尔谢尼会忠实地执行她的命令。她挽起左手的袖子，向在场的人展示了前臂，那儿有一个漆黑的六芒星纹章。她说，这是她和阿尔谢尼之间的契约纹章，有它在，阿尔谢尼就会供她召唤，供她使唤。

   她举起手臂，呼喊了"阿尔谢尼"这个名字。她的身前出现了一个半透明的身影，但不是人印象中那种狰狞的恶魔，而是一个人形的身影，只是个头比较高大罢了，可以举手触摸到天花板。她下了命令，让阿尔谢尼改变形态。阿尔谢尼的右手膨胀了开来，变成了巨大的爪子。

   真正的恶魔。

   军官们纷纷提问，她的能力和红黎的能力的关系，她是否也是召唤型的，她能召唤多少个阿尔谢尼，阿尔谢尼是否可以被触碰到，为什么是半透明的，是否拥有智慧……

   军官们为幽灵小姐指明了谁是红黎，还有谁是阿贝莉亚。当幽灵小姐的目光落向阿贝莉亚时，就再也没有移开过了，直到唐琳琅上前去拍她的肩膀。她笑呵呵地向众人道歉了，然后一一回答问题。

   阿尔谢尼拥有初级的智慧，只能召唤出这样的一个。她的能力和红黎的没有什么关系，根据她和军官们的讨论，她的这一能力更像是异能型的——他们好像已经有了自己的理论——而不是召唤型的，因为阿尔谢尼更像是她的附属，而不是独立的存在。但阿贝莉亚是独立存在的。

   有军官怀疑，如果红黎不在人世了，阿贝莉亚是否还会存在。现在已经没几个人敢接这个话题了。让红黎头皮发麻的是，米教授对此兴致勃勃。这人想在一切测试完毕之后，给红黎注射药剂进入假死状态，以求证这个结果。

   代号幽灵的小姐的眼睛又盯住了阿贝莉亚。她还皱着眉头，探着脑袋，大有靠近后仔细观察的念想。唐琳琅让她下场了。

   她还是那个样子，一直盯着阿贝莉亚。她中途移开过视线，因为阿贝莉亚的目光与她的相交了，但后来，她又一直窥视着阿贝莉亚。

   军官们在一部分士兵的护卫下，离开了地下车库。唐琳琅和笑眯眯军官也离开了。

   地下车库只留下了超常能力者们，黑色制服们，还有在照射灯后鼓捣不停的两位研究员。雷鸣曾嘀咕着要点开墙壁上的灯开关，让这里更亮堂点，但是被米教授给禁止了。似乎这里的某些设备对灯光敏感。

   幽灵还在窥视阿贝莉亚。阿贝莉亚肯定发现了，只是装作没看见，她在拨弄着手机。这时，幽灵凑近了红黎。

   "她是《白心呼吸》的女主人公没错吧？"赵月玥说。

   她脸上是兴奋交杂着得意的神色，脸颊的软肉被她挤上了眼角。

   "你说哪个？"

   "她啊。"

   "我说什么小说。"

   "《白心呼吸》啊！"

   红黎让她写给他看看。但是她拧起了眉头，满脸不可置信的样子。她迟迟不肯动作。

   阿贝莉亚的目光射了过来。

   他还是首次见到她这样的眼神——凶狠的眼神。她丢掉了手机——在半空中消失了——然后箭步到他这儿来，拉着他的胳膊就往车库外走了。最后时刻，她回头看了一眼幽灵。红黎无法挣脱她箍住他的手。

   …………

   红黎领到了住宿房间的钥匙。今夜所有人都要在酒店里落脚了，明天一早展开行动。专家们会通宵制定作战计划。但他觉得，他们所谓的作战计划，阿贝莉亚不一定会遵守。她会按照自己的想法行动，这点是不会变的，他也改变不了。

   阿贝莉亚很快就被请走了，去参加和专家们的会议。

   红黎可不管了，不管她会把那些军官们弄成什么样。他独自找到了住宿的房间。这是一间双人房，里面摆着两张雪白的床铺，入口的左右手边分别是厕所兼浴室和洗漱台。让他没想到的是，和他一起步入这个房间的是杨尔蔓。她在这个晚上有全权监督他的义务。但是，以他一个男人的身份和女人处在一个房间，还是让他难以接受。他把行李丢在了床头，坐在了床上。杨尔蔓也规矩地坐在了床上。

   盥洗池的水龙头似乎关不紧，总是落下水滴，发出滴答滴答的声音。红黎想着刚刚的事，他拿出了自己的手机，决定凭感觉将那名称搜索一下。

   有人敲门了。

   他去打开房门时，发现来者是幽灵小姐。她神秘兮兮的，左右张望，好像怕不小心撞见了谁。她手里捧着手机。

   幽灵小姐率先把脑袋探进了他的房间。她的眼珠子转溜了一圈后，她的神情就放松了下来，她急忙钻了进来，推着他的手，让他把门关上。

   "你的那位阿贝莉亚，她在哪里？"幽灵小姐说。

   "她去参加会议了。"红黎说。

   "那个……就是……"她支支吾吾。

   "我正想和你确认。"

   "阿贝莉亚，她果然是《白心呼吸》里的女主角吧？"

   红黎取出自己的手机，在浏览器内搜索……然而，他换了各种搜索引擎，甚至浏览器都换了，就是搜索不到任何结果——那些都是七零八碎的内容，与阿贝莉亚无关。

   杨尔蔓被他们两人吸引过来了，也挤到了门口这里。红黎问了杨尔蔓，但她也不知道什么《白心呼吸》。这会儿，幽灵小姐一个劲儿地质疑他，既然他身为阿贝莉亚的召唤者，怎么可能不知道《白心呼吸》。她怀疑他是冒牌货。

   "放弃吧，可能找不到了。我之前也试过了，就是找不到。"幽灵小姐说。

   "为什么找不到？"红黎问。

   "下架了吧。但是奇怪，没有理由会下架啊。"幽灵说。

   "谁下架了？"红黎问。

   "即使下架，也会在盗版网站找到。但现在，网络上哪里都找不到这书了，简直就像是被彻底抹除了。"

   "抹除了……"红黎默念着，放下了手机。

   "我这里还有一点开篇的内容，是我个人下载的，你要看吗？"幽灵小姐说着，递出了自己的手机。

   红黎连忙接过了她的手机。屏幕上正打开着一个文档，呈现着一堆的文字，标题是"序章"。

   "毁灭开始的那一天，天空飘零着火星，洒落着泪水。我的眼睛一直盯着明天的光明，我的心被过去的温暖束缚住了。我对即将发生的一切一无所知。沸腾的元素吞噬了我的父亲。母亲为了阻止这一切，义无反顾，但她也紧跟着被吞噬了。敌人暗中策划了这一切，与住宅唯一有联系的仆人被敌人买通了，在父亲指定采购的药品中混入了导致元素暴动的药粉。父亲和母亲的肉体几乎在一瞬间被焚烧殆尽。他们的灵魂被残余的魔法力量包裹着，让他们在人世间不至于飘零破碎。最后的温存也被践踏了。敌人的脚步声包围了我们的住宅，领军的居然是那位父母一直深信的仆人。那仆人生性残忍，指挥手下的魔法师要将父母的灵魂打碎，也要把我这个小女孩杀死。父亲和母亲相继放弃了保全灵魂的打算……"


## Chapter 29


   门开了。

   一阵风吹了进来。

   红黎手中的手机被夺走了。阿贝莉亚的目光冷漠。那目光马上落在了那手机屏幕上。她双手操作着屏幕，手指连点。红黎去夺那手机。阿贝莉亚背过了她，让他无从抢夺手机。红黎双手从她两侧绕过去，去抢她手中的手机。他的身高比高上半个头，从她身后可以看见她正按下了删除键。红黎的手抓到了她的手腕，冷冰冰的，这时候硬的像铁一样，他撼动不了分毫。她按下了确认。那文档就这么消失了。

   他心中回荡起了那文档开头的几句话："毁灭开始的那一天，天空飘零着火星，洒落着泪水。我的眼睛一直盯着明天的光明，我的心被过去的温暖束缚住了……"

   他现在再抢夺那手机也没有用了，除非还有备份……他想到这里，又去夺那手机。但是阿贝莉亚没有给他任何机会。她明明就在他身前，甚至就被他控制在怀抱里，然而他就是夺不走那手机，甚至妨碍她操作都做不到。她操纵着屏幕进入了存储目录，进入搜索……她操作的极快，就像机枪在扫射一样。红黎用力掐住她的手腕。他想着，要是她因为疼痛而松开那操纵手机的手就好了。然而，他怎么做都阻止不了她的操作。

   "啊，你怎么把我的小说给删掉了！"幽灵叫道。

   阿贝莉亚把手机丢给了她。

   "你要怎么赔偿我的损失？"幽灵说。

   阿贝莉亚丢给了她什么。那是一块翻着翡翠色色泽的宝石。

   "这是真的假的？"幽灵的眼睛移不开那宝石了。

   阿贝莉亚把幽灵推出了房间。

   阿贝莉亚回头对红黎说："你要抱到什么时候？"

   红黎百无聊赖地缩回了手。

   然后，阿贝莉亚又把杨尔蔓推出了房间。阿贝莉亚让她和自己换个房间。

   "这是上级的要求……"杨尔蔓的抗议完全无效。

   阿贝莉亚锁上了门。

   "你不需要知道那些事。"阿贝莉亚说。

   "什么事情？"红黎迎上了那双咄咄逼人的眼睛。

   "你看到了。"

   "我只看到一个开头。"

   "你连开头都不需要知道。"

   阿贝莉亚不想让他知道——不想让任何人知道，说明她对过去的事耿耿于怀。红黎说："阿贝莉亚，但是这一切其实并没有发生，那只是虚构。"

   "那又如何？"

   "你太在意自己的过去了。"

   "如果那是你的过去……"

   红黎说："如果我知道了那一切不过是一场虚构，也许我就会释怀了。"

   阿贝莉亚的脸色和声音都冷了下来："我也是虚构的，我不过是一个虚构的人物。"

   "但你人就在这里。"

   "好了，别说这些无意义的话了。"

   阿贝莉亚坐在了一张床上，拍了拍身边的位置，让他也坐下来。她说要帮他去除那魔法印记。

   "阿贝莉亚，其实我很在意……"

   "那我现在告诉你，那是属于我的隐私，请你不要侵犯我的隐私。"

   她这么说，红黎无法回答她。他只能握了一下拳头，又松开。他就这么僵持在那里。他心中的求知欲却在不断的膨胀。他刚刚都看到了那些片段了，但是被突如其来的阿贝莉亚打断了。他的感觉很不好受，他觉得自己像一直被毛球挑逗了的猫一样，想扑身过去；然而递出毛球的人却把毛球藏了起来。他只能弓起背，像猫炸毛了一样。

   他为了让阿贝莉亚重新开口，最后说："但是你因为这件事，把红伊水抓了起来。"

   "我说过会放过她。"

   "我不信是明天。"

   "你坐过来，我可以考虑现在就放过她。"阿贝莉亚就像把他当宠物一样，又拍了拍旁边的座位。

   "你把她关起来，肯定满足了自己的一己之私。"红黎说。

   "呀，是啊！你说的没错。"阿贝莉亚高调地说。

   "但你现在却还在说我侵犯你的隐私。"

   "因为我有力量，但是你没有。"她说着，一条腿搭在了另一条腿上，翘起了脚，微微扬着下巴看着他。

   红黎感觉自己失去了耐心。"够了，我要走了。"

   他抓起了自己的背包，要离开这里，离开这个房间，也离开这个城市。他干嘛要受罪到这里来？他到这里又派不上任何用场。

   "你离开了，红伊水就永远无法脱困。"

   红黎的手都抓上了把手了。是啊，他也是因为如此而不得不来的。

   "你快过来，你身上的魔法印记已经膨胀到要爆发了。"阿贝莉亚说。

   红黎现在一点都不想配合她。"那只是你的妄想吧？"他说。

   阿贝莉亚拍着床的动作停下了。

   他说："我身上这么可能会有印记？我唯一有的印记也是被你施加的印记。"

   阿贝莉亚坐在那儿呆呆的样子。看到她那样子，红黎只想进一步去刺激她。

   他说："我知道了，那是你带到现实的幻想吧？"

   她的回应都变得迟钝了。她说："什么？"

   "就和你的存在一样，那是假的。"

   他刚说完就后悔了。

   阿贝莉亚成功被他激怒了。她站了起来，胸口起伏不已。他从未见过她这样子，也并不想把她惹成这个样子。但是他还是说出了口。他说了言不由衷的话。

   阿贝莉亚跨步到他面前，把他拽了过来，丢向了房间内。

   "我是假的人。"她似乎用了全身的力气说出这样一句话，然后又用了更大的力气让自己表现得冷静一点。她在咬自己的牙齿。她脸上的肌肉都在抽动。她在全力挣扎。她在挣扎着隐藏自己的情绪波动。终于，她似乎成功了——她的脸色冷出了一种几乎不会是人能有的一种冷漠。

   红黎的呼吸变得急促了，好像大脑缺氧了一样。越是这样，他越是被勾起了破坏的冲动。

   "你在伪装。"他说。

   "如果你承认自己的虚假……"他说。

   "那你为什么要报复？"他接着说。

   "你在伪装！"他说。

   阿贝莉亚一步跨出，推了他一把。那力道让他往后跌倒。他的肩膀撞上了床尾。他摔在了地上。她为什么会这么愤怒？……在这一时刻，他甚至都难以面对她的眼神。他的肩膀传来了剧痛，那是一种沉钝的痛，会让人沉闷地喘不过气来。

   他想坐起来，但是阿贝莉亚厚底的皮靴踩住了他的胸口。他的胸口传来了一股冷硬的感受。阿贝莉亚在对他施加压力。但是他不怕她，不怕她现在这样通过宣泄怒火来排遣恐惧的人。

   "你在害怕什么？"他说。

   "我在愤怒你的不自量力。"她说。

   "不，你在害怕。"

   他说出这句话的时候，感觉阿贝莉亚会像踩死一只虫子一样踩死他——但是他的感性又告诉他，阿贝莉亚不会杀死他，不可能会。他没有任何依据。但是这样的感性助长了他的气焰，让他敢去对视阿贝莉亚那双正要逼得他移开目光的眼睛。

   "你看，你在害怕，你都不敢说话——"

   阿贝莉亚在他胸口踏了一脚。

   他一口气陷了进去。他昏了一瞬间。他都因此而忘了自己要说的下一句话。他再次面对阿贝莉亚的神情时，好像看到了她双眼中的悲伤。我到底在做什么？他心想。

   "我唯独不认为你会说这样的话。"阿贝莉亚低声说。

   "我会说什么？"

   "你像个玩具一样，任凭我让你说什么。"她自嘲般地笑着。

   "我是个玩具？"

   "是玩具就好了……也不好。"她在说着矛盾的话。她的眼神对着他，但又不像是看着他，她目光不知道聚焦到了哪里，好像在他身后很远的地方一样——但他身后只是地板。她还踩着他，不让他起来。

   "你想怎么样？"

   他的这句话像换回了她的灵魂一样，她又看向他了。她的焦距集中到了他身上。她说："我不会因为这样就杀了你。但是我会虐待你。"她好像为了证明自己一样，抬起脚踩在了他身上。

   红黎吸取了教训，只在自己呼气的时候承受冲击。否则他会感觉自己的胸腔被压碎了一样。他的胸骨似乎还挺结实得，没有碎掉。但是它再结实，也无法比得上阿贝莉亚的鞋跟结实。他感觉自己的胸腔越来越承受不住她踩下的力量了。她还在不停地抬起，踩下。她变换着力道，不让他一下子就窒息而昏厥……她痛揍了他一顿。他甚至因为最初的疼痛和冲击，而忘记了要逃跑。虽然他也逃不开。

   他一直在想。阿贝莉亚为什么反响这么剧烈。为什么会这么愤怒。她对红伊水的报复，难道不是她不满的全部吗？既然如此，她又为什么会对他说的话有反应？她不是应该保持冷漠的模样吗？……她本该一直沉浸在自己的优雅中的。但是她刚刚心情大起大落。

   我一直在和生与死长跑，和复仇长跑。

   她当时是这么说的。在那本小说《白心呼吸》的开头一段，也是说着与仇恨相关的话。她的故去似乎浸没在悲伤和痛恨之中。

   她的表现是合理的，但好像又是骗人的。她到底在害怕什么，又在愤怒什么。他不过是在宣泄自己的怒火而已，为什么她又有了这么大的反应？……他现在都不知道自己刚刚说了些什么。除非，他刚刚说的一切都说中了。

   就和你的存在一样，那是假的。

   他说的最重的一句话可能是这句话了，这引起了阿贝莉亚的情绪巨变。但是她分明是真实的，因为她就在和他对话，和他交互……

   他好像明白了阿贝莉亚现在的心理：为什么她会这么愤怒，为什么又会这么冷漠，为什么又会对过去的事情这么敏感，又为什么会对红伊水采取那样的行动。

   她以为自己是愤怒，过去受着受人摆布的痛苦，但是其实不是。她真正愤怒的不是这么一回事。她的愤怒，她过去的那些愤怒和怨恨和各种各样的情绪——她害怕那些都是假的，就像她害怕自己是个虚假的人物一样。她不只是想要报复红伊水这么简单，她在害怕——她害怕自己过去的生活不过是一场梦幻，她的喜怒哀乐不过是一场虚构。他原以为她不过是想对红伊水复仇这么简单，想要报复她给她安排这么一段身世。但是她并不仅仅如此。她真正害怕的，只是自己不过是……

   他懂了阿贝莉亚愤怒和冷漠的缘由，也就对她的行为并不害怕了。不受控制地，他甚至都对阿贝莉亚报以了同情看法。

   由于心情作祟，他可能看向阿贝莉亚的眼神带上了怜悯。阿贝莉亚无疑被他的眼神惹恼了，她那平展着的柳叶眉皱了起来，那一瞬间，好像变了颜色，变成了和眼睛一样的深红色，燃烧着怒火。她的长柄镰刀伸长到了红黎的脖子。他要是试图站起来，那刀刃就会划破他的喉咙。

   "我胡说的，阿贝莉亚。"

   阿贝莉亚的刀刃贴住了他的脖子。

   "你是真实存在的。"红黎如此申明。

   "你闭嘴。"

   红黎闭嘴了，因为刀刃已经吻上了他的喉结。那冰凉的触感让他浑身战栗，但那只是生理上的本能。他心中并没有多少害怕。但他也没有试图劝慰阿贝莉亚。她不需要安慰。以她的自尊心，也许只需要他把那些事当做没发生过就好。这是也许对她最大的公正和善意。

   "我不会多管闲事了。"红黎说，"你哪天想告诉我的时候再告诉我吧。"

   "你还想知道什么？"

   "你……想隐瞒的事。"他终究没有把"过去"这两个字说出口。也许这在她眼中有沉甸甸的分量。他不能轻易说出口。

   阿贝莉亚冷声说："永远没有那一天。"

   阿贝莉亚放过了他。他从地上爬起。他的右手臂没事，身上也没事——除了胸口有点疼——唯一的伤就是喉结出流了点血。

   嘭。

   阿贝莉亚把自己丢在了床上，一副疲惫的样子。她仰面看着天花板，不知道在想些什么。她撑起了上半身，向后调整位置，靠在床头屏上。她的裙摆没有展平，被她坐住了，裙褶堆在一起，乱成了一团。她裙子下面的黑色短裤都露出来，她本人却没有意识到。她心不在焉的样子，完全丢失了往日的端庄——战斗的时候除外。她的右脚曲起，撑高了裙摆，手搭在上面。她还是望着天花板，那里好像有什么东西一样。那里只有一盏水晶吊灯，现在是暗着的。嵌入天花板的盏状白炽灯亮着，四角各一个。

   他轻手轻脚地坐上了床，然后躺下来。他学着阿贝莉亚望着天花板。这个夜晚有点无聊。他又推想起了阿贝莉亚的过去……他对自己的求知欲不太理解，了解这种事根本没有任何意义，但是他无法阻止它的膨胀，他想知道一切。这或许是一种纯粹的求知欲，就像人控制不住自己贪吃、贪玩、贪图享乐一样。

   …………

   天亮的时候，阿贝莉亚已经不在房间内了。红黎背上背包，匆匆离开了房间。这幢楼里好像一个人也没有了，冷冷清清的。他乘坐电梯到楼下。门口守卫的两人是士兵。附近，他连黑衣制服都找不到。他询问士兵时，两名士兵都不作回答，好像真的是雕塑一样。他跑出一段路，沿着记忆往酒店的大厅所在赶路。他在那里遇见了杨尔蔓。杨尔蔓转告了阿贝莉亚的话：留在这里。

   他不可能这么做。杨尔蔓貌似也不打算劝阻他。她驾驶来一辆汽车，载着他往行政大厦的方向去了。

   只是在路上，那边就传来接连不绝的枪击声。这枪声就像怒火，一声接着一声，让他想起了昨晚他惹怒了阿贝莉亚的场景。阿贝莉亚一只脚踏在了他的胸口，因为愤怒而接连地踩踏。他现在依然能感受到胸骨的疼痛。但是更让他难以忘记的是，他因为自己的一时气话，伤到了阿贝莉亚——说中了她心中的痛处……他是不是得向她道歉？早上她出发的时候都没有叫他。

   他想到了红伊水。阿贝莉亚答应过他，会在今天放过她的。他昨天那样对她了，她还会信守承诺吗？

   他打电话给红伊水。没过都久，对面就接通了。

   "你打电话给我干什么？"对面说。

   "你没事吧？"红黎问。

   "你听谁说了吗？……我也不知道为什么，会昏倒在路上。"

   "你这段时间都在哪里？"

   "还好许凝找到了我，救回了我。"她的声音好像充满了自豪。

   "我说，你这段时间都在哪里啊？"

   "我在学校里啊！"

   红黎觉得诡异。这人好像什么都不知道。

   "你那边是什么声音啊？"红伊水问。

   红黎这边的枪击声让电话的另一边都听到了。他拉上了车的侧窗。

   "我在看电影。"红黎说。

   "所以你打电话给我干什么？"红伊水问。

   红黎预想中不是这样的。红伊水被拘禁了这么久，要么发疯到性情大变，要么冷漠到世事不顾，再要么痛苦到无法自拔——唯独这种正常对话一般的感觉，是他想象不到的。

   "你确认没有哪里受伤吗？"

   "啊？"

   "阿贝莉亚没把你怎么样吧？"

   "我不就是在家修养了几天吗，需要这么……这么……你说的阿贝莉亚是谁？"

   "阿贝莉亚啊！"

   "所以她是谁啊？"

   "你忘了她？"

   "她？"红伊水说，"你那里的声音听得我好烦。"

   "先这样吧。"红黎挂断了电话。

   他决定回去之后再找她问清楚。不知道是否是晕车的缘故，从刚刚开始他就觉得有点头晕。是因为在车上摆弄手机的缘故吗？

   他坐着的车到了仅隔那大厦一条街的位置。有士兵在这里站岗，守着一家旅馆的入口，向着行政大厦相反的方向。士兵拦住了红黎和杨尔蔓的去路。

   红黎给阿贝莉亚打电话。但是她没有接听。他仰头望向楼层上方。太阳照落下来，让他感到一阵阵的目眩神迷。他想起了作为阿贝莉亚说的话，那在他身上的魔法印记已经膨胀到了出奇的大了。那后来怎么样了？在他睡着的期间，阿贝莉亚有帮他解决了吗？……他昨晚是什么时候睡着的，怎么睡着的，他一点也想不起来。

   这时，二楼的窗户那儿，幽灵小姐的脑袋从帘幕的后面探了出来。她在向他招手。于是，他不再受到士兵们的阻拦。他和驾车离去的杨尔蔓别过，跑入旅馆，从大厅的螺旋楼梯那儿登上了二楼。幽灵小姐在这里等候着他。之后，他们步入了面向行政大厦最大的房间。

   这里比天底下还要亮，天花板上所有的灯都亮了，大盏小盏加起来有数十个。门对面挂着一面大屏幕，占据整个墙面，正放映着行政大厦正面底层两楼的情形。画面中，阿贝莉亚正步向那大厦；她的那一身黑色长裙，还有信步的走姿，不知道的人或许会以为她要去参加一场舞会。

   这个房间的右侧，笑眯眯军官正负手看着屏幕。他身边有十几张座椅，但只坐着唐琳琅和星光，其他都空着。房间的左侧也有十几张空着的座椅。

   红黎和幽灵小姐摄着脚在星光旁边落座。笑眯眯军官和唐琳琅正在分析目前状况。根据他们的只言片语，还有幽灵小姐的解释，红黎得知：此前，在幽灵小姐的阿尔谢尼的掩护下，雷鸣和一批特务潜入了大厦中，他们由星光在身上做了标记，所以可以被这边跟踪位置；他们的目的是探查大厦中的情况，包括敌人的分布、精神状态，人质的生存状态，物资储备等；但是，他们很快就被敌人发现了，他们遭到了枪械的袭击，从这边只能听到连续不绝的枪声，但是不知道发生了什么，在枪声停止之后，星光做的标记就没有再移动位置过了，也许他们被捆绑俘虏了，但也有可能被杀害了。

   笑眯眯军官好像对事情的发展成竹在胸。他是知道敌人有掌握情报的能力的，所以雷鸣和特务们的潜入是一种徒劳。红黎不理解，幽灵小姐也不理解，为什么笑眯眯军官让雷鸣他们去送死。唐琳琅说，有星光在，他们都死不了……

   阿贝莉亚从正面步入了大厦一楼的大厅。

   屏幕中的画面似乎是无人机悬空拍摄的，距离大厦有一百米的距离，也没有再接近过。画面没有声音，但是房间两侧的窗外传来了隐隐的枪声。阿贝莉亚正在战斗中。

   星光站起身，双手在前方捧起，一个全息影像般的透明大方块浮现了。她在先前的能力介绍中演示过，这个大方块就是一个三维地图，模拟现实中的一个三维地块，只是地形地貌、建筑物什么的都没有，只有她做过标记的目标人物。此时那模拟地图中，阿贝莉亚的水平位置正在上升，她可能正在攀登楼梯。他停下了。

   窗外传来巨大的声响，好像地震了一样，厚重的帷幔都飘飞了起来；然后是一连串的碎裂声，有玻璃碎裂声，有混凝土的碎裂声，好像还有楼层的断裂声——这些声音太夸张了。

   红黎蹿了起来。他本想冲到窗边往外眺望，看看发生了什么，但前方的屏幕已经告诉了他答案。自政府大厦的底层，也许是第二层楼开始的，一片白茫茫的银色气流——还是液流？——向前倾泻而出，像瀑布飞泻一样。只有电影特效才会有这样的景象。这成像的液晶电视屏是不是坏了？他看向老人。

   这位老人已经没有了笑眯眯的样子，而是满脸凝重，双目从眼皮底下露了出来，含着碧色的眼仁。屏幕的画面中，那银色气流很宽，横幅侵占了整个楼层，可能前面的玻璃窗、墙面都被冲没了。那大厦失去了一部分承重力，会不会倒塌下来？气流渐渐淡薄了。

   大厦前的花坛广场上，碎石和碎玻璃满地散落，草坪和花坛被摧残得不成样子，好像地皮被翻过来了一样；到处还散落着一些支零部件，看不出是什么，或许是办公桌椅和一些文档工具。最悚人的是，那片地方洒着斑斑点点的血迹，隐隐中，好像还飘着血雾。

   老人的声音变得沙哑了："又出现了……"

   "杀伤范围是前两次的十倍……"唐琳琅说。

   红黎大概能理解了，为什么那些装甲车和直升机会停驻在附近的公园里，好像时刻待命，却迟迟不展开行动了。他担心阿贝莉亚的安危。那模拟地图中，阿贝莉亚还处在那大厦的方位内，但是上移了一大段。她似乎就此躲避了那银色气流。这会儿，她又下来了。她在那一水平位置四面移动，在跑动，更有可能在激战。但没多久，她又放缓了速度。

   从模拟地图实在看不出什么，大屏幕也看不出什么，距离太远了。为什么不能拉近视角？他问了之后，唐琳琅解释：敌人有掌握空间中任何移动物体情报的能力，一旦接近百米距离，无人机可能会受到枪击，也有可能无端失踪。

   门外吵吵嚷嚷的。门被推开了。米教授抱着一个箱子，和他的秘书一起挤了进来。后面，士兵正扯着米教授的领子，不让他进来。米教授吵吵嚷嚷的，拿一些莫须有的罪名警告士兵，声称自己将是未来最伟大的科学家，而士兵扯住了这样一位科学家的领子，会遗臭万年。

   士兵把枪顶在了米教授的脑袋上，但米教授不为所动，他佝着腰，似乎在保护怀中的箱子不受伤害。那看起来就是一个普通的纸箱，从上边敞口和他上半身的遮掩之间，可以看见里面一两个的表环。


## Chapter 30


   笑眯眯军官同时勒令了两人住手，但只有士兵停手了，而米教授跌跌撞撞地冲入了房间，回头还朝士兵啐了一声。士兵令行禁止，没跟他计较。士兵正要离开的时候，笑眯眯军官让他传话，让救援队都做好准备，他下令后就冲进去救人。士兵面带喜色离开了。老人的目光射向米教授。

   米教授的面色不似刚才那么嚣张了，笑容带着谄媚。他从箱子里取出一个表环，扬起来，好像在炫耀。他开始鼓吹它的好，可以让超凡能力者的能力有所增幅；他说昨天的试剂不行的话，今天的这表环一定要尝试一下，它只需要带上就能生效，无效的话摘掉就好了，不像昨天需要喝进去的液体，让人感觉会有副作用。虽然他坚称昨天的试剂没有副作用。

   米教授给星光、幽灵小姐、红黎一人发放了一个。那纸箱里还有好几个。米教授叹息，要是有更多的超凡能力者就好了，让表环在更多的超常能力者身上测试。

   米教授口中的测试实在让人不祥。他绝对是个疯狂科学家。

   咔嚓一声，星光已经把表环戴上了。米教授像夸孙女一样，把星光夸得满面羞红。幽灵小姐迟疑了一阵，在米教授督促的目光中，还是戴上了。

   就剩红黎了，但他就是不想戴——他戴了也没用，他不是超常能力者。要是他戴上了，或许会露馅。米教授紧盯着他。红黎装作自己没看见，把表环收进裤兜里。

   米教授的目光从他身上移开了。米教授从纸箱里取出了另一个表环，解开了表带，欻的一挥手，居然把表环扣在了红黎的手上。

   红黎的左手，金属质感的表带传来一阵冰凉感，似乎有什么在生效了。他急忙想把它取下来，却发现怎么也取不下来。表环由漆黑色的十多个钢节接成。刚才米教授和其他人松开它的时候，好像都没怎么特别拨弄它。不知道它的连结控制在哪里。他试着去按，去捻，去敲，去扣……却怎么也分不开表带。刚刚相连的两个纲节都没有特别之处。它好像是靠磁力相连。他用力去扯它。然而，凭他现在的力气，竟然怎么也扯不开。

   他问幽灵小姐和星光能否摘下表环。她们尝试后，也失败了。

   "别弄了，等我测试完，自然会给你们松开。"米教授得意洋洋地说。

   "啊，真的增强了！"星光惊呼道。

   她召唤出来的模拟地图有了更大的范围，把这幢旅馆的位置都涵盖到了里面，最关键的是，地图上浮现了朦胧的地形轮廓，这是让人辨认出旅馆位置的缘由。接下来，幽灵小姐也召唤出了阿尔谢尼。阿尔谢尼有了更高大的身材，他半透明的身体变得更近乎于实体了，他变出恶魔手臂的时候，爪刃也变得更锋利、更尖锐了。星光与幽灵小姐皆大欢喜。

   米教授志得意满。米教授的目光又落在了红黎身上。

   红黎试图敷衍，告诉他，自己的召唤能力难以测试，因为无法再此召唤了。米教授却说，让他去感知阿贝莉亚的能力是否有变强。他哪里感知得到阿贝莉亚。他敷衍，也许表环起作用了，但必须得问过阿贝莉亚才能知道。米教授终于不再勉强。他离开了这里。

   当喋喋不休消失了好一会儿后，红黎才意识到，这位教授没有给他们解开表环。现在，他还是不能自己解开表环。幽灵小姐和星光看起来倒不怎么在意，只要这表环有效就好——好像也并非如此，幽灵小姐嘀咕着，抱怨这表环实在是一点也不可爱：漆黑的一节节纲节，好像蜈蚣绕成了一圈；笨长的表头不适合女孩子，要是体贴女孩子的话，就该是小巧玲珑的形状，圆溜溜的，可以藏在手腕腹面。

   红黎继续研究这个手表。长矩形的表头是一块全面屏，光滑细腻，乌黑锃亮。他轻触一下，表头就亮起了界面，显示出了一个数字时间。右上角还有一个暗示能量的图标。除此以外，好像没有其他功能了。在一番折腾后，他还是无法拆下它。他只能等之后再去问米教授了。

   阿贝莉亚还在大厦中探索，她的位置在模拟地图里上下变换。这会儿，老人军官让无人机更靠近了大厦。敌人此时疲于应对阿贝莉亚，没有功夫顾及接近的无人机。现在，画面中的场景处在政府大厦五十米外，那一个个的像素点终于勾勒出了底层大楼窗内的轮廓。大厦的二楼就不必说了，被那银色气流冲刷得不成样子，窗户和墙体支离破碎，所在的房间也暴露在了外面，里面的布置一片混乱，那儿有几个黑点，也许是人，可能是敌人也可能是人质。二楼以上，窗户反射着光，看不清里面的样子，倒是偶尔能看到黑色的影子晃来晃去，也许是阿贝莉亚。画面中的景象还在拉近，变得越来越清晰……

   老人军官还在静候，否决了唐琳琅派出救援队的建议。

   景象距离大厦二十米了。在大厦第四层，阿贝莉亚正在与敌人对战，在一个大型会议室内。三名黑衣敌人端着枪，训练有素地游走着，朝阿贝莉亚攒射。

   阿贝莉亚挥舞着大镰刀，以摄像机难以捕捉的速度挡开了那些子弹。她的灼元素在帮助她生存，吞噬掉了越过防线的子弹。阿贝莉亚踩在会议桌上飞奔，到了尽头，镰刀斩了下去，那吞吐着火舌的大枪械就住嘴了。

   敌人倒了下去。

   阿贝莉亚收拾敌人的速度就像演奏乐曲——一章下来，有缓有急，有张有弛，有升有降，有动有静，不断变幻着节奏，让人不知不觉……回过神来时，敌人全都倒下了。阿贝莉亚往上了一层，那里出现了新的敌人。

   视角又拉近了十米，然后就不再接近了。现在即使是普通人也能清楚看见，坐倒在各个房间中的人质们了。无人机的位置一度上下飘移，确认了更多的楼层里更多的房间。

   那些西装的官员们垂丧着脸，面容憔悴，即使上下四方有大动静，楼层都在轻微震颤，他们也难以动弹丝毫。他们看起来饥饿又疲倦，脸庞被灰黄和枯黑色给侵占了，一副生机断绝的样子。大多数人被手脚束缚着，但有些人居然在自由行动，虽然他们的面色都不好看。让人心惊的是，自由行动的人在对被束缚的人施暴，指着鼻子谩骂，或者拳打脚踢……人质被暴徒们囚禁的漫长时间里，一定发生了无数次的黑暗人性暴露。想要活下去的人选择妥协，为暴徒效劳，帮他们监管人质，对昔日的同僚大打出手，甚至出谋划策……

   老人拿着对讲机下令，让救援队出动了。屏幕中的画面一阵盘旋，警卫、医疗人员正从花坛广场外进来：前方的装甲车作为掩护，防止敌人的突袭；道路清障车跟上，起重臂吊起了一个个的大型路障，像巨大的混凝块，断裂的桌椅，还有其他的残碎品；医疗车缓缓跟上，周围的警卫为它清除小型的路障。直升飞机也出动了，它的旋桨带起旋风，吹得地上的人的衣装一阵阵激荡。

   老人还对阿贝莉亚下令，让她压制住暴徒，绝对不能出现此前的那种银色气流袭击。

   红黎感觉左手腕一阵发麻，那是环表戴着的位置。

   几乎同时，星光"啊"的一声惊呼。她弄出来的模拟地图消失了。她失了方寸，手忙脚乱，嘴里念念有词，好像那是咒语一样。她试图再次召唤出模拟地图，双手在身前反复比划。但是她无一不失败了。老人和唐琳琅让她不要着急，慢慢来。星光从衣兜里取出手帕，没抓住，又掉落在了地上，她也没有去捡……她可能害怕别人责怪她——其他人都在看着她。幽灵小姐开始安慰她。

   红黎觉得是表环让星光的能力出了问题。从刚刚开始，他左手腕的麻痹感就没有停下来，这肯定是表环带来的。但是，幽灵小姐和星光好像都没感觉到异常。他马上想到了答案：她们只是普通的身体水平，不像他，拥有强化过的各项能力。现在他能察觉到的"发麻"是正常人感受不到的。

   他再次尝试扯掉环表……他又失败了。他不再徒劳。他让幽灵小姐试试自己的能力。

   幽灵虽然迟疑，但还是照办了。过去了几个呼吸，那半透明的阿尔谢尼也没有出现。

   这事引起了老人和唐琳琅的关注。但是米教授已经不在这里了。

   老人下令让士兵们把米教授逮回来。

   大屏幕上，阿贝莉亚依然在楼层中战斗。她遇上了一个厉害的家伙，用得武器也是一把镰刀，他每次挥动时，都会产生一道银色的冲击波，朝阿贝莉亚飞射而去；她与这人来回追逐了一番后，她的镰刀将这人的镰刀斩断了。

   如果说，阿贝莉亚真是红黎召唤而来的，那么此时她也许就和星光、幽灵小姐的能力一样消失了。但她不是。

   "消失"事件好巧不巧，出现在这个节骨点上……老人和唐琳琅可能马上就会看出其中的端倪，既然星光和幽灵小姐都因为戴上了那手环而失去了能力，那么为什么红黎没有。

   在这一瞬间，红黎有种超级的窒息感，痛苦感，好像浑身的肌表都被无形的力量渗透了，包裹住了，捏住了，掐住了——这是怎么回事，即使这是忧虑，这是对阿贝莉亚的谎言可能被看破的担忧，也不至于如此夸张——那力量越来越大，把他越掐越紧，就像在泥潭中越陷越深。他强大的感官能力把他的痛苦放大了，他本可以击中精神，让自己大脑摒弃那些痛觉信号，但这一瞬间的痛苦是在是太强烈了，让他无法集中精神。

   他的感官还让他的时间观出现了变化，时间流逝得是如此的慢，慢到大屏幕上的画面像被放慢了十倍，百倍，千倍。他的眼睛居然能够捕捉子弹飞窜时周围的螺旋气流。阿贝莉亚的镰刀还飞扬在上空，她在下斩。镰刀由灼元素包裹着，像包着一层糖衣，整体看起来精美、华丽。她一定是珍视着这镰刀，所以在每次的战斗中，都不让它接触到碰撞和外界丝毫。

   他的痛苦感消失了。他的其他感官也消失了。黑暗。静寂。空虚。他的意识在漂流。这个时刻度日如年。他想用时间来形容自己的煎熬，但此时的时间观已经消失了。到底过去了多久？他的记忆好像每个时刻都在刷新。终于，他好像有了一丝知觉。光线像瀑布一样灌进了他的眼睛里。此时他才知道，他此时瞪大着眼睛。他流下了泪水，因为刺痛而紧闭的眼睛。

   周围一阵嘈杂，已经不是他印象中的那些声音了。他本该在那会议室中，只有偶尔有风声和枪声从窗外传来，再有就是老人的和其他人的呼吸声。此时，有好几个中年人在叫喊，声音中透着惶恐和焦急。回应他们的声音更强势，好像是他们的领头人。这人让他们不要慌张，也不要吵着嚷着说逃跑，他已经把关键的人物拿捏住了。

   满地都是呜咽声，从这些声音来看，这个空旷的大房间里有不少人。他觉得这里是空旷的大房间是因为，这里没有流动的风，也没有外界秋季时的那种冷，反而有种温暖感——这种温暖感与四面蕴含的恶意形成对比，让人心底发毛。那个疑似的领头人和那些吵嚷的人都是一些粗暴人物，声音中透着火气。他们呼来喝去，会把怒火发泄在那些只能呜咽着的弱者身上。这里是哪里？

   红黎睁开了眼睛。

   嘭。

   从楼下传来一次剧烈的震颤，整个地面因此而上移了一刹那；在这一刹那，红黎双脚都腾空了。他踉跄着让自己站稳。接连不绝的碎裂声，惊呼声，碰撞声……四面八方的空间都不稳定似的，好像时刻会碎裂开来。

   随着一阵急促的脚步声，有人嚎叫："楼下那个女人疯了——她发了疯一样——正往这边赶！"

   "闭嘴。"这是领头的人的声音。


## Chapter 31


   红黎的眼睛终于适应了光线。这里的确是一个大房间。

   满地堆着人，他们的肢体萎软，面色灰黑，如果不是有细微的胸腔起伏，可能都会被认为是尸体。他们就像破旧的衣服一样，被七零八乱地丢在地上，被这个房间的主人不屑一顾。有人在他们身上踩踏，践踏，奔走，换来了一阵阵呻吟声……

   从未见过如此景象的红黎怔住了。然后，他又被求生的本能唤醒了，因为四面那些行动自如的人饱含着恶意。相由心生是正确的，那些面色中爆发着剧烈的情绪。黑暗。消极。残虐。他们张口说话时，脸上的肌肉必然会扭曲、变形、相互拉扯，产生夸张的阴影震颤和凹凸变幻。他们挥舞手臂时，好像一定要把什么东西砍断。他们踢出脚时，一定要把火气发泄出去，尽管他们只是往前迈出一步，或者后退一步。他们的目光射来射去：好像地鼠行窃完了，正要钻个洞逃跑；又好像导火线逼近了炸药，马上要爆炸了。

   在这些之上，那个统御他们的人正坐在一张办公椅上，向前倾斜身体。他的面前跪着一个同伙，他的双手按在那同伙的脑门上，好像要举行什么邪恶的仪式。

   那个同伙身体打颤，从侧面上看，他的神情狂热又惊恐。他在领头者的手下战栗。随后，领头者一脚踢开了他，而他却像收获了至宝一样窜了起来，脸上充满了惊喜。那同伙看着自己的双手，那儿凭空抓握。他的手中和空气里都并没有什么东西。

   领头者朝红黎招了招手。

   四面有八双眼睛，八把枪，都对准了红黎。他的身体素质大幅度提升了，也许运气好，能像影视剧里那样，在对方扣动扳机的那一瞬间躲过弹道；但是他没法躲开八条弹道。他选择举起双手，朝领头者走近。

   "老——老大，我得——得到的是什么——能力啊？"先前的同伙说道。他在空气里抓握了半天，也没弄出个什么名堂。

   "滚开。"领头者啐道。

   那同伙瑟缩着退开了。这时，领头者又叫住了他，眉头拧起来，抄起身后的办公椅，丢向了那同伙。那同伙反应迟钝，被办公椅砸了个仰面朝天。也有可能他是故意不躲开，让自己的老板发泄一下。其他的同伙们齐声惊呼。倒不是因为那同伙的受伤，而是楼下的女人快要攻上来了，配备各种枪械武器的同伙们都奈何她不得。

   领头者咧开着嘴，露出细小又尖锐的白牙，他让同伙们都不必担心，马上就能解决那女人了。他接着下令，让那被砸翻的同伙用任何的铁制品，比如那椅子的骨架部分，制造出更多的枪械和子弹。

   那同伙听命于他，对那椅子的支撑脚和靠背杆又抓又摸。没一会儿，那椅子就失去了原本的形状，变成了乱糟糟的一团，软垫的部分都脱落了下来。然而，枪械的影子却都没有见着，那充其量是个长长的棒子。也许他想做出步枪什么的。

   领头者过来抓住了红黎的手腕，没有理会那个失败的家伙。他用强硬的力量把红黎压得双膝跪下。即使没有周围盯着的八把枪，红黎单凭借力量也抵不过他。红黎依着他照办。

   红黎想试着说点什么，拖延时间，楼下的阿贝莉亚的四处破坏的声音已经越来越近了。那些乱哄哄的声音，枪击的声音也越来越近了。但好像不用他说什么了，那领头者不知为何闭着眼睛，杵在那儿一动不动。

   阿贝莉亚的脚步声迟迟没有传上来。她的厚低皮靴踩在这样的瓷砖地面时，会发出"咚咚咚"的声响。但他迟迟听不到这样的声响。领头者睁开了眼睛，连带着他的细牙也暴露了出来。像先前那样，领头者把双手按在他的脑袋上。

   这是要做什么？

   红黎不理解。他猜测刚刚发生的事：领头者把双手覆盖在别人的脑袋上，会把自己的能力引渡给对方。但他不觉得领头者对自己会那么友好。除非，这领头者要给他一个异常恶劣的能力……

   现在，他想一个上勾拳打在领头者暴露无疑的鼻梁上，然而，四面黑洞洞的枪眼看起来并不那么好说话。他焦躁地等待，双手还高举着，保持着投降者的姿势。他可以换个姿势吗？他的眼神这么说时，但那些同伙们却没有理会他，只是盯着领头者。

   地面，从下自上的冲击波轰出了一个大破洞，暴露出来的钢筋都被切断了——不，是被侵蚀断的，那是阿贝莉亚的灼元素之力。受到波及的几名人质翻滚了两下，不动弹了——原本就没有动弹，不知生死。

   当即，有四个暴徒撇下了红黎，从那个地面缺口跳了下去……下面又是一番混战的声音。但他们绝对撑不过十秒钟。

   有一股清流从领头者的双手渗入他的脑袋，然后漫及他的全身。领头者欻的一下缩回了手，然后拧着眉头。他怒目横对红黎。

   "你是那个女人的召唤者？"领头者问。

   为什么又有人问他这个其实是谎言的问题？这时候，他想象不出什么样的回答能够让自己活下去了。他猜测了一下，也许米教授是这人的同伙……

   "是。"红黎说。

   "滚，"这人一脚把红黎踹开了，"那个米老头，居然拿个冒牌货糊弄我！"

   红黎摔在了地上。但此时他并不关心新的伤痛，他更在意身体的变化。他究竟是否会像先前的那名同伙一样多出个什么能力……

   "老大，怎么样了？"一名暴徒问道。

   "老大，那女人要上来了。"另一名暴徒说。

   领头者扛起一张办公桌，往地上的缺口丢去。那办公桌的尺寸比缺口要大，底下的两个菱角凸在了外面。那领头者好像就是拿它当填堵物用的。

   领头者一手拎一个人质，把他们当棉花一样往缝洞里塞，一个接着一个。人质发出呻吟。他们因为饥饿和疲倦无力反抗，即使肉体被混凝土的棱角或者钢筋刮出血槽，也只能向上翻着白眼，让凸出皮肤的青筋颤抖……

   红黎已经见识过枪击毙命的景象了，子弹在一瞬间剥夺了生命，死者由胸口绽出血花，或者由颅骨发生形变，再也不省人事；然而，那时候给人的悲怆和愤恨感远不及此刻。这个畜生，是拿他们的生命当做要挟，当做盾牌。人质痛苦地哀嚎，然而他们微弱的气息只允许他们呻吟出声。他们只是抽搐了一下，挣扎了一下，最终没了力气，像具尸体一样变成了漏洞的填充物。

   红黎无法再忍了，他要冲过去，干掉那个领头者，干掉所有的同伙，救出人质；他要任凭自己的冲动，任凭血液在血管里奔涌，任凭大脑被愤怒掌控——他以为自己会这样，会冲出去，用胸膛顶开那些黑洞洞的枪眼，让领头者住手。但是，他没有战胜生理恐惧的本能。

   他要是就这么冲出去，子弹会穿破他的心脏，在他的身体留下一个窟窿——四个窟窿，没有丝毫余地。他控制住了自己的冲动。他只是站在原地，作为一个旁观者。

   砰。

   他精神一振。但是，中弹的不是他，而是那领头者，一颗子弹打中了他的后心窝。但是，鲜血飞溅的情景没有发生。他披着的银灰色外套破了个洞，露出了里面漆黑的内衬。一丝的血丝都没有。那看起来像是一件防弹衣。

   领头者转过身来，藏住了身后的破洞。接连的子弹射向他，可子弹中途好像打中了一面防弹玻璃，那玻璃无形无影，还坚不可摧，所有的子弹都被弹开了。火星四溅。

   场面混乱，原本指着红黎的那四把枪，此时都对准了领头者，疯狂攒射。这激烈持续了一阵，直到他们的弹匣都被打光了。同伙的暴徒露出惊骇欲绝的神色，不敢置信的神色。反观对面，领头者的神色由开始的愠怒转变了，变得嘲讽，变得轻蔑，变得不屑一顾。

   四名同伙似乎成了反叛者。一名反叛者为首，"这不可能——这不可能——"这样的喊着。他们给枪塞上了新的弹匣，又继续集火。但子弹就是无法击穿那无形的屏障。反叛者们在徒劳无功。

   帮反叛者们消灭领头者。红黎心中生出这样的想法。但是要怎么做？……最后，他决定自己注意着点，别被飞窜的子弹给打伤了。还好，现在无论是反叛者，还是领头者，他们的注意力都不在他身上。他绕到了一张办公桌的后面，躲在了桌子底下。他顺便把一位上半身暴露在桌子外面的昏迷的公务员拖了进来。

   反叛者们停止了开火。

   领头者也没有动作。

   他们开始了交涉。

   领头者让反叛者们重新归顺，他的意思是他可以不计前嫌，但眼下他们必须帮他对付楼下的女人——不知道为什么，阿贝莉亚迟迟上不来。

   反叛者们无视了他的请求，而是在质问他的能力。根据他们之前的了解，领头者可以转移超常能力，从别人那里夺取，或者分配给别人。他掠夺了许多人的能力，让它们为自己所用；也转移给了自己的同伙，让他们成为自己的爪牙，心甘情愿为自己卖命，也让自己的团伙更为壮大。

   反叛者们曾旁敲侧击，打探转移能力的细节。他们发现，这转移使用时，必定伴随着能力的转移，不是从对方到己身，就是从己身到对方。曾有一次，领头者错估了一个人，把那人具有的魔术能力以为是魔法，就劫持了那人，试图掠夺那能力。然而，他自己的能力反而丢失了，丢失的是他最近掠夺的一个能力。所以说，他的能力像"堆栈"一样，把它们堆在自己身上时，必定会按照"堆栈"的规律来叠放：先进后出，后进先出。

   反叛者们推敲了头领持有的所有能力——随着他在全国各地的遍历，他劫掠的能力越来越多——有力量增幅的，有速度增幅的，有情报掌握的，还有奇幻的像魔法的……反叛者们推敲了他生活中、战斗中的大量细节，再根据其他团伙的传闻，整理出了一个详细的列表。占领大厦的行动中，头领把许多能力都分配出去了；为了阻拦楼下那女人，他又分配出了一些能力。在所有的能力中，让反叛者们忌惮的能力之一——瞬间移动，在对红黎使用转移的那一刻——反叛者们称之为"移栈"——到了红黎身上……

   反叛者们如此阐述。现在，反叛者们有些心灰意冷了，他们的脸色耷拉了下来，但好像终究没有放弃，还端着枪，把枪口对准着领头者。领头者优哉游哉，从刚刚开始，他就坐在了一张旋转椅子上，翘着二郎腿，一边和他们对话，一边转着椅子，时而背过他们，时而面对他们。好像那些枪只是玩具枪一样。

   不知何时，楼下没有了动静。阿贝莉亚还没上来——她在做什么？红黎实在想象不到，阿贝莉亚会被击溃。敌人的首领都在这里，还从未和阿贝莉亚撞面一次，而且他和反叛者和好的前提是，让他们帮忙一起对付阿贝莉亚。也许，阿贝莉亚被领头者的某种能力困住了，但只能是暂时的。

   "你们分析得很对，不愧是我的专家们。但你们也太笨了。你们失败的原因很简单，自以为聪明了。你们以为你们能分析我，我就不会应对？"

   "你藏得太深了。"一位反叛者说。

   "这挡子弹的能力，你从来没用过。"另一位反叛者说。

   "你的下巴都被子弹打穿过，但你也没用过。"第三位反叛者说。

   领头者点了一根烟，给自己抽上。他的烟雾吞吐出欢快的形状，时而像狗，时而像猫，时而像个游泳圈。他说："太棒了，太棒了……大佬总得有压箱底的绝招，在亮出来的时候，让所有人大吃一惊。你们满足了我的期望。"


## Chapter 32


   领头者丢掉了烟，尽管还没抽上两口。他站起身，伸着懒腰，活动着筋骨。他从上倒下，将身体的各个关节都活动了一遍。最后，他还揉搓了一下双眼，他移开手时，那漆黑的眼袋都变浅了。他折腾了一番，这会儿站直了，好像变成了一个养精蓄锐完的战士。

   "你们考虑的结果呢？"领头者问反叛者。

   反叛者们在相互对视。他们丢下了枪，举起手来。领头者赞赏了他们的决定，又让他们重新拿起枪来，准备战斗。他先让他们到窗边，去对付那些闯入了大厦百米范围的警卫和入侵者们。枪声又一次响起来了。之后，领头者的目光射向了红黎。

   这时，走廊上传来了"咚咚咚"的脚步声。那是阿贝莉亚的脚步声。

   门被烧成了灰烬。阿贝莉亚的黑色身影出现在了房间外。她踱步而来，目光扫视了一遍房间。她马上发现了红黎的所在。她的目光只在他那里停留了一瞬间。

   阿贝莉亚冲向了领头者。

   她的镰刀朝他呼啸而至——她的镰刀速度更快，当镰刀在领头者面前现形的时候，她残影一样的身体才出现在随后。然而，领头者面前的无形屏障挡住了她的镰刀。她停了下来。

   领头者狞笑，双手在身前摆出相机拍照一样的动作，食指和拇指成直角，两手的相互逼近，中间的框框越来越小。随着他的动作，空气中传来了一阵尖锐刺耳的声响，让人厌恶，就像指甲刮擦着玻璃一样。

   明显的，阿贝莉亚的裙摆变形了，原本圆形飘舞着的，现在却出现了四条棱边。有什么东西在挤压着它。阿贝莉亚的长柄镰刀被迫竖了起来。领头者在用他的无形屏障在推压阿贝莉亚，从四面而来。

   阿贝莉亚没有多余的动作，只是双手握着镰刀柄。她好像有一瞬间冥想了，神情仿若遗世。她的镰刀刀身中央那颗深红色宝石微微亮起。这时，阿贝莉亚伸出的手已经不得不缩回来了。四面屏障内只有一人的空间。

   尽管红黎觉得阿贝莉亚不需要帮助，但他还是捡起了地上的一个空弹匣，朝领头者掷去。他现在的力气——

   那空弹匣发出"咻"的一声，砸在了领头者的脑门上。领头者晃了一下身体，跌坐在地上。但是他的头上居然没有丝毫血痕。那空弹匣的速度，要是打在普通人身上，估计会和铅球砸上去差不多。

   领头者的手势似乎是控制无形屏障移动的关键，或者他的注意力，现在推压阿贝莉亚的力量消失了。这会儿，阿贝莉亚那边有了让人目眩神迷的变化。在她的镰刀上空，一簇簇的蔷薇花绽放开来，似实非虚，如梦似幻；那些蔷薇花有着绿叶的衬托；蔷薇花和叶片让出了道路，一个穿着花瓣拼凑而成的连衣裙的女孩飞了出来，手持着一把鹤嘴镰，她紧闭着双眼，露着得意洋洋似的笑容。这女孩出现时，阿贝莉亚就一声令下："斩……"

   那蔷薇丛中出现的女孩——也许就是阿贝莉亚口中的花恶魔——抡了一圈手中的鹤嘴镰。空气中，好像有什么消失了；空气在这一瞬间对流得剧烈了起来，形成了一道四散的强风。那强风带着清香的气息，还带着一些灰尘和砂砾，刮得人难以睁开眼睛。

   花恶魔和阿贝莉亚一上一下，朝领头者冲去。当领头者又做出手势——比如推掌或者压掌之类的动作——时，上方的花恶魔就会挥动一下镰刀，把那生成的无形之物斩去了。这房间不大，阿贝莉亚一个眨眼就冲刺到了。她的镰刀挥下，带着灼元素的赤红。

   领头者险之又险、却又分毫不差地避开了斩击，只是横移了一下侧着的身体而已。领头者抓起地上的两名人质，把他们朝阿贝莉亚抛去；他的手抓在他们的手腕上，暴力地挥动，那一瞬间响着肢体脱臼的声音。咔嚓两下。

   阿贝莉亚平时冷漠着脸，但她没有一刀把人质都劈开了，而是接住了他们：她的灼元素变幻出一张缓冲的大网，把他们都纳了进来。但阿贝莉亚的行动由此迟滞了。

   领头者居然朝着红黎的方向冲了过来。他的目标是他——是他拥有的瞬间移动。红黎想清楚的时候，领头者的前脚已经踢飞了办公桌。嘭的一声，那办公桌在红黎身后撞上了窗户，伴随着一串玻璃碎裂的声音。领头者的一拳打了上来。

   红黎瞪大眼睛，试图捕捉那可能已经超越了声音的拳速。他的双手刚刚反射性得挡在身前了，现在他张开五指，让灼元素在手心凝聚；他根本不控制灼元素，而是任凭它膨胀爆发，因为他感受到了死亡的威胁。领头者要杀了他。也许他死了，领头者可以拖着他的尸首把瞬间移动吸收回来。他指望灼元素挡住领头者。

   不是徒劳。领头者强行改变了拳头的轨迹，在他面前打出了一招挥空的摆拳。摆拳的劲风呼啸，吹飞了他刚刚召唤出的灼元素；飞舞的赤红色吞噬了他的袖子，给手掌带来阵阵刺痛。

   阿贝莉亚的攻击到了。她释放出的灼元素冲击波在领头者身后绽开，然后从各个方向合来，就像出笼草的捕虫囊一样。

   领头者避无可避了。他还维持着挥拳结束的动作。谁想，他身体表面亮起一层金光，把他包装得像个金人一样。元素冲击被抵御住了，但那层金光也出现了裂痕。他抖了一下身子，把被侵蚀的金光都抖落了下来；灼元素也随之落下。他不依不挠，没有转身对付后面，而是朝着红黎出手。

   这人非要夺回他的瞬间移动了。这人想要逃跑了。所以他千万不能让这人得逞。红黎这么想的时候，这人的脚已经踢了上来；他的反应速度跟不上，只是看到那脚呈一个弧线的轨迹，自上而下，踢向他的大腿。看到的和感受到的完全不同，他感受到的是一把锤子砸在了他的腿上。几乎同时，阿贝莉亚的镰刀挥中了领头者。由此，幸好，踢上来的一脚的力量没有完全释放出来。

   领头者被阿贝莉亚的镰刀挥向了后方。哗。一点零星的玻璃碎声。当红黎回过头时，那领头者已经飞下了大厦高楼。他会死吗？——不，看他刚刚的那个空中翻转姿势，就像故意钻出了这层楼一样。红黎想要去窗边看看，但他没有行动能力。

   阿贝莉亚冲了下去，带着她的花恶魔一起。

   场面一下子安静了下来，这个几乎成了废墟的房间。红黎坐在原地平复喘息。一呼，一吸，一呼，一吸……他心潮起伏，但没有多少害怕。可能是肾上腺激素爆发的缘故，他受伤的地方也没有感受到太多的疼痛。

   也不知道是否是阿贝莉亚刻意控制的原因，刚刚的暴乱居然没有伤到满地的人质——如果是，那么选择往下逃逸的领头者要遭殃了。

   办公桌桌椅乱飞，有些嵌入了柜子里，有些翻倒在了地上。有一处，大块的桌子差点就要压住躺倒在地的人的脑袋了，然而一张圆凳微妙地撑起了它，形成了一个稳定的三角。三角下的人安然无恙，虽然奄奄一息。

   红黎撑着地面，单脚站起来。这会儿，刚刚又归顺了的反叛者们消失了，可能是趁着混乱从走廊逃走了。红黎跳向窗边。他扶着窗框，向下俯瞰。他的视力让他隔着七八层大楼也能像看放大镜下的文字一样看着地面。在那里，装甲车和警卫人员都散了开来，围成了一个圈。中间，阿贝莉亚拖着生死不明的领头者，朝迎面而来的老人军官走去。

   事情似乎是收尾了。他的心放了下来。他感觉脑袋空空的，没有什么想法。他感受了一会儿寒冷的空气，听着下面的喧嚣。

   士兵们和警卫们攻入了大厦。楼下一片喊冤和哀嚎，时而还有枪声响起。警卫和士兵们的"不许动"高过了一切。逮捕行动一层一层的往上，救援行动也一层层的往上。从他这里，楼层内的如何救援看不清楚，但是，楼下的医疗车已经一辆又一辆得开进来了。道路清障车正在为它们扫除障碍。

   一副又一副的担架从大厦内抬出，挑上了医疗车，然后被送走了。那些罪犯们也被送走了，只是他们不太一样，被拷上了镣铐，又被推上了警车；警察和士兵们对待他们可没有那么温柔，要是敢不服从，就拿枪口抵着他们的脑袋，或者把他们打一顿。被逮捕的人远远超过了最初报道的五人。实际上，在刚刚混战中的敌人数量就超过二十位了。暴徒壮大了势力。也许有一部分的从犯原本是行政大厦内的公务员。

   活着真好。他想道。他心里滋生了回家的念头——回学校的念头。他还有许多问题想问红伊水。

   他的胸口有些发闷。也许是事后疲劳吧。他并不在意。人的身体总是会在某些时候发出奇怪的信号，也许是预警，但是身为身体主人的人根本无法理解身体的预警。他选择无视。休息一会儿就好了。但是，情况好像有些不对。

   他的胸闷没有结束，反而愈演愈烈了。他的胸闷扩散到了四肢，现在四肢发麻，浑身僵硬了。他让自己的身体朝窗内倾斜，不至于失衡掉下这个楼层。他捂住胸口。他意识到了这胸闷是什么，他的魔力在暴乱。魔力会寄宿在阿贝莉亚烙刻在他身上的"回路"上，潜伏于身体内。"回路"越密集，能贮存的魔力越多。他一般把魔力贮存在躯干的位置。现在，他贮存的魔力失控了，正在乱窜。这是怎么回事？

   他在不久前才感受过一种类似的感受。他因为领头者的力量而突如其来的出现在了这里。他现在的处境好像又有了类似的变化。

   他感受到了一股牵引力——这股牵引力是怎么回事呢？——他感到天旋地转。这股牵引力拽着他旋转。他分明还站在地上，却感觉周围的空间在旋转。天花板在地上，地在天花板上空，窗户就在他脚下，周围躺着的人漂浮了起来；它们的位置又相继转移了。又转移了。转移在加速……这是他的心理作用吗？——不，他现在像被塞入了洗衣机，正在被迫旋转。旋转……他想吐。外界的声音扭曲了，变得嗡嗡呜呜，什么也听不出来。隐约有人在叫他的名字。黎。黎。黎。只有阿贝莉亚会这么叫。

   有人拉住了他。又拉住了他的另一只手。有一层薄膜包被了下来，把他和拉着他的那人一起包住了。薄膜似乎可以隔开牵引力，但只是一部分；另一部分的牵引力还是渗透下了薄膜，拽着他。如果他可以抗拒，他早就把那力丢开了，或者让自己远远的跑开了。但他好像身不由己，无力行动。那牵引力也难以捉摸。旋转。旋转……也许是薄膜起的作用，旋转的速度变慢了，扭曲的感觉也减轻了。他感觉好受了一些。但只是一会儿，牵引力又加剧了，变得更强了，旋转也加剧了，变得更快了，快到他的灵魂都要和肉体分离了……他终于受不住那酷刑，失去了意识。
